(function(){
  const STORAGE_KEY='ward_glucose_learning_curve_v1';
  const MIN_CASES=6;
  function normalize(raw){const x=raw&&typeof raw==='object'?raw:{};return {days:Array.isArray(x.days)?x.days:[],cases:Array.isArray(x.cases)?x.cases:[],objectives:Array.isArray(x.objectives)?x.objectives:[],completion_records:x.completion_records&&typeof x.completion_records==='object'?x.completion_records:{}}}
  function load(){try{return normalize(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'))}catch{return normalize({})}}
  function mean(xs){return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null}
  function ratio(a,b){return b?a/b:null}
  function completedCases(data){const ids=new Set(data.days.map(d=>d?.case_id).filter(Boolean));return data.cases.filter(c=>c?.case_id&&ids.has(c.case_id)&&['discharged','game_over'].includes(c.outcome))}
  function splitTerciles(cases){const n=cases.length,b1=Math.floor(n/3),b2=Math.floor(2*n/3);return {early:cases.slice(0,b1),middle:cases.slice(b1,b2),late:cases.slice(b2)}}
  function ids(cases){return new Set(cases.map(c=>c.case_id))}
  function daysFor(data,cases){const s=ids(cases);return data.days.filter(d=>s.has(d.case_id))}
  function objectivesFor(data,cases){const s=ids(cases);return data.objectives.filter(x=>s.has(x?.target_case_id)&&['resolved','improved','not_resolved'].includes(x?.status))}
  function tracesFor(data,cases){return cases.map(c=>data.completion_records?.[c.case_id]?.case_learning_trace).filter(t=>t?.version===1&&Array.isArray(t.days))}
  function traceMetrics(traces){let correction=0,rapidDelivered=0,repeatPairs=0,repeatSame=0;
    for(const t of traces){const ds=t.days||[];for(let i=0;i<ds.length;i++){const d=ds[i],c=d?.correction_doses_u||{},a=d?.actual_delivered_u||{};for(const k of ['breakfast','lunch','dinner'])correction+=Number(c[k]||0);for(const k of ['breakfast_u','lunch_u','dinner_u'])rapidDelivered+=Number(a[k]||0);if(i>0){const prev=ds[i-1]?.feedback?.primary_tag,cur=d?.feedback?.primary_tag;if(prev&&cur){repeatPairs++;if(prev===cur)repeatSame++;}}}}
    return {correction_share_of_rapid:ratio(correction,rapidDelivered),same_feedback_next_day_rate:ratio(repeatSame,repeatPairs),trace_days:traces.reduce((n,t)=>n+(t.days?.length||0),0)};
  }
  function groupMetrics(data,cases){const days=daysFor(data,cases),objectives=objectivesFor(data,cases),tm=traceMetrics(tracesFor(data,cases));let rapidOver=0,rapidUnder=0,rapidNear=0,basalOver=0,basalUnder=0;for(const d of days){const p=d?.prescribing||{};rapidOver+=Number(p.rapid_over||0);rapidUnder+=Number(p.rapid_under||0);rapidNear+=Number(p.rapid_near||0);if(p.basal_over)basalOver++;if(p.basal_under)basalUnder++}const rapidTotal=rapidOver+rapidUnder+rapidNear,objectiveSuccess=objectives.filter(x=>x.status==='resolved'||x.status==='improved').length,caseDays=cases.map(c=>Number(c.days)).filter(Number.isFinite);return {cases:cases.length,days:days.length,discharge_rate:ratio(cases.filter(c=>c.outcome==='discharged').length,cases.length),mean_completion_days:mean(caseDays),safe_day_rate:ratio(days.filter(d=>d.safe).length,days.length),scale_day_rate:ratio(days.filter(d=>d.used_scale).length,days.length),rapid_error_rate:ratio(rapidOver+rapidUnder,rapidTotal),rapid_over_rate:ratio(rapidOver,rapidTotal),rapid_under_rate:ratio(rapidUnder,rapidTotal),basal_error_day_rate:ratio(basalOver+basalUnder,days.length),basal_over_day_rate:ratio(basalOver,days.length),basal_under_day_rate:ratio(basalUnder,days.length),objective_success_rate:ratio(objectiveSuccess,objectives.length),objective_n:objectives.length,...tm}}
  const METRICS=[
    {id:'discharge_rate',label:'DISCHARGE率',direction:'higher',section:'outcome'},{id:'mean_completion_days',label:'完了日数',direction:'lower',section:'outcome'},{id:'safe_day_rate',label:'安全日率',direction:'higher',section:'outcome'},{id:'scale_day_rate',label:'scale使用日率',direction:'lower',section:'prescribing'},{id:'correction_share_of_rapid',label:'rapid実投与中のscale依存率',direction:'lower',section:'learning'},{id:'same_feedback_next_day_rate',label:'同一feedback翌日再発率',direction:'lower',section:'learning'},{id:'rapid_error_rate',label:'rapid過不足率',direction:'lower',section:'prescribing'},{id:'rapid_over_rate',label:'rapid過量率',direction:'lower',section:'bias'},{id:'rapid_under_rate',label:'rapid不足率',direction:'lower',section:'bias'},{id:'basal_error_day_rate',label:'basal過不足日率',direction:'lower',section:'prescribing'},{id:'basal_over_day_rate',label:'basal過量日率',direction:'lower',section:'bias'},{id:'basal_under_day_rate',label:'basal不足日率',direction:'lower',section:'bias'},{id:'objective_success_rate',label:'学習目標 改善/達成率',direction:'higher',section:'outcome'}];
  function change(m,e,l){if(e==null||l==null)return null;const raw=l-e;return {raw,improvement:m.direction==='lower'?-raw:raw}}
  function summarize(raw){const data=normalize(raw),cases=completedCases(data),g=splitTerciles(cases),out={schema_version:3,case_count:cases.length,ready:cases.length>=MIN_CASES,minimum_cases:MIN_CASES,window_method:'ordered completed cases split into contiguous terciles',groups:{early:groupMetrics(data,g.early),middle:groupMetrics(data,g.middle),late:groupMetrics(data,g.late)},metrics:[]};out.metrics=METRICS.map(m=>{const early=out.groups.early[m.id],middle=out.groups.middle[m.id],late=out.groups.late[m.id];return {...m,early,middle,late,change:change(m,early,late)}});return out}
  function pct(x){return x==null?'—':`${Math.round(100*x)}%`}
  function num(x){return x==null?'—':x.toFixed(1)}
  function formatMetric(id,x){return id==='mean_completion_days'?num(x):pct(x)}
  function deltaText(m){if(!m.change)return '—';const scale=m.id==='mean_completion_days'?1:100,n=m.change.improvement*scale,unit=m.id==='mean_completion_days'?'日':'pt';return `${n>0?'+':''}${n.toFixed(1)}${unit}`}
  function biasSummary(s){const xs=s.metrics.filter(m=>m.section==='bias'&&m.change);if(!xs.length)return '';const best=[...xs].sort((a,b)=>b.change.improvement-a.change.improvement)[0],worst=[...xs].sort((a,b)=>a.change.improvement-b.change.improvement)[0],txt=m=>`${m.label} ${formatMetric(m.id,m.early)}→${formatMetric(m.id,m.late)}（${deltaText(m)}）`;return worst.change.improvement>=0?`<div class="micro-note" style="margin-top:8px"><b>処方バイアス：</b>4方向とも悪化なし。最大改善は ${txt(best)}。</div>`:`<div class="micro-note" style="margin-top:8px"><b>処方バイアス：</b>改善最大 ${txt(best)} ／ 要注意 ${txt(worst)}。</div>`}
  function renderHtml(s){if(!s.ready)return `<div class="micro-note">${s.minimum_cases}症例完了後からearly / middle / lateで学習変化を固定集計します（現在 ${s.case_count}症例）。</div>`;const rows=s.metrics.map(m=>`<tr><td>${m.label}</td><td>${formatMetric(m.id,m.early)}</td><td>${formatMetric(m.id,m.middle)}</td><td>${formatMetric(m.id,m.late)}</td><td>${deltaText(m)}</td></tr>`).join('');return `<div class="micro-note">completed caseを時系列の3群に分け、処方結果だけでなく実投与とfeedback再発も追います。正値ほど改善方向です。</div>${biasSummary(s)}<div style="overflow-x:auto;margin-top:8px"><table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr><th>指標</th><th>early</th><th>middle</th><th>late</th><th>改善量</th></tr></thead><tbody>${rows}</tbody></table></div>`}
  function ensureUI(){if(typeof document==='undefined')return null;let box=document.querySelector('#learningAnalysis');if(box)return box;const anchor=document.querySelector('#learningDataExport')||document.querySelector('#runHistory');if(!anchor)return null;box=document.createElement('section');box.id='learningAnalysis';box.className='section-block';box.style.marginTop='16px';box.innerHTML=`<div class="section-title"><span>L</span> 学習効果サマリー</div><div id="learningAnalysisBody"></div>`;anchor.insertAdjacentElement('afterend',box);return box}
  function refresh(){const box=ensureUI(),body=box?.querySelector('#learningAnalysisBody');if(body)body.innerHTML=renderHtml(summarize(load()))}
  function mount(){refresh();const submit=document.querySelector('#submitBtn'),next=document.querySelector('#newCaseBtn');if(submit&&!submit.dataset.learningAnalysisMounted){submit.dataset.learningAnalysisMounted='1';submit.addEventListener('click',()=>setTimeout(refresh,0))}if(next&&!next.dataset.learningAnalysisMounted){next.dataset.learningAnalysisMounted='1';next.addEventListener('click',()=>setTimeout(refresh,0))}const result=document.querySelector('#resultPanel');if(result&&!result.dataset.learningAnalysisMounted){result.dataset.learningAnalysisMounted='1';result.addEventListener('click',e=>{if(e.target?.closest?.('#restartBtn'))setTimeout(refresh,0)})}}
  window.WardLearningAnalysis={normalize,completedCases,splitTerciles,groupMetrics,traceMetrics,summarize,renderHtml,refresh,METRICS,MIN_CASES,version:'1.3.0'};
  if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount()}
})();
