(function(){
  const STORAGE_KEY='ward_glucose_learning_curve_v1';
  const MIN_CASES=6;
  const ROUTING_TARGET_REASONS=new Set(['recent_tendency_adaptive','persistent','longitudinal']);
  const ROUTING_RELIEF_KINDS=new Set(['recent_tendency_downgraded','recent_tendency_released','persistent_released','longitudinal_released','objective_released']);
  const DOMAIN_LABELS={basal:'basal',breakfast_rapid:'朝rapid',lunch_rapid:'昼rapid',dinner_rapid:'夕rapid',scale_dependence:'scale依存',hidden_awareness:'hidden excursion',safety_response:'安全対応'};
  function prescribingFromTags(tags,scaleUsed=false){const set=new Set(Array.isArray(tags)?tags:[]),meals=['breakfast','lunch','dinner'];let rapidOver=0,rapidUnder=0,rapidNear=0;for(const meal of meals){const over=set.has(`${meal}_rapid_excess`),under=set.has(`${meal}_rapid_deficit`);if(over)rapidOver++;if(under)rapidUnder++;if(!over&&!under)rapidNear++}return {rapid_over:rapidOver,rapid_under:rapidUnder,rapid_near:rapidNear,basal_over:set.has('basal_excess'),basal_under:set.has('basal_deficit'),scale_used:Boolean(scaleUsed)}}
  function migrateDay(day){if(!day||typeof day!=='object')return day;const tags=Array.isArray(day.feedback_tags)?day.feedback_tags.filter(x=>typeof x==='string'):[];if(!tags.length)return day;return {...day,prescribing:prescribingFromTags(tags,Boolean(day.used_scale)),prescribing_source:'feedback_tags_v1'}}
  function normalize(raw){const x=raw&&typeof raw==='object'?raw:{};return {days:Array.isArray(x.days)?x.days.map(migrateDay):[],cases:Array.isArray(x.cases)?x.cases:[],objectives:Array.isArray(x.objectives)?x.objectives:[],completion_records:x.completion_records&&typeof x.completion_records==='object'?x.completion_records:{},active_objective:x.active_objective&&typeof x.active_objective==='object'?x.active_objective:null}}
  function load(){try{return normalize(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'))}catch{return normalize({})}}
  function mean(xs){return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null}
  function ratio(a,b){return b?a/b:null}
  function completedCases(data){const ids=new Set(data.days.map(d=>d?.case_id).filter(Boolean));return data.cases.filter(c=>c?.case_id&&ids.has(c.case_id)&&['discharged','game_over'].includes(c.outcome))}
  function splitTerciles(cases){const n=cases.length,b1=Math.floor(n/3),b2=Math.floor(2*n/3);return {early:cases.slice(0,b1),middle:cases.slice(b1,b2),late:cases.slice(b2)}}
  function ids(cases){return new Set(cases.map(c=>c.case_id))}
  function daysFor(data,cases){const s=ids(cases);return data.days.filter(d=>s.has(d.case_id))}
  function objectivesFor(data,cases){const s=ids(cases);return data.objectives.filter(x=>s.has(x?.target_case_id)&&['resolved','improved','not_resolved'].includes(x?.status))}
  function supportedTraceVersion(value){const v=Number(value);return v===1||v===2}
  function tracesFor(data,cases){return cases.map(c=>data.completion_records?.[c.case_id]?.case_learning_trace).filter(t=>supportedTraceVersion(t?.version)&&Array.isArray(t.days))}
  function routingOutcomeMetrics(data,cases){let targeted=0,relief=0;for(const c of cases){if(!ROUTING_TARGET_REASONS.has(c?.adaptive_practice?.selection_reason))continue;targeted++;const kind=data.completion_records?.[c?.case_id]?.routing_transition?.kind;if(ROUTING_RELIEF_KINDS.has(kind))relief++;}return {routing_targeted_n:targeted,routing_relief_n:relief,routing_relief_rate:ratio(relief,targeted)}}
  function feedbackSemantics(){return typeof globalThis!=='undefined'?globalThis.WardFeedbackActionSemantics:null}
  function feedbackActionSpec(tag){const semantics=feedbackSemantics(),rule=semantics?.ruleForTag?.(tag);if(!rule)return null;return {doseKey:rule.dose_key,direction:rule.direction,source:rule.dose_key==='basal_u'?'active_basal':'scheduled',feedbackTag:rule.feedback_tag||String(tag||'')}}
  function feedbackActionsCompat(){const rules=feedbackSemantics()?.RULES||{};return Object.fromEntries(Object.keys(rules).map(tag=>{const spec=feedbackActionSpec(tag);return [tag,spec?{doseKey:spec.doseKey,direction:spec.direction===-1?'lower':'higher',source:spec.source}:null]}).filter(([,spec])=>spec))}
  function feedbackActionMetrics(traces){let eligible=0,aligned=0,unchanged=0,opposite=0;
    const semantics=feedbackSemantics();
    for(const t of traces){const ds=t.days||[];for(let i=0;i<ds.length-1;i++){const d=ds[i],next=ds[i+1],tag=d?.feedback?.primary_tag,spec=feedbackActionSpec(tag);if(!spec)continue;
      const source=Number(spec.source==='active_basal'?d?.actual_delivered_u?.basal_u:d?.prescribed_order_u?.[spec.doseKey]);
      const target=Number(next?.prescribed_order_u?.[spec.doseKey]);
      if(!Number.isFinite(source)||!Number.isFinite(target))continue;
      const classified=semantics?.classifyTag?.(tag,source,target);if(!classified)continue;
      eligible++;
      if(classified.status==='followed')aligned++;
      else if(classified.status==='unchanged')unchanged++;
      else if(classified.status==='opposite')opposite++;
    }}
    return {feedback_action_alignment_rate:ratio(aligned,eligible),feedback_action_eligible_n:eligible,feedback_action_followed_n:aligned,feedback_action_unchanged_n:unchanged,feedback_action_opposite_n:opposite};
  }
  function traceMetrics(traces){let correction=0,rapidDelivered=0,repeatPairs=0,repeatSame=0;
    for(const t of traces){const ds=t.days||[];for(let i=0;i<ds.length;i++){const d=ds[i],c=d?.correction_doses_u||{},a=d?.actual_delivered_u||{};for(const k of ['breakfast','lunch','dinner'])correction+=Number(c[k]||0);for(const k of ['breakfast_u','lunch_u','dinner_u'])rapidDelivered+=Number(a[k]||0);if(i>0){const prev=ds[i-1]?.feedback?.primary_tag,cur=d?.feedback?.primary_tag;if(prev&&cur){repeatPairs++;if(prev===cur)repeatSame++;}}}}
    return {correction_share_of_rapid:ratio(correction,rapidDelivered),same_feedback_next_day_rate:ratio(repeatSame,repeatPairs),trace_days:traces.reduce((n,t)=>n+(t.days?.length||0),0),...feedbackActionMetrics(traces)};
  }
  function groupMetrics(data,cases){const days=daysFor(data,cases),objectives=objectivesFor(data,cases),tm=traceMetrics(tracesFor(data,cases)),rm=routingOutcomeMetrics(data,cases);let rapidOver=0,rapidUnder=0,rapidNear=0,basalOver=0,basalUnder=0;for(const d of days){const p=d?.prescribing||{};rapidOver+=Number(p.rapid_over||0);rapidUnder+=Number(p.rapid_under||0);rapidNear+=Number(p.rapid_near||0);if(p.basal_over)basalOver++;if(p.basal_under)basalUnder++}const rapidTotal=rapidOver+rapidUnder+rapidNear,objectiveSuccess=objectives.filter(x=>x.status==='resolved'||x.status==='improved').length,caseDays=cases.map(c=>Number(c.days)).filter(Number.isFinite);return {cases:cases.length,days:days.length,discharge_rate:ratio(cases.filter(c=>c.outcome==='discharged').length,cases.length),mean_completion_days:mean(caseDays),safe_day_rate:ratio(days.filter(d=>d.safe).length,days.length),scale_day_rate:ratio(days.filter(d=>d.used_scale).length,days.length),rapid_error_rate:ratio(rapidOver+rapidUnder,rapidTotal),rapid_over_rate:ratio(rapidOver,rapidTotal),rapid_under_rate:ratio(rapidUnder,rapidTotal),basal_error_day_rate:ratio(basalOver+basalUnder,days.length),basal_over_day_rate:ratio(basalOver,days.length),basal_under_day_rate:ratio(basalUnder,days.length),objective_success_rate:ratio(objectiveSuccess,objectives.length),objective_n:objectives.length,...tm,...rm}}
  const METRICS=[
    {id:'discharge_rate',label:'DISCHARGE率',direction:'higher',section:'outcome'},{id:'mean_completion_days',label:'完了日数',direction:'lower',section:'outcome'},{id:'safe_day_rate',label:'安全日率',direction:'higher',section:'outcome'},{id:'scale_day_rate',label:'scale使用日率',direction:'lower',section:'prescribing'},{id:'correction_share_of_rapid',label:'rapid実投与中のscale依存率',direction:'lower',section:'learning'},{id:'same_feedback_next_day_rate',label:'同一feedback翌日再発率',direction:'lower',section:'learning'},{id:'feedback_action_alignment_rate',label:'指摘→翌日scheduled処方方向一致率',direction:'higher',section:'learning'},{id:'rapid_error_rate',label:'rapid過不足率',direction:'lower',section:'prescribing'},{id:'rapid_over_rate',label:'rapid過量率',direction:'lower',section:'bias'},{id:'rapid_under_rate',label:'rapid不足率',direction:'lower',section:'bias'},{id:'basal_error_day_rate',label:'basal過不足日率',direction:'lower',section:'prescribing'},{id:'basal_over_day_rate',label:'basal過量日率',direction:'lower',section:'bias'},{id:'basal_under_day_rate',label:'basal不足日率',direction:'lower',section:'bias'},{id:'objective_success_rate',label:'学習目標 改善/達成率',direction:'higher',section:'outcome'}];
  function change(m,e,l){if(e==null||l==null)return null;const raw=l-e;return {raw,improvement:m.direction==='lower'?-raw:raw}}
  function nextFocusSummary(data){const o=data?.active_objective;if(!o?.domain_id)return null;return {domain_id:o.domain_id,label:DOMAIN_LABELS[o.domain_id]||o.domain_id,focus_tag:o.focus_tag||null,routing_source:o.routing_source||null,selection_reason:o.selection_reason||null}}
  function summarize(raw){const data=normalize(raw),cases=completedCases(data),g=splitTerciles(cases),out={schema_version:9,case_count:cases.length,ready:cases.length>=MIN_CASES,minimum_cases:MIN_CASES,window_method:'ordered completed cases split into contiguous terciles',prescribing_source:'feedback_tags_v1 when feedback tags are available',feedback_action_semantics_version:feedbackSemantics()?.version||null,next_focus:nextFocusSummary(data),groups:{early:groupMetrics(data,g.early),middle:groupMetrics(data,g.middle),late:groupMetrics(data,g.late)},metrics:[]};out.metrics=METRICS.map(m=>{const early=out.groups.early[m.id],middle=out.groups.middle[m.id],late=out.groups.late[m.id];return {...m,early,middle,late,change:change(m,early,late)}});return out}
  function pct(x){return x==null?'—':`${Math.round(100*x)}%`}
  function num(x){return x==null?'—':x.toFixed(1)}
  function formatMetric(id,x){return id==='mean_completion_days'?num(x):pct(x)}
  function deltaText(m){if(!m.change)return '—';const scale=m.id==='mean_completion_days'?1:100,n=m.change.improvement*scale,unit=m.id==='mean_completion_days'?'日':'pt';return `${n>0?'+':''}${n.toFixed(1)}${unit}`}
  function progressAxis(id,label,direction,early,late,evidence=''){return {id,label,direction,early,late,evidence,change:change({direction},early,late)}}
  function learningProgressAxes(s){const e=s.groups?.early||{},l=s.groups?.late||{},metric=id=>s.metrics.find(m=>m.id===id);const objective=metric('objective_success_rate'),feedback=metric('feedback_action_alignment_rate'),correction=metric('correction_share_of_rapid');return [
    progressAxis('objective_miss_rate','学習目標 未達率','lower',objective?.early==null?null:1-objective.early,objective?.late==null?null:1-objective.late,`early n=${e.objective_n||0} / late n=${l.objective_n||0}`),
    progressAxis('feedback_action_alignment_rate','feedback→次処方反映率','higher',feedback?.early??null,feedback?.late??null,`early n=${e.feedback_action_eligible_n||0} / late n=${l.feedback_action_eligible_n||0}`),
    progressAxis('correction_share_of_rapid','rapid実投与中のscale依存率','lower',correction?.early??null,correction?.late??null,`trace days ${e.trace_days||0}→${l.trace_days||0}`),
    progressAxis('routing_relief_rate','重点focus解除率','higher',e.routing_relief_rate??null,l.routing_relief_rate??null,`early ${e.routing_relief_n||0}/${e.routing_targeted_n||0} / late ${l.routing_relief_n||0}/${l.routing_targeted_n||0}`)
  ]}
  function progressDeltaText(axis){if(!axis.change)return '—';const n=axis.change.improvement*100;return `${n>0?'+':''}${n.toFixed(1)}pt`}
  function learningProgressHtml(s){const axes=learningProgressAxes(s),rows=axes.map(a=>`<tr><td>${a.label}</td><td>${pct(a.early)}</td><td>${pct(a.late)}</td><td>${progressDeltaText(a)}</td></tr>`).join('');return `<div class="record-card" style="margin-top:8px"><div class="section-kicker">100本ノック進捗</div><div style="font-weight:800;margin-top:4px">複数focusをまたいだ上達を4軸で確認</div><div style="overflow-x:auto;margin-top:7px"><table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr><th>軸</th><th>early</th><th>late</th><th>改善量</th></tr></thead><tbody>${rows}</tbody></table></div><div class="micro-note" style="margin-top:5px">4軸は長期の学習推移です。未達↓・feedback反映↑・scale依存↓・実routingのfocus解除↑を別々に表示し、次症例のfocusをこの表から再計算しません。</div></div>`}
  function nextPracticeHtml(s){const f=s?.next_focus;if(!f)return '';const evidence=[f.routing_source,f.selection_reason].filter(Boolean).join(' / ');return `<div class="record-card" style="margin-top:8px"><div class="section-kicker">NEXT PRACTICE</div><div style="font-weight:800;margin-top:4px">次の重点：${f.label}</div>${f.focus_tag?`<div class="micro-note" style="margin-top:5px">focus: ${f.focus_tag}</div>`:''}${evidence?`<div class="micro-note" style="margin-top:4px">routing: ${evidence}</div>`:''}<div class="micro-note" style="margin-top:5px">これはadaptive routingのactive objectiveです。上の4軸は長期サーベイランスで、最大悪化項目を機械的に次focusへ置き換えません。</div></div>`}
  function biasSummary(s){const xs=s.metrics.filter(m=>m.section==='bias'&&m.change);if(!xs.length)return '';const best=[...xs].sort((a,b)=>b.change.improvement-a.change.improvement)[0],worst=[...xs].sort((a,b)=>a.change.improvement-b.change.improvement)[0],txt=m=>`${m.label} ${formatMetric(m.id,m.early)}→${formatMetric(m.id,m.late)}（${deltaText(m)}）`;return worst.change.improvement>=0?`<div class="micro-note" style="margin-top:8px"><b>処方バイアス：</b>4方向とも悪化なし。最大改善は ${txt(best)}。</div>`:`<div class="micro-note" style="margin-top:8px"><b>処方バイアス：</b>改善最大 ${txt(best)} ／ 要注意 ${txt(worst)}。</div>`}
  function routingEvidenceHtml(s){const e=s.groups?.early,l=s.groups?.late;if(!e||!l||(!e.routing_targeted_n&&!l.routing_targeted_n))return '';const er=e.routing_relief_rate==null?'—':pct(e.routing_relief_rate),lr=l.routing_relief_rate==null?'—':pct(l.routing_relief_rate);return `<div class="micro-note" style="margin-top:4px"><b>routing整合：</b>重点focus解除 ${er}→${lr}（early ${e.routing_relief_n}/${e.routing_targeted_n}、late ${l.routing_relief_n}/${l.routing_targeted_n}）。objective改善だけでなく、実際の重点解除記録を併記します。</div>`}
  function routingConsistency(s){const e=s.groups?.early,l=s.groups?.late;if(!e||!l||!e.routing_targeted_n||!l.routing_targeted_n||e.routing_relief_rate==null||l.routing_relief_rate==null)return null;return l.routing_relief_rate-e.routing_relief_rate}
  function learningSignalHtml(s){const ids=['feedback_action_alignment_rate','same_feedback_next_day_rate','objective_success_rate'],xs=ids.map(id=>s.metrics.find(m=>m.id===id)).filter(m=>m?.change);if(!xs.length)return '';const improved=xs.filter(m=>m.change.improvement>0).length,worsened=xs.filter(m=>m.change.improvement<0).length,routingDelta=routingConsistency(s);let state=worsened===0&&improved>0?'改善傾向':improved===0&&worsened>0?'要注意':worsened===0?'横ばい':'混在';if(state==='改善傾向'&&routingDelta!=null&&routingDelta<0)state='混在';const detail=xs.map(m=>`${m.label} ${formatMetric(m.id,m.early)}→${formatMetric(m.id,m.late)}`).join(' ／ ');const guard=routingDelta!=null&&routingDelta<0?'<div class="micro-note" style="margin-top:4px"><b>注意：</b>core learning指標は改善していますが、重点focus解除率は低下しているため「改善傾向」とは確定しません。</div>':'';return `<div class="record-card" style="margin-top:8px"><div class="section-kicker">LEARNING RESPONSE</div><div style="font-weight:800;margin-top:4px">学習反応：${state}</div><div class="micro-note" style="margin-top:5px">${detail}</div>${routingEvidenceHtml(s)}${guard}<div class="micro-note" style="margin-top:4px">新しい合成スコアは作らず、行動反映・同一feedback再発・学習目標の3本を既存データのまま要約しています。</div></div>`}
  function detailMetricsHtml(s){const rows=s.metrics.map(m=>`<tr><td>${m.label}</td><td>${formatMetric(m.id,m.early)}</td><td>${formatMetric(m.id,m.middle)}</td><td>${formatMetric(m.id,m.late)}</td><td>${deltaText(m)}</td></tr>`).join('');return `<details style="margin-top:8px"><summary style="cursor:pointer;font-weight:700">詳細指標を表示</summary><div class="micro-note" style="margin-top:7px">completed caseを時系列の3群に分け、処方結果だけでなく実投与・feedback再発・次回scheduled処方への反映も追います。rapidのcorrection scale使用日は除外せず、feedbackを翌日のscheduled doseへ反映したかで判定します。feedback tagがある日は旧prescribing値を再利用せず結果ベースで再構成します。正値ほど改善方向です。</div>${biasSummary(s)}<div style="overflow-x:auto;margin-top:8px"><table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr><th>指標</th><th>early</th><th>middle</th><th>late</th><th>改善量</th></tr></thead><tbody>${rows}</tbody></table></div></details>`}
  function renderHtml(s){if(!s.ready)return `<div class="micro-note">${s.minimum_cases}症例完了後からearly / middle / lateで学習変化を固定集計します（現在 ${s.case_count}症例）。</div>`;return `${learningProgressHtml(s)}${nextPracticeHtml(s)}${learningSignalHtml(s)}${detailMetricsHtml(s)}`}
  function ensureUI(){if(typeof document==='undefined')return null;let box=document.querySelector('#learningAnalysis');if(box)return box;const anchor=document.querySelector('#learningDataExport')||document.querySelector('#runHistory');if(!anchor)return null;box=document.createElement('section');box.id='learningAnalysis';box.className='section-block';box.style.marginTop='16px';box.innerHTML=`<div class="section-title"><span>L</span> 学習効果サマリー</div><div id="learningAnalysisBody"></div>`;anchor.insertAdjacentElement('afterend',box);return box}
  function refresh(){const box=ensureUI(),body=box?.querySelector('#learningAnalysisBody');if(body)body.innerHTML=renderHtml(summarize(load()))}
  function mount(){refresh();const submit=document.querySelector('#submitBtn'),next=document.querySelector('#newCaseBtn');if(submit&&!submit.dataset.learningAnalysisMounted){submit.dataset.learningAnalysisMounted='1';submit.addEventListener('click',()=>setTimeout(refresh,0))}if(next&&!next.dataset.learningAnalysisMounted){next.dataset.learningAnalysisMounted='1';next.addEventListener('click',()=>setTimeout(refresh,0))}const result=document.querySelector('#resultPanel');if(result&&!result.dataset.learningAnalysisMounted){result.dataset.learningAnalysisMounted='1';result.addEventListener('click',e=>{if(e.target?.closest?.('#restartBtn'))setTimeout(refresh,0)})}}
  window.WardLearningAnalysis={normalize,migrateDay,prescribingFromTags,completedCases,splitTerciles,groupMetrics,routingOutcomeMetrics,traceMetrics,feedbackActionMetrics,feedbackActionSpec,supportedTraceVersion,summarize,renderHtml,learningProgressAxes,learningProgressHtml,nextFocusSummary,nextPracticeHtml,learningSignalHtml,routingEvidenceHtml,routingConsistency,detailMetricsHtml,refresh,METRICS,MIN_CASES,get FEEDBACK_ACTIONS(){return feedbackActionsCompat()},version:'1.15.0'};
  if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount()}
})();