(function(){
'use strict';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const POC={pre_breakfast:420,pre_lunch:720,pre_dinner:1080,bedtime:1260};
const MEAL_BASE=[480,780,1140];
const CARB_KEYS=['breakfast','lunch','dinner'];
const DEFAULT_MEALS={breakfast:50,lunch:70,dinner:60};
const FREEZE={state_width_min:330,state_coupling:.32,transient_tau_min:90,transient_amp_mg_dl:8,rapid_scale:.80,fast_scale:.80,setpoint_shift_mg_dl:-5,meal_timing_sd_min:15,bolus_timing_sd_min:15,poc_timing_sd_min:15};
function hash32(x){let h=2166136261>>>0;for(const c of String(x)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=hash32(seed);return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function randn(seed){const r=rng(seed);let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function jitter(seed,sd){return sd?Math.round(sd*randn(seed)):0}
function gamma2(t50,h=1200){const th=Math.max(Number(t50)/1.67835,2),k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=t/(th*th)*Math.exp(-t/th);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
function mealKernel(p){const f=gamma2(p.meal_t50_fast_min),s=gamma2(p.meal_t50_slow_min),q=clamp(Number(p.meal_fast_fraction),.05,.95),k=new Float64Array(1200);for(let i=0;i<k.length;i++)k[i]=q*f[i]+(1-q)*s[i];return k}
function shifted(on,pk,dur,scale=FREEZE.rapid_scale,h=1400,shape=3){on*=scale;pk*=scale;dur*=scale;const th=Math.max((pk-on)/(shape-1),1),k=new Float64Array(h);let S=0,ts=Math.max(pk,.8*dur);for(let i=0;i<h;i++){const t=i+.5,x=Math.max(t-on,0);let v=x>0?x**(shape-1)*Math.exp(-x/th):0;if(t>ts&&t<dur)v*=.5*(1+Math.cos(Math.PI*(t-ts)/(dur-ts)));if(t>=dur)v=0;k[i]=v;S+=v}for(let i=0;i<h;i++)k[i]/=S;return k}
function basalKernel(h=1800){const k=new Float64Array(h);let s=0;for(let t=0;t<h;t++){let v=0;if(t>=60&&t<180)v=(t-60)/120;else if(t>=180&&t<1260)v=1;else if(t>=1260&&t<1500)v=1-(t-1260)/240;k[t]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
function conv(n,events,k){const y=new Float64Array(n);for(const [rawT,a] of events){const t=Math.trunc(rawT),ks=Math.max(0,-t),ys=Math.max(0,t),m=Math.min(k.length-ks,n-ys);for(let j=0;j<m;j++)y[ys+j]+=Number(a)*k[ks+j]}return y}
function gaussian(c,sd,h=600){const k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=Math.exp(-.5*((t-c)/sd)**2);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
const EARLY=gaussian(60,35),LATE=gaussian(210,60),SHAPE=Float64Array.from(EARLY,(_,i)=>LATE[i]-EARLY[i]);
function restoreK(p){return Math.log(2)/(300/clamp(p.egp_suppression_strength,.70,1.35))}
function response(k,kh,T){let d=0;for(let t=0;t<T;t++)d+=(k[t]||0)-kh*d;return d}
function roundUnit(x){return Math.max(0,Math.round(Number(x)||0))}
function bipState(history,minutes,seed,w=FREEZE.state_width_min){const r=rng(seed),L=2*w,h=Array.isArray(history)?history.slice(-L):[];while(h.length<L)h.unshift(0);const y=new Float64Array(minutes+1);function val(){let a=0,b=0;for(let i=0;i<w;i++)b+=h[i];for(let i=w;i<L;i++)a+=h[i];return(a-b)/Math.sqrt(2*w)}y[0]=val();for(let t=0;t<minutes;t++){h.shift();let u=0,v=0;while(!u)u=r();while(!v)v=r();h.push(Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v));y[t+1]=val()}return{series:y,end_history:h}}
function decorateBase(raw,seed=1){if(!window.PatientPhenotypeV2||!window.ClinicalModifiersV2)throw new Error('PatientPhenotypeV2 and ClinicalModifiersV2 must load first');let p=PatientPhenotypeV2.toEnginePatient(ClinicalModifiersV2.decorateClinical(PatientPhenotypeV2.decorate(raw),{egfr_ml_min_1_73m2:90,meal_plan_carb_g:DEFAULT_MEALS}));const kh=restoreK(p),rk=shifted(15,105,300),u240=-response(Float64Array.from(rk,x=>-x),kh,240),si=Number(p.cf_mg_dl_u)/Math.max(u240,1e-9),D=Number(p.insulin_demand_multiplier??Math.exp(.16*(p.z_insulin_need||0))),hep=Number(p.z_hepatic)||0,resid=.0385*randn('t1dm-v2-demand:'+seed),tdd=Math.exp(2.753045787195406+.6014769208863582*Math.log(p.body_weight_kg)-.409797698421174*Math.log(si)+Math.log(D)+.015345686298610663*hep+resid),mk=mealKernel(p),gain=clamp(5*Math.pow(70/clamp(p.body_weight_kg,40,130),.65),1,10),mpg=new Float64Array(1200);for(let t=0;t<mpg.length;t++)mpg[t]=gain*(mk[t]||0)+.1*gain*(SHAPE[t]||0);const meal=.8*response(mpg,kh,240),ins=.8*si*Number(p.incremental_obesity_insulin_action_multiplier??1)*response(rk,kh,240),icr=clamp(ins/Math.max(meal,1e-9),2.5,35);p={...p,si_intrinsic_gain:si,tdd_u_day:tdd,tdd_u_kg_day:tdd/p.body_weight_kg,icr_g_u:icr,v2_icr_g_u:icr};p.legacy_basal_u_day=tdd*p.basal_fraction_tdd;p.v2_basal_u_day=p.legacy_basal_u_day/Number(p.incremental_obesity_insulin_action_multiplier??1);p.basal_u_day=p.v2_basal_u_day;return p}
function generatePatient(seed=1){if(!window.PatientGenerator)throw new Error('PatientGenerator must load first');const raw=PatientGenerator.sampleCandidates(1,seed,false)[0];const p=decorateBase(raw,seed);const meals={...DEFAULT_MEALS};return{patient:p,case:{case_id:raw.candidate_id,phenotype:'T1DM',meal_plan_carb_g:meals,previous_order_u:suggestOrder(p,meals),model_version:'t1dm-game-v2-freeze-2026-08-20'},state:null,history:[]}}
function suggestOrder(p,meals=DEFAULT_MEALS){return{breakfast_u:roundUnit(Number(meals.breakfast)/p.icr_g_u),lunch_u:roundUnit(Number(meals.lunch)/p.icr_g_u),dinner_u:roundUnit(Number(meals.dinner)/p.icr_g_u),basal_u:roundUnit(p.v2_basal_u_day)}}
function simulateDay(p,order,ctx={},seed=1,state=null){const n=1441,mealPlan={...DEFAULT_MEALS,...(ctx.meal_plan_carb_g||{})},intake={breakfast:1,lunch:1,dinner:1,...(ctx.intake_fraction||{})},timing={meal_sd_min:ctx.meal_timing_sd_min??FREEZE.meal_timing_sd_min,bolus_sd_min:ctx.bolus_timing_sd_min??FREEZE.bolus_timing_sd_min,poc_sd_min:ctx.poc_timing_sd_min??FREEZE.poc_timing_sd_min};const rk=shifted(15,105,300),bk=basalKernel(),mk=mealKernel(p),kh=restoreK(p),ob=Number(p.incremental_obesity_insulin_action_multiplier??1),gain=clamp(5*Math.pow(70/clamp(p.body_weight_kg,40,130),.65),1,10),ig=Number(p.si_intrinsic_gain),phys=Number(p.legacy_basal_u_day),actual=roundUnit(order.basal_u),dose=[roundUnit(order.breakfast_u),roundUnit(order.lunch_u),roundUnit(order.dinner_u)],tb=conv(n,[[-120,phys]],bk),ab=conv(n,[[-120,actual]],bk),mt=MEAL_BASE.map((t,i)=>clamp(t+jitter(`meal:${seed}:${i}`,timing.meal_sd_min),0,1439)),bt=mt.map((t,i)=>clamp(t+jitter(`bol:${seed}:${i}`,timing.bolus_sd_min),0,1439)),meal=new Float64Array(n),corr=new Float64Array(n);for(let i=0;i<3;i++){const carbs=Number(mealPlan[CARB_KEYS[i]])*Number(intake[CARB_KEYS[i]]),t=mt[i];for(let j=0;j<Math.min(mk.length,n-t);j++)meal[t+j]+=gain*carbs*mk[j];for(let j=0;j<Math.min(SHAPE.length,n-t);j++)corr[t+j]+=.1*gain*carbs*SHAPE[j]}const bol=conv(n,[[bt[0],dose[0]],[bt[1],dose[1]],[bt[2],dose[2]]],rk),B=bipState(state?.requirement_history||[],1440,`req:${seed}`),g=new Float64Array(n);g[0]=Number(state?.glucose_mg_dl??(p.fasting_setpoint_mg_dl+FREEZE.setpoint_shift_mg_dl));let tr=Number(state?.transient_state||0),trPrev=tr,mn=g[0],mx=g[0];const rho=Math.exp(-1/FREEZE.transient_tau_min),innov=Math.sqrt(1-rho*rho);for(let t=0;t<n-1;t++){const zb=B.series[t],u=randn(`tr:${seed}:${t}`),mult=clamp(Math.exp(FREEZE.state_coupling*zb-.5*FREEZE.state_coupling*FREEZE.state_coupling),.55,1.8),restore=-kh*(g[t]-(p.fasting_setpoint_mg_dl+FREEZE.setpoint_shift_mg_dl)),counter=Math.min(1.8,.020*p.counterreg_strength*Math.max(0,p.counterreg_threshold_mg_dl-g[t])),basal=ig*mult*tb[t]-ig*ob*ab[t],fast=FREEZE.fast_scale*(meal[t]+corr[t]-ig*ob*bol[t]);trPrev=tr;tr=rho*tr+innov*u;g[t+1]=g[t]+fast+basal+restore+counter+FREEZE.transient_amp_mg_dl*(tr-trPrev);mn=Math.min(mn,g[t+1]);mx=Math.max(mx,g[t+1])}const ct=[POC.pre_breakfast,POC.pre_lunch,POC.pre_dinner,POC.bedtime].map((t,i)=>clamp(t+jitter(`poc:${seed}:${i}`,timing.poc_sd_min),0,1440)),bg={pre_breakfast:g[ct[0]],pre_lunch:g[ct[1]],pre_dinner:g[ct[2]],bedtime:g[ct[3]]};return{bg,min:mn,max:mx,end:g[1440],series:g,actual_meal_carb_g:{breakfast:mealPlan.breakfast*intake.breakfast,lunch:mealPlan.lunch*intake.lunch,dinner:mealPlan.dinner*intake.dinner},timing:{meal_min:mt,bolus_min:bt,poc_min:ct},order_u:{breakfast_u:dose[0],lunch_u:dose[1],dinner_u:dose[2],basal_u:actual},next_state:{glucose_mg_dl:g[1440],requirement_history:B.end_history,transient_state:tr}}}
function playDay(game,order,ctx={},seed=1){const r=simulateDay(game.patient,order,ctx,seed,game.state);game.state=r.next_state;game.history.push({day:game.history.length+1,order_u:r.order_u,meal_carb_g:r.actual_meal_carb_g,bg:r.bg,min:r.min,max:r.max,timing:r.timing});game.case.previous_order_u=r.order_u;game.case.previous_day_4point_bg_mg_dl=r.bg;game.case.previous_day_end_glucose_mg_dl=r.end;return r}
window.T1DMGameModelV2={version:'2.0-provisional-freeze-2026-08-20',FREEZE,generatePatient,suggestOrder,simulateDay,playDay,roundUnit};
})();
