const fs=require('fs'),vm=require('vm');global.window=global;const load=f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});for(const f of ['patient_generator.js','patient_phenotype_v2.js','clinical_modifiers_v2.js'])load(f);
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),B={b0:5.210581914736487,bw:.33484491772540936,bsi:-.7483470325321024};
function shifted(on,pk,dur,scale,h=900,shape=3){on*=scale;pk*=scale;dur*=scale;const th=Math.max((pk-on)/(shape-1),1),k=new Float64Array(h);let S=0,ts=Math.max(pk,.8*dur);for(let i=0;i<h;i++){const t=i+.5,x=Math.max(t-on,0);let v=x>0?x**(shape-1)*Math.exp(-x/th):0;if(t>ts&&t<dur)v*=.5*(1+Math.cos(Math.PI*(t-ts)/(dur-ts)));if(t>=dur)v=0;k[i]=v;S+=v}for(let i=0;i<h;i++)k[i]/=S;return k}
function restoreK(p){return Math.log(2)/(300/clamp(p.egp_suppression_strength,.70,1.35))}function response(k,kh,T){let d=0;for(let t=0;t<T;t++)d+=(k[t]||0)-kh*d;return d}
function patient(b){return PatientPhenotypeV2.toEnginePatient(ClinicalModifiersV2.decorateClinical(PatientPhenotypeV2.decorate(b),{egfr_ml_min_1_73m2:90,meal_plan_carb_g:{breakfast:50,lunch:70,dinner:60}}))}
const mean=a=>a.reduce((s,x)=>s+x,0)/a.length,sd=a=>{const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)},corr=(a,b)=>{const ma=mean(a),mb=mean(b);let n=0,da=0,db=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;n+=x*y;da+=x*x;db+=y*y}return n/Math.sqrt(da*db)},q=(a,p)=>{const x=[...a].sort((a,b)=>a-b),i=(x.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return x[l]+(x[h]-x[l])*(i-l)};
const N=Number(process.env.N||10000),P=PatientGenerator.sampleCandidates(N,14731,false).map(patient),rows=[];
for(const p of P){const rk=shifted(15,105,300,.8),u240=-response(Float64Array.from(rk,x=>-x),restoreK(p),240),si=+p.cf_mg_dl_u/Math.max(u240,1e-9),pred=Math.exp(B.b0+B.bw*Math.log(p.body_weight_kg)+B.bsi*Math.log(si)),lr=Math.log(+p.tdd_u_day/pred);rows.push({lr,si,w:+p.body_weight_kg,zneed:+p.z_insulin_need,zsens:+p.z_insulin_sensitivity,zhep:+p.z_hepatic,zsize:+p.z_size,bf:+p.basal_fraction_tdd,adip:+p.adiposity_index,cf:+p.cf_mg_dl_u,icr:+p.icr_g_u})}
const lr=rows.map(r=>r.lr),keys=['si','w','zneed','zsens','zhep','zsize','bf','adip','cf','icr'],cor={};for(const k of keys)cor[k]=corr(lr,rows.map(r=>r[k]));
const result={protocol:{N,question:'Can legacy z_insulin_need be removed after S_I+weight reparameterization?'},residual:{mean:mean(lr),sd:sd(lr),p05:q(lr,.05),p10:q(lr,.1),median:q(lr,.5),p90:q(lr,.9),p95:q(lr,.95)},correlations:cor,interpretation:'If residual is small and not strongly tied to a physiologically indispensable latent, replace it with an independent demand residual rather than retaining z_insulin_need as a primitive treatment axis.'};fs.writeFileSync('v080_demand_residual_ablation_result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));