const fs=require('fs'),vm=require('vm');
const q={w:330,c:.32},tau=90,amp=8,rho=Math.exp(-1/tau),innov=Math.sqrt(1-rho*rho);
let s=fs.readFileSync('validation_generator_v081_si_demand_node.js','utf8');
const inject=`\nfunction bipState(initialHistory,minutes,seed,w){let a=(seed>>>0)||1;function rr(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}function rn(){let u=0,v=0;while(!u)u=rr();while(!v)v=rr();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}const L=2*w,h=Array.isArray(initialHistory)?initialHistory.slice(-L):[];while(h.length<L)h.unshift(0);const y=new Float64Array(minutes+1);function val(){let a=0,b=0;for(let i=0;i<w;i++)b+=h[i];for(let i=w;i<L;i++)a+=h[i];return(a-b)/Math.sqrt(2*w)}y[0]=val();for(let t=0;t<minutes;t++){h.shift();h.push(rn());y[t+1]=val()}return{series:y,end_history:h}}\n`;
s=s.replace("function sim(p,seed){",inject+"function sim(p,seed){");
s=s.replace("let hist=[],g0=p.fasting_setpoint_mg_dl-5,V=[],C=[];for(let d=0;d<7;d++){const S=F.evolveMetabolicState(hist,1440,seed+d,cfg);hist=S.end_history;",`let bhist=[],g0=p.fasting_setpoint_mg_dl-5,V=[],C=[],tr=0,trPrev=0;for(let d=0;d<14;d++){const B=bipState(bhist,1440,seed+d+777777,${q.w});bhist=B.end_history;`);
s=s.replace("const z=S.series[t],mult=clamp(Math.exp(.36*z-.5*.36*.36),.55,1.8),restore=",`const zb=B.series[t],u=randn('v090:${q.w}:${q.c}:'+seed+':'+d+':'+t),mult=clamp(Math.exp(${q.c}*zb-.5*${q.c}*${q.c}),.55,1.8),restore=`);
s=s.replace("g[t+1]=g[t]+fast+basal+restore+counter",`trPrev=tr;tr=${rho}*tr+${innov}*u;g[t+1]=g[t]+fast+basal+restore+counter+${amp}*(tr-trPrev)`);
s=s.replace("if(d>0){C.push([g[420],g[720],g[1080],g[1260]]);for(let i=1;i<g.length;i++)V.push(g[i])}","if(d>1){C.push([g[420],g[720],g[1080],g[1260]]);for(let i=1;i<g.length;i++)V.push(g[i])}");
s=s.replace(/const N=Number\(process\.env\.N\|\|120\)[\s\S]*$/,'');
s += '\nthis.__exports={patient,derive,sim,PatientGenerator};\n';
const sandbox={require,console,process,global:null,window:null};sandbox.global=sandbox;sandbox.window=sandbox;vm.createContext(sandbox);vm.runInContext(s,sandbox,{filename:'v090_transformed.js'});const M=sandbox.__exports;
const N=Number(process.env.N||300),all=[],checks=[],patients=[];function mean(a){return a.reduce((x,y)=>x+y,0)/a.length}function sd(a){const m=mean(a);return Math.sqrt(a.reduce((x,y)=>x+(y-m)*(y-m),0)/a.length)}function quant(a,p){const x=a.slice().sort((u,v)=>u-v),z=(x.length-1)*p,i=Math.floor(z),f=z-i;return x[i]*(1-f)+x[Math.min(i+1,x.length-1)]*f}
const bases=M.PatientGenerator.sampleCandidates(N,24681357,false).map(M.patient).map((p,i)=>M.derive(p,i));for(let i=0;i<N;i++){const z=M.sim(bases[i],97531+i*101);all.push(...z.V);checks.push(...z.C);const vv=z.V,tbr=100*vv.filter(x=>x<70).length/vv.length;patients.push({tbr70:tbr,mean:mean(vv),sd:sd(vv)});}const cv=100*sd(all)/mean(all),qs={p5:quant(all,.05),p10:quant(all,.10),p25:quant(all,.25),p50:quant(all,.5),p75:quant(all,.75),p90:quant(all,.90),p95:quant(all,.95)};const ptbr=patients.map(x=>x.tbr70).sort((a,b)=>a-b),sumT=ptbr.reduce((a,b)=>a+b,0),top20=100*ptbr.slice(Math.floor(.8*N)).reduce((a,b)=>a+b,0)/Math.max(sumT,1e-9);const result={protocol:{N,days:14,warmup_days:2,generator:'v0.81 S_I + D_insulin',state:{w:q.w,c:q.c},transient:{tau,amp}},population:{mean:mean(all),sd:sd(all),cv,quantiles:qs},heterogeneity:{patient_tbr70_median:quant(ptbr,.5),patient_tbr70_p80:quant(ptbr,.8),patient_tbr70_p90:quant(ptbr,.9),patient_tbr70_p95:quant(ptbr,.95),zero_tbr70_pct:100*ptbr.filter(x=>x===0).length/N,top20_hypo_share_pct:top20,between_patient_mean_sd:sd(patients.map(x=>x.mean)),median_within_patient_sd:quant(patients.map(x=>x.sd),.5)},four_check:{any_low_pct:100*checks.filter(c=>c.some(x=>x<70)).length/checks.length,any_high_pct:100*checks.filter(c=>c.some(x=>x>180)).length/checks.length,all_tir_pct:100*checks.filter(c=>c.every(x=>x>=70&&x<=180)).length/checks.length},uom:{cv:38.389,quantiles:{p5:79.280,p10:90.091,p25:108.109,p50:133.335,p75:171.173,p90:223.426,p95:257.660},four_check:{any_low_pct:7.68,any_high_pct:53.77,all_tir_pct:43.31}},hupa:{cv:38.08}};fs.writeFileSync('v090_heldout_fingerprint_result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));