const fs=require('fs'),vm=require('vm');global.window=global;const load=f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});for(const f of ['engine.js','patient_generator.js','patient_phenotype_v2.js','clinical_modifiers_v2.js','state_space_v2_finite_memory.js'])load(f);
const F=GlucoseStateSpaceV2FiniteMemory,clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),CARBS={breakfast:50,lunch:70,dinner:60},UOM={mean:146.463,sd:56.225,tbr70:2.057,tbr54:.276,tir:76.376,tar180:21.567,acf:[.863,.634,.247,-.012],poc:[121.5,149.1,153.2,154.1],anyLow:7.68,anyHigh:53.77,allTir:43.31};
function gamma2(t50,h=1200){const th=Math.max(Number(t50)/1.67835,2),k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=(t/(th*th))*Math.exp(-t/th);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
function mealKernel(p,h=1200){const f=gamma2(p.meal_t50_fast_min,h),s=gamma2(p.meal_t50_slow_min,h),q=clamp(Number(p.meal_fast_fraction),.05,.95),k=new Float64Array(h);for(let i=0;i<h;i++)k[i]=q*f[i]+(1-q)*s[i];return k}
function shifted(on,pk,dur,scale,h=1400,shape=3){on*=scale;pk*=scale;dur*=scale;const theta=Math.max((pk-on)/(shape-1),1),k=new Float64Array(h);let sum=0,taperStart=Math.max(pk,.8*dur);for(let i=0;i<h;i++){const t=i+.5,x=Math.max(t-on,0);let v=x>0?Math.pow(x,shape-1)*Math.exp(-x/theta):0;if(t>taperStart&&t<dur)v*=.5*(1+Math.cos(Math.PI*(t-taperStart)/(dur-taperStart)));if(t>=dur)v=0;k[i]=v;sum+=v}for(let i=0;i<h;i++)k[i]/=sum;return k}
function gaussian(c,sd,h=600){const k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=Math.exp(-.5*((t-c)/sd)**2);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}const E=gaussian(60,35),L=gaussian(210,60),H=new Float64Array(600);for(let i=0;i<H.length;i++)H[i]=L[i]-E[i];
function conv(n,events,k){const y=new Float64Array(n);for(const [t0,a] of events){const t=Math.trunc(t0),ks=Math.max(0,-t),ys=Math.max(0,t),m=Math.min(k.length-ks,n-ys);for(let j=0;j<m;j++)y[ys+j]+=Number(a)*k[ks+j]}return y}
function basalKernel(h=1800){const k=new Float64Array(h);let s=0;for(let t=0;t<h;t++){let v=0;if(t>=60&&t<180)v=(t-60)/120;else if(t>=180&&t<1260)v=1;else if(t>=1260&&t<1500)v=1-(t-1260)/240;k[t]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
function restoreK(p){return Math.log(2)/(300/clamp(p.egp_suppression_strength,.70,1.35))}function response(k,kh,T){let d=0;for(let t=0;t<T;t++)d+=((k[t]||0)-kh*d);return d}function roundHalf(x){return Math.round(x*2)/2}
function hash32(x){let h=2166136261>>>0;for(const c of String(x)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}function randn(seed){let a=hash32(seed),u=0,v=0;function r(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function patient(base){const p=PatientPhenotypeV2.decorate(base),q=ClinicalModifiersV2.decorateClinical(p,{egfr_ml_min_1_73m2:90,meal_plan_carb_g:CARBS});return PatientPhenotypeV2.toEnginePatient(q)}
function neutralICR(p,T=240,alpha=.10){const mk=mealKernel(p),rk=shifted(15,105,300,.80),kh=restoreK(p),ob=Number(p.incremental_obesity_insulin_action_multiplier??1),gain=clamp(5*Math.pow(70/clamp(p.body_weight_kg,40,130),.65),1,10),ig=Number(p.cf_mg_dl_u)/(-response(Float64Array.from(rk,x=>-x),kh,240)),mealPerG=new Float64Array(1200);for(let t=0;t<mealPerG.length;t++)mealPerG[t]=gain*(mk[t]||0)+alpha*gain*(H[t]||0);const mealResp=.80*response(mealPerG,kh,T),insResp=.80*ig*ob*response(rk,kh,T);return clamp(insResp/Math.max(mealResp,1e-9),2.5,35)}
function simulate(p,icr,seed,days=7,alpha=.10){const n=1441,bk=basalKernel(),rk=shifted(15,105,300,.80),mk=mealKernel(p),kh=restoreK(p),ob=Number(p.incremental_obesity_insulin_action_multiplier??1),gain=clamp(5*Math.pow(70/clamp(p.body_weight_kg,40,130),.65),1,10),ig=Number(p.cf_mg_dl_u)/(-response(Float64Array.from(rk,x=>-x),kh,240)),phys=Number(p.legacy_basal_u_day??p.basal_u_day),basalDose=roundHalf(Number(p.v2_basal_u_day??p.basal_u_day)),dose=[roundHalf(50/icr),roundHalf(70/icr),roundHalf(60/icr)];let hist=[],g0=p.fasting_setpoint_mg_dl+15,V=[],C=[];for(let d=0;d<days;d++){const cfg={memory_min:210,stationary_sd:1,basal_requirement_coupling:.28,fast_scale:.80,setpoint_shift_mg_dl:15},S=F.evolveMetabolicState(hist,1440,seed+d,cfg);hist=S.end_history;const meal=new Float64Array(n),corr=new Float64Array(n);for(const [t,c] of [[480,50],[780,70],[1140,60]]){for(let j=0;j<Math.min(mk.length,n-t);j++)meal[t+j]+=gain*c*mk[j];for(let j=0;j<Math.min(H.length,n-t);j++)corr[t+j]+=alpha*gain*c*H[j]}const bol=conv(n,[[480,dose[0]],[780,dose[1]],[1140,dose[2]]],rk),tb=conv(n,[[-120,phys]],bk),ab=conv(n,[[-120,basalDose]],bk),g=new Float64Array(n);g[0]=g0;for(let t=0;t<n-1;t++){const sm=F.modifiers(S.series[t],cfg),restore=-kh*(g[t]-(p.fasting_setpoint_mg_dl+15)),counter=Math.min(1.8,.020*p.counterreg_strength*Math.max(0,p.counterreg_threshold_mg_dl-g[t])),basal=ig*sm.basal_requirement_multiplier*tb[t]-ig*ob*ab[t],fast=sm.fast_scale*(meal[t]+corr[t]-ig*ob*bol[t]);g[t+1]=g[t]+fast+basal+restore+counter}g0=g[n-1];if(d>0){C.push([g[420],g[720],g[1080],g[1260]]);for(let i=1;i<g.length;i++)V.push(g[i])}}return{V,C,dose}}
const mean=a=>a.reduce((s,x)=>s+x,0)/a.length,sd=a=>{const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)},median=a=>{const x=[...a].sort((a,b)=>a-b),n=x.length;return n%2?x[(n-1)/2]:(x[n/2-1]+x[n/2])/2},acf=(a,l)=>{const m=mean(a);let n=0,d=0;for(let i=0;i<a.length-l;i++)n+=(a[i]-m)*(a[i+l]-m);for(const x of a)d+=(x-m)**2;return n/d};
const N=Number(process.env.N||120),sigmas=[-1,0,.05,.10,.15,.20],bases=PatientGenerator.sampleCandidates(N,7901,false).map(patient),out=[];for(const sigma of sigmas){let V=[],C=[],icrs=[],neutral=[];for(let i=0;i<N;i++){const p=bases[i],nI=neutralICR(p),icr=sigma<0?Number(p.v2_icr_g_u??p.icr_g_u):clamp(nI*Math.exp(sigma*randn(`icr:${i}`)),2.5,35);neutral.push(nI);icrs.push(icr);const r=simulate(p,icr,7901+i*100);V.push(...r.V);C.push(...r.C)}const m=mean(V),s=sd(V),A=[30,60,120,240].map(l=>median(Array.from({length:N},(_,i)=>acf(V.slice(i*6*1440,(i+1)*6*1440),l))));let l70=0,l54=0,tir=0,tar=0,anyL=0,anyH=0,allT=0;for(const x of V){if(x<70)l70++;if(x<54)l54++;if(x>=70&&x<=180)tir++;if(x>180)tar++}for(const c of C){if(c.some(x=>x<70))anyL++;if(c.some(x=>x>180))anyH++;if(c.every(x=>x>=70&&x<=180))allT++}out.push({sigma_log:sigma<0?'current_v2_icr':sigma,icr_median:median(icrs),neutral_icr_median:median(neutral),mean:m,sd:s,tbr70:100*l70/V.length,tbr54:100*l54/V.length,tir:100*tir/V.length,tar180:100*tar/V.length,acf:A,poc:[0,1,2,3].map(j=>mean(C.map(c=>c[j]))),anyLow:100*anyL/C.length,anyHigh:100*anyH/C.length,allTir:100*allT/C.length})}fs.writeFileSync('neutral_icr_generator_result.json',JSON.stringify({protocol:{N,days:7,warmup:1,neutral_endpoint_min:240,rapid_scale:.8,fast_scale:.8,alpha:.10,coupling:.28,meal_gain70:5,sigmas},uom:UOM,results:out},null,2));console.log(JSON.stringify({uom:UOM,results:out},null,2));