const fs=require('fs'),cp=require('child_process');
const src=fs.readFileSync('validation_generator_v081_si_demand_node.js','utf8');
const shapes=['box','tri','hann','gauss'];
const widths=[90,120,150,180];
const mcs=[.06,.08,.10,.12,.16];
const bws=[210,240], bcs=[.42,.48];
const configs=[];for(const bw of bws)for(const bc of bcs)for(const shape of shapes)for(const mw of widths)for(const mc of mcs)configs.push({bw,bc,shape,mw,mc});
const tau=90,amp=8,rho=Math.exp(-1/tau),innov=Math.sqrt(1-rho*rho),out=[];
for(const q of configs){let s=src;
 const inject=`\nfunction weightedState(initialHistory,minutes,seed,w,shape){let a=(seed>>>0)||1;function rr(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}function rn(){let u=0,v=0;while(!u)u=rr();while(!v)v=rr();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}const h=Array.isArray(initialHistory)?initialHistory.slice(-w):[];while(h.length<w)h.unshift(0);const wt=[];for(let i=0;i<w;i++){let x=(i+0.5)/w,v=1;if(shape==='tri')v=1-Math.abs(2*x-1);else if(shape==='hann')v=.5-.5*Math.cos(2*Math.PI*x);else if(shape==='gauss'){const z=(x-.5)/.22;v=Math.exp(-.5*z*z)}wt.push(v)}let norm=Math.sqrt(wt.reduce((a,v)=>a+v*v,0));const y=new Float64Array(minutes+1);function val(){let z=0;for(let i=0;i<w;i++)z+=wt[i]*h[i];return z/norm}y[0]=val();for(let t=0;t<minutes;t++){h.shift();h.push(rn());y[t+1]=val()}return{series:y,end_history:h}}\nfunction bipState(initialHistory,minutes,seed,w){let a=(seed>>>0)||1;function rr(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}function rn(){let u=0,v=0;while(!u)u=rr();while(!v)v=rr();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}const L=2*w,h=Array.isArray(initialHistory)?initialHistory.slice(-L):[];while(h.length<L)h.unshift(0);const y=new Float64Array(minutes+1);function val(){let a=0,b=0;for(let i=0;i<w;i++)b+=h[i];for(let i=w;i<L;i++)a+=h[i];return (a-b)/Math.sqrt(2*w)}y[0]=val();for(let t=0;t<minutes;t++){h.shift();h.push(rn());y[t+1]=val()}return{series:y,end_history:h}}\n`;
 s=s.replace("function sim(p,seed){",inject+"function sim(p,seed){");
 s=s.replace("let hist=[],g0=p.fasting_setpoint_mg_dl-5,V=[],C=[];for(let d=0;d<7;d++){const S=F.evolveMetabolicState(hist,1440,seed+d,cfg);hist=S.end_history;",`let mhist=[],bhist=[],g0=p.fasting_setpoint_mg_dl-5,V=[],C=[],tr=0,trPrev=0;for(let d=0;d<7;d++){const S=weightedState(mhist,1440,seed+d,${q.mw},'${q.shape}');mhist=S.end_history;const B=bipState(bhist,1440,seed+d+777777,${q.bw});bhist=B.end_history;`);
 s=s.replace("const z=S.series[t],mult=clamp(Math.exp(.36*z-.5*.36*.36),.55,1.8),restore=",`const z=S.series[t],zb=B.series[t],eta=${q.mc}*z+${q.bc}*zb,u=randn('v085:${q.bw}:${q.bc}:${q.shape}:${q.mw}:${q.mc}:'+seed+':'+d+':'+t),mult=clamp(Math.exp(eta-.5*(${q.mc}*${q.mc}+${q.bc}*${q.bc})),.55,1.8),restore=`);
 s=s.replace("g[t+1]=g[t]+fast+basal+restore+counter",`trPrev=tr;tr=${rho}*tr+${innov}*u;const transient=${amp}*(tr-trPrev);g[t+1]=g[t]+fast+basal+restore+counter+transient`);
 const path=`/tmp/v085_${q.bw}_${String(q.bc).replace('.','p')}_${q.shape}_${q.mw}_${String(q.mc).replace('.','p')}.json`;s=s.replace("fs.writeFileSync('generator_v081_si_demand_result.json'",`fs.writeFileSync('${path}'`);s=s.replace("console.log(JSON.stringify(result,null,2));","");const js=path.replace('.json','.js');fs.writeFileSync(js,s);cp.execFileSync(process.execPath,[js],{cwd:process.cwd(),stdio:'pipe',env:{...process.env,N:process.env.N||'120'}});const j=JSON.parse(fs.readFileSync(path,'utf8'));out.push({...q,...j.population});}
const U={mean:146.463,sd:56.225,tbr70:2.057,tbr54:.276,tir:76.376,tar180:21.567,acf:[.863,.634,.247,-.012]};for(const r of out)r.score=Math.abs(r.mean-U.mean)/10+Math.abs(r.sd-U.sd)/10+Math.abs(r.tbr70-U.tbr70)/2+3*Math.abs(r.acf[0]-U.acf[0])+3*Math.abs(r.acf[1]-U.acf[1])+4*Math.abs(r.acf[2]-U.acf[2])+6*Math.abs(r.acf[3]-U.acf[3]);out.sort((a,b)=>a.score-b.score);const result={protocol:{N:Number(process.env.N||120),question:'Can tapered medium FIR raise ACF120 without restoring ACF240?',generator:'v0.81 S_I+D + biphasic wide state + tapered medium state',transient_amp:8,configs:configs.length},uom:U,results:out};fs.writeFileSync('v085_tapered_medium_state_result.json',JSON.stringify(result,null,2));console.log(JSON.stringify({uom:U,top:out.slice(0,30)},null,2));