const fs=require('fs'),vm=require('vm');global.window=global;const load=f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
for(const f of ['engine.js','patient_generator.js','patient_phenotype_v2.js','clinical_modifiers_v2.js','dosing_policy_v2.js','state_space_v2_finite_memory.js','finite_memory_state_adapter_v2.js','engine_v2.js','engine_v2_continuous.js'])load(f);
const CARBS={breakfast:50,lunch:70,dinner:60},CHECKS=[420,720,1080,1260],LAGS=[30,60,120,240];
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}function sd(a){const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/a.length)}function corr(a,l){const n=a.length-l;if(n<3)return NaN;let sx=0,sy=0;for(let i=0;i<n;i++){sx+=a[i];sy+=a[i+l]}const mx=sx/n,my=sy/n;let xx=0,yy=0,xy=0;for(let i=0;i<n;i++){const x=a[i]-mx,y=a[i+l]-my;xx+=x*x;yy+=y*y;xy+=x*y}return xy/Math.sqrt(xx*yy)}function median(a){const x=a.filter(Number.isFinite).sort((p,q)=>p-q);return x.length%2?x[(x.length-1)/2]:(x[x.length/2-1]+x[x.length/2])/2}
function ctx(){return{rapid_formulation:'aspart',basal_formulation:'glargine',prednisone_mg:0,infection_severity:0,meal_plan_carb_g:{...CARBS},intake_fraction:{breakfast:1,lunch:1,dinner:1}}}
function makePatient(base){const p=PatientPhenotypeV2.decorate(base),q=ClinicalModifiersV2.decorateClinical(p,{egfr_ml_min_1_73m2:90,meal_plan_carb_g:CARBS});delete q.icr_g_u_by_meal;return PatientPhenotypeV2.toEnginePatient(q)}
function orderUniform(p){const r=x=>Math.round(x*2)/2;return{breakfast_u:r(50/p.v2_icr_g_u),lunch_u:r(70/p.v2_icr_g_u),dinner_u:r(60/p.v2_icr_g_u),basal_u:r(p.v2_basal_u_day)}}
function summarize(seriesByPatient,dayChecks){const all=seriesByPatient.flat(),m=mean(all),s=sd(all),time={};for(let j=0;j<4;j++){const v=dayChecks.map(r=>r[j]);time[j]={mean:mean(v),sd:sd(v)}}const ac={};for(const l of LAGS)ac[l]=median(seriesByPatient.map(a=>corr(a,l)));const vals=dayChecks;let lo=0,hi=0,alltir=0;for(const r of vals){if(r.some(x=>x<70))lo++;if(r.some(x=>x>180))hi++;if(r.every(x=>x>=70&&x<=180))alltir++}return{mean:m,sd:s,cv:100*s/m,timepoints:time,any_lt70_pct:100*lo/vals.length,any_gt180_pct:100*hi/vals.length,all_four_tir_pct:100*alltir/vals.length,autocorr:ac}}
const N=Number(process.env.N||300),DAYS=7,params={memory_min:210,stationary_sd:1,basal_requirement_coupling:.28,fast_scale:.80,setpoint_shift_mg_dl:15,circadian_off:true};
const patients=PatientGenerator.sampleCandidates(N,7901,false).map(makePatient), resetSeries=[],resetChecks=[],contSeries=[],contChecks=[];
for(let i=0;i<patients.length;i++){
 const p=patients[i],o=orderUniform(p),rapid={breakfast_u:o.breakfast_u,lunch_u:o.lunch_u,dinner_u:o.dinner_u};let st={glucose_mg_dl:p.fasting_setpoint_mg_dl+15,metabolic_state:[]},arr=[];
 for(let d=0;d<DAYS;d++){const r=GlucoseEngineV2.simulate(p,ctx(),rapid,o.basal_u,7901+i*100+d,st,params);st=r.next_state;if(d>0){for(let t=1;t<r.series.length;t++)arr.push(Number(r.series[t]));resetChecks.push(CHECKS.map(t=>Number(r.series[t])));}}
 resetSeries.push(arr);
 const c=GlucoseEngineV2Continuous.simulate(p,ctx(),rapid,o.basal_u,DAYS,7901+i*100,params),ca=[];for(let t=1440+1;t<c.series.length;t++)ca.push(Number(c.series[t]));contSeries.push(ca);for(let d=1;d<DAYS;d++)contChecks.push(CHECKS.map(t=>Number(c.series[d*1440+t])));
}
const out={protocol:{N,DAYS,warmup_days:1,uniform_icr:true,circadian_off:true},daily_reset:summarize(resetSeries,resetChecks),continuous:summarize(contSeries,contChecks),uom:{timepoints:{0:{mean:121.5,sd:48.8},1:{mean:149.1,sd:48.8},2:{mean:153.2,sd:61.6},3:{mean:154.1,sd:59.5}},any_lt70_pct:7.68,any_gt180_pct:53.77,all_four_tir_pct:43.31}};fs.writeFileSync('continuous_vs_reset_result.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
