(function(){
const CARBS={breakfast:50,lunch:70,dinner:60};
const LAGS=[30,60,120,240];
const roundHalf=x=>Math.round(Number(x)*2)/2;
function mean(a){let s=0;for(const x of a)s+=x;return s/a.length}
function sd(a){const m=mean(a);let s=0;for(const x of a)s+=(x-m)*(x-m);return Math.sqrt(s/a.length)}
function corrLag(a,lag){if(a.length<=lag+2)return NaN;let sx=0,sy=0,n=a.length-lag;for(let i=0;i<n;i++){sx+=a[i];sy+=a[i+lag]}const mx=sx/n,my=sy/n;let xx=0,yy=0,xy=0;for(let i=0;i<n;i++){const x=a[i]-mx,y=a[i+lag]-my;xx+=x*x;yy+=y*y;xy+=x*y}return xy/Math.sqrt(xx*yy)}
function median(a){const x=a.filter(Number.isFinite).sort((p,q)=>p-q),n=x.length;if(!n)return NaN;return n%2?x[(n-1)/2]:(x[n/2-1]+x[n/2])/2}
function metrics(values,perPatient){const m=mean(values),s=sd(values),n=values.length;let lt70=0,lt54=0,gt180=0,gt250=0;for(const x of values){if(x<70)lt70++;if(x<54)lt54++;if(x>180)gt180++;if(x>250)gt250++}const ac={};for(const lag of LAGS)ac[lag]=median(perPatient.map(x=>corrLag(x,lag)));return{mean:m,sd:s,cv:100*s/m,tir:100*(n-lt70-gt180)/n,tbr70:100*lt70/n,tbr54:100*lt54/n,tar180:100*gt180/n,tar250:100*gt250/n,autocorr:ac}}
function orderFor(p){return{breakfast_u:roundHalf(50/p.icr_g_u),lunch_u:roundHalf(70/p.icr_g_u),dinner_u:roundHalf(60/p.icr_g_u)}}
function context(){return{rapid_formulation:'aspart',basal_formulation:'glargine',prednisone_mg:0,patient_steroid_response:.69,infection_severity:0,meal_plan_carb_g:{...CARBS},intake_fraction:{breakfast:1,lunch:1,dinner:1}}}
function pushDay(dst,series,skipFirst){for(let i=skipFirst?1:0;i<series.length;i++)dst.push(series[i])}
function runOne(p,idx,days,stateParams){const o=orderFor(p),ctx=context(),basal=roundHalf(p.basal_u_day);let v1Start=p.fasting_setpoint_mg_dl,v2State={glucose_mg_dl:p.fasting_setpoint_mg_dl,metabolic_state:0};const a1=[],a2=[];for(let d=0;d<days;d++){const r1=GlucoseEngine.simulate(p,ctx,o,basal,7901+idx*100+d,v1Start);v1Start=r1.end;const r2=GlucoseEngineV2.simulate(p,ctx,o,basal,7901+idx*100+d,v2State,stateParams);v2State=r2.next_state;if(d>0){pushDay(a1,r1.series,true);pushDay(a2,r2.series,true)}}return{v1:a1,v2:a2}}
async function run(){const out=document.getElementById('output'),n=Math.max(25,Number(document.getElementById('n').value)||250),days=Math.max(3,Number(document.getElementById('days').value)||7);out.textContent='Running...';await new Promise(r=>setTimeout(r,30));const params={tau_min:Number(document.getElementById('tau').value)||360,stationary_sd:1,hepatic_coupling_mg_dl_min:Number(document.getElementById('hepatic').value)||0.018,insulin_sensitivity_coupling:Number(document.getElementById('isc').value)||0.08};const pts=PatientGenerator.sampleCandidates(n,7901,false),v1all=[],v2all=[],v1pp=[],v2pp=[];for(let i=0;i<pts.length;i++){const r=runOne(pts[i],i,days,params);v1pp.push(r.v1);v2pp.push(r.v2);v1all.push(...r.v1);v2all.push(...r.v2)}const result={protocol:{n:pts.length,days,warmup_days:1,meals:'fixed 50/70/60g',doses:'0.5U rounded nominal',state_params:params},v1:metrics(v1all,v1pp),v2:metrics(v2all,v2pp),targets:{T1D_UOM:{mean:146.46,sd:56.23,cv:38.39,tir:76.38,tbr70:2.06,tbr54:.276,tar180:21.57,tar250:5.94,autocorr:{30:.863,60:.634,120:.247,240:-.012}},HUPA_UCM:{mean:135.6,sd:51.6,cv:38.08,tir:77.5,tbr70:5.74,tbr54:1.26,tar180:16.74,tar250:3.43,autocorr:{30:.923,60:.779,120:.491,240:.132}}}};out.textContent=JSON.stringify(result,null,2);window.lastV2Validation=result}
document.getElementById('run').addEventListener('click',run);
})();
