const fs=require('fs'),vm=require('vm');global.window=global;const load=f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
for(const f of ['engine.js','patient_generator.js','patient_phenotype_v2.js','clinical_modifiers_v2.js','state_space_v2.js','engine_v2.js'])load(f);
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function gamma2(t50,h=900){const th=Math.max(Number(t50)/1.67835,2),k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=(t/(th*th))*Math.exp(-t/th);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
function mealKernel(p,h=900){const f=gamma2(p.meal_t50_fast_min,h),s=gamma2(p.meal_t50_slow_min,h),q=clamp(Number(p.meal_fast_fraction),.05,.95),k=new Float64Array(h);for(let i=0;i<h;i++)k[i]=q*f[i]+(1-q)*s[i];return k}
function shifted(on,pk,dur,scale,h=900,shape=3){on*=scale;pk*=scale;dur*=scale;const theta=Math.max((pk-on)/(shape-1),1),k=new Float64Array(h);let sum=0,taperStart=Math.max(pk,.8*dur);for(let i=0;i<h;i++){const t=i+.5,x=Math.max(t-on,0);let v=x>0?Math.pow(x,shape-1)*Math.exp(-x/theta):0;if(t>taperStart&&t<dur)v*=.5*(1+Math.cos(Math.PI*(t-taperStart)/(dur-taperStart)));if(t>=dur)v=0;k[i]=v;sum+=v}for(let i=0;i<h;i++)k[i]/=sum;return k}
function gaussian(center,sd,h=600){const k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=Math.exp(-.5*((t-center)/sd)**2);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
const EARLY=gaussian(60,35),LATE=gaussian(210,60),H=new Float64Array(600);for(let i=0;i<H.length;i++)H[i]=LATE[i]-EARLY[i];
function restoreK(p){return Math.log(2)/(300/clamp(p.egp_suppression_strength,.70,1.35))}
function response(k,kh,T){let d=0;for(let t=0;t<T;t++)d+=((k[t]||0)-kh*d);return d}
function patient(base){const p=PatientPhenotypeV2.decorate(base),q=ClinicalModifiersV2.decorateClinical(p,{egfr_ml_min_1_73m2:90,meal_plan_carb_g:{breakfast:50,lunch:70,dinner:60}});return PatientPhenotypeV2.toEnginePatient(q)}
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}function sd(a){const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)}function q(a,p){const x=[...a].sort((a,b)=>a-b),i=(x.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return x[l]+(x[h]-x[l])*(i-l)}function acf(x,lag){const m=mean(x);let n=0,a=0,b=0;for(let i=0;i<x.length-lag;i++){const u=x[i]-m,v=x[i+lag]-m;n+=u*v;a+=u*u;b+=v*v}return n/Math.sqrt(a*b)}
const B={b0:5.210581914736487,bw:.33484491772540936,bsi:-.7483470325321024};
function derive(p){const kh=restoreK(p),rk=shifted(15,105,300,.80),u240=-response(Float64Array.from(rk,x=>-x),kh,240),si=Number(p.cf_mg_dl_u)/Math.max(u240,1e-9),cf=si*u240;const tddPred=Math.exp(B.b0+B.bw*Math.log(p.body_weight_kg)+B.bsi*Math.log(si));const demandResidual=Number(p.tdd_u_day)/tddPred;const tdd=tddPred*demandResidual;const mk=mealKernel(p),gain=clamp(5*Math.pow(70/clamp(p.body_weight_kg,40,130),.65),1,10),mealPerGram=new Float64Array(900);for(let t=0;t<mealPerGram.length;t++)mealPerGram[t]=gain*(mk[t]||0)+.10*gain*(H[t]||0);const meal240=.80*response(mealPerGram,kh,240),ins240=.80*si*Number(p.incremental_obesity_insulin_action_multiplier??1)*response(rk,kh,240),neutralICR=ins240/Math.max(meal240,1e-9);const out={...p,si_intrinsic_gain:si,cf_mg_dl_u:cf,tdd_u_day:tdd,tdd_u_kg_day:tdd/p.body_weight_kg,icr_g_u:neutralICR,v2_icr_g_u:neutralICR};out.legacy_basal_u_day=tdd*p.basal_fraction_tdd;out.basal_u_day=out.legacy_basal_u_day/Number(out.incremental_obesity_insulin_action_multiplier??1);return out}
function roundHalf(x){return Math.round(x*2)/2}
const N=Number(process.env.N||120),days=7,warm=1,bases=PatientGenerator.sampleCandidates(N,13171,false).map(patient).map(derive),all=[],checks=[[],[],[],[]],dayRows=[];
const cfg={memory_min:90,stationary_sd:1,basal_requirement_coupling:.36,fast_scale:.80,setpoint_shift_mg_dl:-5};
for(let i=0;i<bases.length;i++){const p=bases[i],ctx={rapid_formulation:'aspart',basal_formulation:'glargine',prednisone_mg:0,infection_severity:0,meal_plan_carb_g:{breakfast:50,lunch:70,dinner:60},intake_fraction:{breakfast:1,lunch:1,dinner:1}},ord={breakfast_u:roundHalf(50/p.icr_g_u),lunch_u:roundHalf(70/p.icr_g_u),dinner_u:roundHalf(60/p.icr_g_u)},basal=roundHalf(p.basal_u_day);let st=null;for(let d=0;d<days;d++){const r=GlucoseEngineV2.simulate(p,ctx,ord,basal,800000+i*31+d,st,cfg);st=r.next_state;if(d<warm)continue;const s=Array.from(r.series);all.push(...s.slice(0,1440));const c=[r.bg.pre_breakfast,r.bg.pre_lunch,r.bg.pre_dinner,r.bg.bedtime];c.forEach((v,j)=>checks[j].push(v));dayRows.push(c)}}
const flat=all,m=mean(flat),S=sd(flat),tbr70=100*flat.filter(x=>x<70).length/flat.length,tbr54=100*flat.filter(x=>x<54).length/flat.length,tir=100*flat.filter(x=>x>=70&&x<=180).length/flat.length,tar180=100*flat.filter(x=>x>180).length/flat.length;const anyLow=100*dayRows.filter(c=>c.some(x=>x<70)).length/dayRows.length,anyHigh=100*dayRows.filter(c=>c.some(x=>x>180)).length/dayRows.length,allTir=100*dayRows.filter(c=>c.every(x=>x>=70&&x<=180)).length/dayRows.length;
const result={protocol:{N,days,warmup:warm,generator:'v0.80 validation-only S_I primitive candidate',si:'primitive insulin gain reconstructed exactly from old CF for migration',cf:'derived from S_I x 240-min 1U response',tdd:'derived from S_I+weight plus preserved demand residual',icr:'240-min neutral meal-vs-insulin ICR',state:cfg},population:{mean:m,sd:S,tbr70,tbr54,tir,tar180,acf:[acf(flat,30),acf(flat,60),acf(flat,120),acf(flat,240)],poc:checks.map(mean),anyLow,anyHigh,allTir},phenotype:{si_mean:mean(bases.map(p=>p.si_intrinsic_gain)),si_sd:sd(bases.map(p=>p.si_intrinsic_gain)),icr_mean:mean(bases.map(p=>p.icr_g_u)),icr_sd:sd(bases.map(p=>p.icr_g_u)),tdd_mean:mean(bases.map(p=>p.tdd_u_day)),tdd_sd:sd(bases.map(p=>p.tdd_u_day)),demand_residual_log_sd:sd(bases.map(p=>Math.log(p.tdd_u_day/Math.exp(B.b0+B.bw*Math.log(p.body_weight_kg)+B.bsi*Math.log(p.si_intrinsic_gain)))))} ,uom:{mean:146.463,sd:56.225,tbr70:2.057,tbr54:.276,tir:76.376,tar180:21.567,acf:[.863,.634,.247,-.012],poc:[121.5,149.1,153.2,154.1],anyLow:7.68,anyHigh:53.77,allTir:43.31}};
fs.writeFileSync('generator_v080_si_primitive_result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));