const fs=require('fs'),vm=require('vm');global.window=global;const load=f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
for(const f of ['engine.js','patient_generator.js','patient_phenotype_v2.js','clinical_modifiers_v2.js','state_space_v2_finite_memory.js'])load(f);
const F=GlucoseStateSpaceV2FiniteMemory,CARBS={breakfast:50,lunch:70,dinner:60},clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function gamma2(t50,h){const th=Math.max(Number(t50)/1.67835,2),k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=(t/(th*th))*Math.exp(-t/th);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
function mealKernel(p,h=1200){const f=gamma2(p.meal_t50_fast_min,h),s=gamma2(p.meal_t50_slow_min,h),q=clamp(Number(p.meal_fast_fraction),.05,.95),k=new Float64Array(h);for(let i=0;i<h;i++)k[i]=q*f[i]+(1-q)*s[i];return k}
function shifted(on,pk,dur,scale,h=1400,shape=3){on*=scale;pk*=scale;dur*=scale;const theta=Math.max((pk-on)/(shape-1),1),k=new Float64Array(h);let sum=0,taperStart=Math.max(pk,.8*dur);for(let i=0;i<h;i++){const t=i+.5,x=Math.max(t-on,0);let v=x>0?Math.pow(x,shape-1)*Math.exp(-x/theta):0;if(t>taperStart&&t<dur)v*=.5*(1+Math.cos(Math.PI*(t-taperStart)/(dur-taperStart)));if(t>=dur)v=0;k[i]=v;sum+=v}for(let i=0;i<h;i++)k[i]/=sum;return k}
function gaussian(c,sd,h=600){const k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=Math.exp(-.5*((t-c)/sd)**2);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
const E=gaussian(60,35),L=gaussian(210,60),H=new Float64Array(600);for(let i=0;i<H.length;i++)H[i]=L[i]-E[i];
function conv(n,events,k){const y=new Float64Array(n);for(const [t0,a] of events){const t=Math.trunc(t0),ks=Math.max(0,-t),ys=Math.max(0,t),m=Math.min(k.length-ks,n-ys);for(let j=0;j<m;j++)y[ys+j]+=Number(a)*k[ks+j]}return y}
function basalKernel(h=1800){const k=new Float64Array(h);let s=0;for(let t=0;t<h;t++){let v=0;if(t>=60&&t<180)v=(t-60)/120;else if(t>=180&&t<1260)v=1;else if(t>=1260&&t<1500)v=1-(t-1260)/240;k[t]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
function restoreK(p){return Math.log(2)/(300/clamp(p.egp_suppression_strength,.70,1.35))}
function unitResponse(p,k,mins=240){const kh=restoreK(p);let d=0;for(let t=0;t<mins;t++)d+=(-(k[t]||0)-kh*d);return Math.max(1e-6,-d)}
function patient(base){const p=PatientPhenotypeV2.decorate(base),q=ClinicalModifiersV2.decorateClinical(p,{egfr_ml_min_1_73m2:90,meal_plan_carb_g:CARBS});return PatientPhenotypeV2.toEnginePatient(q)}
function roundHalf(x){return Math.round(x*2)/2}
function simulate(p,seed,days=14,alpha=.10){const n=1441,bk=basalKernel(),rk=shifted(15,105,300,.80),ig=p.cf_mg_dl_u/unitResponse(p,rk,240),kh=restoreK(p),ob=Number(p.incremental_obesity_insulin_action_multiplier??1),phys=Number(p.legacy_basal_u_day??p.basal_u_day),basalDose=roundHalf(Number(p.v2_basal_u_day??p.basal_u_day)),icr=Number(p.v2_icr_g_u??p.icr_g_u),dose=[roundHalf(50/icr),roundHalf(70/icr),roundHalf(60/icr)],gain=clamp(5*Math.pow(70/clamp(p.body_weight_kg,40,130),.65),1,10),mk=mealKernel(p);let hist=[],g0=p.fasting_setpoint_mg_dl+15,vals=[],checks=[];for(let d=0;d<days;d++){const cfg={memory_min:210,stationary_sd:1,basal_requirement_coupling:.28,fast_scale:.80,setpoint_shift_mg_dl:15},S=F.evolveMetabolicState(hist,1440,seed+d,cfg);hist=S.end_history;const meal=new Float64Array(n),corr=new Float64Array(n);for(const [t,c] of [[480,50],[780,70],[1140,60]]){for(let j=0;j<Math.min(mk.length,n-t);j++)meal[t+j]+=gain*c*mk[j];for(let j=0;j<Math.min(H.length,n-t);j++)corr[t+j]+=alpha*gain*c*H[j]}const bol=conv(n,[[480,dose[0]],[780,dose[1]],[1140,dose[2]]],rk),targetB=conv(n,[[-120,phys]],bk),actualB=conv(n,[[-120,basalDose]],bk),g=new Float64Array(n);g[0]=g0;for(let t=0;t<n-1;t++){const sm=F.modifiers(S.series[t],cfg),restore=-kh*(g[t]-(p.fasting_setpoint_mg_dl+15)),counter=Math.min(1.8,.020*p.counterreg_strength*Math.max(0,p.counterreg_threshold_mg_dl-g[t])),basal=ig*sm.basal_requirement_multiplier*targetB[t]-ig*ob*actualB[t],fast=sm.fast_scale*(meal[t]+corr[t]-ig*ob*bol[t]);g[t+1]=g[t]+fast+basal+restore+counter}g0=g[n-1];if(d>1){for(let i=1;i<g.length;i++)vals.push(g[i]);checks.push([g[420],g[720],g[1080],g[1260]])}}let n70=0,n54=0,min=Infinity;for(const v of vals){if(v<70)n70++;if(v<54)n54++;if(v<min)min=v}let any=0;for(const c of checks)if(c.some(v=>v<70))any++;return{tbr70:100*n70/vals.length,tbr54:100*n54/vals.length,min,anyLow:100*any/checks.length,dose,gain,ig}}
function median(a){const x=[...a].sort((a,b)=>a-b),n=x.length;return n%2?x[(n-1)/2]:(x[n/2-1]+x[n/2])/2}
function q(a,p){const x=[...a].sort((a,b)=>a-b),i=(x.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return x[l]+(x[h]-x[l])*(i-l)}
function pearson(a,b){const ma=a.reduce((s,x)=>s+x,0)/a.length,mb=b.reduce((s,x)=>s+x,0)/b.length;let n=0,da=0,db=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;n+=x*y;da+=x*x;db+=y*y}return n/Math.sqrt(da*db)}
const N=Number(process.env.N||300),bases=PatientGenerator.sampleCandidates(N,7901,false).map(patient),rows=[];for(let i=0;i<bases.length;i++){const p=bases[i],r=simulate(p,7901+i*100);rows.push({i,tbr70:r.tbr70,tbr54:r.tbr54,min:r.min,anyLow:r.anyLow,weight:p.body_weight_kg,legacy_icr:p.icr_g_u,v2_icr:p.v2_icr_g_u,legacy_cf:p.cf_mg_dl_u,v2_cf:p.v2_cf_mg_dl_u,counterreg_threshold:p.counterreg_threshold_mg_dl,counterreg_strength:p.counterreg_strength,meal_t50_fast:p.meal_t50_fast_min,meal_t50_slow:p.meal_t50_slow_min,meal_fast_fraction:p.meal_fast_fraction,egp:p.egp_suppression_strength,z_sens:p.z_insulin_sensitivity,z_need:p.z_insulin_need,tdd:p.tdd_u_day,dose_sum:r.dose.reduce((a,b)=>a+b,0),gain:r.gain,ig:r.ig})}
rows.sort((a,b)=>b.tbr70-a.tbr70);const tbr=rows.map(r=>r.tbr70),topCut=q(tbr,.8),top=rows.filter(r=>r.tbr70>=topCut),rest=rows.filter(r=>r.tbr70<topCut),keys=['legacy_icr','legacy_cf','counterreg_threshold','counterreg_strength','meal_t50_fast','meal_t50_slow','meal_fast_fraction','egp','z_sens','z_need','tdd','dose_sum','gain','ig','weight'];const summarize=g=>Object.fromEntries(keys.map(k=>[k,median(g.map(r=>Number(r[k])))]));const cor=Object.fromEntries(keys.map(k=>[k,pearson(rows.map(r=>Number(r[k])),rows.map(r=>r.tbr70)]));const result={protocol:{N,days:14,warmup_days:2,alpha:.10,rapid_scale:.8,fast_scale:.8,coupling:.28,gain70:5},distribution:{median_tbr70:median(tbr),p80:topCut,p90:q(tbr,.9),p95:q(tbr,.95),max:Math.max(...tbr),share_patients_with_zero_tbr70:100*rows.filter(r=>r.tbr70===0).length/N,share_total_hypo_minutes_from_top20:100*top.reduce((s,r)=>s+r.tbr70,0)/rows.reduce((s,r)=>s+r.tbr70,0)},top20_medians:summarize(top),other80_medians:summarize(rest),correlation_with_tbr70:cor,top20_patients:top.slice(0,30),rows};fs.writeFileSync('patient_hypo_heterogeneity_result.json',JSON.stringify(result,null,2));console.log(JSON.stringify({protocol:result.protocol,distribution:result.distribution,top20_medians:result.top20_medians,other80_medians:result.other80_medians,correlation_with_tbr70:result.correlation_with_tbr70},null,2));