const fs=require('fs'),vm=require('vm');global.window=global;const load=f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
for(const f of ['engine.js','patient_generator.js','patient_phenotype_v2.js','clinical_modifiers_v2.js'])load(f);
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function gamma2(t50,h=900){const th=Math.max(Number(t50)/1.67835,2),k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=(t/(th*th))*Math.exp(-t/th);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
function mealKernel(p,h=900){const f=gamma2(p.meal_t50_fast_min,h),s=gamma2(p.meal_t50_slow_min,h),q=clamp(Number(p.meal_fast_fraction),.05,.95),k=new Float64Array(h);for(let i=0;i<h;i++)k[i]=q*f[i]+(1-q)*s[i];return k}
function shifted(on,pk,dur,scale,h=900,shape=3){on*=scale;pk*=scale;dur*=scale;const theta=Math.max((pk-on)/(shape-1),1),k=new Float64Array(h);let sum=0,taperStart=Math.max(pk,.8*dur);for(let i=0;i<h;i++){const t=i+.5,x=Math.max(t-on,0);let v=x>0?Math.pow(x,shape-1)*Math.exp(-x/theta):0;if(t>taperStart&&t<dur)v*=.5*(1+Math.cos(Math.PI*(t-taperStart)/(dur-taperStart)));if(t>=dur)v=0;k[i]=v;sum+=v}for(let i=0;i<h;i++)k[i]/=sum;return k}
function gaussian(center,sd,h=600){const k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=Math.exp(-.5*((t-center)/sd)**2);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
const EARLY=gaussian(60,35),LATE=gaussian(210,60),H=new Float64Array(600);for(let i=0;i<H.length;i++)H[i]=LATE[i]-EARLY[i];
function restoreK(p){return Math.log(2)/(300/clamp(p.egp_suppression_strength,.70,1.35))}
function response(k,kh,T){let d=0;for(let t=0;t<T;t++)d+=((k[t]||0)-kh*d);return d}
function patient(base){const p=PatientPhenotypeV2.decorate(base),q=ClinicalModifiersV2.decorateClinical(p,{egfr_ml_min_1_73m2:90,meal_plan_carb_g:{breakfast:50,lunch:70,dinner:60}});return PatientPhenotypeV2.toEnginePatient(q)}
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}function sd(a){const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)}function median(a){const x=[...a].sort((a,b)=>a-b),n=x.length;return n%2?x[(n-1)/2]:(x[n/2-1]+x[n/2])/2}function q(a,p){const x=[...a].sort((a,b)=>a-b),i=(x.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return x[l]+(x[h]-x[l])*(i-l)}function corr(a,b){const ma=mean(a),mb=mean(b);let n=0,da=0,db=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;n+=x*y;da+=x*x;db+=y*y}return n/Math.sqrt(da*db)}
const N=Number(process.env.N||1000),alpha=.10,fast=.80,rapid=.80,carb=50,endpoints=[180,240,300],bases=PatientGenerator.sampleCandidates(N,9107,false).map(patient),rows=[];
for(const p of bases){const mk=mealKernel(p),rk=shifted(15,105,300,rapid),kh=restoreK(p),ob=Number(p.incremental_obesity_insulin_action_multiplier??1),gain=clamp(5*Math.pow(70/clamp(p.body_weight_kg,40,130),.65),1,10),ig=Number(p.cf_mg_dl_u)/(-response(Float64Array.from(rk,x=>-x),kh,240));const mealPerGram=new Float64Array(900);for(let t=0;t<mealPerGram.length;t++)mealPerGram[t]=gain*(mk[t]||0)+alpha*gain*(H[t]||0);const out={legacy_cf:Number(p.cf_mg_dl_u),legacy_icr:Number(p.icr_g_u),v2_icr:Number(p.v2_icr_g_u??p.icr_g_u),ob,weight:Number(p.body_weight_kg),gain};for(const T of endpoints){const mealResp=fast*response(mealPerGram,kh,T);const insulinRespPerU=fast*ig*ob*response(rk,kh,T);const effCF=insulinRespPerU,units=(carb*mealResp)/Math.max(insulinRespPerU,1e-9),effICR=carb/Math.max(units,1e-9);out['meal_mgdl_per_g_'+T]=mealResp;out['effective_cf_'+T]=effCF;out['effective_icr_'+T]=effICR;out['effective_ratio_'+T]=effCF/effICR}rows.push(out)}
function summary(T){const cf=rows.map(r=>r['effective_cf_'+T]),icr=rows.map(r=>r['effective_icr_'+T]),rat=rows.map(r=>r['effective_ratio_'+T]),lr=rows.map(r=>r.legacy_cf/r.legacy_icr);return{endpoint_min:T,effective_cf:{mean:mean(cf),sd:sd(cf),median:median(cf),p10:q(cf,.1),p90:q(cf,.9)},effective_icr:{mean:mean(icr),sd:sd(icr),median:median(icr),p10:q(icr,.1),p90:q(icr,.9)},effective_ratio:{geomean:Math.exp(mean(rat.map(Math.log))),log_sd:sd(rat.map(Math.log)),median:median(rat),p10:q(rat,.1),p90:q(rat,.9)},correlations:{effective_cf_icr:corr(cf,icr),label_cf_icr:corr(rows.map(r=>r.legacy_cf),rows.map(r=>r.legacy_icr)),label_ratio_vs_effective_ratio:corr(lr,rat),weight_vs_effective_ratio:corr(rows.map(r=>r.weight),rat),meal_gain_vs_effective_ratio:corr(rows.map(r=>r.gain),rat)}}}
const result={protocol:{N,virtual_tests:'isolated 1U correction and 50g meal, no basal/state/counterreg; same restore dynamics; continuous neutral bolus',rapid_scale:rapid,fast_scale:fast,zero_area_alpha:alpha,endpoints_min:endpoints,meal_gain:'5 mg/dL/g at 70kg with weight exponent 0.65'},literature_reference:{CF_per_ICR:4.44,reported_cf_icr_r:0.90},label_distribution:{cf:{mean:mean(rows.map(r=>r.legacy_cf)),sd:sd(rows.map(r=>r.legacy_cf))},icr:{mean:mean(rows.map(r=>r.legacy_icr)),sd:sd(rows.map(r=>r.legacy_icr))},corr_cf_icr:corr(rows.map(r=>r.legacy_cf),rows.map(r=>r.legacy_icr)),ratio_geomean:Math.exp(mean(rows.map(r=>Math.log(r.legacy_cf/r.legacy_icr)))),ratio_log_sd:sd(rows.map(r=>Math.log(r.legacy_cf/r.legacy_icr)))},effective:endpoints.map(summary)};
fs.writeFileSync('effective_cf_icr_result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));