const fs=require('fs'),vm=require('vm');global.window=global;const load=f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
for(const f of ['engine.js','patient_generator.js','patient_phenotype_v2.js','clinical_modifiers_v2.js','state_space_v2_finite_memory.js'])load(f);
const F=GlucoseStateSpaceV2FiniteMemory,CARBS={breakfast:50,lunch:70,dinner:60};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function gamma2(t50,h){const th=Math.max(Number(t50)/1.67835,2),k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=(t/(th*th))*Math.exp(-t/th);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
function mealKernelPatient(p,carb,h=1200){const f=gamma2(p.meal_t50_fast_min,h),s=gamma2(p.meal_t50_slow_min,h),q=clamp(Number(p.meal_fast_fraction),.05,.95),k=new Float64Array(h);for(let i=0;i<h;i++)k[i]=q*f[i]+(1-q)*s[i];return k}
function shifted(on,pk,dur,scale,h=1400,shape=3){on*=scale;pk*=scale;dur*=scale;const theta=Math.max((pk-on)/(shape-1),1),k=new Float64Array(h);let sum=0,taperStart=Math.max(pk,.8*dur);for(let i=0;i<h;i++){const t=i+.5,x=Math.max(t-on,0);let v=x>0?Math.pow(x,shape-1)*Math.exp(-x/theta):0;if(t>taperStart&&t<dur)v*=.5*(1+Math.cos(Math.PI*(t-taperStart)/(dur-taperStart)));if(t>=dur)v=0;k[i]=v;sum+=v}for(let i=0;i<h;i++)k[i]/=sum;return k}
function conv(n,events,k){const y=new Float64Array(n);for(const [t0,a] of events){const t=Math.trunc(t0),ks=Math.max(0,-t),ys=Math.max(0,t),m=Math.min(k.length-ks,n-ys);for(let j=0;j<m;j++)y[ys+j]+=Number(a)*k[ks+j]}return y}
function addMeals(n,p,gain){const y=new Float64Array(n);for(const [t,carb] of [[480,50],[780,70],[1140,60]]){const k=mealKernelPatient(p,carb),m=Math.min(k.length,n-t);for(let j=0;j<m;j++)y[t+j]+=gain*carb*k[j]}return y}
function basalKernel(h=1800){const k=new Float64Array(h);let s=0;for(let t=0;t<h;t++){let v=0;if(t>=60&&t<180)v=(t-60)/120;else if(t>=180&&t<1260)v=1;else if(t>=1260&&t<1500)v=1-(t-1260)/240;k[t]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
function restoreK(p){return Math.log(2)/(300/clamp(p.egp_suppression_strength,.70,1.35))}
function unitResponse(p,k,mins=240){const kh=restoreK(p);let d=0;for(let t=0;t<mins;t++)d+=(-(k[t]||0)-kh*d);return Math.max(1e-6,-d)}
function patient(base){const p=PatientPhenotypeV2.decorate(base),q=ClinicalModifiersV2.decorateClinical(p,{egfr_ml_min_1_73m2:90,meal_plan_carb_g:CARBS});return PatientPhenotypeV2.toEnginePatient(q)}
function roundHalf(x){return Math.round(x*2)/2}
const CONDITIONS=[
 {name:'baseline',meal:1,bolus:1,basal:1,restore:1,counter:1},
 {name:'bolus_80pct',meal:1,bolus:.8,basal:1,restore:1,counter:1},
 {name:'bolus_off',meal:1,bolus:0,basal:1,restore:1,counter:1},
 {name:'basal_80pct',meal:1,bolus:1,basal:.8,restore:1,counter:1},
 {name:'basal_off',meal:1,bolus:1,basal:0,restore:1,counter:1},
 {name:'restore_80pct',meal:1,bolus:1,basal:1,restore:.8,counter:1},
 {name:'restore_off',meal:1,bolus:1,basal:1,restore:0,counter:1},
 {name:'counter_150pct',meal:1,bolus:1,basal:1,restore:1,counter:1.5},
 {name:'counter_off',meal:1,bolus:1,basal:1,restore:1,counter:0},
 {name:'meal_off',meal:0,bolus:1,basal:1,restore:1,counter:1}
];
function simulate(p,seed,c,days=7){const n=1441,bk=basalKernel(),rk=shifted(15,105,300,.80),ig=p.cf_mg_dl_u/unitResponse(p,rk,240),kh=restoreK(p),ob=Number(p.incremental_obesity_insulin_action_multiplier??1),phys=Number(p.legacy_basal_u_day??p.basal_u_day),basalDose=roundHalf(Number(p.v2_basal_u_day??p.basal_u_day)),icr=Number(p.v2_icr_g_u??p.icr_g_u),dose=[roundHalf(50/icr),roundHalf(70/icr),roundHalf(60/icr)],gain=clamp(5.0*Math.pow(70/clamp(p.body_weight_kg,40,130),.65),1,10);let hist=[],g0=p.fasting_setpoint_mg_dl+15,checks=[],series=[],minutesLow=0,minutes54=0;for(let d=0;d<days;d++){const E=F.evolveMetabolicState(hist,1440,seed+d,{memory_min:210,stationary_sd:1,basal_requirement_coupling:.28,fast_scale:.80,setpoint_shift_mg_dl:15});hist=E.end_history;const meal=addMeals(n,p,gain),bol=conv(n,[[480,dose[0]],[780,dose[1]],[1140,dose[2]]],rk),targetB=conv(n,[[-120,phys]],bk),actualB=conv(n,[[-120,basalDose]],bk),g=new Float64Array(n);g[0]=g0;for(let t=0;t<n-1;t++){const sm=F.modifiers(E.series[t],{memory_min:210,stationary_sd:1,basal_requirement_coupling:.28,fast_scale:.80,setpoint_shift_mg_dl:15}),restore=c.restore*(-kh*(g[t]-(p.fasting_setpoint_mg_dl+15))),counter=c.counter*Math.min(1.8,.020*p.counterreg_strength*Math.max(0,p.counterreg_threshold_mg_dl-g[t])),basal=c.basal*(ig*sm.basal_requirement_multiplier*targetB[t]-ig*ob*actualB[t]),fast=sm.fast_scale*(c.meal*meal[t]-c.bolus*ig*ob*bol[t]);g[t+1]=g[t]+fast+basal+restore+counter}g0=g[n-1];if(d>0){checks.push([g[420],g[720],g[1080],g[1260]]);for(let i=1;i<g.length;i++){series.push(g[i]);if(g[i]<70)minutesLow++;if(g[i]<54)minutes54++;}}}return{checks,series,minutesLow,minutes54}}
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}function sd(a){const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/a.length)}function acf(a,lag){const m=mean(a);let n=0,d=0;for(let i=0;i<a.length-lag;i++)n+=(a[i]-m)*(a[i+lag]-m);for(const x of a)d+=(x-m)*(x-m);return d? n/d:NaN}function median(a){const x=a.filter(Number.isFinite).sort((a,b)=>a-b),n=x.length;return n%2?x[(n-1)/2]:(x[n/2-1]+x[n/2])/2}
const N=Number(process.env.N||120),bases=PatientGenerator.sampleCandidates(N,7901,false).map(patient),out=[];
for(const c of CONDITIONS){let C=[],V=[],loDays=0,lo54Days=0,totalDays=0,lowMin=0,low54Min=0,pa={30:[],60:[],120:[],240:[]};for(let i=0;i<bases.length;i++){const r=simulate(bases[i],7901+i*100,c);C.push(...r.checks);V.push(...r.series);lowMin+=r.minutesLow;low54Min+=r.minutes54;for(const x of r.checks){totalDays++;if(x.some(v=>v<70))loDays++;if(x.some(v=>v<54))lo54Days++;}for(const lag of [30,60,120,240])pa[lag].push(acf(r.series,lag))}const m=[0,1,2,3].map(j=>mean(C.map(x=>x[j])));out.push({name:c.name,poc_mean:m,overall_mean:mean(V),overall_sd:sd(V),tbr70_pct:100*lowMin/V.length,tbr54_pct:100*low54Min/V.length,any_check_lt70_pct:100*loDays/totalDays,any_check_lt54_pct:100*lo54Days/totalDays,median_acf30:median(pa[30]),median_acf60:median(pa[60]),median_acf120:median(pa[120]),median_acf240:median(pa[240])})}
const result={protocol:{N,days:7,warmup:1,patient_specific_meal_kinetics:true,meal_gain_70kg:5.0,no_saturation:true,rapid_scale:.8,bolus_lead_min:0,state:{memory:210,coupling:.28,fast_scale:.80,shift:15},acf:'median within-patient'},uom:{overall_mean:146.463,overall_sd:56.225,tbr70_pct:2.057,tbr54_pct:.276,any_check_lt70_pct:7.68,median_acf:[.863,.634,.247,-.012]},results:out};fs.writeFileSync('hypoglycemia_source_ablation_result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));