const fs=require('fs'),vm=require('vm');global.window=global;const load=f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
for(const f of ['engine.js','patient_generator.js','patient_phenotype_v2.js','clinical_modifiers_v2.js','dosing_policy_v2.js','state_space_v2.js'])load(f);
const OU_STATE=global.GlucoseStateSpaceV2;load('state_space_v2_finite_memory.js');const FINITE_NATIVE=global.GlucoseStateSpaceV2FiniteMemory;load('finite_memory_state_adapter_v2.js');const FINITE_STATE=global.GlucoseStateSpaceV2;load('engine_v2.js');const ENGINE_DIRECT=global.GlucoseEngineV2;load('transient_requirement_state_v2.js');load('engine_v2_transient.js');
const LAGS=[30,60,120,240],CARBS={breakfast:50,lunch:70,dinner:60};
function mean(a){let s=0;for(const x of a)s+=x;return s/a.length}function sd(a){const m=mean(a);let s=0;for(const x of a)s+=(x-m)*(x-m);return Math.sqrt(s/a.length)}function corr(a,l){const n=a.length-l;if(n<3)return NaN;let sx=0,sy=0;for(let i=0;i<n;i++){sx+=a[i];sy+=a[i+l]}const mx=sx/n,my=sy/n;let xx=0,yy=0,xy=0;for(let i=0;i<n;i++){const x=a[i]-mx,y=a[i+l]-my;xx+=x*x;yy+=y*y;xy+=x*y}return xx&&yy?xy/Math.sqrt(xx*yy):NaN}function median(a){const x=a.filter(Number.isFinite).sort((p,q)=>p-q),n=x.length;return n%2?x[(n-1)/2]:(x[n/2-1]+x[n/2])/2}function metrics(v,pp){const m=mean(v),s=sd(v),n=v.length;let a=0,b=0,c=0,d=0;for(const x of v){if(x<70)a++;if(x<54)b++;if(x>180)c++;if(x>250)d++}const ac={};for(const l of LAGS)ac[l]=median(pp.map(x=>corr(x,l)));return{mean:m,sd:s,cv:100*s/m,tir:100*(n-a-c)/n,tbr70:100*a/n,tbr54:100*b/n,tar180:100*c/n,tar250:100*d/n,autocorr:ac}}
const ctx=()=>({rapid_formulation:'aspart',basal_formulation:'glargine',prednisone_mg:0,infection_severity:0,meal_plan_carb_g:{...CARBS},intake_fraction:{breakfast:1,lunch:1,dinner:1}}),add=(a,s)=>{for(let i=1;i<s.length;i++)a.push(Number(s[i]))};
function makePatient(base){const p=PatientPhenotypeV2.decorate(base),q=ClinicalModifiersV2.decorateClinical(p,{egfr_ml_min_1_73m2:90,meal_plan_carb_g:CARBS});return PatientPhenotypeV2.toEnginePatient(q)}
function runDirect(p,i,days,stateModule,params){global.GlucoseStateSpaceV2=stateModule;const o=DosingPolicyV2.starterOrder(p,CARBS),rapid={breakfast_u:o.breakfast_u,lunch_u:o.lunch_u,dinner_u:o.dinner_u},b=o.basal_u,a=[];let st={glucose_mg_dl:p.fasting_setpoint_mg_dl+(params.setpoint_shift_mg_dl||0),metabolic_state:stateModule===FINITE_STATE?[]:0};for(let day=0;day<days;day++){const r=ENGINE_DIRECT.simulate(p,ctx(),rapid,b,7901+i*100+day,st,params);st=r.next_state;if(day>0)add(a,r.series)}return a}
function runTransient(p,i,days,params){const o=DosingPolicyV2.starterOrder(p,CARBS),rapid={breakfast_u:o.breakfast_u,lunch_u:o.lunch_u,dinner_u:o.dinner_u},b=o.basal_u,a=[];let st={glucose_mg_dl:p.fasting_setpoint_mg_dl+(params.setpoint_shift_mg_dl||0),metabolic_history:[],metabolic_effect_mg_dl:0};for(let day=0;day<days;day++){const r=GlucoseEngineV2Transient.simulate(p,ctx(),rapid,b,7901+i*100+day,st,params);st=r.next_state;if(day>0)add(a,r.series)}return a}
function cohort(run,params){const all=[],pp=[];for(let i=0;i<patients.length;i++){const a=run(patients[i],i,DAYS,params);pp.push(a);all.push(...a)}return metrics(all,pp)}
const N=Number(process.env.N||300),DAYS=Number(process.env.DAYS||7),bases=PatientGenerator.sampleCandidates(N,7901,false),patients=bases.map(makePatient);
const common={stationary_sd:1,fast_scale:Number(process.env.FAST_SCALE||0.74),setpoint_shift_mg_dl:Number(process.env.SETPOINT_SHIFT||15)};
const ou={...common,tau_min:Number(process.env.OU_TAU||120),basal_requirement_coupling:Number(process.env.COUPLING||0.28)};
const fin={...common,memory_min:Number(process.env.MEMORY||180),basal_requirement_coupling:Number(process.env.COUPLING||0.28)};
const trans={...common,memory_min:Number(process.env.MEMORY||180),effect_half_life_min:Number(process.env.EFFECT_HALF||45),effect_gain_mg_dl:Number(process.env.EFFECT_GAIN||25)};
const out={protocol:{N,DAYS,warmup:1},ou:{params:ou,metrics:cohort((p,i,d,x)=>runDirect(p,i,d,OU_STATE,x),ou)},finite_direct:{params:fin,metrics:cohort((p,i,d,x)=>runDirect(p,i,d,FINITE_STATE,x),fin)},transient:{params:trans,metrics:cohort(runTransient,trans)},targets:{T1D_UOM:{mean:146.46,sd:56.23,cv:38.39,autocorr:{30:.863,60:.634,120:.247,240:-.012}},HUPA_UCM:{mean:135.6,sd:51.6,cv:38.08,autocorr:{30:.923,60:.779,120:.491,240:.132}}}};fs.writeFileSync('state_shape_3way_result.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));