const fs=require('fs'),vm=require('vm');global.window=global;const load=f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
for(const f of ['engine.js','patient_generator.js','patient_phenotype_v2.js','clinical_modifiers_v2.js'])load(f);
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function gamma2(t50,h=900){const th=Math.max(Number(t50)/1.67835,2),k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=(t/(th*th))*Math.exp(-t/th);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
function mealKernel(p,h=900){const f=gamma2(p.meal_t50_fast_min,h),s=gamma2(p.meal_t50_slow_min,h),q=clamp(Number(p.meal_fast_fraction),.05,.95),k=new Float64Array(h);for(let i=0;i<h;i++)k[i]=q*f[i]+(1-q)*s[i];return k}
function shifted(on,pk,dur,scale,h=900,shape=3){on*=scale;pk*=scale;dur*=scale;const theta=Math.max((pk-on)/(shape-1),1),k=new Float64Array(h);let sum=0,taperStart=Math.max(pk,.8*dur);for(let i=0;i<h;i++){const t=i+.5,x=Math.max(t-on,0);let v=x>0?Math.pow(x,shape-1)*Math.exp(-x/theta):0;if(t>taperStart&&t<dur)v*=.5*(1+Math.cos(Math.PI*(t-taperStart)/(dur-taperStart)));if(t>=dur)v=0;k[i]=v;sum+=v}for(let i=0;i<h;i++)k[i]/=sum;return k}
function gaussian(center,sd,h=600){const k=new Float64Array(h);let s=0;for(let i=0;i<h;i++){const t=i+.5,v=Math.exp(-.5*((t-center)/sd)**2);k[i]=v;s+=v}for(let i=0;i<h;i++)k[i]/=s;return k}
const EARLY=gaussian(60,35),LATE=gaussian(210,60),H=new Float64Array(600);for(let i=0;i<H.length;i++)H[i]=LATE[i]-EARLY[i];
function restoreK(p){return Math.log(2)/(300/clamp(p.egp_suppression_strength,.70,1.35))}
function response(k,kh,T){let d=0;for(let t=0;t<T;t++)d+=((k[t]||0)-kh*d);return d}
function patient(base){const p=PatientPhenotypeV2.decorate(base),q=ClinicalModifiersV2.decorateClinical(p,{egfr_ml_min_1_73m2:90,meal_plan_carb_g:{breakfast:50,lunch:70,dinner:60}});return PatientPhenotypeV2.toEnginePatient(q)}
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}function sd(a){const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)}function corr(a,b){const ma=mean(a),mb=mean(b);let n=0,da=0,db=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;n+=x*y;da+=x*x;db+=y*y}return n/Math.sqrt(da*db)}
function solve3(X,y){const A=Array.from({length:3},()=>Array(4).fill(0));for(let i=0;i<X.length;i++){const x=X[i];for(let r=0;r<3;r++){for(let c=0;c<3;c++)A[r][c]+=x[r]*x[c];A[r][3]+=x[r]*y[i]}}for(let i=0;i<3;i++){let p=i;for(let r=i+1;r<3;r++)if(Math.abs(A[r][i])>Math.abs(A[p][i]))p=r;[A[i],A[p]]=[A[p],A[i]];const d=A[i][i];for(let c=i;c<4;c++)A[i][c]/=d;for(let r=0;r<3;r++)if(r!==i){const f=A[r][i];for(let c=i;c<4;c++)A[r][c]-=f*A[i][c]}}return A.map(r=>r[3])}
function r2(y,p){const m=mean(y),ss=y.reduce((s,v)=>s+(v-m)**2,0),se=y.reduce((s,v,i)=>s+(v-p[i])**2,0);return 1-se/ss}
const N=Number(process.env.N||10000),alpha=.10,fast=.80,rapid=.80,bases=PatientGenerator.sampleCandidates(N,12191,false).map(patient),rows=[];
for(const p of bases){const kh=restoreK(p),rk=shifted(15,105,300,rapid),u240=-response(Float64Array.from(rk,x=>-x),kh,240),si=Number(p.cf_mg_dl_u)/Math.max(u240,1e-9),cfDerived=si*u240;const mk=mealKernel(p),gain=clamp(5*Math.pow(70/clamp(p.body_weight_kg,40,130),.65),1,10),mealPerGram=new Float64Array(900);for(let t=0;t<mealPerGram.length;t++)mealPerGram[t]=gain*(mk[t]||0)+alpha*gain*(H[t]||0);const meal240=fast*response(mealPerGram,kh,240),ins240=fast*si*Number(p.incremental_obesity_insulin_action_multiplier??1)*response(rk,kh,240),neutralICR=ins240/Math.max(meal240,1e-9);rows.push({si,cf:Number(p.cf_mg_dl_u),cfDerived,weight:Number(p.body_weight_kg),tdd:Number(p.tdd_u_day),tddkg:Number(p.tdd_u_kg_day),legacyICR:Number(p.icr_g_u),neutralICR,gain,ob:Number(p.incremental_obesity_insulin_action_multiplier??1)})}
const X=rows.map(r=>[1,Math.log(r.weight),Math.log(r.si)]),y=rows.map(r=>Math.log(r.tdd)),b=solve3(X,y),pred=X.map(x=>Math.exp(b[0]+b[1]*x[1]+b[2]*x[2]));
const result={protocol:{N,definition:'S_I primitive is pre-modifier insulin gain; CF is derived 240-min 1U response; neutral ICR is derived from meal-vs-insulin response at 240 min',rapid_scale:rapid,fast_scale:fast,zero_area_alpha:alpha},identity_check:{max_abs_cf_error:Math.max(...rows.map(r=>Math.abs(r.cf-r.cfDerived))),corr_cf_derived:corr(rows.map(r=>r.cf),rows.map(r=>r.cfDerived))},tdd_from_si_weight:{formula:'log(TDD)=b0+b_weight*log(weight)+b_SI*log(S_I)',coefficients:{b0:b[0],b_weight:b[1],b_SI:b[2]},r2_log:r2(y,X.map(x=>b[0]+b[1]*x[1]+b[2]*x[2])),r2_raw:r2(rows.map(r=>r.tdd),pred),corr_raw:corr(rows.map(r=>r.tdd),pred),residual_log_sd:sd(y.map((v,i)=>v-Math.log(pred[i])))},icr_structure:{corr_legacy_vs_neutral:corr(rows.map(r=>r.legacyICR),rows.map(r=>r.neutralICR)),legacy_mean:mean(rows.map(r=>r.legacyICR)),neutral_mean:mean(rows.map(r=>r.neutralICR)),legacy_sd:sd(rows.map(r=>r.legacyICR)),neutral_sd:sd(rows.map(r=>r.neutralICR)),corr_si_neutral_icr:corr(rows.map(r=>r.si),rows.map(r=>r.neutralICR)),corr_gain_neutral_icr:corr(rows.map(r=>r.gain),rows.map(r=>r.neutralICR))},primitive_distribution:{si_mean:mean(rows.map(r=>r.si)),si_sd:sd(rows.map(r=>r.si)),corr_si_tdd:corr(rows.map(r=>r.si),rows.map(r=>r.tdd)),corr_si_tddkg:corr(rows.map(r=>r.si),rows.map(r=>r.tddkg)),corr_si_cf:corr(rows.map(r=>r.si),rows.map(r=>r.cf))}};
fs.writeFileSync('si_primitive_reparameterization_result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));