#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');
const E0=fs.readFileSync('engine.js','utf8'),G=fs.readFileSync('patient_generator.js','utf8');
const N=40,DAYS=10,LAGS=[30,60,120,240],POC=[420,720,1080,1260];
const TARGET_DAY={30:.8356734642,60:.5790031609,120:.1024831789,240:-.0541005771};
const TARGET_NIGHT={30:.889,60:.760,120:.460,240:.086};
function context(src){const c={console,Float64Array,Math,Number,String,Object,Array,JSON,Date,Set,Map};c.window=c;c.globalThis=c;vm.createContext(c);vm.runInContext(src,c);return c}
function rng(seed){let a=seed>>>0;return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function randn(r){let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function corr(a,b){const n=a.length;if(n<50)return NaN;let sx=0,sy=0,sxx=0,syy=0,sxy=0;for(let i=0;i<n;i++){const x=a[i],y=b[i];sx+=x;sy+=y;sxx+=x*x;syy+=y*y;sxy+=x*y}const den=Math.sqrt((n*sxx-sx*sx)*(n*syy-sy*sy));return den>0?(n*sxy-sx*sy)/den:NaN}
function median(a){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return NaN;const m=a.length>>1;return a.length%2?a[m]:(a[m-1]+a[m])/2}
function quantile(a,q){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return NaN;const p=(a.length-1)*q,i=Math.floor(p),f=p-i;return a[i]+f*((a[i+1]??a[i])-a[i])}
const q=context(E0);vm.runInContext(G,q);const base=[];for(let i=0;i<N;i++){const seed=982001+i,x=q.PatientGenerator.generate(seed);let start=x.case.previous_day_end_glucose_mg_dl,arr=[];for(let d=0;d<DAYS;d++){const o=x.case.previous_order_u,res=q.GlucoseEngine.simulate(x.patient,x.case,{breakfast_u:o.breakfast_u,lunch_u:o.lunch_u,dinner_u:o.dinner_u},o.basal_u,seed+d*997,start);start=res.end;for(let t=0;t<1440;t+=5)arr.push(res.series[t])}base.push({seed,arr})}
function evaluate(sd,half){const acd=Object.fromEntries(LAGS.map(l=>[l,[]])),acn=Object.fromEntries(LAGS.map(l=>[l,[]])),poc=POC.map(()=>[]);let n=0,sum=0,sum2=0,tir=0,l70=0,l54=0,h180=0,h250=0;for(const z of base){const r=rng((z.seed+Math.round(sd*100)+half*7919)>>>0),phi=half?Math.exp(-Math.log(2)*5/half):0,innov=sd*Math.sqrt(1-phi*phi);let e=0,series=[];for(let i=0;i<z.arr.length;i++){if(sd){e=phi*e+innov*randn(r);const lim=2.5*sd;e=Math.max(-lim,Math.min(lim,e))}else e=0;const g=z.arr[i]+e,tod=(i*5)%1440;series.push({g,tod});n++;sum+=g;sum2+=g*g;if(g>=70&&g<=180)tir++;if(g<70)l70++;if(g<54)l54++;if(g>180)h180++;if(g>250)h250++;if(POC.includes(tod))poc[POC.indexOf(tod)].push(g)}for(const lag of LAGS){const k=lag/5,da=[],db=[],na=[],nb=[];for(let i=0;i+k<series.length;i++){const x=series[i],y=series[i+k];if(x.tod>=360&&y.tod>=360){da.push(x.g);db.push(y.g)}if(x.tod<360&&y.tod<360){na.push(x.g);nb.push(y.g)}}acd[lag].push(corr(da,db));acn[lag].push(corr(na,nb))}}
const mean=sum/n,sdg=Math.sqrt((sum2-sum*sum/n)/(n-1)),day=Object.fromEntries(LAGS.map(l=>[l,median(acd[l])])),night=Object.fromEntries(LAGS.map(l=>[l,median(acn[l])])),dr=Math.sqrt(LAGS.reduce((s,l)=>s+(day[l]-TARGET_DAY[l])**2,0)/4),nr=Math.sqrt(LAGS.reduce((s,l)=>s+(night[l]-TARGET_NIGHT[l])**2,0)/4);return{residual_sd:sd,half_life_min:half,day_acf:day,night_acf:night,day_rmse:dr,night_rmse:nr,mean,cv:100*sdg/mean,TIR:100*tir/n,TBR70:100*l70/n,TBR54:100*l54/n,TAR180:100*h180/n,TAR250:100*h250/n,poc:poc.map(a=>({q10:quantile(a,.1),q50:quantile(a,.5),q90:quantile(a,.9)}))}}
const cells=[[0,0],[5,60],[5,120],[5,240],[6,90],[7.5,90],[7.5,120],[8.5,90],[8.5,120],[10,60],[10,120],[10,240],[15,60],[15,120],[15,240],[20,120],[20,240]];
const out=[];for(const c of cells){const x=evaluate(...c);out.push(x);console.error(JSON.stringify({sd:x.residual_sd,half:x.half_life_min,d60:x.day_acf[60],d120:x.day_acf[120],n60:x.night_acf[60],n120:x.night_acf[120],dr:x.day_rmse,nr:x.night_rmse,TBR70:x.TBR70,TBR54:x.TBR54,CV:x.cv}))}
fs.writeFileSync('bounded_ou_residual_results.json',JSON.stringify({protocol:{N,DAYS,sampling_min:5,residual:'bounded zero-mean OU residual added validation-only after latent glucose simulation; bound ±2.5 SD',production_changed:false},targets:{day:TARGET_DAY,night:TARGET_NIGHT},results:out},null,2));
