#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path');
const E=fs.readFileSync('engine.js','utf8'),G=fs.readFileSync('patient_generator.js','utf8');
const N=Number(process.env.N||60),DAYS=Number(process.env.DAYS||10),LAGS=[30,60,120,240];
function context(src){const c={console,Float64Array,Math,Number,String,Object,Array,JSON,Date,Set,Map};c.window=c;c.globalThis=c;vm.createContext(c);vm.runInContext(src,c);return c}
function median(a){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return NaN;const m=a.length>>1;return a.length%2?a[m]:(a[m-1]+a[m])/2}
function corr(a,b){const n=a.length;if(n<50)return NaN;let sx=0,sy=0,sxx=0,syy=0,sxy=0;for(let i=0;i<n;i++){const x=a[i],y=b[i];sx+=x;sy+=y;sxx+=x*x;syy+=y*y;sxy+=x*y}const den=Math.sqrt((n*sxx-sx*sx)*(n*syy-sy*sy));return den>0?(n*sxy-sx*sy)/den:NaN}
function sd(a){if(a.length<2)return NaN;const m=a.reduce((s,x)=>s+x,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))}
function acfPairs(points,residual=false){const byT=new Map(points.map(x=>[x.ms,x]));const out={};for(const lag of LAGS){const a=[],b=[];const dt=lag*60000;for(const x of points){const y=byT.get(x.ms+dt);if(!y)continue;if(x.minuteOfDay<360||y.minuteOfDay<360)continue;a.push(residual?x.r:x.g);b.push(residual?y.r:y.g)}out[lag]=corr(a,b)}return out}
function demeanByClock(points){const s=new Map(),n=new Map();for(const x of points){s.set(x.minuteOfDay,(s.get(x.minuteOfDay)||0)+x.g);n.set(x.minuteOfDay,(n.get(x.minuteOfDay)||0)+1)}return points.map(x=>({...x,r:x.g-s.get(x.minuteOfDay)/n.get(x.minuteOfDay)}))}
function modelAudit(){const q=context(E);vm.runInContext(G,q);const rawBy=Object.fromEntries(LAGS.map(l=>[l,[]])),resBy=Object.fromEntries(LAGS.map(l=>[l,[]])),resSD=[];for(let i=0;i<N;i++){const seed=982001+i,z=q.PatientGenerator.generate(seed),o=z.case.previous_order_u;let start=z.case.previous_day_end_glucose_mg_dl,points=[];for(let d=0;d<DAYS;d++){const rr=q.GlucoseEngine.simulate(z.patient,z.case,{breakfast_u:o.breakfast_u,lunch_u:o.lunch_u,dinner_u:o.dinner_u},o.basal_u,seed+d*997,start);start=rr.end;for(let t=0;t<1440;t+=5){points.push({ms:(d*1440+t)*60000,minuteOfDay:t,g:rr.series[t]})}}points=demeanByClock(points);const raw=acfPairs(points,false),res=acfPairs(points,true);for(const l of LAGS){rawBy[l].push(raw[l]);resBy[l].push(res[l])}resSD.push(sd(points.map(x=>x.r)))}return{N,DAYS,raw_patient_median_acf:Object.fromEntries(LAGS.map(l=>[l,median(rawBy[l])])),clock_demeaned_patient_median_acf:Object.fromEntries(LAGS.map(l=>[l,median(resBy[l])])),clock_demeaned_residual_sd_mg_dl_median:median(resSD)}}
function parseCsv(file){const lines=fs.readFileSync(file,'utf8').trim().split(/\r?\n/);const out=[];for(let i=1;i<lines.length;i++){const j=lines[i].lastIndexOf(',');if(j<0)continue;const ts=lines[i].slice(0,j).trim(),g=Number(lines[i].slice(j+1));if(!Number.isFinite(g))continue;const m=ts.match(/^(\d{4})-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d)$/);if(!m)continue;const ms=Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+m[6]),minuteOfDay=(+m[4])*60+(+m[5]);out.push({ms,minuteOfDay,g})}return out}
function externalAudit(dir){const files=fs.readdirSync(dir).filter(x=>x.toLowerCase().endsWith('.csv')).sort(),rawBy=Object.fromEntries(LAGS.map(l=>[l,[]])),resBy=Object.fromEntries(LAGS.map(l=>[l,[]])),resSD=[];for(const f of files){let p=demeanByClock(parseCsv(path.join(dir,f)));const raw=acfPairs(p,false),res=acfPairs(p,true);for(const l of LAGS){rawBy[l].push(raw[l]);resBy[l].push(res[l])}resSD.push(sd(p.map(x=>x.r)))}return{files:files.length,raw_patient_median_acf:Object.fromEntries(LAGS.map(l=>[l,median(rawBy[l])])),clock_demeaned_patient_median_acf:Object.fromEntries(LAGS.map(l=>[l,median(resBy[l])])),clock_demeaned_residual_sd_mg_dl_median:median(resSD)}}
const payload={generated_at:new Date().toISOString(),purpose:'Separate fixed clock-time mean trajectory from within-patient stochastic covariance before fitting raw ACF.',model:modelAudit()};if(process.env.AZT1D_DIR&&fs.existsSync(process.env.AZT1D_DIR))payload.AZT1D=externalAudit(process.env.AZT1D_DIR);console.log(JSON.stringify(payload,null,2));
