#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path');
const E0=fs.readFileSync('engine.js','utf8'),G=fs.readFileSync('patient_generator.js','utf8');
const OUT=process.env.OUT||'validation/results/day_baseline_state_screen_latest.json';
const N=Number(process.env.N||60),DAYS=Number(process.env.DAYS||10),LAGS=[30,60,120,240],POC=[420,720,1080,1260];
const TARGET={acf:{30:.8356734642,60:.5790031609,120:.1024831789,240:-.0541005771}};
function context(src){const c={console,Float64Array,Math,Number,String,Object,Array,JSON,Date,Set,Map};c.window=c;c.globalThis=c;vm.createContext(c);vm.runInContext(src,c);return c}
function rng(seed){let a=seed>>>0;return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function median(a){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return NaN;const m=a.length>>1;return a.length%2?a[m]:(a[m-1]+a[m])/2}
function quantile(a,q){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return NaN;const p=(a.length-1)*q,i=Math.floor(p),f=p-i;return a[i]+f*((a[i+1]??a[i])-a[i])}
function corr(a,b){const n=a.length;if(n<50)return NaN;let sx=0,sy=0,sxx=0,syy=0,sxy=0;for(let i=0;i<n;i++){const x=a[i],y=b[i];sx+=x;sy+=y;sxx+=x*x;syy+=y*y;sxy+=x*y}const den=Math.sqrt((n*sxx-sx*sx)*(n*syy-sy*sy));return den>0?(n*sxy-sx*sy)/den:NaN}
const q=context(E0);vm.runInContext(G,q);const C=[];for(let i=0;i<N;i++){const seed=982001+i,x=q.PatientGenerator.generate(seed);C.push({seed,p:structuredClone(x.patient),c:structuredClone(x.case)})}
function dayState(amp,seed,day,rho){if(!amp)return 0;let x=0;for(let d=0;d<=day;d++){const r=rng((seed+d*13007+Math.round(amp*1000)+Math.round(rho*100))>>>0),innovation=(2*r()-1)*amp;x=d===0?innovation:rho*x+(1-rho)*innovation}return x}
function run(amp,rho){const acfByLag=Object.fromEntries(LAGS.map(l=>[l,[]])),poc=POC.map(()=>[]);let n=0,sum=0,sum2=0,tir=0,l70=0,l54=0,h180=0,h250=0;for(const z of C){let start=z.c.previous_day_end_glucose_mg_dl,series=[];for(let d=0;d<DAYS;d++){const p=structuredClone(z.p),off=dayState(amp,z.seed,d,rho);p.fasting_setpoint_mg_dl+=off;const o=z.c.previous_order_u,res=q.GlucoseEngine.simulate(p,z.c,{breakfast_u:o.breakfast_u,lunch_u:o.lunch_u,dinner_u:o.dinner_u},o.basal_u,z.seed+d*997,start);start=res.end;for(let t=0;t<1440;t+=5){const g=res.series[t];series.push({g,tod:t});n++;sum+=g;sum2+=g*g;if(g>=70&&g<=180)tir++;if(g<70)l70++;if(g<54)l54++;if(g>180)h180++;if(g>250)h250++}for(let j=0;j<POC.length;j++)poc[j].push(res.series[POC[j]])}for(const lag of LAGS){const k=lag/5,a=[],b=[];for(let i=0;i+k<series.length;i++){const x=series[i],y=series[i+k];if(x.tod>=360&&y.tod>=360){a.push(x.g);b.push(y.g)}}acfByLag[lag].push(corr(a,b))}}
const mean=sum/n,sd=Math.sqrt((sum2-sum*sum/n)/(n-1)),acf=Object.fromEntries(LAGS.map(l=>[l,median(acfByLag[l])])),rmse=Math.sqrt(LAGS.reduce((s,l)=>s+(acf[l]-TARGET.acf[l])**2,0)/LAGS.length);return{amp_mg_dl:amp,rho,acf,rmse,mean,cv:100*sd/mean,TIR:100*tir/n,TBR70:100*l70/n,TBR54:100*l54/n,TAR180:100*h180/n,TAR250:100*h250/n,poc:poc.map(a=>({q10:quantile(a,.1),q50:quantile(a,.5),q90:quantile(a,.9)}))}}
const results=[];for(const rho of [0,.7])for(const amp of [0,10,20,30,40]){if(amp===0&&rho!==0)continue;const r=run(amp,rho);results.push(r);console.error('rho',rho,'amp',amp,'r60',r.acf[60].toFixed(3),'r120',r.acf[120].toFixed(3),'RMSE',r.rmse.toFixed(3),'TBR70',r.TBR70.toFixed(2),'CV',r.cv.toFixed(1))}
const payload={generated_at:new Date().toISOString(),protocol:{N,DAYS,seeds:`982001..${982000+N}`,sampling_min:5,daytime:'06:00-24:00',state:'bounded patient-day fasting-setpoint offset; rho=0 independent, rho=.7 AR-like persistence',production_changed:false},target:TARGET,results};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(payload,null,2));console.log(JSON.stringify(payload,null,2));
