#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path');
const E0=fs.readFileSync('engine.js','utf8');
const G=fs.readFileSync('patient_generator.js','utf8');
const OUT=process.env.OUT||'validation/results/shared_mismatch_kernel_factorial_latest.json';
const N=Number(process.env.N||60),DAYS=Number(process.env.DAYS||10);
const LAGS=[30,60,120,240],POC=[420,720,1080,1260];
const TARGET={acf:{30:.8356734642,60:.5790031609,120:.1024831789,240:-.0541005771}};
function context(src){const c={console,Float64Array,Math,Number,String,Object,Array,JSON,Date,Set,Map};c.window=c;c.globalThis=c;vm.createContext(c);vm.runInContext(src,c);return c}
function patchEngine(k){let e=E0;const sig='return shiftedGammaTaper(15,105,300,h,3)';if(k.peak!==105||k.duration!==300){if(!e.includes(sig))throw Error('rapid signature changed');e=e.replace(sig,`return shiftedGammaTaper(15,${k.peak},${k.duration},h,3)`)}return e}
function rng(seed){let a=seed>>>0;return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function median(a){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return NaN;const m=a.length>>1;return a.length%2?a[m]:(a[m-1]+a[m])/2}
function quantile(a,q){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return NaN;const p=(a.length-1)*q,i=Math.floor(p),f=p-i;return a[i]+f*((a[i+1]??a[i])-a[i])}
function corr(a,b){const n=a.length;if(n<50)return NaN;let sx=0,sy=0,sxx=0,syy=0,sxy=0;for(let i=0;i<n;i++){const x=a[i],y=b[i];sx+=x;sy+=y;sxx+=x*x;syy+=y*y;sxy+=x*y}const den=Math.sqrt((n*sxx-sx*sx)*(n*syy-sy*sy));return den>0?(n*sxy-sx*sy)/den:NaN}
const base=context(E0);vm.runInContext(G,base);const C=[];for(let i=0;i<N;i++){const seed=981001+i,x=base.PatientGenerator.generate(seed);C.push({seed,p:structuredClone(x.patient),c:structuredClone(x.case)})}
function sharedMult(amp,seed,day){if(!amp)return 1;const r=rng((seed+day*10007+Math.round(amp*1e6))>>>0);return 1-amp+r()*2*amp}
function run(k,amp){const q=context(patchEngine(k));vm.runInContext(G,q);const acfByLag=Object.fromEntries(LAGS.map(l=>[l,[]])),poc=POC.map(()=>[]);let n=0,sum=0,sum2=0,tir=0,l70=0,l54=0,h180=0,h250=0;for(const z of C){let start=z.c.previous_day_end_glucose_mg_dl,series=[];for(let d=0;d<DAYS;d++){const p=structuredClone(z.p);p.meal_t50_fast_min*=k.fastScale;p.meal_t50_slow_min*=k.slowScale;p.meal_fast_fraction=Math.max(.05,Math.min(.95,p.meal_fast_fraction+k.qDelta));const m=sharedMult(amp,z.seed,d),cc=structuredClone(z.c);cc.meal_plan_carb_g={breakfast:50*m,lunch:70*m,dinner:60*m};const o=cc.previous_order_u,res=q.GlucoseEngine.simulate(p,cc,{breakfast_u:o.breakfast_u,lunch_u:o.lunch_u,dinner_u:o.dinner_u},o.basal_u,z.seed+d*997,start);start=res.end;for(let t=0;t<1440;t+=5){const g=res.series[t];series.push({g,tod:t});n++;sum+=g;sum2+=g*g;if(g>=70&&g<=180)tir++;if(g<70)l70++;if(g<54)l54++;if(g>180)h180++;if(g>250)h250++}for(let j=0;j<POC.length;j++)poc[j].push(res.series[POC[j]])}for(const lag of LAGS){const kk=lag/5,a=[],b=[];for(let i=0;i+kk<series.length;i++){const x=series[i],y=series[i+kk];if(x.tod>=360&&y.tod>=360){a.push(x.g);b.push(y.g)}}acfByLag[lag].push(corr(a,b))}}
const mean=sum/n,sd=Math.sqrt((sum2-sum*sum/n)/(n-1)),acf=Object.fromEntries(LAGS.map(l=>[l,median(acfByLag[l])])),rmse=Math.sqrt(LAGS.reduce((s,l)=>s+(acf[l]-TARGET.acf[l])**2,0)/LAGS.length);return{kernel:k.name,sharedAmp:amp,acf,rmse,mean,cv:100*sd/mean,TIR:100*tir/n,TBR70:100*l70/n,TBR54:100*l54/n,TAR180:100*h180/n,TAR250:100*h250/n,poc:poc.map(a=>({q10:quantile(a,.1),q50:quantile(a,.5),q90:quantile(a,.9)}))}}
const kernels=[{name:'frozen',peak:105,duration:300,fastScale:1,slowScale:1,qDelta:0},{name:'meal_S060',peak:105,duration:300,fastScale:1,slowScale:.60,qDelta:0},{name:'rapid110_315',peak:110,duration:315,fastScale:1,slowScale:1,qDelta:0},{name:'rapid110_315_F080S080',peak:110,duration:315,fastScale:.80,slowScale:.80,qDelta:0}];
const results=[];for(const k of kernels)for(const amp of [0,.05,.10]){const r=run(k,amp);results.push(r);console.error(k.name,amp,'r60',r.acf[60].toFixed(3),'r120',r.acf[120].toFixed(3),'RMSE',r.rmse.toFixed(3),'TBR70',r.TBR70.toFixed(2),'CV',r.cv.toFixed(1))}
const b=results.find(x=>x.kernel==='frozen'&&x.sharedAmp===0),interactions=[];for(const k of kernels.slice(1))for(const amp of [.05,.10]){const ka=results.find(x=>x.kernel===k.name&&x.sharedAmp===0),fa=results.find(x=>x.kernel==='frozen'&&x.sharedAmp===amp),both=results.find(x=>x.kernel===k.name&&x.sharedAmp===amp);interactions.push({kernel:k.name,sharedAmp:amp,interaction_r120:(both.acf[120]-b.acf[120])-(ka.acf[120]-b.acf[120])-(fa.acf[120]-b.acf[120]),interaction_rmse:(both.rmse-b.rmse)-(ka.rmse-b.rmse)-(fa.rmse-b.rmse),TBR70_both:both.TBR70,cv_both:both.cv})}
const payload={generated_at:new Date().toISOString(),protocol:{N,DAYS,seeds:`981001..${981000+N}`,sampling_min:5,daytime:'06:00-24:00',shared_day_carb_multiplier:'uniform 1±amp, same multiplier for all 3 meals of a patient-day',same_seeds_across_cells:true,production_changed:false},target:TARGET,results,interactions};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(payload,null,2));console.log(JSON.stringify(payload,null,2));
