#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_emory_u300_trial_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,EP=T2DMTreatmentPolicyEmoryU300TrialExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const gp=PK.get('glulisine'),N=10000;
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))}
function statePatch(ctx,counter){const st=ctx.state||{},mealShift={breakfast:0,lunch:0,dinner:0,...(st.meal_shift_min||{})},bolusShift={},bolusFraction={};for(const meal of ['breakfast','lunch','dinner']){bolusShift[meal]=Number(mealShift[meal])||0;bolusFraction[meal]=1;}return{bolus_shift_min:bolusShift,bolus_fraction:bolusFraction,prandial_safety_adjustment_fn:({meal,poc_glucose_mg_dl,planned_units,state})=>{const f=Number(state&&state.intake_fraction&&state.intake_fraction[meal]),poor=Number.isFinite(f)&&f<.85,scale=poor?'sensitive':'usual',supp=EP.premealSupplement(poc_glucose_mg_dl,scale),sched=poor?0:Math.max(0,Math.round(Number(planned_units)||0));counter.supp+=supp;if(poor)counter.held++;return sched+supp;}}}
let pocTotal=0,poc70=0,poc54=0,poc180=0,poc250=0,pocAny70=0,pocAny54=0;const pocMeans=[],pocCV=[];
let latTotal=0,lat70=0,lat54=0,lat180=0,lat250=0,latAny70=0,latAny54=0,latNoct70=0,latNoct54=0,latDeep54=0,lat20=0;const latMeans=[],latCV=[];
let supp=0,bed=0;const tddkg=[],basal=[],prand=[];
for(let i=1;i<=N;i++){
 const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(140,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=EP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i),cnt={supp:0,held:0};
 const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:0,underbolus_probability:0,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:EP.registered2019Titrate,state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...statePatch(ctx,cnt),bedtime_correction_fn:({glucose_mg_dl})=>{const u=EP.bedtimeSupplement(glucose_mg_dl,'usual');bed+=u;return u;}})};
 const c=C.simulateCourse(M,D,p,o,cfg,i);supp+=cnt.supp;let pa70=false,pa54=false,la70=false,la54=false,ln70=false,ln54=false,ld54=false,l20=false;const px=[],lx=[];
 for(const r of c.records){tddkg.push((r.order.basal_u+r.order.breakfast_u+r.order.lunch_u+r.order.dinner_u)/p.body_weight_kg);basal.push(r.order.basal_u);prand.push(r.order.breakfast_u+r.order.lunch_u+r.order.dinner_u);for(const x0 of Object.values(r.bg||{})){const x=Number(x0);if(!Number.isFinite(x))continue;px.push(x);pocTotal++;if(x<70){poc70++;pa70=true}if(x<54){poc54++;pa54=true}if(x>180)poc180++;if(x>250)poc250++;}for(let t=0;t<1440;t+=15){const x=r.series[t];lx.push(x);latTotal++;if(x<20)l20=true;if(x<70){lat70++;la70=true}if(x<54){lat54++;la54=true}if(x>180)lat180++;if(x>250)lat250++;const no=t>=1320||t<360;if(no&&x<70)ln70=true;if(no&&x<54)ln54=true;if(t<360&&x<54)ld54=true;}}
 if(pa70)pocAny70++;if(pa54)pocAny54++;if(la70)latAny70++;if(la54)latAny54++;if(ln70)latNoct70++;if(ln54)latNoct54++;if(ld54)latDeep54++;if(l20)lat20++;pocMeans.push(mean(px));pocCV.push(100*sd(px)/mean(px));latMeans.push(mean(lx));latCV.push(100*sd(lx)/mean(lx));
}
const poc={mean:mean(pocMeans),tir_pct:100*(pocTotal-poc70-poc180)/pocTotal,tar180_pct:100*poc180/pocTotal,tar250_pct:100*poc250/pocTotal,tbr70_pct:100*poc70/pocTotal,tbr54_pct:100*poc54/pocTotal,cv_pct:mean(pocCV),patients_any70_pct:100*pocAny70/N,patients_any54_pct:100*pocAny54/N};
const latent={mean:mean(latMeans),tir_pct:100*(latTotal-lat70-lat180)/latTotal,tar180_pct:100*lat180/latTotal,tar250_pct:100*lat250/latTotal,tbr70_pct:100*lat70/latTotal,tbr54_pct:100*lat54/latTotal,cv_pct:mean(latCV),patients_any70_pct:100*latAny70/N,patients_any54_pct:100*latAny54/N,noct70_pct:100*latNoct70/N,noct54_pct:100*latNoct54/N,deep00_06_54_pct:100*latDeep54/N,patients_below20_pct:100*lat20/N};
const targets={poc:{mean:188.9,tir_pct:48.4,tar180_pct:50.5,tar250_pct:17.8,tbr70_pct:1.1,tbr54_pct:.20,cv_pct:30,patients_any70_pct:14,patients_any54_pct:4.1},cgm:{mean:176.1,tir_pct:53.5,tar180_pct:42.2,tar250_pct:16.1,tbr70_pct:4.5,tbr54_pct:1.58,cv_pct:32,patients_any70_pct:56,patients_any54_pct:36,noct70_pct:41,noct54_pct:26}};
const out={purpose:'Separate treatment/physiology validation against observed capillary POC from the FreeStyle Libre Pro observation layer. No model parameter is changed. The simulator POC sample is compared to Galindo POC endpoints; the 15-min latent trajectory is reported separately and must not be called Libre CGM until a measurement model is defined.',n:N,protocol:'registered 2019 U300 Hospital Trial policy, legacy low-side physiology',targets,poc,latent,treatment_exposure:{scheduled_tdd_ukg:mean(tddkg),basal_u:mean(basal),scheduled_prandial_u:mean(prand),supplement_u_day:(supp+bed)/(N*8)},differences:{poc_minus_target:Object.fromEntries(Object.keys(targets.poc).map(k=>[k,poc[k]-targets.poc[k]])),latent_minus_cgm_target:Object.fromEntries(Object.keys(targets.cgm).filter(k=>latent[k]!=null).map(k=>[k,latent[k]-targets.cgm[k]]))}};
const dir='analysis/emory_poc_latent_decomposition';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Emory POC vs latent decomposition','','No new mechanism or parameter. This audit asks whether the physiology+treatment stack resembles the trial POC data before any Libre Pro observation model is applied.','','| metric | trial POC | simulator POC | Δ | trial CGM | latent 15-min | Δ latent-CGM |','|---|---:|---:|---:|---:|---:|---:|'];for(const [label,key] of [['mean','mean'],['TIR','tir_pct'],['TAR>180','tar180_pct'],['TAR>250','tar250_pct'],['TBR<70','tbr70_pct'],['TBR<54','tbr54_pct'],['CV','cv_pct'],['any<70','patients_any70_pct'],['any<54','patients_any54_pct']]){const pt=targets.poc[key],ps=poc[key],ct=targets.cgm[key],ls=latent[key];md.push(`| ${label} | ${pt.toFixed(2)} | ${ps.toFixed(2)} | ${(ps-pt).toFixed(2)} | ${ct.toFixed(2)} | ${ls.toFixed(2)} | ${(ls-ct).toFixed(2)} |`);}md.push('','Latent nocturnal: <70 '+latent.noct70_pct.toFixed(1)+'%, <54 '+latent.noct54_pct.toFixed(1)+'%, 00–06 <54 '+latent.deep00_06_54_pct.toFixed(1)+'%.','Latent patients <20: '+latent.patients_below20_pct.toFixed(2)+'%.',`Treatment exposure: scheduled TDD ${out.treatment_exposure.scheduled_tdd_ukg.toFixed(3)} U/kg/day; basal ${out.treatment_exposure.basal_u.toFixed(1)} U/day; scheduled prandial ${out.treatment_exposure.scheduled_prandial_u.toFixed(1)} U/day; supplemental ${(out.treatment_exposure.supplement_u_day).toFixed(2)} U/day.`,'','Interpretation guardrail: Galindo directly observed a systematic POC–Libre difference. Do not compare latent simulator glucose to Libre CGM as if they were the same measurement channel. Build/validate an observation model separately before using CGM endpoints to change physiology.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
