#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','insulin_basal_time_profile_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,BT=InsulinBasalTimeProfilePriorExp;
const NSH=1000,NEM=1200,ARMS=[['flat',0],['u100',.10],['u100',.20],['u100',.30],['u300',.10],['u300',.20],['u300',.30]];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}function noct(t){return t>=1320||t<360}
function shanghai(form,amp){const vals={all:[],preB:[],preL:[],preD:[],d120:[]};for(let i=1;i<=NSH;i++){const p={...P1.sample(i)},base=M.suggestOrder(p,M.DEFAULT_MEALS),o={breakfast_u:base.breakfast_u,lunch_u:base.lunch_u,dinner_u:base.dinner_u,basal_u:Math.max(0,Math.round(.201*p.body_weight_kg))};let prev=null;for(let d=0;d<6;d++){const st={meal_plan_carb_g:M.DEFAULT_MEALS,...B.statePatch(M,.20),...(form==='flat'?{}:BT.statePatch(form,amp))},x=D.simulateDay(M,p,o,st,i*100+d,prev);prev=x.next_state;if(d<2)continue;for(let t=0;t<1440;t++)vals.all.push(x.series[t]);vals.preB.push(x.series[420]);vals.preL.push(x.series[720]);vals.preD.push(x.series[1080]);vals.d120.push(x.series[600]-x.series[480]);}}
 const m=mean(vals.all),tbr=100*vals.all.filter(x=>x<70).length/vals.all.length,tir=100*vals.all.filter(x=>x>=70&&x<=180).length/vals.all.length;return{mean:m,tbr,tir,preB:mean(vals.preB),preL:mean(vals.preL),preD:mean(vals.preD),delta120:mean(vals.d120)};}
function external(form,amp){const gp=PK.get('glulisine'),rows=[];let noct70=0,noct54=0,deep54=0,correctDays=0,totalDays=0;for(let i=1;i<=NEM;i++){const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i),cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.componentTitrate(ord,bg),state_modifier_fn:({day})=>({...T.statePatch(tr,day,i),...B.statePatch(M,.20),...(form==='flat'?{}:BT.statePatch(form,amp)),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i),xs=[];let p70=false,p54=false,pDeep=false;for(const r of c.records){totalDays++;if((r.bedtime_corrections||[]).length)correctDays++;for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);if(noct(t)&&x<70)p70=true;if(noct(t)&&x<54)p54=true;if(t<360&&x<54)pDeep=true;}}if(p70)noct70++;if(p54)noct54++;if(pDeep)deep54++;const mm=mean(xs),ss=sd(xs);rows.push({mean:mm,tir:100*xs.filter(x=>x>=70&&x<=180).length/xs.length,tar:100*xs.filter(x=>x>180).length/xs.length,tbr70:100*xs.filter(x=>x<70).length/xs.length,tbr54:100*xs.filter(x=>x<54).length/xs.length,cv:100*ss/mm});}
 return{mean:mean(rows.map(x=>x.mean)),tir:mean(rows.map(x=>x.tir)),tar:mean(rows.map(x=>x.tar)),tbr70:mean(rows.map(x=>x.tbr70)),tbr54:mean(rows.map(x=>x.tbr54)),cv:mean(rows.map(x=>x.cv)),noct70:100*noct70/NEM,noct54:100*noct54/NEM,deep54:100*deep54/NEM,correction_day_pct:100*correctDays/totalDays};}
const sh0=shanghai('flat',0),rows=[];for(const [form,amp] of ARMS){const s=shanghai(form,amp),e=external(form,amp),d={};for(const k of Object.keys(sh0))d[k]=s[k]-sh0[k];const gate=Math.abs(d.mean)<5&&Math.abs(d.preB)<5&&Math.abs(d.preL)<5&&Math.abs(d.preD)<5&&Math.abs(d.delta120)<2&&Math.abs(d.tbr)<1&&Math.abs(d.tir)<3;rows.push({formulation:form,amplitude:amp,shanghai:s,delta_vs_flat:d,shanghai_gate:gate,external:e});}
const out={n:{shanghai:NSH,external:NEM},definition:{injection_time:'21:00 sensitivity anchor',profile:'24h mean multiplier exactly 1; zero-area timing redistribution only',bedtime_correction:'published protocol table, fixed'},rows};const dir='analysis/glargine_time_profile_sensitivity';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Glargine time-profile sensitivity audit','','No candidate is selected from Emory. Profiles redistribute the already-frozen basal effect over time with 24 h mean multiplier = 1. Bedtime correction uses the published protocol table.','','| arm | Shanghai gate | Δmean | ΔpreB | ΔTBR | ΔTIR | Emory-like mean | TBR<54 | CV | noct<70 | noct<54 | 00–06 <54 |','|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const d=r.delta_vs_flat,e=r.external;md.push(`| ${r.formulation} a=${r.amplitude.toFixed(2)} | ${r.shanghai_gate?'PASS':'FAIL'} | ${d.mean.toFixed(2)} | ${d.preB.toFixed(2)} | ${d.tbr.toFixed(2)}pp | ${d.tir.toFixed(2)}pp | ${e.mean.toFixed(1)} | ${e.tbr54.toFixed(2)}% | ${e.cv.toFixed(1)}% | ${e.noct70.toFixed(1)}% | ${e.noct54.toFixed(1)}% | ${e.deep54.toFixed(1)}% |`)}md.push('','Guardrails:','- Do not choose an amplitude by closeness to Emory.','- U100/U300 shapes remain sensitivity-only until independent PK/PD amplitude identification.','- Reject any shape that fails Shanghai preservation.','- Do not change glulisine PK or basal relative potency 0.20 in response to this audit.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
