#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_emory_u300_trial_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyEmoryU300TrialExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const gp=PK.get('glulisine'),N=10000,POC=new Set([420,720,1080,1260]);
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function mealDosePatch({state}){return{prandial_safety_adjustment_fn:({meal,poc_glucose_mg_dl,planned_units})=>TP.mealDose({meal,poc_glucose_mg_dl,planned_units,state})};}
function protocolPocRescue({t,glucose_mg_dl,prior_rescues}){const g=Number(glucose_mg_dl);if(!(g<70))return 0;const rs=prior_rescues||[],last=rs.length?rs[rs.length-1]:null;const scheduled=POC.has(t),repeat=!!(last&&last.label==='protocol_poc_glucose'&&t===last.minute+15);if(!(scheduled||repeat))return 0;return{carbs_g:12.5,cooldown_min:15,label:'protocol_poc_glucose'};}
function relevantMeal(t){if(t>=465&&t<720)return 'breakfast';if(t>=765&&t<1080)return 'lunch';if(t>=1125)return 'dinner';return null;}
const rows=[];
for(let i=1;i<=N;i++){
 const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(140,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);
 const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.registered2019Titrate(ord,bg),state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...mealDosePatch(ctx),bedtime_correction_fn:({glucose_mg_dl})=>TP.bedtimeSupplement(glucose_mg_dl,'usual'),hypoglycemia_rescue_fn:protocolPocRescue})};
 const c=C.simulateCourse(M,D,p,o,cfg,i);let found=null;for(const r of c.records){for(let t=0;t<1440;t++){if(r.series[t]<20){found={r,t};break}}if(found)break}if(!found)continue;
 const {r,t}=found,meal=relevantMeal(t);if(!meal)continue;const adj=(r.prandial_safety_adjustments||[]).find(a=>a.meal===meal)||{};const intake=Number(r.state&&r.state.intake_fraction&&r.state.intake_fraction[meal]);const priorPocTimes=[420,720,1080,1260].filter(x=>x<t);const priorPocMinute=priorPocTimes.length?priorPocTimes[priorPocTimes.length-1]:null;const priorPoc=priorPocMinute==null?null:r.series[priorPocMinute];const planned=Number(adj.planned_units),given=Number(adj.given_units),correction=Number.isFinite(given)&&Number.isFinite(planned)?given-planned:null;
 rows.push({patient:i,day:r.day,minute:t,hour:Math.floor(t/60),profile:tr.name||tr.id||String(tr),meal,prior_poc_minute:priorPocMinute,prior_poc:priorPoc,meal_intake_fraction:intake,planned_scheduled_u:planned,given_total_u:given,correction_delta_u:correction,order_component_u:Number(r.order[meal+'_u']),basal_u:r.order.basal_u,scheduled_tdd_per_kg:(r.order.basal_u+r.order.breakfast_u+r.order.lunch_u+r.order.dinner_u)/p.body_weight_kg,protocol_rescues_before_event:(r.hypoglycemia_rescues||[]).filter(x=>x.minute<t).length});
}
function summarize(xs){return{n:xs.length,pct_all:100*xs.length/N,prior_poc:mean(xs.map(x=>x.prior_poc).filter(Number.isFinite)),prior_poc_lt70_pct:100*xs.filter(x=>x.prior_poc<70).length/xs.length,prior_poc_lt100_pct:100*xs.filter(x=>x.prior_poc<100).length/xs.length,intake:mean(xs.map(x=>x.meal_intake_fraction).filter(Number.isFinite)),partial_pct:100*xs.filter(x=>Number.isFinite(x.meal_intake_fraction)&&x.meal_intake_fraction<.85).length/xs.length,planned_u:mean(xs.map(x=>x.planned_scheduled_u).filter(Number.isFinite)),given_u:mean(xs.map(x=>x.given_total_u).filter(Number.isFinite)),correction_u:mean(xs.map(x=>x.correction_delta_u).filter(Number.isFinite)),correction_positive_pct:100*xs.filter(x=>x.correction_delta_u>0).length/xs.length,scheduled_tdd_per_kg:mean(xs.map(x=>x.scheduled_tdd_per_kg)),rescue_before_pct:100*xs.filter(x=>x.protocol_rescues_before_event>0).length/xs.length};}
const groups={all:summarize(rows)};for(const m of ['breakfast','lunch','dinner'])groups[m]=summarize(rows.filter(x=>x.meal===m));for(const d of [1,2,3,4,5,6,7,8])groups['day'+d]=summarize(rows.filter(x=>x.day===d));
const out={purpose:'Causal-timing attribution for residual <20 under registered protocol plus observable POC rescue. Uses only the most recent POC and the meal insulin actually preceding the first event; future POC values are excluded from precursor interpretation.',n:N,event_patients:rows.length,event_patients_pct:100*rows.length/N,groups,events:rows};
const dir='analysis/emory_registered_rescue_causal_meal_attribution';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));
let md=['# Emory registered protocol + POC rescue causal meal attribution','',`N=${N}; attributable first <20 events after a meal: ${rows.length} (${(100*rows.length/N).toFixed(2)}%).`,'','| group | n | prior POC | prior POC<100 | intake | partial | planned U | given U | correction ΔU | correction>0 | sched TDD/kg | rescue before |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const k of ['all','breakfast','lunch','dinner']){const r=groups[k];md.push(`| ${k} | ${r.n} | ${r.prior_poc.toFixed(1)} | ${r.prior_poc_lt100_pct.toFixed(1)}% | ${r.intake.toFixed(3)} | ${r.partial_pct.toFixed(1)}% | ${r.planned_u.toFixed(2)} | ${r.given_u.toFixed(2)} | ${r.correction_u.toFixed(2)} | ${r.correction_positive_pct.toFixed(1)}% | ${r.scheduled_tdd_per_kg.toFixed(3)} | ${r.rescue_before_pct.toFixed(1)}% |`);}md.push('','Guardrails:','- Future POC values are never used as precursors.','- Hidden minute glucose only locates the post-hoc outcome.','- No protocol threshold, dose scale, PK, stress, basal potency or phenotype weight is changed by this audit.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
