#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_fasting_balance_v2_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,F=T2DMFastingBalanceV2Exp;
const TARGET={mean:176.1,tir:53.5,tar:42.2,tar250:16.1,tbr70:4.5,tbr54:1.58,cv:32,any70:56,any54:36,nocturnal54:26};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function summarizePoints(xs){const m=mean(xs),s=sd(xs);return{mean:m,sd:s,tbr70:100*xs.filter(x=>x<70).length/xs.length,tbr54:100*xs.filter(x=>x<54).length/xs.length,tir:100*xs.filter(x=>x>=70&&x<=180).length/xs.length,tar:100*xs.filter(x=>x>180).length/xs.length,tar250:100*xs.filter(x=>x>250).length/xs.length,cv:100*s/m}}
function shanghai(N=2000){const DAYS=8,WARM=2,q={legacy:{all:[],preB:[],preL:[],preD:[],d120:[]},fasting:{all:[],preB:[],preL:[],preD:[],d120:[]}};for(let i=1;i<=N;i++){
 const p={...P1.sample(i)};p.dynamic_fasting_setpoint_mg_dl=Math.max(70,Math.min(260,122.8+(p.dynamic_fasting_setpoint_mg_dl-147)*(31.5/28)));p.fasting_setpoint_mg_dl=p.dynamic_fasting_setpoint_mg_dl;const base=M.suggestOrder(p,M.DEFAULT_MEALS),order={breakfast_u:base.breakfast_u,lunch_u:base.lunch_u,dinner_u:base.dinner_u,basal_u:Math.max(0,Math.round(.201*p.body_weight_kg))};
 for(const mode of Object.keys(q)){let prev=null;for(let d=0;d<DAYS;d++){const state={meal_plan_carb_g:M.DEFAULT_MEALS,...(mode==='fasting'?F.statePatch(M):{})},out=D.simulateDay(M,p,order,state,i*100+d,prev);prev=out.next_state;if(d<WARM)continue;const s=out.series,z=q[mode];for(let t=0;t<1440;t++)z.all.push(s[t]);z.preB.push(s[420]);z.preL.push(s[720]);z.preD.push(s[1080]);z.d120.push(s[600]-s[480]);}}
 }
 function sum(z){const a=summarizePoints(z.all);return{...a,preB:mean(z.preB),preL:mean(z.preL),preD:mean(z.preD),delta120:mean(z.d120)}}const a=sum(q.legacy),b=sum(q.fasting),delta={};for(const k of ['mean','sd','tbr70','tbr54','tir','tar','tar250','cv','preB','preL','preD','delta120'])delta[k]=b[k]-a[k];const checks={mean:Math.abs(delta.mean)<5,preB:Math.abs(delta.preB)<5,preL:Math.abs(delta.preL)<5,preD:Math.abs(delta.preD)<5,delta120:Math.abs(delta.delta120)<2,tbr70:Math.abs(delta.tbr70)<1,tir:Math.abs(delta.tir)<3};return{n:N,legacy:a,fasting:b,delta,checks,pass:Object.values(checks).every(Boolean)};}
function patientMetrics(c){const xs=[],nox=[];for(const r of c.records)for(let t=0;t<1440;t+=15){xs.push(r.series[t]);if(t<360)nox.push(r.series[t]);}const m=summarizePoints(xs);return{...m,any70:xs.some(x=>x<70),any54:xs.some(x=>x<54),nocturnal54:nox.some(x=>x<54)};}
function emoryArm(mode,N=1000){const gp=PK.get('glulisine'),rows=[],hourly=Array.from({length:24},()=>[]);for(let i=1;i<=N;i++){
 const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),admission=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:admission}),trajectory=T.choose(i),cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.componentTitrate(ord,bg),steroid:false,admission_glucose_offset_mg_dl:0,initial_stress_severity:0,stress_daily_decay:0,state_modifier_fn:({day})=>{const z={...T.statePatch(trajectory,day,i)};if(mode==='scalar')Object.assign(z,B.statePatch(M,.20));if(mode==='fasting')Object.assign(z,F.statePatch(M));return z;}};
 const c=C.simulateCourse(M,D,p,o,cfg,i),pm=patientMetrics(c);rows.push(pm);for(const r of c.records)for(let t=0;t<1440;t+=15)hourly[Math.floor(t/60)].push(r.series[t]);
 }
 return{n:N,mean:mean(rows.map(x=>x.mean)),tir:mean(rows.map(x=>x.tir)),tar:mean(rows.map(x=>x.tar)),tar250:mean(rows.map(x=>x.tar250)),tbr70:mean(rows.map(x=>x.tbr70)),tbr54:mean(rows.map(x=>x.tbr54)),cv:mean(rows.map(x=>x.cv)),any70:100*rows.filter(x=>x.any70).length/N,any54:100*rows.filter(x=>x.any54).length/N,nocturnal54:100*rows.filter(x=>x.nocturnal54).length/N,hourly_tbr54:hourly.map(xs=>100*xs.filter(x=>x<54).length/xs.length)};}
const sh=shanghai(),external={off:emoryArm('off'),scalar020:emoryArm('scalar'),fasting_v2:emoryArm('fasting')};const out={structure:{fasting_window:'23:00-07:00',relative_basal_potency:.20,homeostatic_rule:'endogenous-insulin nonlinear feedback slope-matched to frozen legacy restore at fasting setpoint',basal_rule:'separate frozen 0.20 dose-deviation potency'},shanghai:sh,emory_reference:TARGET,external};const dir='analysis/fasting_balance_v2';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));
let md=['# Mechanistic overnight fasting balance v2 audit','','v2 preserves the old local restoring slope at each patient fasting setpoint, but replaces the linear response away from the setpoint with the pre-existing endogenous-insulin saturation curve. Basal dose deviation remains the already-frozen 0.20 potency. No Emory metric selects a coefficient.','','## Shanghai preservation','','| metric | legacy | fasting v2 | delta |','|---|---:|---:|---:|'];for(const k of ['mean','sd','tbr70','tbr54','tir','tar','preB','preL','preD','delta120'])md.push(`| ${k} | ${sh.legacy[k].toFixed(2)} | ${sh.fasting[k].toFixed(2)} | ${sh.delta[k].toFixed(2)} |`);md.push('',`Shanghai gate: **${sh.pass?'PASS':'FAIL'}**`,'','## External descriptive comparison','','| arm | mean | TIR | TAR | >250 | TBR<70 | TBR<54 | CV | any<70 | any<54 | nocturnal<54 |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|');for(const [name,x] of Object.entries(external))md.push(`| ${name} | ${x.mean.toFixed(1)} | ${x.tir.toFixed(1)}% | ${x.tar.toFixed(1)}% | ${x.tar250.toFixed(1)}% | ${x.tbr70.toFixed(2)}% | ${x.tbr54.toFixed(2)}% | ${x.cv.toFixed(1)}% | ${x.any70.toFixed(1)}% | ${x.any54.toFixed(1)}% | ${x.nocturnal54.toFixed(1)}% |`);md.push('',`Emory reference: mean ${TARGET.mean}, TIR ${TARGET.tir}%, TAR ${TARGET.tar}%, TBR<70 ${TARGET.tbr70}%, TBR<54 ${TARGET.tbr54}%, CV ${TARGET.cv}%, nocturnal<54 ${TARGET.nocturnal54}%.`,'','## Guardrails','- Reject v2 if Shanghai preservation fails, regardless of Emory direction.','- Do not tune slope normalization: it is algebraically fixed to the existing restore_gain.','- Do not increase basal relative potency above frozen 0.20 from this result.','- No generic Gaussian glucose noise is added.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));if(!sh.pass)process.exitCode=2;
