#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const gp=PK.get('glulisine'),N=2500,map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function persistentTitrator(order,bg){const next=TP.componentTitrate(order,bg),vals=Object.values(bg).map(Number).filter(Number.isFinite),nHigh=vals.filter(x=>x>=180).length;for(const [comp,key] of Object.entries(map)){const cur=Number(order[comp])||0,nxt=Number(next[comp])||0,signal=Number(bg[key]);if(nxt>cur && !(Number.isFinite(signal)&&signal>=180&&nHigh>=2))next[comp]=cur;}return next}
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
const arms=[
 {name:'current_full_mismatch',policy:'current',partial:true},
 {name:'persistent_full_mismatch',policy:'persistent',partial:true},
 {name:'current_no_partial',policy:'current',partial:false},
 {name:'persistent_no_partial',policy:'persistent',partial:false}
];
function run(a){let p20=0,p54=0;const means=[];for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);const cfg={days:8,titrate:true,allow_meal_mismatch:a.partial,partial_meal_probability:a.partial?.14:0,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:a.policy==='current'?((ord,bg)=>TP.componentTitrate(ord,bg)):persistentTitrator,state_modifier_fn:({day})=>({...T.statePatch(tr,day,i),...B.statePatch(M,.20),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i);let a20=false,a54=false,xs=[];for(const r of c.records){xs=xs.concat(r.series);if(r.series.some(x=>x<20))a20=true;if(r.series.some(x=>x<54))a54=true}if(a20)p20++;if(a54)p54++;means.push(mean(xs))}return{name:a.name,policy:a.policy,partial:a.partial,below20_pct:100*p20/N,any54_pct:100*p54/N,mean_bg:mean(means)}}
const rows=arms.map(run);const out={purpose:'Factorial diagnostic of policy persistence and partial-meal mismatch; not calibration',n_per_arm:N,rows};const dir='analysis/persistent_policy_meal_interaction';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Persistent policy × partial meal interaction audit','','Factorial diagnostic only. No thresholds are selected from these outcomes.','','| arm | <20 patients | any <54 | mean BG |','|---|---:|---:|---:|'];for(const r of rows)md.push(`| ${r.name} | ${r.below20_pct.toFixed(1)}% | ${r.any54_pct.toFixed(1)}% | ${r.mean_bg.toFixed(1)} |`);md.push('','Interpretation:','- Compare current_full_mismatch vs persistent_full_mismatch for policy effect.','- Compare full_mismatch vs no_partial within each policy for partial-meal effect.','- If effects remain approximately additive, treat policy wind-up and nutrition mismatch as separable structural causes.','- Do not remove bolus delay; prior ablation showed delay is protective.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
