#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of[
 't2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js',
 't2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_scheduled_correction_exp.js','t2dm_inpatient_course_v1_exp.js',
 't2dm_treatment_policy_diatec_poc_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js',
 'insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v2_egp_exp.js'
])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1ScheduledCorrectionExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyDiatecPocExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV2EgpExp;
const asp=PK.get('aspart'),N=4000,DAYS=8,CORR=[180,465,765,1125,1320],target={age:76.1,age_sd:9.8,duration:13.1,duration_sd:8.7};
const ARMS=[
 {name:'decay_retitrate',freeze_stress:false,freeze_prandial:false},
 {name:'decay_no_prandial_retitration',freeze_stress:false,freeze_prandial:true},
 {name:'fixed_stress_retitrate',freeze_stress:true,freeze_prandial:false},
 {name:'fixed_stress_no_prandial_retitration',freeze_stress:true,freeze_prandial:true}
];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function dot(a,b){let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s}
function solve(A,b){const n=b.length,X=A.map((r,i)=>r.slice().concat([b[i]]));for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(X[r][c])>Math.abs(X[p][c]))p=r;if(Math.abs(X[p][c])<1e-12)throw new Error('singular');[X[c],X[p]]=[X[p],X[c]];const q=X[c][c];for(let j=c;j<=n;j++)X[c][j]/=q;for(let r=0;r<n;r++){if(r===c)continue;const f=X[r][c];for(let j=c;j<=n;j++)X[r][j]-=f*X[c][j]}}return X.map(r=>r[n])}
function entropyWeights(xs){const k=xs[0].length;let lam=Array(k).fill(0),p=[];for(let it=0;it<60;it++){const sc=xs.map(x=>dot(lam,x)),mx=Math.max(...sc),raw=sc.map(s=>Math.exp(s-mx)),z=raw.reduce((a,b)=>a+b,0);p=raw.map(w=>w/z);const mu=Array(k).fill(0);for(let n=0;n<xs.length;n++)for(let j=0;j<k;j++)mu[j]+=p[n]*xs[n][j];if(Math.max(...mu.map(Math.abs))<1e-9)break;const cov=Array.from({length:k},()=>Array(k).fill(0));for(let n=0;n<xs.length;n++)for(let j=0;j<k;j++)for(let l=0;l<k;l++)cov[j][l]+=p[n]*(xs[n][j]-mu[j])*(xs[n][l]-mu[l]);for(let j=0;j<k;j++)cov[j][j]+=1e-6;lam=lam.map((v,j)=>v-solve(cov,mu)[j])}return p}
function wq(v,w,q){const a=v.map((x,i)=>[x,w[i]]).sort((a,b)=>a[0]-b[0]);let c=0;for(const [x,ww] of a){c+=ww;if(c>=q)return x}return a[a.length-1][0]}
function frozenPatch(p){return{prandial_mass_action_low_side:true,prandial_mass_action_reference_mg_dl:Number(p.endogenous_insulin&&p.endogenous_insulin.glucose_threshold_mg_dl)||100,...CR.statePatch(M,{reserve:1,activation_width_mg_dl:10})}}
function trajPatch(tr,day,seed,freeze){if(!freeze)return T.statePatch(tr,day,seed);return{stress_severity:T.stressFor(tr,1,seed),admission_glucose_offset_mg_dl:day===1?T.admissionOffset(tr,seed):0,trajectory_class:tr}}
function copy(o){return{breakfast_u:Math.round(o.breakfast_u||0),lunch_u:Math.round(o.lunch_u||0),dinner_u:Math.round(o.dinner_u||0),basal_u:Math.round(o.basal_u||0)}}
function patient(z,arm){
 const {i,p}=z,tr=T.choose(i),initial=TP.startingOrder(p),corr=Array(DAYS).fill(0);
 const titrate=(ord,bg,ctx)=>{const before=copy(ord),next=TP.titratePoc(before,bg,ctx,{prandial_start_days:2}),was=before.breakfast_u+before.lunch_u+before.dinner_u;if(arm.freeze_prandial&&was>0){next.breakfast_u=before.breakfast_u;next.lunch_u=before.lunch_u;next.dinner_u=before.dinner_u}return next};
 const cfg={days:DAYS,titrate:true,allow_meal_mismatch:false,allow_npo:false,bolus_tau_min:asp.candidate.tau_min,bolus_duration_min:asp.candidate.duration_min,titrate_order_fn:titrate,
  state_modifier_fn:(ctx)=>({...trajPatch(tr,ctx.day,i,arm.freeze_stress),...B.statePatch(M,.20),...frozenPatch(p),prandial_poc_min:{breakfast:465,lunch:765,dinner:1125},prandial_safety_adjustment_fn:({poc_glucose_mg_dl,planned_units})=>Number(poc_glucose_mg_dl)<70?0:planned_units,scheduled_correction_minutes:CORR,scheduled_correction_fn:({glucose_mg_dl})=>{const u=TP.supplement(glucose_mg_dl,'recommended');corr[ctx.day-1]+=u;return{units:u,label:'diatec_recommended'}}})};
 const c=C.simulateCourse(M,D,p,initial,cfg,i),all=[],days=[];for(let d=0;d<DAYS;d++){const r=c.records[d],v=[];for(let t=0;t<1440;t+=5){const x=Number(r.series[t]);v.push(x);all.push(x)}const basal=Number(r.order.basal_u)||0,pr=(Number(r.order.breakfast_u)||0)+(Number(r.order.lunch_u)||0)+(Number(r.order.dinner_u)||0);days.push({tir:100*v.filter(x=>x>=70&&x<=180).length/v.length,tar:100*v.filter(x=>x>180).length/v.length,tbr:100*v.filter(x=>x<70).length/v.length,mean_bg:mean(v),basal,prandial:pr,correction:corr[d],total:basal+pr+corr[d],stress:Number(r.state.stress_severity)||0})}
 return{tir:100*all.filter(x=>x>=70&&x<=180).length/all.length,tar:100*all.filter(x=>x>180).length/all.length,tbr:100*all.filter(x=>x<70).length/all.length,mean_bg:mean(all),total_day:mean(days.map(x=>x.total)),days};
}
const pts=[];for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'support_sweep'});if(Number(p.egfr_ml_min_1_73m2)<15)continue;pts.push({i,p,x:[(Number(p.age_years)-target.age)/target.age_sd,(Number(p.duration_years)-target.duration)/target.duration_sd]})}
const w=entropyWeights(pts.map(z=>z.x)),ess=1/w.reduce((s,x)=>s+x*x,0),results=[];
for(const arm of ARMS){const rows=pts.map(z=>patient(z,arm)),wm=fn=>rows.reduce((s,r,i)=>s+w[i]*fn(r),0),day=[];for(let d=0;d<DAYS;d++)day.push({day:d+1,tir_median:wq(rows.map(r=>r.days[d].tir),w,.5),tar_median:wq(rows.map(r=>r.days[d].tar),w,.5),mean_bg:wm(r=>r.days[d].mean_bg),total_insulin:wm(r=>r.days[d].total),basal:wm(r=>r.days[d].basal),prandial:wm(r=>r.days[d].prandial),correction:wm(r=>r.days[d].correction),stress:wm(r=>r.days[d].stress)});results.push({...arm,summary:{tir_median:wq(rows.map(r=>r.tir),w,.5),tar_median:wq(rows.map(r=>r.tar),w,.5),tbr_median:wq(rows.map(r=>r.tbr),w,.5),mean_bg:wm(r=>r.mean_bg),total_insulin:wm(r=>r.total_day),day}})}
const ref=Object.fromEntries(results.map(r=>[r.name,r.summary]));const effects={stress_effect_on_tir_at_retitration:ref.decay_retitrate.tir_median-ref.fixed_stress_retitrate.tir_median,prandial_retitration_effect_on_tir_with_decay:ref.decay_retitrate.tir_median-ref.decay_no_prandial_retitration.tir_median,prandial_retitration_effect_on_tir_fixed_stress:ref.fixed_stress_retitrate.tir_median-ref.fixed_stress_no_prandial_retitration.tir_median,interaction_tir:(ref.decay_retitrate.tir_median-ref.decay_no_prandial_retitration.tir_median)-(ref.fixed_stress_retitrate.tir_median-ref.fixed_stress_no_prandial_retitration.tir_median)};
const out={purpose:'2x2 causal diagnostic of DIATEC excessive late-course improvement: current vs frozen day-1 stress crossed with prandial retitration on vs frozen after initiation. No arm is a candidate.',n:{requested:N,eligible:pts.length,ess},frozen_candidate:{mass_action_reference_mg_dl:100,cr_width_mg_dl:10,cr_reserve:1,basal_potency:.20},published_context:{poc_tir_median_pct:62.7,poc_tar180_median_pct:36.5,poc_total_insulin_u_day:29.3,los_median_days:7.8,poc_tir_plateau_after_day5_approx_pct:60},results,effects,guardrails:['Diagnostic factorial only.','Do not tune stress decay or treatment titration from outcome closeness.','All physiology, PK, basal potency, correction thresholds, starting doses, and phenotype weights are unchanged.']};
const dir='analysis/diatec_stress_prandial_factorial';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# DIATEC stress × prandial-retitration factorial','',`Eligible N=${pts.length}; ESS=${ess.toFixed(0)}.`,'','| arm | TIR median | TAR median | mean BG | insulin U/day |','|---|---:|---:|---:|---:|'];for(const r of results){const s=r.summary;md.push(`| ${r.name} | ${s.tir_median.toFixed(1)}% | ${s.tar_median.toFixed(1)}% | ${s.mean_bg.toFixed(1)} | ${s.total_insulin.toFixed(1)} |`)}md.push('',`Stress effect on TIR with retitration: ${effects.stress_effect_on_tir_at_retitration.toFixed(1)} pp.`,`Prandial-retitration effect with decay: ${effects.prandial_retitration_effect_on_tir_with_decay.toFixed(1)} pp.`,`Prandial-retitration effect with fixed stress: ${effects.prandial_retitration_effect_on_tir_fixed_stress.toFixed(1)} pp.`,`Interaction: ${effects.interaction_tir.toFixed(1)} pp.`,'','Diagnostic only; no parameter selection from DIATEC closeness.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
