#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_emory_u300_trial_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyEmoryU300TrialExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const gp=PK.get('glulisine'),N=10000,POC=new Set([420,720,1080,1260]);
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function mealDosePatch({state}){return{prandial_safety_adjustment_fn:({meal,poc_glucose_mg_dl,planned_units})=>TP.mealDose({meal,poc_glucose_mg_dl,planned_units,state})};}
function protocolPocRescue({t,glucose_mg_dl,prior_rescues}){const g=Number(glucose_mg_dl);if(!(g<70))return 0;const rs=prior_rescues||[],last=rs.length?rs[rs.length-1]:null;const scheduled=POC.has(t),repeat=!!(last&&last.label==='protocol_poc_glucose'&&t===last.minute+15);if(!(scheduled||repeat))return 0;return{carbs_g:12.5,cooldown_min:15,label:'protocol_poc_glucose'};}
const ev=[],ct=[];
for(let i=1;i<=N;i++){
 const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(140,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);
 const cfg={days:1,titrate:false,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:false,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...mealDosePatch(ctx),bedtime_correction_fn:({glucose_mg_dl})=>TP.bedtimeSupplement(glucose_mg_dl,'usual'),hypoglycemia_rescue_fn:protocolPocRescue})};
 const c=C.simulateCourse(M,D,p,o,cfg,i),r=c.records[0];let event=false;for(let t=480;t<720;t++){if(r.series[t]<20){event=true;break}}
 const a=(r.prandial_safety_adjustments||[]).find(x=>x.meal==='breakfast');const prior=r.series[420],planned=a?a.planned_units:o.breakfast_u,given=a?a.given_units:planned,corr=given-planned;
 const x={archetype:p.patient_archetype,trajectory:tr.name||tr.id||String(tr),age:p.age_years,bmi:p.bmi_kg_m2,weight:p.body_weight_kg,egfr:p.egfr_ml_min_1_73m2,duration:p.duration_years,si:p.si_relative,beta:p.beta_cell_reserve,hepatic_ir:p.hepatic_ir,admission_bg:adm,start_tdd_kg:(o.breakfast_u+o.lunch_u+o.dinner_u+o.basal_u)/p.body_weight_kg,preB:prior,planned_u:planned,given_u:given,correction_u:corr,dose_kg:given/p.body_weight_kg,intake:r.state.intake_fraction&&r.state.intake_fraction.breakfast,meal_shift:r.state.meal_shift_min&&r.state.meal_shift_min.breakfast,bolus_shift:r.state.bolus_shift_min&&r.state.bolus_shift_min.breakfast};
 (event?ev:ct).push(x);
}
function sum(arr){const num=k=>mean(arr.map(x=>x[k]).filter(Number.isFinite));const cat=k=>Object.fromEntries([...new Set(arr.map(x=>x[k]))].map(v=>[v,arr.filter(x=>x[k]===v).length]));return{n:arr.length,age:num('age'),bmi:num('bmi'),weight:num('weight'),egfr:num('egfr'),duration:num('duration'),si:num('si'),beta:num('beta'),hepatic_ir:num('hepatic_ir'),admission_bg:num('admission_bg'),start_tdd_kg:num('start_tdd_kg'),preB:num('preB'),planned_u:num('planned_u'),given_u:num('given_u'),correction_u:num('correction_u'),dose_kg:num('dose_kg'),intake:num('intake'),archetype:cat('archetype'),trajectory:cat('trajectory'),age70_pct:100*arr.filter(x=>x.age>=70).length/arr.length,egfr60_pct:100*arr.filter(x=>x.egfr<60).length/arr.length,start03_pct:100*arr.filter(x=>x.start_tdd_kg<.35).length/arr.length,start04_pct:100*arr.filter(x=>x.start_tdd_kg>=.35&&x.start_tdd_kg<.45).length/arr.length,start05_pct:100*arr.filter(x=>x.start_tdd_kg>=.45).length/arr.length};}
const E=sum(ev),C0=sum(ct),out={purpose:'D1 breakfast-tail specificity. Event label uses hidden minute glucose post hoc only. Treatment inputs remain observed POC and registered protocol. Baseline latent physiology is reported for attribution, never as policy input.',n:N,event_pct:100*ev.length/N,event:E,control:C0};
const dir='analysis/emory_d1_breakfast_tail_baseline_specificity';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));
let md=['# Emory D1 breakfast <20 baseline specificity','',`N=${N}; D1 breakfast-window <20: ${ev.length} (${out.event_pct.toFixed(2)}%).`,'','| metric | event | non-event |','|---|---:|---:|'];for(const [k,label] of [['age','age'],['bmi','BMI'],['weight','weight kg'],['egfr','eGFR'],['duration','duration y'],['si','SI relative'],['beta','beta reserve'],['hepatic_ir','hepatic IR'],['admission_bg','admission BG'],['start_tdd_kg','start TDD/kg'],['preB','07:00 POC'],['planned_u','planned breakfast U'],['given_u','given breakfast U'],['correction_u','correction U'],['dose_kg','given U/kg'],['intake','breakfast intake']])md.push(`| ${label} | ${E[k].toFixed(3)} | ${C0[k].toFixed(3)} |`);md.push('',`Start tier event: <.35 ${E.start03_pct.toFixed(1)}%, .35-.45 ${E.start04_pct.toFixed(1)}%, >=.45 ${E.start05_pct.toFixed(1)}%.`,`Start tier non-event: <.35 ${C0.start03_pct.toFixed(1)}%, .35-.45 ${C0.start04_pct.toFixed(1)}%, >=.45 ${C0.start05_pct.toFixed(1)}%.`,'','Event archetypes: '+JSON.stringify(E.archetype),'Non-event archetypes: '+JSON.stringify(C0.archetype),'Event trajectories: '+JSON.stringify(E.trajectory),'Non-event trajectories: '+JSON.stringify(C0.trajectory),'','Guardrails:','- Attribution only; SI/beta/hepatic IR are hidden and cannot become treatment inputs.','- Do not change registered start tiers, correction table, PK, stress, basal potency, or phenotype weights from this result alone.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
