#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','t2dm_treatment_policy_emory_u300_trial_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v2_egp_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,EP=T2DMTreatmentPolicyEmoryU300TrialExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV2EgpExp;
const gp=PK.get('glulisine'),NEX=5000,NSH=1500;
const MAP={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))}
function persistent2of4(order,bg){const next=TP.componentTitrate(order,bg),vals=Object.values(bg).map(Number).filter(Number.isFinite),nHigh=vals.filter(x=>x>=180).length;for(const [comp,key] of Object.entries(MAP)){const cur=Number(order[comp])||0,nxt=Number(next[comp])||0,signal=Number(bg[key]);if(nxt>cur&&!(Number.isFinite(signal)&&signal>=180&&nHigh>=2))next[comp]=cur;}return next}
function genericMealMatchedPatch({order,state}){const intake=state.intake_fraction||{},mealShift=state.meal_shift_min||{},bolusShift={...(state.bolus_shift_min||{})},bolusFraction={...(state.bolus_fraction||{})};for(const meal of ['breakfast','lunch','dinner']){const f=Number(intake[meal]);if(!Number.isFinite(f)||f>=.85)continue;const key=meal+'_u',ordered=Math.max(0,Math.round(Number(order[key])||0)),given=Math.max(0,Math.round(ordered*Math.max(0,Math.min(1,f))));bolusFraction[meal]=ordered>0?given/ordered:0;const ms=Number(mealShift[meal])||0;bolusShift[meal]=Math.max(Number(bolusShift[meal])||0,15+ms);}return{bolus_fraction:bolusFraction,bolus_shift_min:bolusShift};}
function safetyOnly({poc_glucose_mg_dl,planned_units}){const bg=Number(poc_glucose_mg_dl),u=Math.max(0,Math.round(Number(planned_units)||0));if(bg<70)return Math.max(0,u-2);if(bg<100)return Math.max(0,u-1);return u;}
function thresholdAlignedPatch(){const width=10,maxDrive=CR.maxDriveMgDlMin();return{fasting_adjustment_fn:({t,glucose_mg_dl})=>{const g=Number(glucose_mg_dl),threshold=CR.isSleepMinute(t)?CR.SLEEP_THRESHOLD_MG_DL:CR.AWAKE_THRESHOLD_MG_DL;if(!Number.isFinite(g)||g>=threshold)return{restore_multiplier:1,drive_mg_dl_per_min:0};return{restore_multiplier:0,drive_mg_dl_per_min:maxDrive*CR.activation(threshold-g,width)};},counterregulation_model:'threshold-aligned-egp-v2-sensitivity'};}
function protocolStatePatch(ctx,counter){
 const state=ctx.state||{},intake={breakfast:1,lunch:1,dinner:1,...(state.intake_fraction||{})},mealShift={breakfast:0,lunch:0,dinner:0,...(state.meal_shift_min||{})};
 const bolusShift={},bolusFraction={};for(const meal of ['breakfast','lunch','dinner']){bolusShift[meal]=Number(mealShift[meal])||0;bolusFraction[meal]=1;}
 const mealFn=({meal,poc_glucose_mg_dl,planned_units,state:s})=>{const f=Number(s&&s.intake_fraction&&s.intake_fraction[meal]);const poor=Number.isFinite(f)&&f<.85,scale=poor?'sensitive':'usual',supp=EP.premealSupplement(poc_glucose_mg_dl,scale),sched=poor?0:Math.max(0,Math.round(Number(planned_units)||0));counter.supplement_u+=supp;counter.supplement_events+=supp>0?1:0;if(poor){counter.held_meals++;counter.poor_meals++;}return sched+supp;};
 return{bolus_shift_min:bolusShift,bolus_fraction:bolusFraction,prandial_safety_adjustment_fn:mealFn};
}
const ARMS=[
 {name:'generic_persistent2of4_legacy',policy:'generic',cr:false,primary:false},
 {name:'emory_registered2019_legacy',policy:'emory',cr:false,primary:true},
 {name:'emory_registered2019_threshold_aligned_cr_sensitivity',policy:'emory',cr:true,primary:false}
];
function external(arm,N=NEX){
 let p20=0,p30=0,p40=0,p54=0,p70=0,noct70=0,noct54=0,deep54=0,total=0,n70=0,n54=0,n180=0,n250=0;const pMeans=[],pCV=[],pocVals=[],scheduledTddKg=[],basalU=[],prandialScheduledU=[];let supplementU=0,bedtimeSupplementU=0,heldMeals=0;
 for(let i=1;i<=N;i++){
  const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(140,Math.min(400,p.observed_fasting_glucose_mg_dl)),tr=T.choose(i);const counter={supplement_u:0,supplement_events:0,held_meals:0,poor_meals:0};
  const o=arm.policy==='emory'?EP.startingOrder(p,{admission_bg_mg_dl:adm}):TP.startingOrder(p,{admission_bg_mg_dl:adm});
  const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:arm.policy==='emory'?0:30,underbolus_probability:arm.policy==='emory'?0:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:arm.policy==='emory'?EP.registered2019Titrate:persistent2of4,state_modifier_fn:(ctx)=>{
    let patch={...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20)};if(arm.cr)Object.assign(patch,thresholdAlignedPatch());
    if(arm.policy==='emory'){Object.assign(patch,protocolStatePatch(ctx,counter));patch.bedtime_correction_fn=({glucose_mg_dl})=>{const u=EP.bedtimeSupplement(glucose_mg_dl,'usual');bedtimeSupplementU+=u;return u;};}
    else{Object.assign(patch,genericMealMatchedPatch(ctx));patch.prandial_safety_adjustment_fn=safetyOnly;patch.bedtime_correction_fn=({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl);}
    return patch;
  }};
  const c=C.simulateCourse(M,D,p,o,cfg,i);supplementU+=counter.supplement_u;heldMeals+=counter.held_meals;let a20=false,a30=false,a40=false,a54=false,a70=false,n70p=false,n54p=false,d54p=false;const xs=[];
  for(const r of c.records){const ord=r.order;scheduledTddKg.push((ord.basal_u+ord.breakfast_u+ord.lunch_u+ord.dinner_u)/p.body_weight_kg);basalU.push(ord.basal_u);prandialScheduledU.push(ord.breakfast_u+ord.lunch_u+ord.dinner_u);for(const x of Object.values(r.bg||{}))if(Number.isFinite(Number(x)))pocVals.push(Number(x));for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);total++;if(x<20)a20=true;if(x<30)a30=true;if(x<40)a40=true;if(x<54){a54=true;n54++;}if(x<70){a70=true;n70++;}if(x>180)n180++;if(x>250)n250++;const no=t>=1320||t<360;if(no&&x<70)n70p=true;if(no&&x<54)n54p=true;if(t<360&&x<54)d54p=true;}}
  if(a20)p20++;if(a30)p30++;if(a40)p40++;if(a54)p54++;if(a70)p70++;if(n70p)noct70++;if(n54p)noct54++;if(d54p)deep54++;const m=mean(xs);pMeans.push(m);pCV.push(100*sd(xs)/m);
 }
 return{arm:arm.name,n:N,mean_bg:mean(pMeans),tir_pct:100*(total-n70-n180)/total,tar180_pct:100*n180/total,tar250_pct:100*n250/total,tbr70_pct:100*n70/total,tbr54_pct:100*n54/total,cv_pct:mean(pCV),patients_any70_pct:100*p70/N,patients_any54_pct:100*p54/N,noct70_pct:100*noct70/N,noct54_pct:100*noct54/N,deep00_06_54_pct:100*deep54/N,patients_below20_pct:100*p20/N,patients_below30_pct:100*p30/N,patients_below40_pct:100*p40/N,poc_mean_mg_dl:mean(pocVals),mean_scheduled_tddkg:mean(scheduledTddKg),mean_basal_u:mean(basalU),mean_scheduled_prandial_u:mean(prandialScheduledU),supplement_u_per_patient_day:supplementU/(N*8),bedtime_supplement_u_per_patient_day:bedtimeSupplementU/(N*8),held_meals_per_patient_day:heldMeals/(N*8)};
}
function shanghaiDescriptive(N=NSH){const all=[],poc=[];let tbr=0,tir=0,total=0;for(let i=1;i<=N;i++){const p=P1.sample(i),adm=Math.max(140,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=EP.startingOrder(p,{admission_bg_mg_dl:adm}),counter={supplement_u:0,supplement_events:0,held_meals:0,poor_meals:0};const cfg={days:8,titrate:true,allow_meal_mismatch:false,allow_npo:false,bolus_tau_min:90,bolus_duration_min:330,titrate_order_fn:EP.registered2019Titrate,state_modifier_fn:(ctx)=>({...B.statePatch(M,.20),...protocolStatePatch(ctx,counter),bedtime_correction_fn:({glucose_mg_dl})=>EP.bedtimeSupplement(glucose_mg_dl,'usual')})};const c=C.simulateCourse(M,D,p,o,cfg,i);for(let d=2;d<c.records.length;d++){const r=c.records[d];for(const x of Object.values(r.bg||{}))poc.push(Number(x));for(let t=0;t<1440;t++){const x=r.series[t];all.push(x);total++;if(x<70)tbr++;if(x>=70&&x<=180)tir++;}}}return{n:N,mean:mean(all),poc_mean:mean(poc),tbr70:100*tbr/total,tir:100*tir/total,note:'Descriptive only: Emory trial policy is context-specific and is not proposed as the Shanghai/global treatment policy.'};}
const rows=ARMS.map(a=>external(a)),primary=rows.find((r,i)=>ARMS[i].primary);const out={purpose:'External validation under the documented Glargine U300 Hospital Trial treatment context rather than a generic invented ward titration policy. Primary physiology is frozen legacy low-side; threshold-aligned counterregulation is sensitivity only and cannot be selected by Emory fit.',source_protocol:{trial:'NCT03013985, protocol version 2019-01-28',starting:'0.4 U/kg for admission BG 140-200, 0.5 U/kg for 201-400, 0.3 U/kg if age >=70 or eGFR <60; 50% basal / 50% prandial',nutrition:'full scheduled glulisine before meals when eating; hold scheduled prandial for poor intake/NPO; sensitive supplemental scale when poor/NPO',correction:'usual premeal scale: 141-180=3, 181-220=4, 221-260=5, 261-300=6, 301-350=8, 351-400=10, >400=12 U; usual bedtime >220 scale 2/3/4/5/6 U',daily_adjustment:'registered 2019 protocol: basal +10% for 141-180, +20% for 181-299, +30% for >=300 based on fasting/predinner in absence of low; TDD -10% when fasting+predinner 70-99, -20% for any POC <70, deterministic -30% for <40 (published range 30-40%)'},n:{external:NEX,shanghai_descriptive:NSH},targets:{emory_cgm:{mean:176.1,tir:53.5,tar180:42.2,tar250:16.1,tbr70:4.5,tbr54:1.58,cv:32,any70:56,any54:36,noct70:41,noct54:26},parent_trial_treatment_exposure:{tdd_ukg_day:0.43,basal_u_day:29,prandial_u_day:14,supplement_u_day:7.5,poc_mean_approx:185}},rows,primary_safety_gate:primary.patients_below20_pct<=1,shanghai_descriptive:shanghaiDescriptive()};
const dir='analysis/emory_published_protocol_external_validation';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Emory published-protocol external validation','','Primary arm uses the registered 2019 Glargine U300 Hospital Trial treatment protocol with frozen legacy low-side physiology. Threshold-aligned counterregulation is sensitivity only.','','| arm | <20 safety | mean | POC mean | TIR | TAR>180 | TAR>250 | TBR<70 | TBR<54 | CV | any<70 | any<54 | noct<70 | noct<54 | 00–06<54 | <20pt | TDD/kg | basal U | sched prandial U | supp U/day |','|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows)md.push(`| ${r.arm} | ${r.patients_below20_pct<=1?'PASS':'FAIL'} | ${r.mean_bg.toFixed(1)} | ${r.poc_mean_mg_dl.toFixed(1)} | ${r.tir_pct.toFixed(1)}% | ${r.tar180_pct.toFixed(1)}% | ${r.tar250_pct.toFixed(1)}% | ${r.tbr70_pct.toFixed(2)}% | ${r.tbr54_pct.toFixed(2)}% | ${r.cv_pct.toFixed(1)}% | ${r.patients_any70_pct.toFixed(1)}% | ${r.patients_any54_pct.toFixed(1)}% | ${r.noct70_pct.toFixed(1)}% | ${r.noct54_pct.toFixed(1)}% | ${r.deep00_06_54_pct.toFixed(1)}% | ${r.patients_below20_pct.toFixed(2)}% | ${r.mean_scheduled_tddkg.toFixed(3)} | ${r.mean_basal_u.toFixed(1)} | ${r.mean_scheduled_prandial_u.toFixed(1)} | ${(r.supplement_u_per_patient_day+r.bedtime_supplement_u_per_patient_day).toFixed(2)} |`);md.push('','Emory CGM target: mean 176.1, TIR 53.5%, TAR>180 42.2%, TAR>250 16.1%, TBR<70 4.5%, TBR<54 1.58%, CV 32%, any<70 56%, any<54 36%, noct<70 41%, noct<54 26%.','Parent U300 trial treatment exposure: TDD ~0.43 U/kg/day, basal ~29 U/day, scheduled prandial ~14 U/day, supplemental ~7.5 U/day.','',`Primary catastrophic-tail gate: **${out.primary_safety_gate?'PASS':'FAIL'}**`,'',`Shanghai descriptive under Emory context policy: mean ${out.shanghai_descriptive.mean.toFixed(1)}, POC mean ${out.shanghai_descriptive.poc_mean.toFixed(1)}, TIR ${out.shanghai_descriptive.tir.toFixed(1)}%, TBR<70 ${out.shanghai_descriptive.tbr70.toFixed(2)}%. This is not a global-policy preservation gate.`,'','Guardrails:','- Do not tune the published correction scale, starting doses, or registered basal-adjustment percentages to Emory outcomes.','- Do not select threshold-aligned counterregulation by Emory closeness; it is sensitivity only.','- Hidden CGM values never trigger treatment.','- Protocol-adherent timing overrides generated underbolus/delay; nutrition variability remains, and poor intake uses the published hold/sensitive-scale branch.','- The <40 deterministic reduction uses 30%, the lower bound of the published 30–40% range; treat this as an explicit operationalization uncertainty.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));if(!out.primary_safety_gate)process.exitCode=2;
