#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const gp=PK.get('glulisine'),map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function tdd(o){return o.basal_u+o.breakfast_u+o.lunch_u+o.dinner_u}
function persistentTitrator(order,bg){const next=TP.componentTitrate(order,bg),vals=Object.values(bg).map(Number).filter(Number.isFinite),nHigh=vals.filter(x=>x>=180).length;for(const [comp,key] of Object.entries(map)){const cur=Number(order[comp])||0,nxt=Number(next[comp])||0,signal=Number(bg[key]);if(nxt>cur && !(Number.isFinite(signal)&&signal>=180&&nHigh>=2))next[comp]=cur;}return next}
function shanghai(arm,N=1200){const all=[],preB=[],preL=[],preD=[],d120=[];let tbr70n=0,tirn=0,total=0;for(let i=1;i<=N;i++){const p=P1.sample(i),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});const cfg={days:6,titrate:true,allow_meal_mismatch:false,allow_npo:false,bolus_tau_min:90,bolus_duration_min:330,titrate_order_fn:arm==='current'?((ord,bg)=>TP.componentTitrate(ord,bg)):persistentTitrator,state_modifier_fn:()=>({...B.statePatch(M,.20)})};const c=C.simulateCourse(M,D,p,o,cfg,i);for(let d=2;d<c.records.length;d++){const r=c.records[d];for(let t=0;t<1440;t++){const x=r.series[t];all.push(x);total++;if(x<70)tbr70n++;if(x>=70&&x<=180)tirn++;}preB.push(r.series[420]);preL.push(r.series[720]);preD.push(r.series[1080]);d120.push(r.series[600]-r.series[480]);}}
return{mean:mean(all),preB:mean(preB),preL:mean(preL),preD:mean(preD),delta120:mean(d120),tbr70:100*tbr70n/total,tir:100*tirn/total};}
function external(arm,N=1800){let p20=0,p54=0;const d8bg=[],d8tdd=[];for(let i=1;i<=N;i++){const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:arm==='current'?((ord,bg)=>TP.componentTitrate(ord,bg)):persistentTitrator,state_modifier_fn:({day})=>({...T.statePatch('resolving_acute',day,i),...B.statePatch(M,.20),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i);let a20=false,a54=false;for(const r of c.records){if(r.series.some(x=>x<20))a20=true;if(r.series.some(x=>x<54))a54=true}if(a20)p20++;if(a54)p54++;const r=c.records[c.records.length-1];d8bg.push(mean(r.series));d8tdd.push(tdd(r.order)/p.body_weight_kg)}return{below20_pct:100*p20/N,any54_pct:100*p54/N,d8_mean_bg:mean(d8bg),d8_tddkg:mean(d8tdd)}}
const sh0=shanghai('current'),rows=[];for(const arm of ['current','persistent_2of4']){const sh=arm==='current'?sh0:shanghai(arm),ex=external(arm),d={};for(const k of ['mean','preB','preL','preD','delta120','tbr70','tir'])d[k]=sh[k]-sh0[k];const gate=Math.abs(d.mean)<5&&Math.abs(d.preB)<5&&Math.abs(d.preL)<5&&Math.abs(d.preD)<5&&Math.abs(d.delta120)<2&&Math.abs(d.tbr70)<1&&Math.abs(d.tir)<3;rows.push({arm,shanghai:sh,delta:d,shanghai_gate:gate,resolving_acute:ex})}
const out={purpose:'Guideline-grounded persistence gate diagnostic; not outcome calibration',rule:'Upward component titration is allowed only when its corresponding POC glucose is >=180 mg/dL and at least two of the four same-day POC values are >=180 mg/dL. Downward titration remains immediate and unchanged.',rows};const dir='analysis/persistent_hyperglycemia_intensification';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Persistent hyperglycemia intensification audit','','Structural diagnostic based on the inpatient principle that therapy intensification should follow persistent hyperglycemia rather than an isolated elevated reading. No hidden physiology is visible to the policy.','','| arm | Shanghai | Δmean | ΔpreB | ΔpreL | ΔpreD | Δ120 | ΔTBR<70 | ΔTIR | resolving <20 | resolving any<54 | D8 mean |','|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const d=r.delta,e=r.resolving_acute;md.push(`| ${r.arm} | ${r.shanghai_gate?'PASS':'FAIL'} | ${d.mean.toFixed(2)} | ${d.preB.toFixed(2)} | ${d.preL.toFixed(2)} | ${d.preD.toFixed(2)} | ${d.delta120.toFixed(2)} | ${d.tbr70.toFixed(2)}pp | ${d.tir.toFixed(2)}pp | ${e.below20_pct.toFixed(1)}% | ${e.any54_pct.toFixed(1)}% | ${e.d8_mean_bg.toFixed(1)} |`)}md.push('','Guardrails:','- Do not tune the >=180 mg/dL threshold or the persistence count to Shanghai or Emory outcomes.','- This audit tests a guideline-grounded policy structure only.','- Reject before external validation if Shanghai preservation fails.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));if(rows.some(r=>r.arm!=='current'&&!r.shanghai_gate))process.exitCode=2;
