#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_emory_u300_trial_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyEmoryU300TrialExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const gp=PK.get('glulisine'),N=6000,POC=new Set([420,720,1080,1260]);
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function mealDosePatch({state}){return{prandial_safety_adjustment_fn:({meal,poc_glucose_mg_dl,planned_units})=>TP.mealDose({meal,poc_glucose_mg_dl,planned_units,state})};}
function protocolPocRescue({t,glucose_mg_dl,prior_rescues}){const g=Number(glucose_mg_dl);if(!(g<70))return 0;const rs=prior_rescues||[],last=rs.length?rs[rs.length-1]:null;const scheduled=POC.has(t),repeat=!!(last&&last.label==='protocol_poc_glucose'&&t===last.minute+15);if(!(scheduled||repeat))return 0;return{carbs_g:12.5,cooldown_min:15,label:'protocol_poc_glucose'};}
const meta={breakfast:{poc:420,start:465,end:720},lunch:{poc:720,start:765,end:1080},dinner:{poc:1080,start:1125,end:1260}};
const rows=[];
for(let i=1;i<=N;i++){
 const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(140,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);
 const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.registered2019Titrate(ord,bg),state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...mealDosePatch(ctx),bedtime_correction_fn:({glucose_mg_dl})=>TP.bedtimeSupplement(glucose_mg_dl,'usual'),hypoglycemia_rescue_fn:protocolPocRescue})};
 const c=C.simulateCourse(M,D,p,o,cfg,i);
 for(const r of c.records){for(const meal of ['breakfast','lunch','dinner']){const m=meta[meal],adj=(r.prandial_safety_adjustments||[]).find(a=>a.meal===meal)||null;const planned=adj?Number(adj.planned_units):Number(r.order[meal+'_u']);const given=adj?Number(adj.given_units):planned;const correction=Number.isFinite(given)&&Number.isFinite(planned)?given-planned:0;const intake=Number(r.state&&r.state.intake_fraction&&r.state.intake_fraction[meal]);const poc=Number(r.series[m.poc]);let event=false,minv=Infinity;for(let t=m.start;t<m.end;t++){const x=r.series[t];if(x<minv)minv=x;if(x<20)event=true;}rows.push({event,meal,day:r.day,poc,planned_u:planned,given_u:given,correction_u:correction,intake,partial:Number.isFinite(intake)&&intake<.85,dose_per_kg:given/p.body_weight_kg,scheduled_tdd_per_kg:(r.order.basal_u+r.order.breakfast_u+r.order.lunch_u+r.order.dinner_u)/p.body_weight_kg,min_window:minv,profile:tr.name||tr.id||String(tr)});}}
}
function s(xs){return{n:xs.length,event_pct:100*xs.filter(x=>x.event).length/xs.length,poc:mean(xs.map(x=>x.poc)),planned_u:mean(xs.map(x=>x.planned_u)),given_u:mean(xs.map(x=>x.given_u)),correction_u:mean(xs.map(x=>x.correction_u)),correction_positive_pct:100*xs.filter(x=>x.correction_u>0).length/xs.length,intake:mean(xs.map(x=>x.intake).filter(Number.isFinite)),partial_pct:100*xs.filter(x=>x.partial).length/xs.length,dose_per_kg:mean(xs.map(x=>x.dose_per_kg)),scheduled_tdd_per_kg:mean(xs.map(x=>x.scheduled_tdd_per_kg))};}
const eventRows=rows.filter(x=>x.event),non=rows.filter(x=>!x.event);const groups={all_event:s(eventRows),all_non_event:s(non)};for(const meal of ['breakfast','lunch','dinner']){groups[meal+'_event']=s(eventRows.filter(x=>x.meal===meal));groups[meal+'_non_event']=s(non.filter(x=>x.meal===meal));}
const out={purpose:'Specificity audit across all simulated patient-meals under registered protocol plus observable POC rescue. Compares meal windows containing <20 with non-event meal windows using only observable treatment inputs; hidden physiology is not used for policy.',n_patients:N,n_meals:rows.length,n_event_meals:eventRows.length,event_meal_pct:100*eventRows.length/rows.length,groups};
const dir='analysis/emory_registered_rescue_meal_specificity';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Emory registered protocol + POC rescue meal specificity','',`N patients=${N}; meals=${rows.length}; event meals=${eventRows.length} (${out.event_meal_pct.toFixed(3)}%).`,'','| group | n | POC | planned U | given U | correction U | correction>0 | intake | partial | dose/kg | sched TDD/kg |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const k of ['all_event','all_non_event','breakfast_event','breakfast_non_event','lunch_event','lunch_non_event','dinner_event','dinner_non_event']){const r=groups[k];md.push(`| ${k} | ${r.n} | ${r.poc.toFixed(1)} | ${r.planned_u.toFixed(2)} | ${r.given_u.toFixed(2)} | ${r.correction_u.toFixed(2)} | ${r.correction_positive_pct.toFixed(1)}% | ${r.intake.toFixed(3)} | ${r.partial_pct.toFixed(1)}% | ${r.dose_per_kg.toFixed(3)} | ${r.scheduled_tdd_per_kg.toFixed(3)} |`);}md.push('','Guardrails:','- No threshold or dose is selected from this result.','- Hidden minute glucose labels the outcome window only.','- Published treatment rules and frozen physiology remain unchanged.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
