#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const N=1800,gp=PK.get('glulisine'),PROFILE='resolving_acute';
const ARMS=['current','freeze_basal','freeze_breakfast','freeze_lunch','freeze_dinner'];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function tdd(o){return o.breakfast_u+o.lunch_u+o.dinner_u+o.basal_u}
function titrator(arm){return(ord,bg)=>{const nxt=TP.componentTitrate(ord,bg);if(arm==='freeze_basal')nxt.basal_u=ord.basal_u;if(arm==='freeze_breakfast')nxt.breakfast_u=ord.breakfast_u;if(arm==='freeze_lunch')nxt.lunch_u=ord.lunch_u;if(arm==='freeze_dinner')nxt.dinner_u=ord.dinner_u;return nxt;}}
function run(arm){let p20=0,p54=0;const days=Array.from({length:8},(_,i)=>({day:i+1,n:0,meanbg:[],tddkg:[],basal:[],breakfast:[],lunch:[],dinner:[],low54:0}));for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:titrator(arm),state_modifier_fn:({day})=>({...T.statePatch(PROFILE,day,i),...B.statePatch(M,.20),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i);let a20=false,a54=false;for(const r of c.records){const z=r.series,d=days[r.day-1],w=p.body_weight_kg;d.n++;d.meanbg.push(mean(z));d.tddkg.push(tdd(r.order)/w);d.basal.push(r.order.basal_u/w);d.breakfast.push(r.order.breakfast_u/w);d.lunch.push(r.order.lunch_u/w);d.dinner.push(r.order.dinner_u/w);if(z.some(x=>x<54)){d.low54++;a54=true}if(z.some(x=>x<20))a20=true;}if(a20)p20++;if(a54)p54++;}return{arm,below20_pct:100*p20/N,any54_pct:100*p54/N,days:days.map(d=>({day:d.day,meanbg:mean(d.meanbg),tddkg:mean(d.tddkg),basal:mean(d.basal),breakfast:mean(d.breakfast),lunch:mean(d.lunch),dinner:mean(d.dinner),day_any54_pct:100*d.low54/d.n}))};}
const rows=ARMS.map(run),out={purpose:'component-specific titration ablation in resolving acute trajectory; causal diagnostic only',n:N,profile:PROFILE,rows};const dir='analysis/resolving_component_titration_ablation';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Resolving-acute component titration ablation','','Diagnostic only. Each arm freezes one insulin component at its prior-day dose while all other policy and physiology remain unchanged. No arm is eligible for calibration.','','| arm | patients <20 | any <54 | D8 mean BG | D8 TDD/kg | D8 basal/kg | D8 breakfast/kg | D8 lunch/kg | D8 dinner/kg |','|---|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const d=r.days[7];md.push(`| ${r.arm} | ${r.below20_pct.toFixed(1)}% | ${r.any54_pct.toFixed(1)}% | ${d.meanbg.toFixed(1)} | ${d.tddkg.toFixed(3)} | ${d.basal.toFixed(3)} | ${d.breakfast.toFixed(3)} | ${d.lunch.toFixed(3)} | ${d.dinner.toFixed(3)} |`);}md.push('','Interpretation guardrails:','- A selective fall in <20 when freezing one component implicates that component\'s titration path.','- Do not adopt a frozen-component arm as treatment policy.','- Any later policy change must use observable data only and must be independently validated.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
