#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_emory_u300_trial_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyEmoryU300TrialExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const gp=PK.get('glulisine'),N=10000,POC=new Set([420,720,1080,1260]);
const target={age:54.5,age_sd:11,bmi:33.8,bmi_sd:9,duration:11.5,duration_sd:9};
function dot(a,b){let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s}
function inv3(A){const a=A[0][0],b=A[0][1],c=A[0][2],d=A[1][0],e=A[1][1],f=A[1][2],g=A[2][0],h=A[2][1],i=A[2][2];const A11=e*i-f*h,A12=-(d*i-f*g),A13=d*h-e*g,A21=-(b*i-c*h),A22=a*i-c*g,A23=-(a*h-b*g),A31=b*f-c*e,A32=-(a*f-c*d),A33=a*e-b*d;const det=a*A11+b*A12+c*A13;if(Math.abs(det)<1e-12)throw new Error('singular covariance');return[[A11/det,A21/det,A31/det],[A12/det,A22/det,A32/det],[A13/det,A23/det,A33/det]]}
function matvec(A,x){return A.map(r=>dot(r,x))}
function entropyWeights(xs){let lam=[0,0,0],p=[];for(let it=0;it<40;it++){const scores=xs.map(x=>dot(lam,x)),mx=Math.max(...scores),raw=scores.map(s=>Math.exp(s-mx)),z=raw.reduce((a,b)=>a+b,0);p=raw.map(w=>w/z);const mu=[0,0,0];for(let n=0;n<xs.length;n++)for(let j=0;j<3;j++)mu[j]+=p[n]*xs[n][j];if(Math.max(...mu.map(Math.abs))<1e-10)break;const cov=[[0,0,0],[0,0,0],[0,0,0]];for(let n=0;n<xs.length;n++)for(let j=0;j<3;j++)for(let k=0;k<3;k++)cov[j][k]+=p[n]*(xs[n][j]-mu[j])*(xs[n][k]-mu[k]);for(let j=0;j<3;j++)cov[j][j]+=1e-9;const step=matvec(inv3(cov),mu);lam=lam.map((v,j)=>v-step[j]);}return{p,lambda:lam}}
function wmean(rows,w,key){let s=0;for(let i=0;i<rows.length;i++)s+=w[i]*rows[i][key];return s}
function shares(rows,w,key){const out={};for(let i=0;i<rows.length;i++)out[rows[i][key]]=(out[rows[i][key]]||0)+w[i];return out}
function mealDosePatch({state}){const ms={breakfast:0,lunch:0,dinner:0,...(state.meal_shift_min||{})};return{bolus_shift_min:{...ms},bolus_fraction:{breakfast:1,lunch:1,dinner:1},prandial_safety_adjustment_fn:({meal,poc_glucose_mg_dl,planned_units})=>TP.mealDose({meal,poc_glucose_mg_dl,planned_units,state})};}
function protocolPocRescue({t,glucose_mg_dl,prior_rescues}){const g=Number(glucose_mg_dl);if(!(g<70))return 0;const rs=prior_rescues||[],last=rs.length?rs[rs.length-1]:null;const scheduled=POC.has(t),repeat=!!(last&&last.label==='protocol_poc_glucose'&&t===last.minute+15);if(!(scheduled||repeat))return 0;return{carbs_g:12.5,cooldown_min:15,label:'protocol_poc_glucose'};}
const pts=[];for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'});if(p.egfr_ml_min_1_73m2<30)continue;pts.push({i,p,x:[(p.age_years-target.age)/target.age_sd,(p.bmi_kg_m2-target.bmi)/target.bmi_sd,(p.duration_years-target.duration)/target.duration_sd]});}
const ew=entropyWeights(pts.map(x=>x.x)),weights=ew.p,uw=pts.map(()=>1/pts.length),rows=[];
for(let n=0;n<pts.length;n++){const {i,p}=pts[n],adm=Math.max(140,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.registered2019Titrate(ord,bg),state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...mealDosePatch(ctx),bedtime_correction_fn:({glucose_mg_dl})=>TP.bedtimeSupplement(glucose_mg_dl,'usual'),hypoglycemia_rescue_fn:protocolPocRescue})};const c=C.simulateCourse(M,D,p,o,cfg,i);let total=0,l70=0,l54=0,h180=0,h250=0,a20=0,a30=0,a40=0,pocN=0,poc70=0,poc54=0,poc180=0,poc250=0,sum=0,pocSum=0;for(const r of c.records){for(const t of [420,720,1080,1260]){const x=r.series[t];pocN++;pocSum+=x;if(x<70)poc70++;if(x<54)poc54++;if(x>180)poc180++;if(x>250)poc250++;}for(let t=0;t<1440;t+=15){const x=r.series[t];total++;sum+=x;if(x<70)l70++;if(x<54)l54++;if(x>180)h180++;if(x>250)h250++;if(x<20)a20=1;if(x<30)a30=1;if(x<40)a40=1;}}rows.push({age:p.age_years,bmi:p.bmi_kg_m2,duration:p.duration_years,egfr:p.egfr_ml_min_1_73m2,si:p.si_relative,archetype:p.patient_archetype,trajectory:tr.name||tr.id||String(tr),mean_bg:sum/total,tir:(total-l70-h180)/total,tar180:h180/total,tar250:h250/total,tbr70:l70/total,tbr54:l54/total,p20:a20,p30:a30,p40:a40,poc_mean:pocSum/pocN,poc_tir:(pocN-poc70-poc180)/pocN,poc_tar180:poc180/pocN,poc_tar250:poc250/pocN,poc_tbr70:poc70/pocN,poc_tbr54:poc54/pocN});}
function summarize(w){return{baseline:{age:wmean(rows,w,'age'),bmi:wmean(rows,w,'bmi'),duration:wmean(rows,w,'duration'),egfr:wmean(rows,w,'egfr'),si_hidden_diagnostic:wmean(rows,w,'si'),archetype_weighted_shares:shares(rows,w,'archetype')},latent:{mean_bg:wmean(rows,w,'mean_bg'),tir_pct:100*wmean(rows,w,'tir'),tar180_pct:100*wmean(rows,w,'tar180'),tar250_pct:100*wmean(rows,w,'tar250'),tbr70_pct:100*wmean(rows,w,'tbr70'),tbr54_pct:100*wmean(rows,w,'tbr54'),patients_below20_pct:100*wmean(rows,w,'p20'),patients_below30_pct:100*wmean(rows,w,'p30'),patients_below40_pct:100*wmean(rows,w,'p40')},poc:{mean_bg:wmean(rows,w,'poc_mean'),tir_pct:100*wmean(rows,w,'poc_tir'),tar180_pct:100*wmean(rows,w,'poc_tar180'),tar250_pct:100*wmean(rows,w,'poc_tar250'),tbr70_pct:100*wmean(rows,w,'poc_tbr70'),tbr54_pct:100*wmean(rows,w,'poc_tbr54')}}}
const unweighted=summarize(uw),matched=summarize(weights),ess=1/weights.reduce((s,x)=>s+x*x,0),out={purpose:'Outcome-blind external-cohort conditioning audit. The generator and phenotype weights are unchanged. Among protocol-eligible generated patients (eGFR >=30), entropy weights use only observed Emory CGM cohort baseline age, BMI and diabetes-duration means/SDs; no glycemic outcome, SI, beta reserve, stress or treatment response enters the weights.',candidate_n:pts.length,target,entropy_lambda:ew.lambda,effective_sample_size:ess,unweighted,baseline_entropy_matched:matched,emory_poc:{mean_bg:188.9,tir_pct:48.4,tar180_pct:50.5,tar250_pct:17.8,tbr70_pct:1.1,tbr54_pct:.20},emory_cgm:{mean_bg:176.1,tir_pct:53.5,tar180_pct:42.2,tar250_pct:16.1,tbr70_pct:4.5,tbr54_pct:1.58},safety_gate_pct:1};
const dir='analysis/emory_baseline_entropy_matched_external';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Emory baseline entropy-matched external audit','',`Eligible candidate N=${pts.length}; entropy-weight ESS=${ess.toFixed(0)}.`,'','Matching variables are baseline age, BMI and diabetes duration only; glycemic outcomes are blinded to weighting.','','| arm | age | BMI | duration | hidden SI diagnostic | latent mean | latent TIR | <20 patients | POC mean | POC TIR | POC TBR<70 |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const [name,r] of [['unweighted',unweighted],['baseline_entropy_matched',matched]])md.push(`| ${name} | ${r.baseline.age.toFixed(1)} | ${r.baseline.bmi.toFixed(1)} | ${r.baseline.duration.toFixed(1)} | ${r.baseline.si_hidden_diagnostic.toFixed(3)} | ${r.latent.mean_bg.toFixed(1)} | ${r.latent.tir_pct.toFixed(1)}% | ${r.latent.patients_below20_pct.toFixed(2)}% | ${r.poc.mean_bg.toFixed(1)} | ${r.poc.tir_pct.toFixed(1)}% | ${r.poc.tbr70_pct.toFixed(2)}% |`);md.push('','Emory target baseline: age 54.5, BMI 33.8, duration 11.5 years.','Emory POC: mean 188.9, TIR 48.4%, TBR<70 1.1%.','','Guardrails:','- No outcome, hidden physiology or treatment response is used to construct weights.','- Generator support weights are not changed.','- eGFR <30 is excluded because the registered trial excluded these patients.','- The protocol-adherent prandial timing arm is used because timing fidelity is a design correction, not an outcome-selected parameter.','- This remains a sensitivity/conditioning audit: home-insulin exposure and HbA1c are not yet matched.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
