#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const N=1800,gp=PK.get('glulisine');
const PROFILES=['persistent_inflammatory','resolving_acute','moderate_stable'];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function tdd(o){return o.breakfast_u+o.lunch_u+o.dinner_u+o.basal_u}
function run(profile,titrate){let p20=0,p54=0;const days=Array.from({length:8},(_,i)=>({day:i+1,stress:[],tddkg:[],meanbg:[],low54:0,n:0}));const pre=[];
 for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});const cfg={days:8,titrate,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.componentTitrate(ord,bg),state_modifier_fn:({day})=>({...T.statePatch(profile,day,i),...B.statePatch(M,.20),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i);let first20=null,any54=false;for(const r of c.records){const z=r.series,m=mean(z),d=days[r.day-1];d.stress.push(r.state.stress_severity||0);d.tddkg.push(tdd(r.order)/p.body_weight_kg);d.meanbg.push(m);d.n++;if(z.some(x=>x<54)){d.low54++;any54=true}if(!first20){const k=z.findIndex(x=>x<20);if(k>=0)first20={day:r.day,tddkg:tdd(r.order)/p.body_weight_kg,stress:r.state.stress_severity||0,prev:[]};}}if(first20){p20++;for(let dd=Math.max(1,first20.day-3);dd<first20.day;dd++){const r=c.records[dd-1];first20.prev.push({day:dd,tddkg:tdd(r.order)/p.body_weight_kg,stress:r.state.stress_severity||0,meanbg:mean(r.series)});}pre.push(first20)}if(any54)p54++;}
 return{profile,titrate,below20_pct:100*p20/N,any54_pct:100*p54/N,days:days.map(d=>({day:d.day,stress:mean(d.stress),tddkg:mean(d.tddkg),meanbg:mean(d.meanbg),day_any54_pct:100*d.low54/d.n})),pre20:{n:pre.length,mean_event_day:mean(pre.map(x=>x.day)),mean_event_tddkg:mean(pre.map(x=>x.tddkg)),mean_event_stress:mean(pre.map(x=>x.stress)),mean_delta_tddkg_dminus3_to_event:mean(pre.filter(x=>x.prev.length).map(x=>x.tddkg-x.prev[0].tddkg)),mean_delta_stress_dminus3_to_event:mean(pre.filter(x=>x.prev.length).map(x=>x.stress-x.prev[0].stress))}};}
const rows=[];for(const p of PROFILES){rows.push(run(p,true));rows.push(run(p,false));}
const out={purpose:'diagnose stress-resolution versus treatment-titration lag; no calibration',n_per_arm:N,rows};const dir='analysis/stress_titration_lag';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Stress resolution × treatment titration lag audit','','Diagnostic only. Profile definitions and componentTitrate are unchanged; no parameter is selected by Emory closeness.','','| profile | titrate | <20 patients | any <54 | event day | event TDD/kg | ΔTDD/kg D-3→event | Δstress D-3→event |','|---|---|---:|---:|---:|---:|---:|---:|'];for(const r of rows){md.push(`| ${r.profile} | ${r.titrate?'on':'off'} | ${r.below20_pct.toFixed(1)}% | ${r.any54_pct.toFixed(1)}% | ${r.pre20.mean_event_day.toFixed(2)} | ${r.pre20.mean_event_tddkg.toFixed(2)} | ${r.pre20.mean_delta_tddkg_dminus3_to_event.toFixed(3)} | ${r.pre20.mean_delta_stress_dminus3_to_event.toFixed(3)} |`);md.push('',`### ${r.profile} / titration ${r.titrate?'on':'off'}`,'| day | stress | TDD/kg | mean BG | day any <54 |','|---:|---:|---:|---:|---:|');for(const d of r.days)md.push(`| ${d.day} | ${d.stress.toFixed(3)} | ${d.tddkg.toFixed(3)} | ${d.meanbg.toFixed(1)} | ${d.day_any54_pct.toFixed(1)}% |`);md.push('');}md.push('Guardrails:','- This is causal attribution, not a policy tuning sweep.','- Do not change stress decay or titration steps from this audit alone.','- A resolving-profile-specific late rise in hypoglycemia while stress falls faster than TDD supports treatment-lag structure.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
