#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV1ShanghaiExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,B=InsulinBasalPotencyPriorExp;
const N=1200,reg=PK.get('regular').implementation_anchor,arms=['current','lunch_unwind','all_unwind'];
const map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function titrator(arm){const h={pre_breakfast:[],pre_lunch:[],pre_dinner:[],bedtime:[]};return(o,s)=>{const n=TP.componentTitrate(o,s);for(const k of Object.values(map)){const v=Number(s[k]);if(Number.isFinite(v))h[k].push(v)}if(arm==='current')return n;for(const [c,k] of Object.entries(map)){if(arm==='lunch_unwind'&&c!=='lunch_u')continue;const x=h[k];if(x.length>=3){const a=x[x.length-3],b=x[x.length-2],d=x[x.length-1];if(a>b&&b>d&&d<=180)n[c]=Math.max(0,n[c]-1)}}return n}}
function run(arm){const z=[],preB=[],preL=[],preD=[],d120=[];let low=0;for(let i=1;i<=N;i++){const p=P.sample(i),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});const c=C.simulateCourse(M,D,p,o,{days:8,titrate:true,allow_meal_mismatch:false,allow_npo:false,bolus_tau_min:reg.tau_min,bolus_duration_min:reg.duration_min,titrate_order_fn:titrator(arm),state_modifier_fn:()=>({...B.statePatch(M,.20),stress_severity:0,admission_glucose_offset_mg_dl:0})},i);for(const r of c.records.slice(2)){for(let t=0;t<1440;t+=15)z.push(r.series[t]);preB.push(r.series[420]);preL.push(r.series[720]);preD.push(r.series[1080]);d120.push(r.series[600]-r.series[480]);if(r.series.some(x=>x<54))low++}}
return{arm,mean:mean(z),tbr70:100*z.filter(x=>x<70).length/z.length,tir:100*z.filter(x=>x>=70&&x<=180).length/z.length,preB:mean(preB),preL:mean(preL),preD:mean(preD),delta120:mean(d120),day54_pct:100*low/(N*6)}}
const rows=arms.map(run),base=rows[0];for(const r of rows){r.delta={};for(const k of ['mean','tbr70','tir','preB','preL','preD','delta120'])r.delta[k]=r[k]-base[k];r.gate=Math.abs(r.delta.mean)<5&&Math.abs(r.delta.preB)<5&&Math.abs(r.delta.preL)<5&&Math.abs(r.delta.preD)<5&&Math.abs(r.delta.delta120)<2&&Math.abs(r.delta.tbr70)<1&&Math.abs(r.delta.tir)<3}
const out={purpose:'Shanghai phenotype policy-preservation comparison; current policy is reference, not outcome fitting',n:N,regular_anchor:reg,rows};const dir='analysis/shanghai_policy_unwind_preservation';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Shanghai policy unwind preservation audit','','Policy comparison on Shanghai-derived T2DM phenotypes with stable meals, no stress trajectory, no meal mismatch/NPO, frozen basal potency 0.20, and frozen Regular anchor. Current policy is the reference; this does not refit Shanghai.','','| arm | gate | mean | Δmean | ΔpreB | ΔpreL | ΔpreD | Δ120 | ΔTBR<70 | ΔTIR |','|---|---|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows)md.push(`| ${r.arm} | ${r.gate?'PASS':'FAIL'} | ${r.mean.toFixed(1)} | ${r.delta.mean.toFixed(2)} | ${r.delta.preB.toFixed(2)} | ${r.delta.preL.toFixed(2)} | ${r.delta.preD.toFixed(2)} | ${r.delta.delta120.toFixed(2)} | ${r.delta.tbr70.toFixed(2)}pp | ${r.delta.tir.toFixed(2)}pp |`);md.push('','Guardrails:','- This is policy preservation, not calibration to Shanghai outcomes.','- Do not use Emory closeness to choose lunch vs all-component unwind.','- Any candidate failing this gate is rejected before external revalidation.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));if(rows.slice(1).some(r=>!r.gate))process.exitCode=2;
