#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_fasting_balance_v2_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,F=T2DMFastingBalanceV2Exp;
const N=1600,TARGET={nocturnal70:41,nocturnal54:26};
function nocturnal(t){return t>=1320||t<360}function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function baseConfig(mode,trajectory,seed){const gp=PK.get('glulisine');return{days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(o,bg)=>TP.componentTitrate(o,bg),steroid:false,admission_glucose_offset_mg_dl:0,initial_stress_severity:0,stress_daily_decay:0,state_modifier_fn:({day})=>{const z={...T.statePatch(trajectory,day,seed)};if(mode==='scalar020')Object.assign(z,B.statePatch(M,.20));if(mode==='fasting_v2')Object.assign(z,F.statePatch(M));return z;}}}
function analyze(mode){const gp=PK.get('glulisine'),duration=gp.candidate.duration_min,firstHour54=Array(24).fill(0),firstHour70=Array(24).fill(0);let patientNoct54=0,patientNoct70=0,patientFirst54DinnerTail=0,patientAny54DinnerTail=0,patientFirst54LateEvening=0,patientFirst54DeepNight=0,patientFirst54AfterDinnerTail=0,totalNoct54Points=0,totalNoct54TailPoints=0,totalNoct70Points=0,totalNoct70TailPoints=0;
 for(let i=1;i<=N;i++){
  const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),admission=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:admission}),trajectory=T.choose(i),c=C.simulateCourse(M,D,p,o,baseConfig(mode,trajectory,i),i);let first54=null,first70=null,any54Tail=false;
  for(const rec of c.records){const shift=Number(rec.state?.bolus_shift_min?.dinner)||0,frac=Number(rec.state?.bolus_fraction?.dinner??1),dinnerStart=1125+shift,dinnerEnd=dinnerStart+duration,dinnerActive=frac>0&&Number(rec.order?.dinner_u)>0;
   for(let t=0;t<1440;t+=15){if(!nocturnal(t))continue;const x=rec.series[t],tail=dinnerActive&&t>=dinnerStart&&t<dinnerEnd;
    if(x<70){totalNoct70Points++;if(tail)totalNoct70TailPoints++;if(!first70)first70={day:rec.day,t,hour:Math.floor(t/60),tail};}
    if(x<54){totalNoct54Points++;if(tail){totalNoct54TailPoints++;any54Tail=true}if(!first54)first54={day:rec.day,t,hour:Math.floor(t/60),tail,dinnerEnd};}
   }
  }
  if(first70){patientNoct70++;firstHour70[first70.hour]++;}
  if(first54){patientNoct54++;firstHour54[first54.hour]++;if(first54.tail)patientFirst54DinnerTail++;if(any54Tail)patientAny54DinnerTail++;if(first54.t>=1320){patientFirst54LateEvening++;if(!first54.tail)patientFirst54AfterDinnerTail++;}else patientFirst54DeepNight++;}
 }
 return{mode,n:N,nocturnal70_patient_pct:100*patientNoct70/N,nocturnal54_patient_pct:100*patientNoct54/N,among_noct54_patients:{first_event_in_dinner_glulisine_tail_pct:patientNoct54?100*patientFirst54DinnerTail/patientNoct54:0,any_event_in_dinner_glulisine_tail_pct:patientNoct54?100*patientAny54DinnerTail/patientNoct54:0,first_event_22_24_pct:patientNoct54?100*patientFirst54LateEvening/patientNoct54:0,first_event_00_06_pct:patientNoct54?100*patientFirst54DeepNight/patientNoct54:0,first_event_22_24_after_dinner_tail_pct:patientNoct54?100*patientFirst54AfterDinnerTail/patientNoct54:0},point_attribution:{noct54_points:totalNoct54Points,dinner_tail_noct54_points:totalNoct54TailPoints,dinner_tail_fraction_noct54_pct:totalNoct54Points?100*totalNoct54TailPoints/totalNoct54Points:0,noct70_points:totalNoct70Points,dinner_tail_noct70_points:totalNoct70TailPoints,dinner_tail_fraction_noct70_pct:totalNoct70Points?100*totalNoct70TailPoints/totalNoct70Points:0},first_event_hour54:firstHour54.map((n,h)=>({hour:h,n,pct_of_noct54_patients:patientNoct54?100*n/patientNoct54:0})),first_event_hour70:firstHour70.map((n,h)=>({hour:h,n,pct_of_noct70_patients:patientNoct70?100*n/patientNoct70:0}))};
}
const arms={off:analyze('off'),scalar020:analyze('scalar020'),fasting_v2:analyze('fasting_v2')},out={definition:{nocturnal:'22:00-06:00',dinner_glulisine_tail:`actual dinner bolus time through +${PK.get('glulisine').candidate.duration_min} min`,first_event:'first nocturnal threshold crossing across 8-day course'},emory_reference:TARGET,arms};const dir='analysis/emory_nocturnal_event_attribution';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));
const md=['# Emory nocturnal hypoglycemia event attribution','','Nocturnal window is the study definition 22:00–06:00. This audit does not fit any parameter. It asks whether simulated nocturnal events are late-evening dinner-glulisine overlap or true post-midnight fasting events.','','| arm | noct<70 patients | noct<54 patients | first <54 in dinner tail | any <54 in dinner tail | first <54 22–24 | first <54 00–06 |','|---|---:|---:|---:|---:|---:|---:|'];for(const [k,x] of Object.entries(arms)){const a=x.among_noct54_patients;md.push(`| ${k} | ${x.nocturnal70_patient_pct.toFixed(1)}% | ${x.nocturnal54_patient_pct.toFixed(1)}% | ${a.first_event_in_dinner_glulisine_tail_pct.toFixed(1)}% | ${a.any_event_in_dinner_glulisine_tail_pct.toFixed(1)}% | ${a.first_event_22_24_pct.toFixed(1)}% | ${a.first_event_00_06_pct.toFixed(1)}% |`)}md.push('',`Emory reference: nocturnal <70 ${TARGET.nocturnal70}%, nocturnal <54 ${TARGET.nocturnal54}%.`,'','## Interpretation','- If most simulated nocturnal events are in the dinner-glulisine tail, the remaining deficit is not evidence for simply strengthening basal insulin.','- If post-midnight events remain rare, a basal formulation/time-profile mechanism is a separate hypothesis to test.','- Keep glulisine PK inside its literature prior; do not tune it to the Emory event rate.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
console.log('\n--- Published protocol bedtime correction validation ---\n');require('./validate_emory_bedtime_correction_protocol.js');
