#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v1_exp.js','t2dm_hypoglycemia_rescue_policy_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV1Exp,HR=T2DMHypoglycemiaRescuePolicyExp;
const NSH=800,NEM=1600;
const ARMS=[
 {name:'legacy',counterreg:false,reserve:1,rescue:null},
 {name:'thresholded',counterreg:true,reserve:1,rescue:null},
 {name:'thresholded_plus_rescue54',counterreg:true,reserve:1,rescue:'54'},
 {name:'thresholded_plus_rescue70',counterreg:true,reserve:1,rescue:'70'},
 {name:'thresholded_beta_failure055_plus_rescue54',counterreg:true,reserve:'beta055',rescue:'54'}
];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}function minOf(a){let m=Infinity;for(const x of a)if(x<m)m=x;return m}function noct(t){return t>=1320||t<360}
function patch(a,p){const s={};if(a.counterreg){const r=a.reserve==='beta055'&&p.patient_archetype==='beta_failure_long_duration'?.55:1;Object.assign(s,CR.statePatch(M,{reserve:r}));}if(a.rescue==='54')s.hypoglycemia_rescue_fn=HR.severe54_15g();if(a.rescue==='70')s.hypoglycemia_rescue_fn=HR.alert70_15g();return s;}
function shanghai(a){const xs=[];for(let i=1;i<=NSH;i++){const p=P1.sample(i),base=M.suggestOrder(p,M.DEFAULT_MEALS),o={...base,basal_u:Math.max(0,Math.round(.201*p.body_weight_kg))};let prev=null;for(let d=0;d<6;d++){const x=D.simulateDay(M,p,o,{meal_plan_carb_g:M.DEFAULT_MEALS,...B.statePatch(M,.20),...patch(a,p)},i*100+d,prev);prev=x.next_state;if(d<2)continue;for(let t=0;t<1440;t++)xs.push(x.series[t]);}}return{mean:mean(xs),tbr70:100*xs.filter(x=>x<70).length/xs.length,tbr54:100*xs.filter(x=>x<54).length/xs.length,tir:100*xs.filter(x=>x>=70&&x<=180).length/xs.length,min:minOf(xs)};}
function external(a){const gp=PK.get('glulisine'),rows=[];let n70=0,n54=0,deep54=0,below20=0,rescuePatients=0,rescues=0,patientDays=0;for(let i=1;i<=NEM;i++){const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i),cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.componentTitrate(ord,bg),state_modifier_fn:({day})=>({...T.statePatch(tr,day,i),...B.statePatch(M,.20),...patch(a,p),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i),xs=[];let p70=false,p54=false,pDeep=false,p20=false,pRescue=false;for(const r of c.records){patientDays++;const rr=r.hypoglycemia_rescues||[];rescues+=rr.length;if(rr.length)pRescue=true;for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);if(noct(t)&&x<70)p70=true;if(noct(t)&&x<54)p54=true;if(t<360&&x<54)pDeep=true;if(x<20)p20=true;}}if(p70)n70++;if(p54)n54++;if(pDeep)deep54++;if(p20)below20++;if(pRescue)rescuePatients++;const m=mean(xs),s=sd(xs);rows.push({mean:m,tbr70:100*xs.filter(x=>x<70).length/xs.length,tbr54:100*xs.filter(x=>x<54).length/xs.length,cv:100*s/m,min:minOf(xs)});}return{mean:mean(rows.map(x=>x.mean)),tbr70:mean(rows.map(x=>x.tbr70)),tbr54:mean(rows.map(x=>x.tbr54)),cv:mean(rows.map(x=>x.cv)),noct70:100*n70/NEM,noct54:100*n54/NEM,deep54:100*deep54/NEM,below20_patient_pct:100*below20/NEM,rescue_patient_pct:100*rescuePatients/NEM,rescues_per_100_patient_days:100*rescues/patientDays,mean_patient_min:mean(rows.map(x=>x.min))};}
const sh0=shanghai(ARMS[0]),rows=[];for(const a of ARMS){const sh=shanghai(a),ex=external(a),d={mean:sh.mean-sh0.mean,tbr70:sh.tbr70-sh0.tbr70,tbr54:sh.tbr54-sh0.tbr54,tir:sh.tir-sh0.tir};const gate=Math.abs(d.mean)<5&&Math.abs(d.tbr70)<1&&Math.abs(d.tir)<3;rows.push({...a,shanghai:sh,delta_shanghai:d,shanghai_gate:gate,external:ex});}
const out={purpose:'separate low-glucose physiology from rescue treatment; no Emory calibration',n:{shanghai:NSH,external:NEM},emory_reference:{mean:176.1,tbr70:4.5,tbr54:1.58,cv:32,noct70:41,noct54:26},rows};const dir='analysis/counterregulation_rescue_interaction';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Counterregulation × hypoglycemia rescue interaction audit','','Counterregulation thresholds are literature-derived (awake 60, sleep 50 mg/dL). Rescue is a treatment-policy layer. The <54 arm gives 15 g fast carbohydrate with 15-min reassessment; the <70 arm is a management upper-bound sensitivity. No arm is selected by Emory closeness.','','| arm | Shanghai | mean | TBR<70 | TBR<54 | CV | noct<70 | noct<54 | 00–06 <54 | <20 pt | rescued pt | rescues/100 pt-days |','|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const e=r.external;md.push(`| ${r.name} | ${r.shanghai_gate?'PASS':'FAIL'} | ${e.mean.toFixed(1)} | ${e.tbr70.toFixed(2)}% | ${e.tbr54.toFixed(2)}% | ${e.cv.toFixed(1)}% | ${e.noct70.toFixed(1)}% | ${e.noct54.toFixed(1)}% | ${e.deep54.toFixed(1)}% | ${e.below20_patient_pct.toFixed(1)}% | ${e.rescue_patient_pct.toFixed(1)}% | ${e.rescues_per_100_patient_days.toFixed(1)} |`)}md.push('','Decision rules:','- Reject any physiology arm with persistent implausible <20 mg/dL despite rescue.','- Do not weaken counterregulation or change rescue carbohydrate amount to fit Emory incidence.','- If rescue removes extreme lows while preserving the thresholded incidence structure, keep physiology and treatment as separate candidate layers for further independent validation.','- The <70 rescue arm is not representative of blinded-CGM detection in Emory and must not be chosen by fit.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
