#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','t2dm_treatment_policy_emory_u300_trial_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v2_egp_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,EP=T2DMTreatmentPolicyEmoryU300TrialExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV2EgpExp;
const gp=PK.get('glulisine'),POC=new Set([420,720,1080,1260]);
const ARMS=[
 {name:'control',mass:false,cr:false,primary:false},
 {name:'mass100_only',mass:true,cr:false,primary:false},
 {name:'mass100_plus_crv2_width10',mass:true,cr:true,primary:true}
];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))}
function ref100(p){return Number(p&&p.endogenous_insulin&&p.endogenous_insulin.glucose_threshold_mg_dl)||100}
function physiologyPatch(p,arm){return{
  ...(arm.mass?{prandial_mass_action_low_side:true,prandial_mass_action_reference_mg_dl:ref100(p)}:{}),
  ...(arm.cr?CR.statePatch(M,{reserve:1,activation_width_mg_dl:10}):{})
};}
function protocolPocRescue({t,glucose_mg_dl,prior_rescues}){const g=Number(glucose_mg_dl);if(!(g<70))return 0;const rs=prior_rescues||[],last=rs.length?rs[rs.length-1]:null;const scheduled=POC.has(t),repeat=!!(last&&last.label==='protocol_poc_glucose'&&t===last.minute+15);if(!(scheduled||repeat))return 0;return{carbs_g:12.5,cooldown_min:15,label:'protocol_poc_glucose'};}
function emoryPatch({patient,state},arm){const ms={breakfast:0,lunch:0,dinner:0,...(state.meal_shift_min||{})};return{
  bolus_shift_min:{...ms},bolus_fraction:{breakfast:1,lunch:1,dinner:1},
  ...physiologyPatch(patient,arm),
  prandial_safety_adjustment_fn:({meal,poc_glucose_mg_dl,planned_units})=>EP.mealDose({meal,poc_glucose_mg_dl,planned_units,state})
};}
function shanghai(arm,N=2500){const all=[],preB=[],preL=[],preD=[],d120=[];let tbr=0,tir=0,total=0;for(let i=1;i<=N;i++){const p=P1.sample(i),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});const cfg={days:8,titrate:true,allow_meal_mismatch:false,allow_npo:false,bolus_tau_min:90,bolus_duration_min:330,titrate_order_fn:(ord,bg)=>TP.componentTitrate(ord,bg),state_modifier_fn:(ctx)=>({...B.statePatch(M,.20),...physiologyPatch(ctx.patient,arm)})};const c=C.simulateCourse(M,D,p,o,cfg,i);for(let d=2;d<c.records.length;d++){const r=c.records[d];for(let t=0;t<1440;t++){const x=r.series[t];all.push(x);total++;if(x<70)tbr++;if(x>=70&&x<=180)tir++;}preB.push(r.series[420]);preL.push(r.series[720]);preD.push(r.series[1080]);d120.push(r.series[600]-r.series[480]);}}return{n:N,mean:mean(all),preB:mean(preB),preL:mean(preL),preD:mean(preD),delta120:mean(d120),tbr70:100*tbr/total,tir:100*tir/total};}
function external(arm,N=8000){let n=0,total=0,n70=0,n54=0,n180=0,n250=0,p20=0,p30=0,p40=0,p70=0,p54=0,noct70=0,noct54=0,deep54=0,d1b20=0;const means=[],cvs=[],poc=[];for(let i=1;i<=N;i++){const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'});if(p.egfr_ml_min_1_73m2<30)continue;n++;const adm=Math.max(140,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=EP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>EP.registered2019Titrate(ord,bg),state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...emoryPatch(ctx,arm),bedtime_correction_fn:({glucose_mg_dl})=>EP.bedtimeSupplement(glucose_mg_dl,'usual'),hypoglycemia_rescue_fn:protocolPocRescue})};const c=C.simulateCourse(M,D,p,o,cfg,i);let a20=false,a30=false,a40=false,a70=false,a54=false,n70p=false,n54p=false,d54p=false,d1=false;const xs=[];for(let d=0;d<c.records.length;d++){const r=c.records[d];poc.push(r.series[420],r.series[720],r.series[1080],r.series[1260]);for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);total++;if(x<20)a20=true;if(x<30)a30=true;if(x<40)a40=true;if(x<70){a70=true;n70++;}if(x<54){a54=true;n54++;}if(x>180)n180++;if(x>250)n250++;const isNoct=t>=1320||t<360;if(isNoct&&x<70)n70p=true;if(isNoct&&x<54)n54p=true;if(t<360&&x<54)d54p=true;}if(d===0)for(let t=480;t<720;t++)if(r.series[t]<20){d1=true;break;}}if(a20)p20++;if(a30)p30++;if(a40)p40++;if(a70)p70++;if(a54)p54++;if(n70p)noct70++;if(n54p)noct54++;if(d54p)deep54++;if(d1)d1b20++;const m=mean(xs);means.push(m);cvs.push(100*sd(xs)/m);}let pl70=0,pl54=0,ph180=0,ph250=0;for(const x of poc){if(x<70)pl70++;if(x<54)pl54++;if(x>180)ph180++;if(x>250)ph250++;}return{n,mean:mean(means),tir:100*(total-n70-n180)/total,tar180:100*n180/total,tar250:100*n250/total,tbr70:100*n70/total,tbr54:100*n54/total,cv:mean(cvs),any70:100*p70/n,any54:100*p54/n,noct70:100*noct70/n,noct54:100*noct54/n,deep00_06_54:100*deep54/n,below20:100*p20/n,below30:100*p30/n,below40:100*p40/n,d1_breakfast_below20:100*d1b20/n,poc_mean:mean(poc),poc_tir:100*(poc.length-pl70-ph180)/poc.length,poc_tar180:100*ph180/poc.length,poc_tar250:100*ph250/poc.length,poc_tbr70:100*pl70/poc.length,poc_tbr54:100*pl54/poc.length};}
const shRows=ARMS.map(a=>({arm:a.name,...shanghai(a)})),shRef=shRows[0],exRows=ARMS.map(a=>({arm:a.name,...external(a)}));
const rows=ARMS.map(a=>{const sh=shRows.find(x=>x.arm===a.name),ex=exRows.find(x=>x.arm===a.name),delta={};for(const k of ['mean','preB','preL','preD','delta120','tbr70','tir'])delta[k]=sh[k]-shRef[k];const shGate=Math.abs(delta.mean)<5&&Math.abs(delta.preB)<5&&Math.abs(delta.preL)<5&&Math.abs(delta.preD)<5&&Math.abs(delta.delta120)<2&&Math.abs(delta.tbr70)<1&&Math.abs(delta.tir)<3;return{...a,shanghai:sh,delta_vs_control:delta,shanghai_gate:shGate,external:ex,safety_gate:ex.below20<=1};});
const primary=rows.find(r=>r.primary),out={purpose:'Composite a priori physiology audit. The candidate combines two independently pre-defined structures without changing either parameterization: (1) prandial low-side mass action referenced to the pre-existing endogenous-insulin glucose threshold (100 mg/dL), and (2) counterregulation V2 at its pre-existing primary default width=10 mg/dL with healthy reserve=1. The combination is tested because mass action prevents additive insulin removal from overshooting at low glucose while CR V2 restores low-side physiology/counterregulatory structure. No Emory outcome defines a threshold, width, reserve or coefficient.',definitions:{mass_action_reference:'patient.endogenous_insulin.glucose_threshold_mg_dl (pre-existing; 100 mg/dL)',cr_width_mg_dl:10,cr_reserve:1,cr_selection:'pre-existing V2 primary default; width5/20 and reserve0.68 are not tested or selected here'},n:{shanghai:2500,external_requested:8000,external_eligible:exRows[0].n},rows,primary_pass:!!primary&&primary.shanghai_gate&&primary.safety_gate};
const dir='analysis/mass100_crv2_width10_composite';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Mass-action100 + CR V2 width10 composite audit','','Primary is fixed a priori: mass-action reference = pre-existing 100 mg/dL generator threshold; CR V2 width=10, reserve=1 = pre-existing module default.','','## Shanghai preservation','','| arm | Shanghai gate | mean | preB | preL | preD | delta120 | TBR<70 | TIR | delta TIR |','|---|---|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const s=r.shanghai,d=r.delta_vs_control;md.push(`| ${r.arm} | ${r.shanghai_gate?'PASS':'FAIL'} | ${s.mean.toFixed(2)} | ${s.preB.toFixed(2)} | ${s.preL.toFixed(2)} | ${s.preD.toFixed(2)} | ${s.delta120.toFixed(2)} | ${s.tbr70.toFixed(3)}% | ${s.tir.toFixed(2)}% | ${d.tir.toFixed(3)} pp |`);}md.push('','## Emory registered-protocol diagnostic context','','| arm | safety<20 | mean | TIR | TBR<70 | TBR<54 | any<70 | any<54 | noct<70 | noct<54 | 00–06<54 | <20 | <30 | <40 | D1B<20 | POC mean | POC TIR | POC TBR<70 | POC TBR<54 |','|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const e=r.external;md.push(`| ${r.arm} | ${r.safety_gate?'PASS':'FAIL'} | ${e.mean.toFixed(1)} | ${e.tir.toFixed(1)}% | ${e.tbr70.toFixed(2)}% | ${e.tbr54.toFixed(2)}% | ${e.any70.toFixed(1)}% | ${e.any54.toFixed(1)}% | ${e.noct70.toFixed(1)}% | ${e.noct54.toFixed(1)}% | ${e.deep00_06_54.toFixed(1)}% | ${e.below20.toFixed(2)}% | ${e.below30.toFixed(2)}% | ${e.below40.toFixed(2)}% | ${e.d1_breakfast_below20.toFixed(2)}% | ${e.poc_mean.toFixed(1)} | ${e.poc_tir.toFixed(1)}% | ${e.poc_tbr70.toFixed(2)}% | ${e.poc_tbr54.toFixed(2)}% |`);}md.push('',`Composite primary: **${out.primary_pass?'PASS':'FAIL'}**`,'','Guardrails:','- Emory moderate-hypoglycemia closeness is descriptive only and cannot select or tune the composite.','- Do not change 100 mg/dL, CR width=10 or reserve=1 from this result.','- No hidden SI enters treatment decisions.','- No PK, stress, basal potency, phenotype weight, insulin scale or rescue tuning.','- If primary passes, freeze before testing an independent inpatient T2DM dataset; do not alter it to match that dataset.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));if(!out.primary_pass)process.exitCode=2;
