#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_emory_u300_trial_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyEmoryU300TrialExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const gp=PK.get('glulisine'),N=6000,POC=new Set([420,720,1080,1260]);
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))}
function mealDosePatch({state},sync){const patch={prandial_safety_adjustment_fn:({meal,poc_glucose_mg_dl,planned_units})=>TP.mealDose({meal,poc_glucose_mg_dl,planned_units,state})};if(sync){const ms={breakfast:0,lunch:0,dinner:0,...(state.meal_shift_min||{})};patch.bolus_shift_min={...ms};patch.bolus_fraction={breakfast:1,lunch:1,dinner:1};}return patch;}
function protocolPocRescue({t,glucose_mg_dl,prior_rescues}){const g=Number(glucose_mg_dl);if(!(g<70))return 0;const rs=prior_rescues||[],last=rs.length?rs[rs.length-1]:null;const scheduled=POC.has(t),repeat=!!(last&&last.label==='protocol_poc_glucose'&&t===last.minute+15);if(!(scheduled||repeat))return 0;return{carbs_g:12.5,cooldown_min:15,label:'protocol_poc_glucose'};}
function run(sync){let p20=0,p30=0,p40=0,p70=0,p54=0,total=0,n70=0,n54=0,n180=0,n250=0;const means=[],cvs=[],poc=[];for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(140,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.registered2019Titrate(ord,bg),state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...mealDosePatch(ctx,sync),bedtime_correction_fn:({glucose_mg_dl})=>TP.bedtimeSupplement(glucose_mg_dl,'usual'),hypoglycemia_rescue_fn:protocolPocRescue})};const c=C.simulateCourse(M,D,p,o,cfg,i);let a20=false,a30=false,a40=false,a70=false,a54=false,xs=[];for(const r of c.records){poc.push(r.series[420],r.series[720],r.series[1080],r.series[1260]);for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);total++;if(x<20)a20=true;if(x<30)a30=true;if(x<40)a40=true;if(x<70){a70=true;n70++;}if(x<54){a54=true;n54++;}if(x>180)n180++;if(x>250)n250++;}}if(a20)p20++;if(a30)p30++;if(a40)p40++;if(a70)p70++;if(a54)p54++;const m=mean(xs);means.push(m);cvs.push(100*sd(xs)/m);}let pl70=0,pl54=0,ph180=0,ph250=0;for(const x of poc){if(x<70)pl70++;if(x<54)pl54++;if(x>180)ph180++;if(x>250)ph250++;}return{name:sync?'protocol_adherent_synced_timing':'generated_independent_timing',latent:{mean:mean(means),tir_pct:100*(total-n70-n180)/total,tar180_pct:100*n180/total,tar250_pct:100*n250/total,tbr70_pct:100*n70/total,tbr54_pct:100*n54/total,cv_pct:mean(cvs),patients_any70_pct:100*p70/N,patients_any54_pct:100*p54/N,patients_below20_pct:100*p20/N,patients_below30_pct:100*p30/N,patients_below40_pct:100*p40/N},poc:{mean:mean(poc),tir_pct:100*(poc.length-pl70-ph180)/poc.length,tar180_pct:100*ph180/poc.length,tar250_pct:100*ph250/poc.length,tbr70_pct:100*pl70/poc.length,tbr54_pct:100*pl54/poc.length}};}
const rows=[run(false),run(true)],out={purpose:'Protocol-fidelity ablation. Trial documentation specifies glulisine before meals. The existing external arm unintentionally retained independently generated meal shifts, bolus delays and underbolus fractions. The protocol-adherent arm synchronizes bolus shift to meal shift, preserving the model default 15-min premeal interval, and administers the full protocol-computed dose; poor intake/NPO remains handled by the published mealDose branch.',n:N,rows,safety_gate_pct:1};const dir='analysis/emory_protocol_adherent_timing';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Emory protocol-adherent prandial timing audit','','No outcome tuning. Published treatment thresholds/doses and physiology are unchanged.','','| arm | <20 safety | mean | TIR | TBR<70 | any<54 | <20pt | <30pt | <40pt | POC mean | POC TIR | POC TBR<70 |','|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows)md.push(`| ${r.name} | ${r.latent.patients_below20_pct<=1?'PASS':'FAIL'} | ${r.latent.mean.toFixed(1)} | ${r.latent.tir_pct.toFixed(1)}% | ${r.latent.tbr70_pct.toFixed(2)}% | ${r.latent.patients_any54_pct.toFixed(1)}% | ${r.latent.patients_below20_pct.toFixed(2)}% | ${r.latent.patients_below30_pct.toFixed(2)}% | ${r.latent.patients_below40_pct.toFixed(2)}% | ${r.poc.mean.toFixed(1)} | ${r.poc.tir_pct.toFixed(1)}% | ${r.poc.tbr70_pct.toFixed(2)}% |`);md.push('','Guardrails:','- Synchronization is a protocol-fidelity fix, not a fitted timing parameter.','- Meal quantity variability and poor-intake/NPO branches remain.','- Hidden CGM never triggers treatment.','- Do not alter PK, physiology, stress, basal potency or phenotype weights from this ablation.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
