#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const gp=PK.get('glulisine'),map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function persistentTitrator(order,bg){const next=TP.componentTitrate(order,bg),vals=Object.values(bg).map(Number).filter(Number.isFinite),nHigh=vals.filter(x=>x>=180).length;for(const [comp,key] of Object.entries(map)){const cur=Number(order[comp])||0,nxt=Number(next[comp])||0,signal=Number(bg[key]);if(nxt>cur&&!(Number.isFinite(signal)&&signal>=180&&nHigh>=2))next[comp]=cur;}return next}
function mealMatchedPatch({order,state}){const intake=state.intake_fraction||{},mealShift=state.meal_shift_min||{},bolusShift={...(state.bolus_shift_min||{})},bolusFraction={...(state.bolus_fraction||{})};for(const meal of ['breakfast','lunch','dinner']){const f=Number(intake[meal]);if(!Number.isFinite(f)||f>=.85)continue;const key=meal+'_u',ordered=Math.max(0,Math.round(Number(order[key])||0)),given=Math.max(0,Math.round(ordered*Math.max(0,Math.min(1,f))));bolusFraction[meal]=ordered>0?given/ordered:0;const ms=Number(mealShift[meal])||0;bolusShift[meal]=Math.max(Number(bolusShift[meal])||0,15+ms);}return{bolus_fraction:bolusFraction,bolus_shift_min:bolusShift};}
function safetyOverride({poc_glucose_mg_dl,planned_units}){const bg=Number(poc_glucose_mg_dl),u=Math.max(0,Math.round(Number(planned_units)||0));if(bg<70)return Math.max(0,u-2);if(bg<100)return Math.max(0,u-1);return u;}
function external(useSafety,N=3000){let p20=0,p54=0,p70=0,total=0,n70=0,n54=0,n180=0;const means=[],adjMeals={breakfast:0,lunch:0,dinner:0};let adjustments=0;for(let i=1;i<=N;i++){const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:persistentTitrator,state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl),...mealMatchedPatch(ctx),...(useSafety?{prandial_safety_adjustment_fn:safetyOverride}:{})})};const c=C.simulateCourse(M,D,p,o,cfg,i);let a20=false,a54=false,a70=false,xs=[];for(const r of c.records){for(const a of (r.prandial_safety_adjustments||[])){adjustments++;adjMeals[a.meal]=(adjMeals[a.meal]||0)+1;}for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);total++;if(x<20)a20=true;if(x<54){a54=true;n54++;}if(x<70){a70=true;n70++;}if(x>180)n180++;}}if(a20)p20++;if(a54)p54++;if(a70)p70++;means.push(mean(xs));}
return{arm:useSafety?'combined_plus_same_day_poc_safety':'combined',n:N,mean_bg:mean(means),tir_pct:100*(total-n70-n180)/total,tar180_pct:100*n180/total,tbr70_pct:100*n70/total,tbr54_pct:100*n54/total,patients_below20_pct:100*p20/N,patients_any54_pct:100*p54/N,patients_any70_pct:100*p70/N,adjustments_per_patient_day:adjustments/(N*8),adjustments_by_meal:adjMeals};}
function shanghai(arm,N=1200){const all=[],preB=[],preL=[],preD=[],d120=[];let tbr70=0,tir=0,total=0,adjustments=0;for(let i=1;i<=N;i++){const p=P1.sample(i),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});const usePersistent=arm!=='current',useSafety=arm==='combined_plus_same_day_poc_safety';const cfg={days:8,titrate:true,allow_meal_mismatch:false,allow_npo:false,bolus_tau_min:90,bolus_duration_min:330,titrate_order_fn:usePersistent?persistentTitrator:((ord,bg)=>TP.componentTitrate(ord,bg)),state_modifier_fn:()=>({...B.statePatch(M,.20),...(useSafety?{prandial_safety_adjustment_fn:safetyOverride}:{})})};const c=C.simulateCourse(M,D,p,o,cfg,i);for(let d=2;d<c.records.length;d++){const r=c.records[d];adjustments+=(r.prandial_safety_adjustments||[]).length;for(let t=0;t<1440;t++){const x=r.series[t];all.push(x);total++;if(x<70)tbr70++;if(x>=70&&x<=180)tir++;}preB.push(r.series[420]);preL.push(r.series[720]);preD.push(r.series[1080]);d120.push(r.series[600]-r.series[480]);}}
return{arm,mean:mean(all),preB:mean(preB),preL:mean(preL),preD:mean(preD),delta120:mean(d120),tbr70:100*tbr70/total,tir:100*tir/total,adjustments_per_analyzed_patient_day:adjustments/(N*6)};}
const externalRows=[external(false),external(true)];const shanghaiRows=[shanghai('current'),shanghai('combined'),shanghai('combined_plus_same_day_poc_safety')];const ref=shanghaiRows[0],cand=shanghaiRows[2],delta={};for(const k of ['mean','preB','preL','preD','delta120','tbr70','tir'])delta[k]=cand[k]-ref[k];const gate=Math.abs(delta.mean)<5&&Math.abs(delta.preB)<5&&Math.abs(delta.preL)<5&&Math.abs(delta.preD)<5&&Math.abs(delta.delta120)<2&&Math.abs(delta.tbr70)<1&&Math.abs(delta.tir)<3;
const out={purpose:'Diagnostic same-day prandial safety override using only the existing four-point POC measurement immediately preceding each meal. Thresholds and decrement sizes are inherited from the existing component policy; no outcome calibration.',rule:'At each meal, use only the corresponding recorded premeal POC. If POC <70 mg/dL, reduce that meal administered prandial dose by 2 integer units; else if POC <100, reduce by 1 integer unit; otherwise no same-day change. Never increase dose same-day.',external:externalRows,formal_shanghai_8day:{rows:shanghaiRows,delta_candidate_vs_current:delta,gate}};
const dir='analysis/same_day_poc_prandial_safety';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));
let md=['# Same-day observable POC prandial safety audit','','Uses only four-point bedside POC values. No minute-series/hidden CGM, latent physiology, trajectory label, or outcome-selected threshold is available to the safety override.','','## External inpatient sensitivity','| arm | mean | TIR | TAR>180 | TBR<70 | TBR<54 | any<70 | any<54 | <20 patients | adjustments / patient-day |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of externalRows)md.push(`| ${r.arm} | ${r.mean_bg.toFixed(1)} | ${r.tir_pct.toFixed(1)}% | ${r.tar180_pct.toFixed(1)}% | ${r.tbr70_pct.toFixed(2)}% | ${r.tbr54_pct.toFixed(2)}% | ${r.patients_any70_pct.toFixed(1)}% | ${r.patients_any54_pct.toFixed(1)}% | ${r.patients_below20_pct.toFixed(2)}% | ${r.adjustments_per_patient_day.toFixed(3)} |`);md.push('','## Formal Shanghai preservation: 8 days, analyze days 3–8','| arm | mean | preB | preL | preD | Δ120 | TBR<70 | TIR | safety adjustments/day |','|---|---:|---:|---:|---:|---:|---:|---:|---:|');for(const r of shanghaiRows)md.push(`| ${r.arm} | ${r.mean.toFixed(1)} | ${r.preB.toFixed(1)} | ${r.preL.toFixed(1)} | ${r.preD.toFixed(1)} | ${r.delta120.toFixed(1)} | ${r.tbr70.toFixed(2)}% | ${r.tir.toFixed(1)}% | ${r.adjustments_per_analyzed_patient_day.toFixed(3)} |`);md.push('',`Formal Shanghai gate: **${gate?'PASS':'FAIL'}**`,`Δmean ${delta.mean.toFixed(2)}, ΔpreB ${delta.preB.toFixed(2)}, ΔpreL ${delta.preL.toFixed(2)}, ΔpreD ${delta.preD.toFixed(2)}, Δ120 ${delta.delta120.toFixed(2)}, ΔTBR ${delta.tbr70.toFixed(2)}pp, ΔTIR ${delta.tir.toFixed(2)}pp`,'','Guardrails:','- Do not alter 70/100 mg/dL thresholds or 2U/1U decrements from these results.','- Do not convert usual starting TDD ranges into hard caps.','- Same-day override can only decrease the imminent prandial dose; daily titration remains the persistent_2of4 policy.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));if(!gate)process.exitCode=2;
