#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const N=1200,gp=PK.get('glulisine'),PROFILES=['persistent_inflammatory','resolving_acute','moderate_stable'];
const MAP={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function tdd(o){return o.breakfast_u+o.lunch_u+o.dinner_u+o.basal_u}
function makePolicy(mode,counter){return(ord,bg,ctx={})=>{const next=TP.componentTitrate(ord,bg);if(mode==='current')return next;const recs=(ctx.course&&ctx.course.records)||[];for(const [comp,key] of Object.entries(MAP)){if(mode==='lunch_only'&&comp!=='lunch_u')continue;if(next[comp]<=ord[comp])continue;if(recs.length<3)continue;const a=Number(recs[recs.length-3].bg[key]),b=Number(recs[recs.length-2].bg[key]),c=Number(recs[recs.length-1].bg[key]);if(Number.isFinite(a)&&Number.isFinite(b)&&Number.isFinite(c)&&a>b&&b>c){next[comp]=ord[comp];counter[comp]=(counter[comp]||0)+1;}}return next;};}
function run(profile,mode){let below20=0,any54=0,blocked={};const days=Array.from({length:8},(_,i)=>({day:i+1,meanbg:[],tddkg:[],low54:0,n:0}));for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:makePolicy(mode,blocked),state_modifier_fn:({day})=>({...T.statePatch(profile,day,i),...B.statePatch(M,.20),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i);let p20=false,p54=false;for(const r of c.records){const d=days[r.day-1],z=r.series;d.meanbg.push(mean(z));d.tddkg.push(tdd(r.order)/p.body_weight_kg);d.n++;if(z.some(x=>x<54)){d.low54++;p54=true}if(z.some(x=>x<20))p20=true;}if(p20)below20++;if(p54)any54++;}
return{profile,mode,below20_pct:100*below20/N,any54_pct:100*any54/N,blocked,days:days.map(d=>({day:d.day,mean_bg:mean(d.meanbg),tdd_per_kg:mean(d.tddkg),day_any54_pct:100*d.low54/d.n}))};}
const rows=[];for(const p of PROFILES)for(const m of ['current','lunch_only','all_components'])rows.push(run(p,m));
const out={purpose:'diagnose whether observable falling glucose trends can prevent repeated upward titration wind-up without using hidden physiology; no calibration',rule:'If the corresponding premeal/bedtime glucose has fallen strictly for 3 consecutive days, block only an additional upward change in that component; decreases and unchanged doses remain allowed.',n_per_arm:N,rows};const dir='analysis/observable_trend_antiwindup';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Observable trend anti-windup audit','','Diagnostic only. No hidden SI, beta-cell reserve, hepatic IR, trajectory label or stress value is used by the policy. Existing componentTitrate thresholds/step sizes are unchanged.','','Rule: when the corresponding observed glucose has fallen strictly across three consecutive days, block only a further upward titration for that component.','','| profile | arm | patients <20 | any <54 | D8 mean BG | D8 TDD/kg |','|---|---|---:|---:|---:|---:|'];for(const r of rows){const d8=r.days[7];md.push(`| ${r.profile} | ${r.mode} | ${r.below20_pct.toFixed(1)}% | ${r.any54_pct.toFixed(1)}% | ${d8.mean_bg.toFixed(1)} | ${d8.tdd_per_kg.toFixed(3)} |`);}md.push('','## Guardrails','- This is a structural anti-windup diagnostic, not an Emory-fitting sweep.','- Do not adopt either guarded arm without Shanghai preservation and independent external validation.','- A useful signal is selective reduction of late extreme hypoglycemia in resolving trajectories without marked hyperglycemic drift in persistent trajectories.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
