#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v2_egp_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV2EgpExp;
const aspart=PK.get('aspart'),N=8000,DAYS=6;
const target={age:68.5,age_sd:10.3,bmi:31.0,bmi_sd:6.6,duration:15.1,duration_sd:11.1,weight:89.1,weight_sd:18.8};
const graz={
 overall:{mean:145.8,cv:37.7,lt50_4:0.3,lt59_4:0.8,lt70_2:2.4,tir70_180:75.8,mid100_8_140_4:36.2,gt180:21.9,gt250_2:5.6,gt349_2:0.5},
 day1:{mean:156.6,cv:39.6,lt50_4:0.5,lt59_4:1.2,lt70_2:2.6,tir70_180:67.7,mid100_8_140_4:30.7,gt180:29.7,gt250_2:8.6,gt349_2:0.9},
 last:{mean:142.2,cv:36.9,lt50_4:0.4,lt59_4:0.9,lt70_2:2.8,tir70_180:77.5,mid100_8_140_4:37.9,gt180:19.7,gt250_2:3.7,gt349_2:0.4},
 bg_overall:{mean:149.4,cv:38.6,lt50_4:0.2,lt59_4:0.7,lt70_2:2.7,tir70_180:73.2,mid100_8_140_4:33.5,gt180:24.1,gt250_2:5.9,gt349_2:0.6}
};
function dot(a,b){let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s}
function solve(A,b){const n=b.length,Mx=A.map((r,i)=>r.slice().concat([b[i]]));for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(Mx[r][c])>Math.abs(Mx[p][c]))p=r;if(Math.abs(Mx[p][c])<1e-12)throw new Error('singular entropy covariance');[Mx[c],Mx[p]]=[Mx[p],Mx[c]];const q=Mx[c][c];for(let j=c;j<=n;j++)Mx[c][j]/=q;for(let r=0;r<n;r++){if(r===c)continue;const f=Mx[r][c];for(let j=c;j<=n;j++)Mx[r][j]-=f*Mx[c][j];}}return Mx.map(r=>r[n])}
function entropyWeights(xs){const k=xs[0].length;let lam=Array(k).fill(0),p=[];for(let it=0;it<50;it++){const scores=xs.map(x=>dot(lam,x)),mx=Math.max(...scores),raw=scores.map(s=>Math.exp(s-mx)),z=raw.reduce((a,b)=>a+b,0);p=raw.map(w=>w/z);const mu=Array(k).fill(0);for(let n=0;n<xs.length;n++)for(let j=0;j<k;j++)mu[j]+=p[n]*xs[n][j];if(Math.max(...mu.map(Math.abs))<1e-10)break;const cov=Array.from({length:k},()=>Array(k).fill(0));for(let n=0;n<xs.length;n++)for(let j=0;j<k;j++)for(let l=0;l<k;l++)cov[j][l]+=p[n]*(xs[n][j]-mu[j])*(xs[n][l]-mu[l]);for(let j=0;j<k;j++)cov[j][j]+=1e-7;const step=solve(cov,mu);lam=lam.map((v,j)=>v-step[j]);}return{p,lambda:lam}}
function exposure(day){const f=(day-1)/(DAYS-1);return{basal:Math.round(24+3*f),bolus:Math.round(32-3*f)}}
function splitBolus(total,day){const base=Math.floor(total/3),out=[base,base,base],rem=total-3*base,start=(day-1)%3;for(let k=0;k<rem;k++)out[(start+k)%3]++;return out}
function orderForDay(day){const d=Math.max(1,Math.min(DAYS,day)),e=exposure(d),x=splitBolus(e.bolus,d);return{breakfast_u:x[0],lunch_u:x[1],dinner_u:x[2],basal_u:e.basal}}
function frozenPatch(p){return{prandial_mass_action_low_side:true,prandial_mass_action_reference_mg_dl:Number(p.endogenous_insulin&&p.endogenous_insulin.glucose_threshold_mg_dl)||100,...CR.statePatch(M,{reserve:1,activation_width_mg_dl:10})}}
function syncMealTiming(state){const ms={breakfast:0,lunch:0,dinner:0,...(state.meal_shift_min||{})};return{bolus_shift_min:{...ms},bolus_fraction:{breakfast:1,lunch:1,dinner:1}}}
function emptyAgg(){return{n:0,sum:0,sumsq:0,lt50_4:0,lt59_4:0,lt70_2:0,tir70_180:0,mid100_8_140_4:0,gt180:0,gt250_2:0,gt349_2:0}}
function addValue(a,x){a.n++;a.sum+=x;a.sumsq+=x*x;if(x<50.4)a.lt50_4++;if(x<59.4)a.lt59_4++;if(x<70.2)a.lt70_2++;if(x>=70.2&&x<=180)a.tir70_180++;if(x>=100.8&&x<=140.4)a.mid100_8_140_4++;if(x>180)a.gt180++;if(x>250.2)a.gt250_2++;if(x>349.2)a.gt349_2++}
function finish(a){const m=a.sum/a.n,v=Math.max(0,a.sumsq/a.n-m*m);return{mean:m,sd:Math.sqrt(v),cv:100*Math.sqrt(v)/m,lt50_4:100*a.lt50_4/a.n,lt59_4:100*a.lt59_4/a.n,lt70_2:100*a.lt70_2/a.n,tir70_180:100*a.tir70_180/a.n,mid100_8_140_4:100*a.mid100_8_140_4/a.n,gt180:100*a.gt180/a.n,gt250_2:100*a.gt250_2/a.n,gt349_2:100*a.gt349_2/a.n}}
function patientMetrics(course){const overall=emptyAgg(),day1=emptyAgg(),last=emptyAgg(),poc=emptyAgg();let any20=0,any30=0,any40=0;for(let d=0;d<course.records.length;d++){const r=course.records[d];for(let t=0;t<1440;t+=5){const x=r.series[t];addValue(overall,x);if(d===0)addValue(day1,x);if(d===course.records.length-1)addValue(last,x);if(x<20)any20=1;if(x<30)any30=1;if(x<40)any40=1;}for(const t of [420,720,1080,1260])addValue(poc,r.series[t]);}return{overall:finish(overall),day1:finish(day1),last:finish(last),poc:finish(poc),any20,any30,any40}}
const pts=[];for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'support_sweep'});pts.push({i,p,x:[(p.age_years-target.age)/target.age_sd,(p.bmi_kg_m2-target.bmi)/target.bmi_sd,(p.duration_years-target.duration)/target.duration_sd,(p.body_weight_kg-target.weight)/target.weight_sd]});}
const ew=entropyWeights(pts.map(z=>z.x)),weights=ew.p,uw=pts.map(()=>1/pts.length),rows=[];
for(const {i,p} of pts){const tr=T.choose(i),cfg={days:DAYS,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:0,underbolus_probability:0,allow_npo:false,bolus_tau_min:aspart.candidate.tau_min,bolus_duration_min:aspart.candidate.duration_min,titrate_order_fn:(ord,bg,ctx)=>orderForDay(ctx.day+1),state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...frozenPatch(p),...syncMealTiming(ctx.state)})};const c=C.simulateCourse(M,D,p,orderForDay(1),cfg,i);rows.push({age:p.age_years,bmi:p.bmi_kg_m2,duration:p.duration_years,weight:p.body_weight_kg,si:p.si_relative,...patientMetrics(c)});}
function wmean(w,get){let s=0;for(let i=0;i<rows.length;i++)s+=w[i]*get(rows[i]);return s}
function summary(w){const base={age:wmean(w,r=>r.age),bmi:wmean(w,r=>r.bmi),duration:wmean(w,r=>r.duration),weight:wmean(w,r=>r.weight),si_hidden_diagnostic:wmean(w,r=>r.si)};function part(k){const keys=['mean','sd','cv','lt50_4','lt59_4','lt70_2','tir70_180','mid100_8_140_4','gt180','gt250_2','gt349_2'],o={};for(const q of keys)o[q]=wmean(w,r=>r[k][q]);return o}return{baseline:base,overall:part('overall'),day1:part('day1'),last:part('last'),poc:part('poc'),patients_any20_pct:100*wmean(w,r=>r.any20),patients_any30_pct:100*wmean(w,r=>r.any30),patients_any40_pct:100*wmean(w,r=>r.any40)}}
const unweighted=summary(uw),matched=summary(weights),ess=1/weights.reduce((s,x)=>s+x*x,0);
const out={purpose:'Independent validation of the pre-frozen mass-action100 + CR V2 width10 T2DM low-side physiology in the Graz 2015 noncritical inpatient cohort. Candidate physiology is unchanged after Emory freeze. Outcome-blind entropy weighting uses only Graz baseline age, BMI, diabetes duration and body weight. Insulin treatment is exposure-conditioned to the published cohort mean basal/bolus doses: day1 24/32 U and day6 27/29 U with linear interpolation; integer meal bolus remainders rotate across meals to avoid systematic meal bias. No Graz glycemic outcome enters weighting, dosing, physiology, trajectory, PK, or rescue.',n:N,days:DAYS,target_baseline:target,entropy_lambda:ew.lambda,effective_sample_size:ess,insulin_exposure_by_day:Array.from({length:DAYS},(_,j)=>({day:j+1,...exposure(j+1),order:orderForDay(j+1)})),frozen_candidate:{mass_action_reference_mg_dl:100,cr_width_mg_dl:10,cr_reserve:1,aspart_pk:'pre-existing candidate',basal_potency:.20,stress_trajectory:'unchanged three-class module',hidden_cgm_rescue:false},graz_targets:graz,unweighted,baseline_entropy_matched:matched};
const dir='analysis/graz_2015_frozen_composite_external';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));
function line(name,s,t){return `| ${name} | ${s.mean.toFixed(1)} | ${t.mean.toFixed(1)} | ${s.cv.toFixed(1)}% | ${t.cv.toFixed(1)}% | ${s.lt70_2.toFixed(2)}% | ${t.lt70_2.toFixed(2)}% | ${s.tir70_180.toFixed(1)}% | ${t.tir70_180.toFixed(1)}% | ${s.gt180.toFixed(1)}% | ${t.gt180.toFixed(1)}% | ${s.gt250_2.toFixed(1)}% | ${t.gt250_2.toFixed(1)}% |`}
const m=matched,md=['# Graz 2015 independent validation — frozen composite','','Candidate frozen before this dataset: mass-action reference 100 mg/dL + CR V2 width10/reserve1. No Graz outcome is used to alter the candidate.','',`Generated N=${N}; entropy-weight ESS=${ess.toFixed(0)}.`,'',`Matched baseline: age ${m.baseline.age.toFixed(1)} (target 68.5), BMI ${m.baseline.bmi.toFixed(1)} (31.0), duration ${m.baseline.duration.toFixed(1)} (15.1), weight ${m.baseline.weight.toFixed(1)} kg (89.1).`,'','| period | sim mean | Graz mean | sim CV | Graz CV | sim <70.2 | Graz <70.2 | sim 70.2–180 | Graz | sim >180 | Graz | sim >250.2 | Graz |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|',line('overall',m.overall,graz.overall),line('day1',m.day1,graz.day1),line('last/day6',m.last,graz.last),'',`Deep-tail diagnostic: patients any <20 ${m.patients_any20_pct.toFixed(2)}%, <30 ${m.patients_any30_pct.toFixed(2)}%, <40 ${m.patients_any40_pct.toFixed(2)}%.`,'',`POC-like 4-point: mean ${m.poc.mean.toFixed(1)} vs Graz BG ${graz.bg_overall.mean.toFixed(1)}; TIR ${m.poc.tir70_180.toFixed(1)}% vs ${graz.bg_overall.tir70_180.toFixed(1)}%; TBR<70.2 ${m.poc.lt70_2.toFixed(2)}% vs ${graz.bg_overall.lt70_2.toFixed(2)}%.`,'','Guardrails:','- This is external validation, not calibration. Do not tune 100 mg/dL, CR width/reserve, PK, basal potency, stress trajectories, phenotype weights, meal probabilities or insulin exposure to improve Graz agreement.','- Baseline weights use age/BMI/duration/weight only.','- Cohort-mean insulin exposure is conditioned from the paper; dose heterogeneity/correlation is intentionally not invented.','- No hidden CGM rescue.'];fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
