#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const N=5000,gp=PK.get('glulisine'),map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function persistentTitrator(order,bg){const next=TP.componentTitrate(order,bg),vals=Object.values(bg).map(Number).filter(Number.isFinite),nHigh=vals.filter(x=>x>=180).length;for(const [comp,key] of Object.entries(map)){const cur=Number(order[comp])||0,nxt=Number(next[comp])||0,signal=Number(bg[key]);if(nxt>cur&&!(Number.isFinite(signal)&&signal>=180&&nHigh>=2))next[comp]=cur;}return next}
function mealMatchedPatch({order,state}){const intake=state.intake_fraction||{},mealShift=state.meal_shift_min||{},bolusShift={...(state.bolus_shift_min||{})},bolusFraction={...(state.bolus_fraction||{})};for(const meal of ['breakfast','lunch','dinner']){const f=Number(intake[meal]);if(!Number.isFinite(f)||f>=.85)continue;const key=meal+'_u',ordered=Math.max(0,Math.round(Number(order[key])||0)),given=Math.max(0,Math.round(ordered*Math.max(0,Math.min(1,f))));bolusFraction[meal]=ordered>0?given/ordered:0;const ms=Number(mealShift[meal])||0;bolusShift[meal]=Math.max(Number(bolusShift[meal])||0,15+ms);}return{bolus_fraction:bolusFraction,bolus_shift_min:bolusShift};}
function hourBin(min){return String(Math.floor(min/60)).padStart(2,'0')+':00'}
const events=[],profileCounts={},dayCounts={},hourCounts={};let patients20=0,patients54=0;
for(let i=1;i<=N;i++){
 const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);
 const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:persistentTitrator,state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl),...mealMatchedPatch(ctx)})};
 const c=C.simulateCourse(M,D,p,o,cfg,i);let first=null,a54=false;
 for(const r of c.records){for(let t=0;t<1440;t++){const x=r.series[t];if(x<54)a54=true;if(!first&&x<20)first={r,t,x};}}
 if(a54)patients54++;if(!first)continue;patients20++;
 const {r,t,x}=first,st=r.state||{},intake=st.intake_fraction||{},bolusShift=st.bolus_shift_min||{},bolusFrac=st.bolus_fraction||{};
 const partial=Object.values(intake).some(v=>Number.isFinite(Number(v))&&Number(v)>0&&Number(v)<.85);
 const npo=Object.values(intake).some(v=>Number(v)===0);
 const delayed=Object.values(bolusShift).some(v=>Number(v)>0);
 const under=Object.values(bolusFrac).some(v=>Number(v)<.999);
 const ev={patient:i,profile:tr,day:r.day,minute:t,hour_bin:hourBin(t),glucose:x,npo,partial_intake:partial,any_bolus_delay:delayed,any_bolus_fraction_lt1:under,tddkg:(r.order.basal_u+r.order.breakfast_u+r.order.lunch_u+r.order.dinner_u)/p.body_weight_kg,stress:Number(st.stress_severity)||0};events.push(ev);
 profileCounts[tr]=(profileCounts[tr]||0)+1;dayCounts[r.day]=(dayCounts[r.day]||0)+1;hourCounts[ev.hour_bin]=(hourCounts[ev.hour_bin]||0)+1;
}
function pct(n){return patients20?100*n/patients20:0}
const out={purpose:'Residual first-<20 attribution after guideline-grounded persistent_2of4 plus observable meal-matched postmeal policy; diagnostic only',n:N,patients_below20_pct:100*patients20/N,patients_any54_pct:100*patients54/N,event_count:events.length,first_event_attribution:{profile_counts:profileCounts,day_counts:dayCounts,hour_counts:hourCounts,npo_pct:pct(events.filter(e=>e.npo).length),partial_intake_pct:pct(events.filter(e=>e.partial_intake).length),any_bolus_delay_pct:pct(events.filter(e=>e.any_bolus_delay).length),any_bolus_fraction_lt1_pct:pct(events.filter(e=>e.any_bolus_fraction_lt1).length),mean_event_tddkg:mean(events.map(e=>e.tddkg)),mean_event_stress:mean(events.map(e=>e.stress))},events};
const dir='analysis/combined_policy_residual_tail_attribution';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));
const topHours=Object.entries(hourCounts).sort((a,b)=>b[1]-a[1]).slice(0,8),topDays=Object.entries(dayCounts).sort((a,b)=>Number(a[0])-Number(b[0])),profiles=Object.entries(profileCounts).sort((a,b)=>b[1]-a[1]);
let md=['# Combined-policy residual catastrophic-tail attribution','','Diagnostic only. Policy inputs remain observable-only; trajectory labels are used here only for post hoc attribution.','','Patients <20: '+out.patients_below20_pct.toFixed(2)+'% ('+patients20+'/'+N+')','Patients any <54: '+out.patients_any54_pct.toFixed(2)+'%','','## First <20 event attribution','- NPO on event day: '+out.first_event_attribution.npo_pct.toFixed(1)+'%','- Partial intake on event day: '+out.first_event_attribution.partial_intake_pct.toFixed(1)+'%','- Any bolus delay on event day: '+out.first_event_attribution.any_bolus_delay_pct.toFixed(1)+'%','- Any bolus fraction <1 on event day: '+out.first_event_attribution.any_bolus_fraction_lt1_pct.toFixed(1)+'%','- Mean event TDD/kg: '+out.first_event_attribution.mean_event_tddkg.toFixed(3),'- Mean event stress: '+out.first_event_attribution.mean_event_stress.toFixed(3),'','### By profile','| profile | events | share |','|---|---:|---:|'];for(const [k,v] of profiles)md.push(`| ${k} | ${v} | ${pct(v).toFixed(1)}% |`);md.push('','### By day','| day | events | share |','|---:|---:|---:|');for(const [k,v] of topDays)md.push(`| ${k} | ${v} | ${pct(v).toFixed(1)}% |`);md.push('','### Top hour bins','| hour | events | share |','|---|---:|---:|');for(const [k,v] of topHours)md.push(`| ${k} | ${v} | ${pct(v).toFixed(1)}% |`);md.push('','Guardrails:','- Do not change stress decay, glulisine PK, basal potency, or phenotype weights based on this attribution.','- Do not use trajectory label as a treatment-policy input.','- Use the attribution only to identify the next structural diagnostic.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
