#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of[
 't2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js',
 't2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_dynamic_v1_scheduled_correction_exp.js',
 't2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_diatec_poc_exp.js','insulin_prandial_pk_prior_ranges_exp.js',
 't2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v2_egp_exp.js'
])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D0=T2DMInpatientDynamicV1PocSafetyExp,D=T2DMInpatientDynamicV1ScheduledCorrectionExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyDiatecPocExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV2EgpExp;
const asp=PK.get('aspart'),N=5000,DAYS=8,CORR_MIN=[180,465,765,1125,1320];
const target={age:76.1,age_sd:9.8,duration:13.1,duration_sd:8.7};
const arms=[{name:'prandial_after_1_observed_high_day',start_days:1},{name:'prandial_after_2_observed_high_days',start_days:2}];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))}
function dot(a,b){let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s}
function solve(A,b){const n=b.length,X=A.map((r,i)=>r.slice().concat([b[i]]));for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(X[r][c])>Math.abs(X[p][c]))p=r;if(Math.abs(X[p][c])<1e-12)throw new Error('singular');[X[c],X[p]]=[X[p],X[c]];const q=X[c][c];for(let j=c;j<=n;j++)X[c][j]/=q;for(let r=0;r<n;r++){if(r===c)continue;const f=X[r][c];for(let j=c;j<=n;j++)X[r][j]-=f*X[c][j];} }return X.map(r=>r[n])}
function entropyWeights(xs){const k=xs[0].length;let lam=Array(k).fill(0),p=[];for(let it=0;it<60;it++){const sc=xs.map(x=>dot(lam,x)),mx=Math.max(...sc),raw=sc.map(s=>Math.exp(s-mx)),z=raw.reduce((a,b)=>a+b,0);p=raw.map(w=>w/z);const mu=Array(k).fill(0);for(let n=0;n<xs.length;n++)for(let j=0;j<k;j++)mu[j]+=p[n]*xs[n][j];if(Math.max(...mu.map(Math.abs))<1e-9)break;const cov=Array.from({length:k},()=>Array(k).fill(0));for(let n=0;n<xs.length;n++)for(let j=0;j<k;j++)for(let l=0;l<k;l++)cov[j][l]+=p[n]*(xs[n][j]-mu[j])*(xs[n][l]-mu[l]);for(let j=0;j<k;j++)cov[j][j]+=1e-6;const step=solve(cov,mu);lam=lam.map((v,j)=>v-step[j]);}return p}
function wquant(v,w,q){const a=v.map((x,i)=>[x,w[i]]).sort((a,b)=>a[0]-b[0]);let c=0;for(const [x,ww] of a){c+=ww;if(c>=q)return x}return a[a.length-1][0]}
function frozenPatch(p){return{prandial_mass_action_low_side:true,prandial_mass_action_reference_mg_dl:Number(p.endogenous_insulin&&p.endogenous_insulin.glucose_threshold_mg_dl)||100,...CR.statePatch(M,{reserve:1,activation_width_mg_dl:10})}}
function regressionSmoke(){let mx=0;for(let i=1;i<=40;i++){const p=P.sample(i,{preset:'support_sweep'}),o=M.suggestOrder(p),tr=T.choose(i),st={...T.statePatch(tr,1,i),...B.statePatch(M,.20),...frozenPatch(p),bolus_tau_min:asp.candidate.tau_min,bolus_duration_min:asp.candidate.duration_min};const a=D0.simulateDay(M,p,o,st,i,null),b=D.simulateDay(M,p,o,st,i,null);for(let t=0;t<=1440;t++)mx=Math.max(mx,Math.abs(a.series[t]-b.series[t]));}if(mx>1e-12)throw new Error('scheduled-correction derivative changed no-hook behavior; max diff '+mx);return mx}
function patientMetrics(z,arm){const {i,p}=z,counter={corr:0},tr=T.choose(i),o=TP.startingOrder(p);const cfg={days:DAYS,titrate:true,allow_meal_mismatch:false,allow_npo:false,bolus_tau_min:asp.candidate.tau_min,bolus_duration_min:asp.candidate.duration_min,titrate_order_fn:(ord,bg,ctx)=>TP.titratePoc(ord,bg,ctx,{prandial_start_days:arm.start_days}),state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...frozenPatch(p),prandial_poc_min:{breakfast:465,lunch:765,dinner:1125},prandial_safety_adjustment_fn:({poc_glucose_mg_dl,planned_units})=>Number(poc_glucose_mg_dl)<70?0:planned_units,scheduled_correction_minutes:CORR_MIN,scheduled_correction_fn:({glucose_mg_dl})=>{const u=TP.supplement(glucose_mg_dl,'recommended');counter.corr+=u;return{units:u,label:'diatec_poc_recommended'}}})};
 const c=C.simulateCourse(M,D,p,o,cfg,i),vals=[],day=[];let basal=0,pr=0,held=0,any40=0;
 for(const r of c.records){basal+=r.order.basal_u;pr+=r.order.breakfast_u+r.order.lunch_u+r.order.dinner_u;for(const a of r.prandial_safety_adjustments||[])held+=Math.max(0,Number(a.planned_units)-Number(a.given_units));const v=[];for(let t=0;t<1440;t+=5){const x=Number(r.series[t]);v.push(x);vals.push(x);if(x<40)any40=1}const m=mean(v),s=sd(v);day.push({tir:100*v.filter(x=>x>=70&&x<=180).length/v.length,tar:100*v.filter(x=>x>180).length/v.length,tbr:100*v.filter(x=>x<70).length/v.length,mean:m,cv:100*s/m})}
 const m=mean(vals),s=sd(vals);return{tir:100*vals.filter(x=>x>=70&&x<=180).length/vals.length,tar:100*vals.filter(x=>x>180).length/vals.length,tbr70:100*vals.filter(x=>x<70).length/vals.length,tbr54:100*vals.filter(x=>x<54).length/vals.length,mean_bg:m,cv:100*s/m,any40,tdd_day:(basal+pr-held+counter.corr)/DAYS,correction_day:counter.corr/DAYS,basal_day:basal/DAYS,scheduled_prandial_day:(pr-held)/DAYS,day};}
const pts=[];for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'support_sweep'});if(Number(p.egfr_ml_min_1_73m2)<15)continue;pts.push({i,p,x:[(Number(p.age_years)-target.age)/target.age_sd,(Number(p.duration_years)-target.duration)/target.duration_sd]})}
const w=entropyWeights(pts.map(z=>z.x)),ess=1/w.reduce((s,x)=>s+x*x,0),baseline={age:pts.reduce((s,z,i)=>s+w[i]*z.p.age_years,0),duration:pts.reduce((s,z,i)=>s+w[i]*z.p.duration_years,0),bmi:pts.reduce((s,z,i)=>s+w[i]*z.p.bmi_kg_m2,0),weight:pts.reduce((s,z,i)=>s+w[i]*z.p.body_weight_kg,0),egfr:pts.reduce((s,z,i)=>s+w[i]*z.p.egfr_ml_min_1_73m2,0),si:pts.reduce((s,z,i)=>s+w[i]*z.p.si_relative,0)};
const noHookMaxDiff=regressionSmoke(),results=[];
for(const arm of arms){const rows=pts.map(z=>patientMetrics(z,arm));const wm=k=>rows.reduce((s,r,i)=>s+w[i]*r[k],0),day=[];for(let d=0;d<DAYS;d++)day.push({day:d+1,tir_median:wquant(rows.map(r=>r.day[d].tir),w,.5),mean_bg:rows.reduce((s,r,i)=>s+w[i]*r.day[d].mean,0)});results.push({...arm,summary:{tir_median:wquant(rows.map(r=>r.tir),w,.5),tar_median:wquant(rows.map(r=>r.tar),w,.5),tbr70_median:wquant(rows.map(r=>r.tbr70),w,.5),tbr54_median:wquant(rows.map(r=>r.tbr54),w,.5),mean_bg:wm('mean_bg'),cv_mean:wm('cv'),any40_pct:100*wm('any40'),tdd_day:wm('tdd_day'),basal_day:wm('basal_day'),scheduled_prandial_day:wm('scheduled_prandial_day'),correction_day:wm('correction_day'),day}})}
const out={purpose:'Independent DIATEC POC-arm context audit of frozen mass-action100 + CR V2 width10/reserve1 physiology using observable POC-only treatment decisions.',no_hook_regression_max_abs_diff:noHookMaxDiff,n:{requested:N,eligible:pts.length,ess},baseline_target:target,baseline_weighted:baseline,frozen_candidate:{mass_action_reference_mg_dl:100,cr_width_mg_dl:10,cr_reserve:1,freeze_commit:'71c967785233763fe1522014004050dd2cdc38c7'},trial_context:{poc_arm_n:82,age_mean_sd:'76.1 (9.8) overall trial; no baseline arm difference',duration_mean_sd:'13.1 (8.7) overall trial; no baseline arm difference',prior_insulin_pct:24.7,insulin_note:'Patient-level home insulin doses unavailable in the generator; all simulated patients use protocol weight-based starts.',correction:'03:00, premeal x3, 22:00; recommended 4/6/8/10 U scale only in primary context.',prandial_start:'Published discretion after postprandial >180 for 1-2 days; both 1-day and 2-day observed-POC persistence arms are reported and neither is selected by outcome.',duration_days:8,rescue_note:'POC-detected hypoglycemia treatment amount was not specified in the accessible protocol summary, so no carbohydrate rescue is modeled in this first audit.'},targets:{tir_median_pct:62.7,tar_median_pct:36.5,cv_mean_pct:28.0,total_insulin_mean_u_day:29.3,weekday_mean_glucose_mg_dl:9.6*18,weekday_tir_median_pct:62.4,weekday_tar_median_pct:36.7},results,guardrails:['No hidden CGM/minute-series value is used for treatment decisions.','Do not select prandial-start arm by closeness to DIATEC outcomes.','Do not alter frozen physiology using DIATEC results.','HbA1c and home-insulin dose cannot be baseline-conditioned because the current generator lacks those observables.']};
const dir='analysis/diatec_poc_frozen_composite';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# DIATEC POC frozen-composite external audit','',`No-hook derivative regression max abs diff: ${noHookMaxDiff}.`,`Eligible N=${pts.length}; ESS=${ess.toFixed(0)}.`,`Weighted baseline: age ${baseline.age.toFixed(1)}, duration ${baseline.duration.toFixed(1)}, BMI ${baseline.bmi.toFixed(1)}, eGFR ${baseline.egfr.toFixed(1)}, SI ${baseline.si.toFixed(3)}.`,'','| arm | TIR median | TAR median | TBR<70 median | mean BG | CV mean | total insulin | basal | scheduled prandial | correction | any<40 |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of results){const s=r.summary;md.push(`| ${r.name} | ${s.tir_median.toFixed(1)}% | ${s.tar_median.toFixed(1)}% | ${s.tbr70_median.toFixed(2)}% | ${s.mean_bg.toFixed(1)} | ${s.cv_mean.toFixed(1)}% | ${s.tdd_day.toFixed(1)} U/d | ${s.basal_day.toFixed(1)} | ${s.scheduled_prandial_day.toFixed(1)} | ${s.correction_day.toFixed(1)} | ${s.any40_pct.toFixed(2)}% |`)}md.push('','DIATEC POC anchors: TIR median 62.7%, TAR>180 median 36.5%, CV mean 28.0%, total insulin 29.3 U/day. Weekday sensitivity mean glucose 9.6 mmol/L (~172.8 mg/dL), TIR 62.4%, TAR 36.7%.','','## Day-by-day TIR median');for(const r of results)md.push('',r.name+': '+r.summary.day.map(x=>`D${x.day} ${x.tir_median.toFixed(1)}%`).join(' | '));md.push('','Interpret as a treatment-context validation, not a parameter-fitting target.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
