#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v1_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV1Exp;
const NSH=1200,NEM=1600,ARMS=['legacy','thresholded_preserved','thresholded_beta_failure_055'];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}function minOf(a){let m=Infinity;for(const x of a)if(x<m)m=x;return m}function noct(t){return t>=1320||t<360}
function reserveFor(arm,p){if(arm==='legacy')return null;if(arm==='thresholded_beta_failure_055'&&p.patient_archetype==='beta_failure_long_duration')return .55;return 1;}
function patchFor(arm,p){const r=reserveFor(arm,p);return r===null?{}:CR.statePatch(M,{reserve:r});}
function shanghai(arm){const vals={all:[],preB:[],preL:[],preD:[],d120:[]};for(let i=1;i<=NSH;i++){const p=P1.sample(i),base=M.suggestOrder(p,M.DEFAULT_MEALS),o={...base,basal_u:Math.max(0,Math.round(.201*p.body_weight_kg))};let prev=null;for(let d=0;d<6;d++){const st={meal_plan_carb_g:M.DEFAULT_MEALS,...B.statePatch(M,.20),...patchFor(arm,p)},x=D.simulateDay(M,p,o,st,i*100+d,prev);prev=x.next_state;if(d<2)continue;for(let t=0;t<1440;t++)vals.all.push(x.series[t]);vals.preB.push(x.series[420]);vals.preL.push(x.series[720]);vals.preD.push(x.series[1080]);vals.d120.push(x.series[600]-x.series[480]);}}const a=vals.all,m=mean(a);return{mean:m,sd:sd(a),tbr70:100*a.filter(x=>x<70).length/a.length,tbr54:100*a.filter(x=>x<54).length/a.length,tir:100*a.filter(x=>x>=70&&x<=180).length/a.length,preB:mean(vals.preB),preL:mean(vals.preL),preD:mean(vals.preD),delta120:mean(vals.d120),min:minOf(a)};}
function external(arm){const gp=PK.get('glulisine'),rows=[];let noct70=0,noct54=0,deep54=0,deep70=0,below20=0;for(let i=1;i<=NEM;i++){const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i),cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.componentTitrate(ord,bg),state_modifier_fn:({day})=>({...T.statePatch(tr,day,i),...B.statePatch(M,.20),...patchFor(arm,p),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i),xs=[];let n70=false,n54=false,d54=false,d70=false,lo20=false;for(const r of c.records)for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);if(noct(t)&&x<70)n70=true;if(noct(t)&&x<54)n54=true;if(t<360&&x<70)d70=true;if(t<360&&x<54)d54=true;if(x<20)lo20=true;}if(n70)noct70++;if(n54)noct54++;if(d70)deep70++;if(d54)deep54++;if(lo20)below20++;const m=mean(xs),s=sd(xs);rows.push({mean:m,tbr70:100*xs.filter(x=>x<70).length/xs.length,tbr54:100*xs.filter(x=>x<54).length/xs.length,cv:100*s/m,min:minOf(xs)});}return{mean:mean(rows.map(x=>x.mean)),tbr70:mean(rows.map(x=>x.tbr70)),tbr54:mean(rows.map(x=>x.tbr54)),cv:mean(rows.map(x=>x.cv)),noct70:100*noct70/NEM,noct54:100*noct54/NEM,deep70:100*deep70/NEM,deep54:100*deep54/NEM,below20_patient_pct:100*below20/NEM,mean_patient_min:mean(rows.map(x=>x.min))};}
const shLegacy=shanghai('legacy'),rows=[];for(const arm of ARMS){const sh=shanghai(arm),ex=external(arm),d={};for(const k of ['mean','tbr70','tbr54','tir','preB','preL','preD','delta120'])d[k]=sh[k]-shLegacy[k];const gate=Math.abs(d.mean)<5&&Math.abs(d.preB)<5&&Math.abs(d.preL)<5&&Math.abs(d.preD)<5&&Math.abs(d.delta120)<2&&Math.abs(d.tbr70)<1&&Math.abs(d.tir)<3;rows.push({arm,shanghai:sh,delta_vs_legacy:d,shanghai_gate:gate,external:ex});}
const out={definition:{model:'thresholded counterregulation v1',awake_threshold_mg_dl:CR.AWAKE_THRESHOLD_MG_DL,sleep_threshold_mg_dl:CR.SLEEP_THRESHOLD_MG_DL,low_side_switch_mg_dl:CR.LOW_SIDE_SWITCH_MG_DL,beta_failure_reserve_sensitivity:.55,selection_rule:'No Emory outcome may select reserve or thresholds.'},n:{shanghai:NSH,external:NEM},emory_reference:{mean:176.1,tbr70:4.5,tbr54:1.58,cv:32,noct70:41,noct54:26},rows};const dir='analysis/counterregulation_v1';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Thresholded counterregulation v1 audit','','The generic low-side setpoint tether below 80 mg/dL is replaced by an explicit threshold-triggered counterregulatory drive. Awake/sleep thresholds (60/50 mg/dL) are literature-derived; the drive slope reuses frozen restore_gain. The beta-failure 0.55 reserve arm is a sensitivity informed by approximately halved epinephrine responses reported in intensively treated T2D, not a calibrated parameter.','','| arm | Shanghai gate | Δmean | ΔTBR<70 | Emory-like mean | TBR<70 | TBR<54 | CV | noct<70 | noct<54 | 00–06 <70 | 00–06 <54 | <20 patients |','|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const d=r.delta_vs_legacy,e=r.external;md.push(`| ${r.arm} | ${r.shanghai_gate?'PASS':'FAIL'} | ${d.mean.toFixed(2)} | ${d.tbr70.toFixed(2)}pp | ${e.mean.toFixed(1)} | ${e.tbr70.toFixed(2)}% | ${e.tbr54.toFixed(2)}% | ${e.cv.toFixed(1)}% | ${e.noct70.toFixed(1)}% | ${e.noct54.toFixed(1)}% | ${e.deep70.toFixed(1)}% | ${e.deep54.toFixed(1)}% | ${e.below20_patient_pct.toFixed(1)}% |`)}md.push('','Guardrails:','- This is a structural physiology audit, not an Emory calibration sweep.','- Reject any arm that causes implausible extreme glucose (<20 mg/dL) or fails Shanghai preservation.','- Do not alter basal potency 0.20, glulisine PK, phenotype weights, or treatment policy to compensate.','- If the thresholded model is directionally useful but too extreme, refine the counterregulatory mechanism from independent clamp physiology rather than fitting Emory incidence.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
