#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v2_egp_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV2EgpExp;
const N=10000,gp=PK.get('glulisine'),map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function persistentTitrator(order,bg){const next=TP.componentTitrate(order,bg),vals=Object.values(bg).map(Number).filter(Number.isFinite),nHigh=vals.filter(x=>x>=180).length;for(const [comp,key] of Object.entries(map)){const cur=Number(order[comp])||0,nxt=Number(next[comp])||0,signal=Number(bg[key]);if(nxt>cur&&!(Number.isFinite(signal)&&signal>=180&&nHigh>=2))next[comp]=cur;}return next}
function mealMatchedPatch({order,state}){const intake=state.intake_fraction||{},mealShift=state.meal_shift_min||{},bolusShift={...(state.bolus_shift_min||{})},bolusFraction={...(state.bolus_fraction||{})};for(const meal of ['breakfast','lunch','dinner']){const f=Number(intake[meal]);if(!Number.isFinite(f)||f>=.85)continue;const key=meal+'_u',ordered=Math.max(0,Math.round(Number(order[key])||0)),given=Math.max(0,Math.round(ordered*Math.max(0,Math.min(1,f))));bolusFraction[meal]=ordered>0?given/ordered:0;const ms=Number(mealShift[meal])||0;bolusShift[meal]=Math.max(Number(bolusShift[meal])||0,15+ms);}return{bolus_fraction:bolusFraction,bolus_shift_min:bolusShift};}
function safetyOverride({poc_glucose_mg_dl,planned_units}){const bg=Number(poc_glucose_mg_dl),u=Math.max(0,Math.round(Number(planned_units)||0));if(bg<70)return Math.max(0,u-2);if(bg<100)return Math.max(0,u-1);return u;}
function thresholdAlignedPatch(){const width=10,maxDrive=CR.maxDriveMgDlMin();return{fasting_adjustment_fn:({t,glucose_mg_dl})=>{const g=Number(glucose_mg_dl),threshold=CR.isSleepMinute(t)?CR.SLEEP_THRESHOLD_MG_DL:CR.AWAKE_THRESHOLD_MG_DL;if(!Number.isFinite(g)||g>=threshold)return{restore_multiplier:1,drive_mg_dl_per_min:0};return{restore_multiplier:0,drive_mg_dl_per_min:maxDrive*CR.activation(threshold-g,width)};},counterregulation_model:'threshold-aligned-abrupt-egp-v2'};}
function hourBin(min){return String(Math.floor(min/60)).padStart(2,'0')+':00'}
const events=[];let p20=0,p54=0,totalAdjustments=0;const profileCounts={},dayCounts={},hourCounts={};
for(let i=1;i<=N;i++){
 const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);
 const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:persistentTitrator,state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...thresholdAlignedPatch(),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl),...mealMatchedPatch(ctx),prandial_safety_adjustment_fn:safetyOverride})};
 const c=C.simulateCourse(M,D,p,o,cfg,i);let first=null,a54=false;
 for(let ri=0;ri<c.records.length;ri++){
   const r=c.records[ri];for(const a of (r.prandial_safety_adjustments||[]))totalAdjustments++;
   for(let t=0;t<1440;t++){const x=r.series[t];if(x<54)a54=true;if(!first&&x<20)first={ri,r,t,x};}
 }
 if(a54)p54++;if(!first)continue;p20++;
 const {ri,r,t,x}=first,prev=ri>0?c.records[ri-1]:null,st=r.state||{},intake=st.intake_fraction||{},shift=st.bolus_shift_min||{},frac=st.bolus_fraction||{};
 const preL=Number(r.bg?.pre_lunch),priorPoc=prev?Object.values(prev.bg||{}).map(Number).filter(Number.isFinite):[],dayAdj=r.prandial_safety_adjustments||[],lunchAdj=dayAdj.find(a=>a.meal==='lunch')||null;
 const lunchOrdered=Math.max(0,Math.round(Number(r.order?.lunch_u)||0)),lunchIntake=Number(intake.lunch),lunchBolusFrac=Number(frac.lunch),lunchBolusDelay=Number(shift.lunch)||0;
 const ev={patient:i,profile:tr,day:r.day,minute:t,hour_bin:hourBin(t),glucose:x,current_preL:preL,prior_poc_min:priorPoc.length?Math.min(...priorPoc):NaN,lunch_adjusted:!!lunchAdj,lunch_adjustment:lunchAdj,partial_any:Object.values(intake).some(v=>Number.isFinite(Number(v))&&Number(v)>0&&Number(v)<.85),partial_lunch:Number.isFinite(lunchIntake)&&lunchIntake>0&&lunchIntake<.85,npo:Object.values(intake).some(v=>Number(v)===0),lunch_intake_fraction:lunchIntake,lunch_ordered_u:lunchOrdered,lunch_bolus_fraction:lunchBolusFrac,lunch_effective_u:Number.isFinite(lunchBolusFrac)?lunchOrdered*lunchBolusFrac:lunchOrdered,lunch_bolus_shift_min:lunchBolusDelay,tddkg:(r.order.basal_u+r.order.breakfast_u+r.order.lunch_u+r.order.dinner_u)/p.body_weight_kg,stress:Number(st.stress_severity)||0};
 events.push(ev);profileCounts[tr]=(profileCounts[tr]||0)+1;dayCounts[r.day]=(dayCounts[r.day]||0)+1;hourCounts[ev.hour_bin]=(hourCounts[ev.hour_bin]||0)+1;
}
function pct(n){return events.length?100*n/events.length:0}
const out={purpose:'Residual first-minute <20 attribution after threshold-aligned abrupt counterregulation plus persistent_2of4, meal matching, and same-day observable POC safety. Diagnostic only; trajectory labels are post hoc.',n:N,patients_below20_pct:100*p20/N,patients_any54_pct:100*p54/N,adjustments_per_patient_day:totalAdjustments/(N*8),event_count:events.length,first_event_attribution:{profile_counts:profileCounts,day_counts:dayCounts,hour_counts:hourCounts,lunch_adjusted_pct:pct(events.filter(e=>e.lunch_adjusted).length),event_preL_lt100_pct:pct(events.filter(e=>e.current_preL<100).length),event_preL_100_139_pct:pct(events.filter(e=>e.current_preL>=100&&e.current_preL<140).length),event_preL_ge140_pct:pct(events.filter(e=>e.current_preL>=140).length),prior_poc_min_lt100_pct:pct(events.filter(e=>e.prior_poc_min<100).length),partial_any_pct:pct(events.filter(e=>e.partial_any).length),partial_lunch_pct:pct(events.filter(e=>e.partial_lunch).length),npo_pct:pct(events.filter(e=>e.npo).length),mean_lunch_intake_fraction:mean(events.map(e=>e.lunch_intake_fraction).filter(Number.isFinite)),mean_lunch_ordered_u:mean(events.map(e=>e.lunch_ordered_u)),mean_lunch_effective_u:mean(events.map(e=>e.lunch_effective_u)),mean_lunch_bolus_shift_min:mean(events.map(e=>e.lunch_bolus_shift_min)),mean_tddkg:mean(events.map(e=>e.tddkg)),mean_stress:mean(events.map(e=>e.stress))},events};
const dir='analysis/threshold_aligned_residual_tail_attribution';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));const a=out.first_event_attribution,profiles=Object.entries(profileCounts).sort((a,b)=>b[1]-a[1]),days=Object.entries(dayCounts).sort((a,b)=>Number(a[0])-Number(b[0])),hours=Object.entries(hourCounts).sort((a,b)=>b[1]-a[1]).slice(0,8);let md=['# Threshold-aligned residual tail attribution','',`Patients <20: ${out.patients_below20_pct.toFixed(3)}% (${p20}/${N})`,`Patients any <54: ${out.patients_any54_pct.toFixed(2)}%`,'','## First <20 events',`- Lunch safety adjustment: ${a.lunch_adjusted_pct.toFixed(1)}%`,`- preL <100: ${a.event_preL_lt100_pct.toFixed(1)}%`,`- preL 100–139: ${a.event_preL_100_139_pct.toFixed(1)}%`,`- preL >=140: ${a.event_preL_ge140_pct.toFixed(1)}%`,`- Prior-day POC min <100: ${a.prior_poc_min_lt100_pct.toFixed(1)}%`,`- Any partial intake: ${a.partial_any_pct.toFixed(1)}%`,`- Partial lunch: ${a.partial_lunch_pct.toFixed(1)}%`,`- NPO: ${a.npo_pct.toFixed(1)}%`,`- Mean lunch intake fraction: ${a.mean_lunch_intake_fraction.toFixed(3)}`,`- Mean lunch ordered U: ${a.mean_lunch_ordered_u.toFixed(2)}`,`- Mean lunch effective U: ${a.mean_lunch_effective_u.toFixed(2)}`,`- Mean lunch bolus shift: ${a.mean_lunch_bolus_shift_min.toFixed(1)} min`,`- Mean TDD/kg: ${a.mean_tddkg.toFixed(3)}`,`- Mean stress: ${a.mean_stress.toFixed(3)}`,'','### By profile','| profile | events | share |','|---|---:|---:|'];for(const [k,v] of profiles)md.push(`| ${k} | ${v} | ${pct(v).toFixed(1)}% |`);md.push('','### By day','| day | events | share |','|---:|---:|---:|');for(const [k,v] of days)md.push(`| ${k} | ${v} | ${pct(v).toFixed(1)}% |`);md.push('','### Top hours','| hour | events | share |','|---|---:|---:|');for(const [k,v] of hours)md.push(`| ${k} | ${v} | ${pct(v).toFixed(1)}% |`);md.push('','Guardrails:','- Attribution only; do not retune counterregulation thresholds/width or the 1% gate.','- Do not use trajectory labels as treatment inputs.','- Do not alter stress decay, PK, basal potency or phenotype weights from this result.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
