#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v2_egp_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV2EgpExp;
const aspart=PK.get('aspart'),N=8000;
const target={age:68.5,age_sd:10.3,bmi:31.0,bmi_sd:6.6,duration:15.1,duration_sd:11.1,weight:89.1,weight_sd:18.8};
const grazDay1={mean:156.6,cv:39.6,lt50_4:.5,lt59_4:1.2,lt70_2:2.6,tir70_180:67.7,gt180:29.7,gt250_2:8.6};
function hash32(x){let h=2166136261>>>0;for(const c of String(x)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=hash32(seed);return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function randn(seed){const r=rng(seed);let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function lognormalFromMeanSd(mean,sd,z){const s2=Math.log(1+(sd*sd)/(mean*mean)),sigma=Math.sqrt(s2),mu=Math.log(mean)-.5*s2;return Math.exp(mu+sigma*z)}
function dot(a,b){let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s}
function solve(A,b){const n=b.length,X=A.map((r,i)=>r.slice().concat([b[i]]));for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(X[r][c])>Math.abs(X[p][c]))p=r;if(Math.abs(X[p][c])<1e-12)throw new Error('singular');[X[c],X[p]]=[X[p],X[c]];const q=X[c][c];for(let j=c;j<=n;j++)X[c][j]/=q;for(let r=0;r<n;r++){if(r===c)continue;const f=X[r][c];for(let j=c;j<=n;j++)X[r][j]-=f*X[c][j];}}return X.map(r=>r[n])}
function entropyWeights(xs){const k=xs[0].length;let lam=Array(k).fill(0),p=[];for(let it=0;it<50;it++){const sc=xs.map(x=>dot(lam,x)),mx=Math.max(...sc),raw=sc.map(s=>Math.exp(s-mx)),z=raw.reduce((a,b)=>a+b,0);p=raw.map(w=>w/z);const mu=Array(k).fill(0);for(let n=0;n<xs.length;n++)for(let j=0;j<k;j++)mu[j]+=p[n]*xs[n][j];if(Math.max(...mu.map(Math.abs))<1e-10)break;const cov=Array.from({length:k},()=>Array(k).fill(0));for(let n=0;n<xs.length;n++)for(let j=0;j<k;j++)for(let l=0;l<k;l++)cov[j][l]+=p[n]*(xs[n][j]-mu[j])*(xs[n][l]-mu[l]);for(let j=0;j<k;j++)cov[j][j]+=1e-7;const step=solve(cov,mu);lam=lam.map((v,j)=>v-step[j]);}return{p,lambda:lam}}
function splitRefined(total){total=Math.max(0,Math.round(total));const f=[.45,.25,.30],raw=f.map(x=>x*total),out=raw.map(Math.floor);let rem=total-out.reduce((a,b)=>a+b,0);const idx=[0,1,2].sort((a,b)=>(raw[b]-out[b])-(raw[a]-out[a]));for(let k=0;k<rem;k++)out[idx[k%3]]++;return out}
function makeOrder(basal,bolus){basal=Math.max(0,Math.round(basal));bolus=Math.max(0,Math.round(bolus));const x=splitRefined(bolus);return{breakfast_u:x[0],lunch_u:x[1],dinner_u:x[2],basal_u:basal}}
const ARMS=[
 {name:'uniform_published_day1_means',order:(p,i)=>makeOrder(24,32)},
 {name:'weight_scaled_published_means',order:(p,i)=>makeOrder(24*p.body_weight_kg/89.1,32*p.body_weight_kg/89.1)},
 {name:'independent_published_marginals',order:(p,i)=>makeOrder(lognormalFromMeanSd(24,16,randn('graz-basal:'+i)),lognormalFromMeanSd(32,21,randn('graz-bolus:'+i)))},
 {name:'insulin_naive_published_age_rule_boundary',order:(p,i)=>{const tdd=p.body_weight_kg*(p.age_years>=70?.3:.5),b=Math.round(tdd*.5);return makeOrder(b,Math.max(0,Math.round(tdd)-b))}},
 {name:'insulin_naive_age_or_egfr60_sensitivity',order:(p,i)=>{const tdd=p.body_weight_kg*((p.age_years>=70||p.egfr_ml_min_1_73m2<60)?.3:.5),b=Math.round(tdd*.5);return makeOrder(b,Math.max(0,Math.round(tdd)-b))}}
];
function frozenPatch(p){return{prandial_mass_action_low_side:true,prandial_mass_action_reference_mg_dl:Number(p.endogenous_insulin&&p.endogenous_insulin.glucose_threshold_mg_dl)||100,...CR.statePatch(M,{reserve:1,activation_width_mg_dl:10})}}
function syncTiming(state){const ms={breakfast:0,lunch:0,dinner:0,...(state.meal_shift_min||{})};return{bolus_shift_min:{...ms},bolus_fraction:{breakfast:1,lunch:1,dinner:1}}}
function metrics(r){let n=0,sum=0,ss=0,l50=0,l59=0,l70=0,tir=0,h180=0,h250=0,a20=0,a30=0,a40=0;for(let t=0;t<1440;t+=5){const x=r.series[t];n++;sum+=x;ss+=x*x;if(x<50.4)l50++;if(x<59.4)l59++;if(x<70.2)l70++;if(x>=70.2&&x<=180)tir++;if(x>180)h180++;if(x>250.2)h250++;if(x<20)a20=1;if(x<30)a30=1;if(x<40)a40=1;}const m=sum/n,sd=Math.sqrt(Math.max(0,ss/n-m*m));return{mean:m,cv:100*sd/m,lt50_4:100*l50/n,lt59_4:100*l59/n,lt70_2:100*l70/n,tir70_180:100*tir/n,gt180:100*h180/n,gt250_2:100*h250/n,any20:a20,any30:a30,any40:a40}}
const pts=[];for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'support_sweep'});pts.push({i,p,x:[(p.age_years-target.age)/target.age_sd,(p.bmi_kg_m2-target.bmi)/target.bmi_sd,(p.duration_years-target.duration)/target.duration_sd,(p.body_weight_kg-target.weight)/target.weight_sd]});}
const ew=entropyWeights(pts.map(z=>z.x)),w=ew.p,ess=1/w.reduce((s,x)=>s+x*x,0),all=[];
for(const arm of ARMS){const rows=[];for(const {i,p} of pts){const tr=T.choose(i),o=arm.order(p,i),cfg={days:1,titrate:false,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:0,underbolus_probability:0,allow_npo:false,bolus_tau_min:aspart.candidate.tau_min,bolus_duration_min:aspart.candidate.duration_min,state_modifier_fn:(ctx)=>({...T.statePatch(tr,1,i),...B.statePatch(M,.20),...frozenPatch(p),...syncTiming(ctx.state)})};const c=C.simulateCourse(M,D,p,o,cfg,i),q=metrics(c.records[0]);rows.push({...q,basal:o.basal_u,bolus:o.breakfast_u+o.lunch_u+o.dinner_u,tdd:o.basal_u+o.breakfast_u+o.lunch_u+o.dinner_u,tddkg:(o.basal_u+o.breakfast_u+o.lunch_u+o.dinner_u)/p.body_weight_kg});}
 function wm(k){let s=0;for(let i=0;i<rows.length;i++)s+=w[i]*rows[i][k];return s}all.push({arm:arm.name,mean:wm('mean'),cv:wm('cv'),lt50_4:wm('lt50_4'),lt59_4:wm('lt59_4'),lt70_2:wm('lt70_2'),tir70_180:wm('tir70_180'),gt180:wm('gt180'),gt250_2:wm('gt250_2'),patients_any20_pct:100*wm('any20'),patients_any30_pct:100*wm('any30'),patients_any40_pct:100*wm('any40'),exposure:{basal_u:wm('basal'),bolus_u:wm('bolus'),tdd_u:wm('tdd'),tdd_u_kg:wm('tddkg')}});}
const out={purpose:'Treatment-context identifiability audit for Graz Day 1 with the frozen mass-action100 + CR V2 width10 physiology. All arms use identical frozen physiology, aspart PK, stress model, meal variability, and outcome-blind baseline entropy weights. Arms vary only the individual allocation implied or permitted by published treatment information. No arm is selected by closeness to Graz outcomes.',n:N,effective_sample_size:ess,target_baseline:target,graz_day1:grazDay1,arms:all,guardrails:['Do not tune frozen physiology from this audit.','uniform/weight-scaled/marginal arms use published day-1 aggregate basal 24±16 U and bolus 32±21 U.','insulin-naive boundary uses published 0.5 U/kg, reduced to 0.3 U/kg for age>=70; renal creatinine>=2 criterion is unavailable in the generator.','eGFR<60 arm is a pre-existing renal-risk threshold sensitivity only, not a Graz-fitted mapping.','Published refined meal bolus allocation 45/25/30 is used for all arms.','No hidden CGM rescue and no outcome-informed treatment inputs.']};
const dir='analysis/graz_day1_treatment_identifiability';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Graz Day-1 treatment-context identifiability audit','',`Frozen physiology unchanged. N=${N}; baseline entropy-weight ESS=${ess.toFixed(0)}.`,'','Graz Day-1 target: mean 156.6 mg/dL, CV 39.6%, <70.2 2.6%, TIR 67.7%, >180 29.7%, >250.2 8.6%.','','| arm | basal U | bolus U | TDD/kg | mean | CV | <70.2 | TIR | >180 | >250.2 | any<40 |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of all)md.push(`| ${r.arm} | ${r.exposure.basal_u.toFixed(1)} | ${r.exposure.bolus_u.toFixed(1)} | ${r.exposure.tdd_u_kg.toFixed(3)} | ${r.mean.toFixed(1)} | ${r.cv.toFixed(1)}% | ${r.lt70_2.toFixed(2)}% | ${r.tir70_180.toFixed(1)}% | ${r.gt180.toFixed(1)}% | ${r.gt250_2.toFixed(1)}% | ${r.patients_any40_pct.toFixed(2)}% |`);md.push('','Interpretation rule: if glycemic outputs change materially across equally outcome-blind plausible dose-allocation assumptions, aggregate Graz insulin summaries are not sufficient to identify physiology. Do not select an arm by closeness to Graz.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
