#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_emory_u300_trial_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyEmoryU300TrialExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const gp=PK.get('glulisine'),N=10000,POC=new Set([420,720,1080,1260]);
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function mealDosePatch({state}){return{prandial_safety_adjustment_fn:({meal,poc_glucose_mg_dl,planned_units})=>TP.mealDose({meal,poc_glucose_mg_dl,planned_units,state})};}
function protocolPocRescue({t,glucose_mg_dl,prior_rescues}){const g=Number(glucose_mg_dl);if(!(g<70))return 0;const rs=prior_rescues||[],last=rs.length?rs[rs.length-1]:null;const scheduled=POC.has(t),repeat=!!(last&&last.label==='protocol_poc_glucose'&&t===last.minute+15);if(!(scheduled||repeat))return 0;return{carbs_g:12.5,cooldown_min:15,label:'protocol_poc_glucose'};}
const byDay={},byHour={},byProfile={};let nEvent=0;const rows=[];
for(let i=1;i<=N;i++){
 const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(140,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);
 const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.registered2019Titrate(ord,bg),state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...mealDosePatch(ctx),bedtime_correction_fn:({glucose_mg_dl})=>TP.bedtimeSupplement(glucose_mg_dl,'usual'),hypoglycemia_rescue_fn:protocolPocRescue})};
 const c=C.simulateCourse(M,D,p,o,cfg,i);let found=null;
 for(const r of c.records){for(let t=0;t<1440;t++){if(r.series[t]<20){found={r,t};break}}if(found)break}
 if(!found)continue;nEvent++;const r=found.r,t=found.t,h=Math.floor(t/60);byDay[r.day]=(byDay[r.day]||0)+1;byHour[h]=(byHour[h]||0)+1;byProfile[tr.name||tr.id||String(tr)]=(byProfile[tr.name||tr.id||String(tr)]||0)+1;
 const priorPocTimes=[420,720,1080,1260].filter(x=>x<t),priorPoc=priorPocTimes.length?r.series[priorPocTimes[priorPocTimes.length-1]]:null;
 const priorRec=c.records[r.day-2]||null,priorDayPoc=priorRec?[priorRec.series[420],priorRec.series[720],priorRec.series[1080],priorRec.series[1260]]:[];
 const state=r.state||{},lunchIntake=state.intake_fraction&&state.intake_fraction.lunch, lunchShift=state.meal_shift_min&&state.meal_shift_min.lunch, lunchDelay=state.bolus_delay_min&&state.bolus_delay_min.lunch;
 const supp=(r.prandial_safety_adjustments||[]).filter(a=>a.meal==='lunch').map(a=>({planned:a.planned_units,given:a.given_units,poc:a.poc_glucose_mg_dl}));
 rows.push({patient:i,profile:tr.name||tr.id||String(tr),day:r.day,minute:t,hour:h,prior_same_day_poc:priorPoc,preB:r.series[420],preL:r.series[720],preD:t>1080?r.series[1080]:null,bedtime:t>1260?r.series[1260]:null,prior_day_poc_min:priorDayPoc.length?Math.min(...priorDayPoc):null,prior_day_poc_any_lt100:priorDayPoc.some(x=>x<100),basal_u:r.order.basal_u,breakfast_u:r.order.breakfast_u,lunch_u:r.order.lunch_u,dinner_u:r.order.dinner_u,scheduled_tdd_per_kg:(r.order.basal_u+r.order.breakfast_u+r.order.lunch_u+r.order.dinner_u)/p.body_weight_kg,lunch_intake_fraction:lunchIntake,lunch_meal_shift_min:lunchShift,lunch_bolus_delay_min:lunchDelay,lunch_dose_adjustments:supp,protocol_rescues_before_event:(r.hypoglycemia_rescues||[]).filter(x=>x.minute<t).length});
}
const pct=x=>nEvent?100*x/nEvent:0,summary={n:N,patients_below20:nEvent,patients_below20_pct:100*nEvent/N,by_day:byDay,by_hour:byHour,by_profile:byProfile,features:{d6_8_pct:pct((byDay[6]||0)+(byDay[7]||0)+(byDay[8]||0)),h13_15_pct:pct((byHour[13]||0)+(byHour[14]||0)+(byHour[15]||0)),preL_lt100_pct:pct(rows.filter(x=>x.preL<100).length),preL_100_139_pct:pct(rows.filter(x=>x.preL>=100&&x.preL<140).length),prior_day_poc_lt100_pct:pct(rows.filter(x=>x.prior_day_poc_any_lt100).length),partial_lunch_pct:pct(rows.filter(x=>Number.isFinite(x.lunch_intake_fraction)&&x.lunch_intake_fraction<.85).length),mean_lunch_intake:mean(rows.map(x=>x.lunch_intake_fraction).filter(Number.isFinite)),mean_lunch_u:mean(rows.map(x=>x.lunch_u)),mean_scheduled_tdd_per_kg:mean(rows.map(x=>x.scheduled_tdd_per_kg)),rescue_before_event_pct:pct(rows.filter(x=>x.protocol_rescues_before_event>0).length)}};
const dir='analysis/emory_registered_rescue_residual_tail';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify({summary,events:rows},null,2));
let md=['# Emory registered protocol + POC rescue residual <20 attribution','',`N=${N}; patients <20: ${nEvent} (${summary.patients_below20_pct.toFixed(2)}%).`,'',`D6-8: ${summary.features.d6_8_pct.toFixed(1)}%; 13-15h: ${summary.features.h13_15_pct.toFixed(1)}%.`,`preL <100: ${summary.features.preL_lt100_pct.toFixed(1)}%; preL 100-139: ${summary.features.preL_100_139_pct.toFixed(1)}%.`,`Prior-day 4-point POC <100: ${summary.features.prior_day_poc_lt100_pct.toFixed(1)}%.`,`Partial lunch: ${summary.features.partial_lunch_pct.toFixed(1)}%; mean lunch intake ${summary.features.mean_lunch_intake.toFixed(3)}.`,`Mean lunch scheduled dose: ${summary.features.mean_lunch_u.toFixed(2)} U; mean scheduled TDD/kg: ${summary.features.mean_scheduled_tdd_per_kg.toFixed(3)}.`,`Protocol POC rescue before first <20 event: ${summary.features.rescue_before_event_pct.toFixed(1)}%.`,'','By day: '+JSON.stringify(byDay),'By hour: '+JSON.stringify(byHour),'By profile: '+JSON.stringify(byProfile),'','Guardrails:','- Attribution only; do not tune protocol thresholds, correction scales, PK, stress, basal potency or phenotype weights from these outcomes.','- Hidden minute glucose is used only to locate the post-hoc event, never as treatment input.'];fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
