#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const N=2000,gp=PK.get('glulisine');
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function run(profile){const days=Array.from({length:8},(_,i)=>({day:i+1,stress:[],basal:[],bf:[],lu:[],di:[],preB:[],preL:[],preD:[],bed:[],low54:0,n:0}));const events=[];
 for(let i=1;i<=N;i++){
  const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});
  const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.componentTitrate(ord,bg),state_modifier_fn:({day})=>({...T.statePatch(profile,day,i),...B.statePatch(M,.20),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};
  const c=C.simulateCourse(M,D,p,o,cfg,i);let first54=null;
  for(const r of c.records){const d=days[r.day-1],ord=r.order,bg=r.bg;d.stress.push(r.state.stress_severity||0);d.basal.push(ord.basal_u/p.body_weight_kg);d.bf.push(ord.breakfast_u/p.body_weight_kg);d.lu.push(ord.lunch_u/p.body_weight_kg);d.di.push(ord.dinner_u/p.body_weight_kg);d.preB.push(bg.pre_breakfast);d.preL.push(bg.pre_lunch);d.preD.push(bg.pre_dinner);d.bed.push(bg.bedtime);d.n++;if(r.series.some(x=>x<54)){d.low54++;if(!first54)first54=r.day;}}
  if(first54){const r=c.records[first54-1],prev=c.records[Math.max(0,first54-3)];events.push({day:first54,basal_delta:(r.order.basal_u-prev.order.basal_u)/p.body_weight_kg,bf_delta:(r.order.breakfast_u-prev.order.breakfast_u)/p.body_weight_kg,lu_delta:(r.order.lunch_u-prev.order.lunch_u)/p.body_weight_kg,di_delta:(r.order.dinner_u-prev.order.dinner_u)/p.body_weight_kg,stress_delta:(r.state.stress_severity||0)-(prev.state.stress_severity||0)});}
 }
 return{profile,days:days.map(d=>({day:d.day,stress:mean(d.stress),basal_ukg:mean(d.basal),breakfast_ukg:mean(d.bf),lunch_ukg:mean(d.lu),dinner_ukg:mean(d.di),preB:mean(d.preB),preL:mean(d.preL),preD:mean(d.preD),bedtime:mean(d.bed),day_any54_pct:100*d.low54/d.n})),pre54:{n:events.length,mean_event_day:mean(events.map(x=>x.day)),delta_basal:mean(events.map(x=>x.basal_delta)),delta_breakfast:mean(events.map(x=>x.bf_delta)),delta_lunch:mean(events.map(x=>x.lu_delta)),delta_dinner:mean(events.map(x=>x.di_delta)),delta_stress:mean(events.map(x=>x.stress_delta))}};
}
const rows=['persistent_inflammatory','resolving_acute','moderate_stable'].map(run);const out={purpose:'attribute late-course hypoglycemia to individual insulin-order components under unchanged observable policy',n:N,rows};const dir='analysis/resolving_component_overshoot';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Resolving-acute component overshoot audit','','Diagnostic only. No policy coefficients or physiology parameters are changed.','','| profile | first <54 day | Δbasal/kg | Δbreakfast/kg | Δlunch/kg | Δdinner/kg | Δstress |','|---|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const e=r.pre54;md.push(`| ${r.profile} | ${e.mean_event_day.toFixed(2)} | ${e.delta_basal.toFixed(3)} | ${e.delta_breakfast.toFixed(3)} | ${e.delta_lunch.toFixed(3)} | ${e.delta_dinner.toFixed(3)} | ${e.delta_stress.toFixed(3)} |`);md.push('',`## ${r.profile}`,'| day | stress | basal/kg | breakfast/kg | lunch/kg | dinner/kg | preB | preL | preD | bedtime | any<54 |','|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|');for(const d of r.days)md.push(`| ${d.day} | ${d.stress.toFixed(3)} | ${d.basal_ukg.toFixed(3)} | ${d.breakfast_ukg.toFixed(3)} | ${d.lunch_ukg.toFixed(3)} | ${d.dinner_ukg.toFixed(3)} | ${d.preB.toFixed(1)} | ${d.preL.toFixed(1)} | ${d.preD.toFixed(1)} | ${d.bedtime.toFixed(1)} | ${d.day_any54_pct.toFixed(1)}% |`);md.push('');}md.push('Guardrails:','- This audit identifies which observable-policy component accumulates while stress resolves.','- Do not alter componentTitrate thresholds or step size from this audit alone.','- The next intervention, if justified, must remain observable-data-only and be evaluated against Shanghai plus external cohorts.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
