#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV1ShanghaiExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,B=InsulinBasalPotencyPriorExp;
function mean(a){return a.reduce((x,y)=>x+y,0)/a.length}function sd(a){const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/a.length)}
function hash32(x){let h=2166136261>>>0;for(const c of String(x)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=hash32(seed);return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function randn(r){let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
const N=3000,DAYS=8,WARM=2,TARGET={mean:134.8,sd:31.2,tbr:.50,tir:81.58,tar:17.92,preB:122.8,preL:135.1,preD:124.9,delta120:16.8};
const modes={legacy:{all:[],preB:[],preL:[],preD:[],d120:[]},basal_prior:{all:[],preB:[],preL:[],preD:[],d120:[]}};
for(let i=1;i<=N;i++){
 const p={...P.sample(i)};p.dynamic_fasting_setpoint_mg_dl=Math.max(70,Math.min(260,122.8+(p.dynamic_fasting_setpoint_mg_dl-147)*(31.5/28)));p.fasting_setpoint_mg_dl=p.dynamic_fasting_setpoint_mg_dl;
 const r=rng('strict-current:'+i),orders=[];for(let d=0;d<DAYS;d++){const base=M.suggestOrder(p,M.DEFAULT_MEALS),bu=Math.max(0,Math.round(11.1+3.6*randn(r))),scale=base.breakfast_u>0?bu/base.breakfast_u:1;orders.push({breakfast_u:bu,lunch_u:Math.max(0,Math.round(base.lunch_u*scale)),dinner_u:Math.max(0,Math.round(base.dinner_u*scale)),basal_u:base.basal_u});}
 for(const mode of Object.keys(modes)){let state=null;for(let d=0;d<DAYS;d++){const order=orders[d];let out;if(mode==='legacy')out=M.simulateDay(p,order,{meal_plan_carb_g:M.DEFAULT_MEALS},i,state);else out=D.simulateDay(M,p,order,{meal_plan_carb_g:M.DEFAULT_MEALS,...B.statePatch(M,1)},i,state);state=out.next_state;if(d<WARM)continue;const s=out.series,q=modes[mode];for(let t=0;t<1440;t++)q.all.push(s[t]);q.preB.push(s[420]);q.preL.push(s[720]);q.preD.push(s[1080]);q.d120.push(s[600]-s[480]);}}
}
function summarize(q){const pct=(a,f)=>100*a.filter(f).length/a.length;return{mean:mean(q.all),sd:sd(q.all),tbr:pct(q.all,x=>x<70),tir:pct(q.all,x=>x>=70&&x<=180),tar:pct(q.all,x=>x>180),preB:mean(q.preB),preL:mean(q.preL),preD:mean(q.preD),delta120:mean(q.d120)}}
const legacy=summarize(modes.legacy),prior=summarize(modes.basal_prior);const delta={};for(const k of Object.keys(legacy))delta[k]=prior[k]-legacy[k];
const checks=[['mean preserved',Math.abs(delta.mean)<5],['pre-breakfast preserved',Math.abs(delta.preB)<5],['pre-lunch preserved',Math.abs(delta.preL)<5],['pre-dinner preserved',Math.abs(delta.preD)<5],['breakfast delta120 preserved',Math.abs(delta.delta120)<2],['TBR preserved',Math.abs(delta.tbr)<1],['TIR preserved',Math.abs(delta.tir)<3]];
const out={target:TARGET,legacy,basal_prior:prior,delta_prior_minus_legacy:delta,checks,derived_daily_gain:B.unitConsistentDailyGain(M,1)};const dir='analysis/shanghai_basal_prior_preservation';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));
let md=['# Shanghai strict Basal+Regular preservation audit for basal potency prior','','Same Shanghai-anchor patients, same strict-inspired Regular treatment inputs, same meals and same frozen Regular kernel. Only the optional basal-dose-deviation gain is switched on. This is a preservation test, not recalibration.','','| metric | legacy | basal prior | delta | strict target |','|---|---:|---:|---:|---:|'];for(const k of ['mean','sd','tbr','tir','tar','preB','preL','preD','delta120'])md.push(`| ${k} | ${legacy[k].toFixed(2)} | ${prior[k].toFixed(2)} | ${delta[k].toFixed(2)} | ${TARGET[k]??''} |`);md+=['','## Checks'];for(const [n,ok] of checks)md.push(`- ${ok?'PASS':'FAIL'} — ${n}`);md+=['','## Guardrails','- Do not retune the Regular kernel from this audit.','- Do not fit basal potency to Shanghai outcomes; the gain is derived from per-unit consistency.','- Reject promotion if the prior materially shifts the frozen Shanghai fingerprint.'];fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));if(checks.some(x=>!x[1]))process.exitCode=2;
