#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v2_egp_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV2EgpExp;
const gp=PK.get('glulisine'),map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
const ARMS=[
 {name:'combined_poc_safety_legacy_low_side',enabled:false,width:null,reserve:1,primary:false},
 {name:'cr_v2_width10_default',enabled:true,width:10,reserve:1,primary:true},
 {name:'cr_v2_width5_sensitivity',enabled:true,width:5,reserve:1,primary:false},
 {name:'cr_v2_width20_sensitivity',enabled:true,width:20,reserve:1,primary:false},
 {name:'cr_v2_width10_reserve068_sensitivity',enabled:true,width:10,reserve:CR.ANTECEDENT_HYPO_RESERVE,primary:false}
];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))}
function persistent2of4(order,bg){const next=TP.componentTitrate(order,bg),vals=Object.values(bg).map(Number).filter(Number.isFinite),nHigh=vals.filter(x=>x>=180).length;for(const [comp,key] of Object.entries(map)){const cur=Number(order[comp])||0,nxt=Number(next[comp])||0,signal=Number(bg[key]);if(nxt>cur&&!(Number.isFinite(signal)&&signal>=180&&nHigh>=2))next[comp]=cur;}return next}
function mealMatchedPatch({order,state}){const intake=state.intake_fraction||{},mealShift=state.meal_shift_min||{},bolusShift={...(state.bolus_shift_min||{})},bolusFraction={...(state.bolus_fraction||{})};for(const meal of ['breakfast','lunch','dinner']){const f=Number(intake[meal]);if(!Number.isFinite(f)||f>=.85)continue;const key=meal+'_u',ordered=Math.max(0,Math.round(Number(order[key])||0)),given=Math.max(0,Math.round(ordered*Math.max(0,Math.min(1,f))));bolusFraction[meal]=ordered>0?given/ordered:0;const ms=Number(mealShift[meal])||0;bolusShift[meal]=Math.max(Number(bolusShift[meal])||0,15+ms);}return{bolus_fraction:bolusFraction,bolus_shift_min:bolusShift};}
function safetyOverride({poc_glucose_mg_dl,planned_units}){const bg=Number(poc_glucose_mg_dl),u=Math.max(0,Math.round(Number(planned_units)||0));if(bg<70)return Math.max(0,u-2);if(bg<100)return Math.max(0,u-1);return u;}
function crPatch(arm){return arm.enabled?CR.statePatch(M,{reserve:arm.reserve,activation_width_mg_dl:arm.width}):{}}
function external(arm,N=3500){let p20=0,p30=0,p40=0,p54=0,p70=0,noct70=0,noct54=0,deep54=0,total=0,n70=0,n54=0,n180=0,n250=0,adjustments=0;const pMeans=[],pCV=[];for(let i=1;i<=N;i++){const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:persistent2of4,state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),...crPatch(arm),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl),...mealMatchedPatch(ctx),prandial_safety_adjustment_fn:safetyOverride})};const c=C.simulateCourse(M,D,p,o,cfg,i);let a20=false,a30=false,a40=false,a54=false,a70=false,n70p=false,n54p=false,d54p=false;const xs=[];for(const r of c.records){adjustments+=(r.prandial_safety_adjustments||[]).length;for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);total++;if(x<20)a20=true;if(x<30)a30=true;if(x<40)a40=true;if(x<54){a54=true;n54++;}if(x<70){a70=true;n70++;}if(x>180)n180++;if(x>250)n250++;const isNoct=t>=1320||t<360;if(isNoct&&x<70)n70p=true;if(isNoct&&x<54)n54p=true;if(t<360&&x<54)d54p=true;}}if(a20)p20++;if(a30)p30++;if(a40)p40++;if(a54)p54++;if(a70)p70++;if(n70p)noct70++;if(n54p)noct54++;if(d54p)deep54++;const m=mean(xs);pMeans.push(m);pCV.push(100*sd(xs)/m);}
return{arm:arm.name,n:N,mean_bg:mean(pMeans),tir_pct:100*(total-n70-n180)/total,tar180_pct:100*n180/total,tar250_pct:100*n250/total,tbr70_pct:100*n70/total,tbr54_pct:100*n54/total,cv_pct:mean(pCV),patients_any70_pct:100*p70/N,patients_any54_pct:100*p54/N,noct70_pct:100*noct70/N,noct54_pct:100*noct54/N,deep00_06_54_pct:100*deep54/N,patients_below20_pct:100*p20/N,patients_below30_pct:100*p30/N,patients_below40_pct:100*p40/N,adjustments_per_patient_day:adjustments/(N*8)};}
function shanghaiCurrent(N=1200){return shanghaiInternal({name:'current',current:true},N)}
function shanghaiInternal(arm,N=1200){const all=[],preB=[],preL=[],preD=[],d120=[];let tbr70=0,tir=0,total=0;for(let i=1;i<=N;i++){const p=P1.sample(i),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});const current=!!arm.current;const cfg={days:8,titrate:true,allow_meal_mismatch:false,allow_npo:false,bolus_tau_min:90,bolus_duration_min:330,titrate_order_fn:current?((ord,bg)=>TP.componentTitrate(ord,bg)):persistent2of4,state_modifier_fn:()=>({...B.statePatch(M,.20),...(current?{}:crPatch(arm)),...(current?{}:{prandial_safety_adjustment_fn:safetyOverride})})};const c=C.simulateCourse(M,D,p,o,cfg,i);for(let d=2;d<c.records.length;d++){const r=c.records[d];for(let t=0;t<1440;t++){const x=r.series[t];all.push(x);total++;if(x<70)tbr70++;if(x>=70&&x<=180)tir++;}preB.push(r.series[420]);preL.push(r.series[720]);preD.push(r.series[1080]);d120.push(r.series[600]-r.series[480]);}}
return{arm:arm.name,mean:mean(all),preB:mean(preB),preL:mean(preL),preD:mean(preD),delta120:mean(d120),tbr70:100*tbr70/total,tir:100*tir/total};}
const shRef=shanghaiCurrent();const rows=[];for(const arm of ARMS){const ex=external(arm),sh=shanghaiInternal(arm),delta={};for(const k of ['mean','preB','preL','preD','delta120','tbr70','tir'])delta[k]=sh[k]-shRef[k];const shGate=Math.abs(delta.mean)<5&&Math.abs(delta.preB)<5&&Math.abs(delta.preL)<5&&Math.abs(delta.preD)<5&&Math.abs(delta.delta120)<2&&Math.abs(delta.tbr70)<1&&Math.abs(delta.tir)<3;const safetyGate=ex.patients_below20_pct<=1;rows.push({arm,...arm,external:ex,shanghai:sh,delta_vs_current:delta,shanghai_gate:shGate,safety_gate:safetyGate});}
const primary=rows.find(r=>r.primary);const out={purpose:'Re-evaluate physiology-grounded counterregulation V2 after structural treatment-policy safety improvements. The width=10 healthy-reserve arm is the pre-existing module default and is primary a priori; widths 5/20 and reserve 0.68 are sensitivity analyses only. Emory closeness must not select an arm.',definition:{awake_threshold_mg_dl:CR.AWAKE_THRESHOLD_MG_DL,sleep_threshold_mg_dl:CR.SLEEP_THRESHOLD_MG_DL,low_side_switch_mg_dl:CR.LOW_SIDE_SWITCH_MG_DL,healthy_egp_increment_mg_kg_min:CR.HEALTHY_COUNTERREG_EGP_INCREMENT_MG_KG_MIN,glucose_distribution_volume_l_kg:CR.GLUCOSE_DISTRIBUTION_VOLUME_L_KG,healthy_max_drive_mg_dl_min:CR.maxDriveMgDlMin(),antecedent_hypo_reserve:CR.ANTECEDENT_HYPO_RESERVE,selection_rule:'width10 healthy is primary because it is the pre-existing default. Other arms are sensitivity only; do not select by Emory closeness.'},n:{shanghai:1200,external:3500},shanghai_reference:shRef,rows,primary_pass:!!primary&&primary.shanghai_gate&&primary.safety_gate};
const dir='analysis/counterregulation_v2_safe_policy';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Counterregulation V2 after safer treatment policy','','Primary a priori arm: width 10 mg/dL, healthy reserve (the pre-existing module default). Width 5/20 and reserve 0.68 are sensitivity analyses only; Emory closeness cannot select an arm.','','| arm | Shanghai | safety<20 | mean | TIR | TAR>180 | TBR<70 | TBR<54 | CV | noct<70 | noct<54 | 00–06<54 | <20pt | <30pt | <40pt |','|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const e=r.external;md.push(`| ${r.name} | ${r.shanghai_gate?'PASS':'FAIL'} | ${r.safety_gate?'PASS':'FAIL'} | ${e.mean_bg.toFixed(1)} | ${e.tir_pct.toFixed(1)}% | ${e.tar180_pct.toFixed(1)}% | ${e.tbr70_pct.toFixed(2)}% | ${e.tbr54_pct.toFixed(2)}% | ${e.cv_pct.toFixed(1)}% | ${e.noct70_pct.toFixed(1)}% | ${e.noct54_pct.toFixed(1)}% | ${e.deep00_06_54_pct.toFixed(1)}% | ${e.patients_below20_pct.toFixed(2)}% | ${e.patients_below30_pct.toFixed(2)}% | ${e.patients_below40_pct.toFixed(2)}% |`);}md.push('','Primary width10 result: **'+(out.primary_pass?'PASS':'FAIL')+'**','','Guardrails:','- Do not choose width/reserve by closeness to Emory hypoglycemia rates.','- Safety gate only rejects catastrophic depth; Shanghai gate is unchanged.','- No real-time hidden-CGM rescue is used.','- Do not alter stress decay, glulisine PK, basal potency, or phenotype weights to compensate.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));if(!out.primary_pass)process.exitCode=2;
