#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,N=10000;
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}
function sd(a){const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))}
const cols={age:[],bmi:[],height:[],weight:[],egfr:[],duration:[],fpg:[],cpep:[],si:[]},arch={};
for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'});cols.age.push(p.age_years);cols.bmi.push(p.bmi_kg_m2);cols.height.push(p.height_cm);cols.weight.push(p.body_weight_kg);cols.egfr.push(p.egfr_ml_min_1_73m2);cols.duration.push(p.duration_years);cols.fpg.push(p.observed_fasting_glucose_mg_dl);cols.cpep.push(p.fasting_c_peptide_nmol_l);cols.si.push(p.si_relative);arch[p.patient_archetype]=(arch[p.patient_archetype]||0)+1;}
const stats={};for(const [k,a] of Object.entries(cols))stats[k]={mean:mean(a),sd:sd(a)};
const out={purpose:'Static support audit only. No glucose outcomes and no Emory outcome tuning.',n:N,stats,archetype_counts:arch,emory_reference:{age_years:54.5,bmi_kg_m2:33.8,duration_years:11.5,hba1c_pct:10.2,infection_pct:41}};
const dir='analysis/us_obese_preset_demographics';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# US-obese preset demographic audit','','Static generator support only; no outcome calibration.','','| variable | simulator mean | SD | Emory reference |','|---|---:|---:|---:|',`| age, y | ${stats.age.mean.toFixed(1)} | ${stats.age.sd.toFixed(1)} | 54.5 |`,`| BMI, kg/m2 | ${stats.bmi.mean.toFixed(1)} | ${stats.bmi.sd.toFixed(1)} | 33.8 |`,`| duration, y | ${stats.duration.mean.toFixed(1)} | ${stats.duration.sd.toFixed(1)} | 11.5 |`,`| height, cm | ${stats.height.mean.toFixed(1)} | ${stats.height.sd.toFixed(1)} | n/a |`,`| weight, kg | ${stats.weight.mean.toFixed(1)} | ${stats.weight.sd.toFixed(1)} | n/a |`,`| eGFR | ${stats.egfr.mean.toFixed(1)} | ${stats.egfr.sd.toFixed(1)} | severe renal excluded |`,`| observed fasting BG | ${stats.fpg.mean.toFixed(1)} | ${stats.fpg.sd.toFixed(1)} | n/a |`,`| fasting C-peptide, nmol/L | ${stats.cpep.mean.toFixed(3)} | ${stats.cpep.sd.toFixed(3)} | n/a |`,`| SI relative | ${stats.si.mean.toFixed(3)} | ${stats.si.sd.toFixed(3)} | n/a |`,'','Archetype counts: '+JSON.stringify(arch),'','Guardrails:','- Weights are support/sensitivity, not prevalence estimates.','- Do not change preset weights from glucose outcomes.','- This audit only determines whether the named US-obese sensitivity preset actually spans the external cohort phenotype.'];fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
