#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','insulin_basal_time_profile_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,BT=InsulinBasalTimeProfilePriorExp;
const NSH=600,NEM=1200;
const ARMS=[
  {name:'flat_restore1',form:'flat',amp:0,restore:1},
  {name:'u100_a030_restore1',form:'u100',amp:.30,restore:1},
  {name:'u300_a030_restore1',form:'u300',amp:.30,restore:1},
  {name:'flat_restore0',form:'flat',amp:0,restore:0},
  {name:'u100_a030_restore0',form:'u100',amp:.30,restore:0},
  {name:'u300_a030_restore0',form:'u300',amp:.30,restore:0}
];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}function noct(t){return t>=1320||t<360}
function lowPatch(mult){return{fasting_adjustment_fn:({t,glucose_mg_dl})=>({restore_multiplier:(t>=1320||t<420)&&glucose_mg_dl<80?mult:1})}}
function statePatch(a){return{...B.statePatch(M,.20),...(a.form==='flat'?{}:BT.statePatch(a.form,a.amp)),...lowPatch(a.restore)}}
function shanghai(a){const xs=[];for(let i=1;i<=NSH;i++){const p=P1.sample(i),base=M.suggestOrder(p,M.DEFAULT_MEALS),o={...base,basal_u:Math.max(0,Math.round(.201*p.body_weight_kg))};let prev=null;for(let d=0;d<6;d++){const x=D.simulateDay(M,p,o,{meal_plan_carb_g:M.DEFAULT_MEALS,...statePatch(a)},i*100+d,prev);prev=x.next_state;if(d<2)continue;for(let t=0;t<1440;t++)xs.push(x.series[t]);}}return{mean:mean(xs),tbr70:100*xs.filter(x=>x<70).length/xs.length,tir:100*xs.filter(x=>x>=70&&x<=180).length/xs.length};}
function external(a){const gp=PK.get('glulisine'),rows=[];let n70=0,n54=0,deep=0;for(let i=1;i<=NEM;i++){const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i),cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.componentTitrate(ord,bg),state_modifier_fn:({day})=>({...T.statePatch(tr,day,i),...statePatch(a),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i),xs=[];let p70=false,p54=false,pDeep=false;for(const r of c.records)for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);if(noct(t)&&x<70)p70=true;if(noct(t)&&x<54)p54=true;if(t<360&&x<54)pDeep=true;}if(p70)n70++;if(p54)n54++;if(pDeep)deep++;const m=mean(xs),s=sd(xs);rows.push({mean:m,tbr70:100*xs.filter(x=>x<70).length/xs.length,tbr54:100*xs.filter(x=>x<54).length/xs.length,cv:100*s/m});}return{mean:mean(rows.map(x=>x.mean)),tbr70:mean(rows.map(x=>x.tbr70)),tbr54:mean(rows.map(x=>x.tbr54)),cv:mean(rows.map(x=>x.cv)),noct70:100*n70/NEM,noct54:100*n54/NEM,deep54:100*deep/NEM};}
const sh0=shanghai(ARMS[0]),rows=[];for(const a of ARMS){const sh=shanghai(a),ex=external(a);rows.push({...a,shanghai:sh,delta_shanghai:{mean:sh.mean-sh0.mean,tbr70:sh.tbr70-sh0.tbr70,tir:sh.tir-sh0.tir},external:ex});}
const out={purpose:'upper-bound interaction diagnostic only; no parameter selection',n:{shanghai:NSH,external:NEM},reference:{emory_noct70:41,emory_noct54:26},rows};const dir='analysis/nocturnal_upper_bound_combined';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Nocturnal upper-bound combined mechanism audit','','This is an upper-bound diagnostic, not a calibration sweep. It combines the prespecified maximum glargine time-profile sensitivity amplitude (0.30) with complete removal of the generic low-side restore below 80 mg/dL at night. No arm is eligible for adoption from Emory closeness.','','| arm | ΔShanghai mean | ΔShanghai TBR | mean | TBR<54 | CV | noct<70 | noct<54 | 00–06 <54 |','|---|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const d=r.delta_shanghai,e=r.external;md.push(`| ${r.name} | ${d.mean.toFixed(2)} | ${d.tbr70.toFixed(2)}pp | ${e.mean.toFixed(1)} | ${e.tbr54.toFixed(2)}% | ${e.cv.toFixed(1)}% | ${e.noct70.toFixed(1)}% | ${e.noct54.toFixed(1)}% | ${e.deep54.toFixed(1)}% |`)}md.push('','Guardrails:','- If even the restore=0 + max shape arms remain far below the external nocturnal incidence, do not further increase shape amplitude or weaken restore.','- Then treat the residual as evidence for another mechanism class, especially time-varying insulin requirement / treatment lag or patient-specific counterregulatory impairment.','- Basal relative potency remains frozen at 0.20.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
