#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const MULT=[1,.75,.5,.25,0],NSH=800,NEM=1200;
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}function noct(t){return t>=1320||t<360}
function lowSidePatch(mult){return{fasting_adjustment_fn:({t,glucose_mg_dl})=>({restore_multiplier:(t>=1320||t<420)&&glucose_mg_dl<80?mult:1})}}
function shanghai(mult){const v=[];for(let i=1;i<=NSH;i++){const p=P1.sample(i),base=M.suggestOrder(p,M.DEFAULT_MEALS),o={...base,basal_u:Math.max(0,Math.round(.201*p.body_weight_kg))};let prev=null;for(let d=0;d<6;d++){const st={meal_plan_carb_g:M.DEFAULT_MEALS,...B.statePatch(M,.20),...lowSidePatch(mult)},x=D.simulateDay(M,p,o,st,i*100+d,prev);prev=x.next_state;if(d<2)continue;for(let t=0;t<1440;t++)v.push(x.series[t]);}}const m=mean(v);return{mean:m,tbr70:100*v.filter(x=>x<70).length/v.length,tbr54:100*v.filter(x=>x<54).length/v.length,tir:100*v.filter(x=>x>=70&&x<=180).length/v.length};}
function external(mult){const gp=PK.get('glulisine'),rows=[];let noct70=0,noct54=0,deep54=0;for(let i=1;i<=NEM;i++){const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i),cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.componentTitrate(ord,bg),state_modifier_fn:({day})=>({...T.statePatch(tr,day,i),...B.statePatch(M,.20),...lowSidePatch(mult),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i),xs=[];let a70=false,a54=false,d54=false;for(const r of c.records)for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);if(noct(t)&&x<70)a70=true;if(noct(t)&&x<54)a54=true;if(t<360&&x<54)d54=true;}if(a70)noct70++;if(a54)noct54++;if(d54)deep54++;const m=mean(xs),s=sd(xs);rows.push({mean:m,tbr70:100*xs.filter(x=>x<70).length/xs.length,tbr54:100*xs.filter(x=>x<54).length/xs.length,cv:100*s/m});}return{mean:mean(rows.map(x=>x.mean)),tbr70:mean(rows.map(x=>x.tbr70)),tbr54:mean(rows.map(x=>x.tbr54)),cv:mean(rows.map(x=>x.cv)),noct70:100*noct70/NEM,noct54:100*noct54/NEM,deep54:100*deep54/NEM};}
const baseSh=shanghai(1),rows=[];for(const m of MULT){const sh=shanghai(m),ex=external(m);rows.push({low_side_restore_multiplier:m,shanghai:sh,delta_shanghai:{mean:sh.mean-baseSh.mean,tbr70:sh.tbr70-baseSh.tbr70,tbr54:sh.tbr54-baseSh.tbr54,tir:sh.tir-baseSh.tir},external:ex});}
const out={definition:{purpose:'mechanism ablation only; not parameter selection',low_side_condition:'22:00-07:00 and glucose <80 mg/dL',legacy_restore_multiplier:1,external_reference:{noct70:41,noct54:26}},n:{shanghai:NSH,external:NEM},rows};const dir='analysis/low_side_homeostasis_ablation';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Low-side homeostasis ablation','','Diagnostic only. No multiplier is eligible for calibration from Emory. The frozen restore_gain is untouched; this temporarily attenuates its contribution only when glucose <80 mg/dL during 22:00–07:00.','','| low-side restore | ΔShanghai mean | ΔShanghai TBR<70 | Emory-like mean | TBR<70 | TBR<54 | CV | noct<70 | noct<54 | 00–06 <54 |','|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const d=r.delta_shanghai,e=r.external;md.push(`| ${r.low_side_restore_multiplier.toFixed(2)} | ${d.mean.toFixed(2)} | ${d.tbr70.toFixed(2)}pp | ${e.mean.toFixed(1)} | ${e.tbr70.toFixed(2)}% | ${e.tbr54.toFixed(2)}% | ${e.cv.toFixed(1)}% | ${e.noct70.toFixed(1)}% | ${e.noct54.toFixed(1)}% | ${e.deep54.toFixed(1)}% |`)}md.push('','Interpretation guardrail:','- This is an ablation, not a candidate sweep. Do not choose a multiplier by Emory closeness.','- If post-midnight hypoglycemia is highly sensitive to this term, replace generic low-side restore with an explicit counterregulatory physiology model before any calibration.','- If it remains insensitive even at zero, low-side homeostasis is not the missing mechanism.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
