#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV1ShanghaiExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,B=InsulinBasalPotencyPriorExp;
const map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}
function persistentTitrator(order,bg){const next=TP.componentTitrate(order,bg),vals=Object.values(bg).map(Number).filter(Number.isFinite),nHigh=vals.filter(x=>x>=180).length;for(const [comp,key] of Object.entries(map)){const cur=Number(order[comp])||0,nxt=Number(next[comp])||0,signal=Number(bg[key]);if(nxt>cur && !(Number.isFinite(signal)&&signal>=180&&nHigh>=2))next[comp]=cur;}return next}
function run(arm,N=1200){const all=[],preB=[],preL=[],preD=[],d120=[];let tbr70=0,tir=0,total=0;for(let i=1;i<=N;i++){const p=P.sample(i),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});const cfg={days:6,titrate:true,allow_meal_mismatch:false,allow_npo:false,bolus_tau_min:90,bolus_duration_min:330,titrate_order_fn:arm==='current'?((ord,bg)=>TP.componentTitrate(ord,bg)):persistentTitrator,state_modifier_fn:()=>({...B.statePatch(M,.20)})};const c=C.simulateCourse(M,D,p,o,cfg,i);for(let d=2;d<c.records.length;d++){const r=c.records[d];for(let t=0;t<1440;t++){const x=r.series[t];all.push(x);total++;if(x<70)tbr70++;if(x>=70&&x<=180)tir++;}preB.push(r.series[420]);preL.push(r.series[720]);preD.push(r.series[1080]);d120.push(r.series[600]-r.series[480]);}}
return{mean:mean(all),preB:mean(preB),preL:mean(preL),preD:mean(preD),delta120:mean(d120),tbr70:100*tbr70/total,tir:100*tir/total};}
const ref=run('current'),cand=run('combined'),d={};for(const k of ['mean','preB','preL','preD','delta120','tbr70','tir'])d[k]=cand[k]-ref[k];const gate=Math.abs(d.mean)<5&&Math.abs(d.preB)<5&&Math.abs(d.preL)<5&&Math.abs(d.preD)<5&&Math.abs(d.delta120)<2&&Math.abs(d.tbr70)<1&&Math.abs(d.tir)<3;
const out={purpose:'Shanghai preservation for combined candidate; meal-matching is inactive because Shanghai preservation uses stable full intake, so this isolates persistent_2of4 policy compatibility.',reference:ref,candidate:cand,delta:d,gate};const dir='analysis/combined_policy_shanghai_preservation';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));const md=['# Combined policy Shanghai preservation','','Meal-matched postmeal logic is inactive under stable full intake; this gate therefore verifies that the combined candidate retains the already-passed persistent_2of4 Shanghai behavior.','','| gate | Δmean | ΔpreB | ΔpreL | ΔpreD | Δ120 | ΔTBR<70 | ΔTIR |','|---|---:|---:|---:|---:|---:|---:|---:|',`| ${gate?'PASS':'FAIL'} | ${d.mean.toFixed(2)} | ${d.preB.toFixed(2)} | ${d.preL.toFixed(2)} | ${d.preD.toFixed(2)} | ${d.delta120.toFixed(2)} | ${d.tbr70.toFixed(2)}pp | ${d.tir.toFixed(2)}pp |`,'','Guardrail: do not alter thresholds from this result.'];fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));if(!gate)process.exitCode=2;
