#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const N=3000,gp=PK.get('glulisine'),map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function persistentTitrator(order,bg){const next=TP.componentTitrate(order,bg),vals=Object.values(bg).map(Number).filter(Number.isFinite),nHigh=vals.filter(x=>x>=180).length;for(const [comp,key] of Object.entries(map)){const cur=Number(order[comp])||0,nxt=Number(next[comp])||0,signal=Number(bg[key]);if(nxt>cur&&!(Number.isFinite(signal)&&signal>=180&&nHigh>=2))next[comp]=cur;}return next}
function run(arm){const rows=[];let any70=0,any54=0,noct70=0,noct54=0,deep54=0,b20=0,b30=0,b40=0;for(let i=1;i<=N;i++){
 const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);
 const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:arm==='current'?((ord,bg)=>TP.componentTitrate(ord,bg)):persistentTitrator,state_modifier_fn:({day})=>({...T.statePatch(tr,day,i),...B.statePatch(M,.20),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};
 const c=C.simulateCourse(M,D,p,o,cfg,i),xs=[];let a70=false,a54=false,n70=false,n54=false,d54=false,x20=false,x30=false,x40=false;
 for(const r of c.records){for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);if(x<70)a70=true;if(x<54)a54=true;if((t>=1320||t<360)&&x<70)n70=true;if((t>=1320||t<360)&&x<54)n54=true;if(t<360&&x<54)d54=true;if(x<20)x20=true;if(x<30)x30=true;if(x<40)x40=true;}}
 if(a70)any70++;if(a54)any54++;if(n70)noct70++;if(n54)noct54++;if(d54)deep54++;if(x20)b20++;if(x30)b30++;if(x40)b40++;
 const m=mean(xs),s=sd(xs);rows.push({mean:m,tir:100*xs.filter(x=>x>=70&&x<=180).length/xs.length,tar180:100*xs.filter(x=>x>180).length/xs.length,tar250:100*xs.filter(x=>x>250).length/xs.length,tbr70:100*xs.filter(x=>x<70).length/xs.length,tbr54:100*xs.filter(x=>x<54).length/xs.length,cv:100*s/m});
 }
 return{mean:mean(rows.map(x=>x.mean)),tir:mean(rows.map(x=>x.tir)),tar180:mean(rows.map(x=>x.tar180)),tar250:mean(rows.map(x=>x.tar250)),tbr70:mean(rows.map(x=>x.tbr70)),tbr54:mean(rows.map(x=>x.tbr54)),cv:mean(rows.map(x=>x.cv)),any70:100*any70/N,any54:100*any54/N,noct70:100*noct70/N,noct54:100*noct54/N,deep54:100*deep54/N,below20:100*b20/N,below30:100*b30/N,below40:100*b40/N};}
const rows=['current','persistent_2of4'].map(arm=>({arm,...run(arm)}));
const ref={mean:176.1,tir:53.5,tar180:42.2,tar250:16.1,tbr70:4.5,tbr54:1.58,cv:32,any70:56,any54:36,noct70:41,noct54:26};
const out={purpose:'External descriptive revalidation after Shanghai preservation PASS; no coefficient selection from Emory closeness',n:N,emory_reference:ref,rows};const dir='analysis/persistent_hyperglycemia_external_validation';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));
let md=['# Persistent hyperglycemia policy — full external revalidation','','Shanghai preservation already passed. Emory values are descriptive only; they do not select thresholds or persistence count.','','| arm | mean | TIR | TAR>180 | TAR>250 | TBR<70 | TBR<54 | CV | any<70 | any<54 | noct<70 | noct<54 | 00-06<54 | <20pt | <30pt | <40pt |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows)md.push(`| ${r.arm} | ${r.mean.toFixed(1)} | ${r.tir.toFixed(1)}% | ${r.tar180.toFixed(1)}% | ${r.tar250.toFixed(1)}% | ${r.tbr70.toFixed(2)}% | ${r.tbr54.toFixed(2)}% | ${r.cv.toFixed(1)}% | ${r.any70.toFixed(1)}% | ${r.any54.toFixed(1)}% | ${r.noct70.toFixed(1)}% | ${r.noct54.toFixed(1)}% | ${r.deep54.toFixed(1)}% | ${r.below20.toFixed(1)}% | ${r.below30.toFixed(1)}% | ${r.below40.toFixed(1)}% |`);md.push('','Emory reference: mean 176.1, TIR 53.5%, TAR>180 42.2%, TAR>250 16.1%, TBR<70 4.5%, TBR<54 1.58%, CV 32%, any<70 56%, any<54 36%, noct<70 41%, noct<54 26%.','','Guardrails:','- Do not change >=180 mg/dL or 2-of-4 persistence based on this external comparison.','- Do not add hidden-CGM rescue.','- This policy audit does not alter basal potency, glulisine PK, phenotype weights or trajectory parameters.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
