#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v2_egp_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV2EgpExp;
const NSH=1000,NEM=1600;
const ARMS=[
 {name:'legacy',enabled:false,width:null,reserve:1},
 {name:'v2_width5_healthy',enabled:true,width:5,reserve:1},
 {name:'v2_width10_healthy',enabled:true,width:10,reserve:1},
 {name:'v2_width20_healthy',enabled:true,width:20,reserve:1},
 {name:'v2_width10_antecedent_hypo068',enabled:true,width:10,reserve:CR.ANTECEDENT_HYPO_RESERVE},
 {name:'v2_width10_beta_failure068',enabled:true,width:10,reserve:'beta068'}
];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}function minOf(a){let m=Infinity;for(const x of a)if(x<m)m=x;return m}function noct(t){return t>=1320||t<360}
function patch(a,p){if(!a.enabled)return{};const reserve=a.reserve==='beta068'&&p.patient_archetype==='beta_failure_long_duration'?CR.ANTECEDENT_HYPO_RESERVE:1;return CR.statePatch(M,{reserve:a.reserve==='beta068'?reserve:a.reserve,activation_width_mg_dl:a.width});}
function shanghai(a){const v={all:[],preB:[],preL:[],preD:[],d120:[]};for(let i=1;i<=NSH;i++){const p=P1.sample(i),base=M.suggestOrder(p,M.DEFAULT_MEALS),o={...base,basal_u:Math.max(0,Math.round(.201*p.body_weight_kg))};let prev=null;for(let d=0;d<6;d++){const x=D.simulateDay(M,p,o,{meal_plan_carb_g:M.DEFAULT_MEALS,...B.statePatch(M,.20),...patch(a,p)},i*100+d,prev);prev=x.next_state;if(d<2)continue;for(let t=0;t<1440;t++)v.all.push(x.series[t]);v.preB.push(x.series[420]);v.preL.push(x.series[720]);v.preD.push(x.series[1080]);v.d120.push(x.series[600]-x.series[480]);}}const z=v.all;return{mean:mean(z),tbr70:100*z.filter(x=>x<70).length/z.length,tbr54:100*z.filter(x=>x<54).length/z.length,tir:100*z.filter(x=>x>=70&&x<=180).length/z.length,preB:mean(v.preB),preL:mean(v.preL),preD:mean(v.preD),delta120:mean(v.d120),min:minOf(z)};}
function external(a){const gp=PK.get('glulisine'),rows=[];let n70=0,n54=0,d70=0,d54=0,b20=0,b30=0,b40=0;for(let i=1;i<=NEM;i++){const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i),cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.componentTitrate(ord,bg),state_modifier_fn:({day})=>({...T.statePatch(tr,day,i),...B.statePatch(M,.20),...patch(a,p),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i),xs=[];let p70=false,p54=false,pD70=false,pD54=false,p20=false,p30=false,p40=false;for(const r of c.records)for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);if(noct(t)&&x<70)p70=true;if(noct(t)&&x<54)p54=true;if(t<360&&x<70)pD70=true;if(t<360&&x<54)pD54=true;if(x<20)p20=true;if(x<30)p30=true;if(x<40)p40=true;}if(p70)n70++;if(p54)n54++;if(pD70)d70++;if(pD54)d54++;if(p20)b20++;if(p30)b30++;if(p40)b40++;const m=mean(xs),s=sd(xs);rows.push({mean:m,tbr70:100*xs.filter(x=>x<70).length/xs.length,tbr54:100*xs.filter(x=>x<54).length/xs.length,cv:100*s/m,min:minOf(xs)});}return{mean:mean(rows.map(x=>x.mean)),tbr70:mean(rows.map(x=>x.tbr70)),tbr54:mean(rows.map(x=>x.tbr54)),cv:mean(rows.map(x=>x.cv)),noct70:100*n70/NEM,noct54:100*n54/NEM,deep70:100*d70/NEM,deep54:100*d54/NEM,below20_patient_pct:100*b20/NEM,below30_patient_pct:100*b30/NEM,below40_patient_pct:100*b40/NEM,mean_patient_min:mean(rows.map(x=>x.min))};}
const sh0=shanghai(ARMS[0]),rows=[];for(const a of ARMS){const sh=shanghai(a),ex=external(a),d={};for(const k of ['mean','tbr70','tbr54','tir','preB','preL','preD','delta120'])d[k]=sh[k]-sh0[k];const shGate=Math.abs(d.mean)<5&&Math.abs(d.preB)<5&&Math.abs(d.preL)<5&&Math.abs(d.preD)<5&&Math.abs(d.delta120)<2&&Math.abs(d.tbr70)<1&&Math.abs(d.tir)<3;const safetyGate=ex.below20_patient_pct<=1;rows.push({...a,shanghai:sh,delta_vs_legacy:d,shanghai_gate:shGate,safety_gate:safetyGate,external:ex});}
const out={definition:{model:'counterregulation-v2-egp',healthy_egp_increment_mg_kg_min:CR.HEALTHY_COUNTERREG_EGP_INCREMENT_MG_KG_MIN,glucose_distribution_volume_l_kg:CR.GLUCOSE_DISTRIBUTION_VOLUME_L_KG,healthy_max_drive_mg_dl_min:CR.maxDriveMgDlMin(),antecedent_hypo_reserve:CR.ANTECEDENT_HYPO_RESERVE,activation_widths_mg_dl:[5,10,20],selection_rule:'Widths are structural sensitivities. No Emory outcome may select an arm. Safety gate only rejects catastrophic depth.'},n:{shanghai:NSH,external:NEM},emory_reference:{mean:176.1,tbr70:4.5,tbr54:1.58,cv:32,noct70:41,noct54:26},rows};const dir='analysis/counterregulation_v2_egp';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Counterregulation V2 — physiology-grounded EGP audit','',`Independent anchors: healthy hypoglycemic glucose-production increment ${CR.HEALTHY_COUNTERREG_EGP_INCREMENT_MG_KG_MIN.toFixed(3)} mg/kg/min; glucose distribution volume ${CR.GLUCOSE_DISTRIBUTION_VOLUME_L_KG.toFixed(2)} L/kg; implied max drive ${CR.maxDriveMgDlMin().toFixed(3)} mg/dL/min. Antecedent hypoglycemia reserve ${CR.ANTECEDENT_HYPO_RESERVE.toFixed(2)} comes from a 32% reduction in Ra response. Widths 5/10/20 mg/dL are structural sensitivities and are not selected from Emory.','','| arm | Shanghai | safety<20 | mean | TBR<70 | TBR<54 | CV | noct<70 | noct<54 | 00–06<54 | <20pt | <30pt | <40pt |','|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows){const e=r.external;md.push(`| ${r.name} | ${r.shanghai_gate?'PASS':'FAIL'} | ${r.safety_gate?'PASS':'FAIL'} | ${e.mean.toFixed(1)} | ${e.tbr70.toFixed(2)}% | ${e.tbr54.toFixed(2)}% | ${e.cv.toFixed(1)}% | ${e.noct70.toFixed(1)}% | ${e.noct54.toFixed(1)}% | ${e.deep54.toFixed(1)}% | ${e.below20_patient_pct.toFixed(1)}% | ${e.below30_patient_pct.toFixed(1)}% | ${e.below40_patient_pct.toFixed(1)}% |`)}md.push('','Guardrails:','- External Emory values are descriptive only; do not choose activation width or reserve by closeness.','- Reject any arm failing Shanghai preservation or the pre-specified catastrophic-depth safety gate (>1% of patients <20 mg/dL).','- Do not add real-time rescue to blinded-CGM Emory validation.','- Do not change basal potency 0.20, glulisine PK, phenotype weights, or treatment policy to compensate.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
