#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const N=1800,gp=PK.get('glulisine'),profiles=['persistent_inflammatory','resolving_acute','moderate_stable'];
const arms=['current','lunch_unwind','all_unwind'];
const map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function tdd(o){return o.breakfast_u+o.lunch_u+o.dinner_u+o.basal_u}function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function makeTitrator(arm){const hist={pre_breakfast:[],pre_lunch:[],pre_dinner:[],bedtime:[]};return(order,summary)=>{const next=TP.componentTitrate(order,summary);for(const k of Object.values(map)){const v=Number(summary[k]);if(Number.isFinite(v))hist[k].push(v)}if(arm==='current')return next;for(const [comp,key] of Object.entries(map)){if(arm==='lunch_unwind'&&comp!=='lunch_u')continue;const h=hist[key];if(h.length<3)continue;const a=h[h.length-3],b=h[h.length-2],c=h[h.length-1];if(a>b&&b>c&&c<=180){next[comp]=Math.max(0,next[comp]-1)}}return next}}
function run(profile,arm){let p20=0,p54=0;const d8bg=[],d8tdd=[];for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tit=makeTitrator(arm);const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:tit,state_modifier_fn:({day})=>({...T.statePatch(profile,day,i),...B.statePatch(M,.20),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i);let a20=false,a54=false;for(const r of c.records){if(r.series.some(x=>x<20))a20=true;if(r.series.some(x=>x<54))a54=true}if(a20)p20++;if(a54)p54++;const r=c.records[c.records.length-1];d8bg.push(mean(r.series));d8tdd.push(tdd(r.order)/p.body_weight_kg)}return{profile,arm,below20_pct:100*p20/N,any54_pct:100*p54/N,d8_mean_bg:mean(d8bg),d8_tddkg:mean(d8tdd)}}
const rows=[];for(const p of profiles)for(const a of arms)rows.push(run(p,a));const out={purpose:'diagnostic observable-only trend de-escalation; not calibration',rule:'If the corresponding observed glucose falls strictly for 3 consecutive days and current value is <=180 mg/dL, subtract 1 U after applying the unchanged componentTitrate rule.',n_per_arm:N,rows};const dir='analysis/observable_trend_deescalation';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Observable trend de-escalation audit','','Diagnostic only. Hidden physiology and trajectory labels are not policy inputs. Existing componentTitrate thresholds/step sizes are unchanged.','','Rule: after unchanged titration, if the corresponding observed glucose has fallen strictly for 3 consecutive days and is now <=180 mg/dL, unwind 1 U for the guarded component.','','| profile | arm | patients <20 | any <54 | D8 mean BG | D8 TDD/kg |','|---|---|---:|---:|---:|---:|'];for(const r of rows)md.push(`| ${r.profile} | ${r.arm} | ${r.below20_pct.toFixed(1)}% | ${r.any54_pct.toFixed(1)}% | ${r.d8_mean_bg.toFixed(1)} | ${r.d8_tddkg.toFixed(3)} |`);md.push('','Guardrails:','- Diagnostic only; do not adopt from Emory-like closeness.','- Any candidate must pass Shanghai preservation before external revalidation.','- If all-component unwind causes broad hyperglycemic drift, prefer a narrower observable policy structure.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
