#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v2_egp_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV2EgpExp;
const N=1000,MODELS=[{name:'legacy',patch:()=>({})},{name:'v2_width5',patch:()=>CR.statePatch(M,{reserve:1,activation_width_mg_dl:5})}],ARMS=[
{name:'current',cfg:{}},
{name:'no_partial_meals',cfg:{partial_meal_probability:0}},
{name:'no_bolus_delay',cfg:{bolus_delay_max_min:0}},
{name:'no_partial_no_delay',cfg:{partial_meal_probability:0,bolus_delay_max_min:0}},
{name:'no_daily_titration',cfg:{titrate:false}},
{name:'no_meal_mismatch',cfg:{allow_meal_mismatch:false}}
];
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function run(model,arm){const gp=PK.get('glulisine'),rows=[];let b20=0,afternoon=0,late=0;for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(ord,bg)=>TP.componentTitrate(ord,bg),...arm.cfg,state_modifier_fn:({day})=>({...T.statePatch(tr,day,i),...B.statePatch(M,.20),...model.patch(p),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl)})};const c=C.simulateCourse(M,D,p,o,cfg,i),xs=[];let first=null;for(const r of c.records){for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);if(x<20&&!first)first={day:r.day,t};}}if(first){b20++;if(first.t>=780&&first.t<960)afternoon++;if(first.day>=6)late++;}const m=mean(xs),s=sd(xs);rows.push({mean:m,tbr54:100*xs.filter(x=>x<54).length/xs.length,cv:100*s/m});}return{model:model.name,arm:arm.name,mean:mean(rows.map(x=>x.mean)),tbr54:mean(rows.map(x=>x.tbr54)),cv:mean(rows.map(x=>x.cv)),below20_patient_pct:100*b20/N,first_below20_13_16_pct:b20?100*afternoon/b20:0,first_below20_day6_8_pct:b20?100*late/b20:0};}
const rows=[];for(const m of MODELS)for(const a of ARMS)rows.push(run(m,a));const out={purpose:'causal ablation of extreme <20 tail; no parameter selection',n:N,rows};const dir='analysis/extreme_hypoglycemia_mismatch_ablation';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Extreme hypoglycemia meal/treatment mismatch ablation','','Diagnostic factorial ablation only. No arm is eligible for calibration from Emory.','','| model | arm | mean | TBR<54 | CV | patients<20 | first<20 13–16 | first<20 D6–8 |','|---|---|---:|---:|---:|---:|---:|---:|'];for(const r of rows)md.push(`| ${r.model} | ${r.arm} | ${r.mean.toFixed(1)} | ${r.tbr54.toFixed(2)}% | ${r.cv.toFixed(1)}% | ${r.below20_patient_pct.toFixed(1)}% | ${r.first_below20_13_16_pct.toFixed(1)}% | ${r.first_below20_day6_8_pct.toFixed(1)}% |`);md.push('','Interpretation guardrails:','- A large fall in <20 after removing partial meals implicates nutrition-dose mismatch, not counterregulation gain.','- A large fall after disabling daily titration implicates treatment-lag/overshoot structure.','- Bolus delay is tested separately; do not infer causality from simple event co-occurrence.','- Do not choose any arm by Emory closeness or modify frozen basal potency/PK from this audit.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
