#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const N=5000,gp=PK.get('glulisine'),map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function persistentTitrator(order,bg){const next=TP.componentTitrate(order,bg),vals=Object.values(bg).map(Number).filter(Number.isFinite),nHigh=vals.filter(x=>x>=180).length;for(const [comp,key] of Object.entries(map)){const cur=Number(order[comp])||0,nxt=Number(next[comp])||0,signal=Number(bg[key]);if(nxt>cur&&!(Number.isFinite(signal)&&signal>=180&&nHigh>=2))next[comp]=cur;}return next}
function mealMatchedPatch({order,state}){const intake=state.intake_fraction||{},mealShift=state.meal_shift_min||{},bolusShift={...(state.bolus_shift_min||{})},bolusFraction={...(state.bolus_fraction||{})};for(const meal of ['breakfast','lunch','dinner']){const f=Number(intake[meal]);if(!Number.isFinite(f)||f>=.85)continue;const key=meal+'_u',ordered=Math.max(0,Math.round(Number(order[key])||0)),given=Math.max(0,Math.round(ordered*Math.max(0,Math.min(1,f))));bolusFraction[meal]=ordered>0?given/ordered:0;const ms=Number(mealShift[meal])||0;bolusShift[meal]=Math.max(Number(bolusShift[meal])||0,15+ms);}return{bolus_fraction:bolusFraction,bolus_shift_min:bolusShift};}
let n20=0;const ev=[];
for(let i=1;i<=N;i++){
 const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm}),tr=T.choose(i);
 const cfg={days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:persistentTitrator,state_modifier_fn:(ctx)=>({...T.statePatch(tr,ctx.day,i),...B.statePatch(M,.20),bedtime_correction_fn:({glucose_mg_dl})=>TP.emoryBedtimeCorrection(glucose_mg_dl),...mealMatchedPatch(ctx)})};
 const c=C.simulateCourse(M,D,p,o,cfg,i);let first=null;
 for(let ri=0;ri<c.records.length&&!first;ri++){const r=c.records[ri];for(let t=0;t<1440;t++){if(r.series[t]<20){first={ri,r,t};break;}}}
 if(!first)continue;n20++;
 const {ri,r,t}=first,prev=ri>0?c.records[ri-1]:null,prev2=ri>1?c.records[ri-2]:null;
 const prevBG=prev?.bg||{}, prev2BG=prev2?.bg||{}, curBG=r.bg||{};
 const priorDayMin=prev?Math.min(...prev.series):NaN;
 const priorDayAny70=Number.isFinite(priorDayMin)&&priorDayMin<70;
 const priorDayAny100=Number.isFinite(priorDayMin)&&priorDayMin<100;
 const preD1=Number(prevBG.pre_dinner),preD2=Number(prev2BG.pre_dinner);
 const preDDeclining2=Number.isFinite(preD1)&&Number.isFinite(preD2)&&preD1<preD2;
 const preDAtOrBelow180=Number.isFinite(preD1)&&preD1<=180;
 const preB=Number(curBG.pre_breakfast),preL=Number(curBG.pre_lunch);
 const morningAnyLt100=(Number.isFinite(preB)&&preB<100)||(Number.isFinite(preL)&&preL<100);
 const morningAnyLt140=(Number.isFinite(preB)&&preB<140)||(Number.isFinite(preL)&&preL<140);
 const lunchDose=Number(r.order.lunch_u)||0,prevLunch=Number(prev?.order?.lunch_u)||0;
 ev.push({patient:i,profile:tr,day:r.day,hour:Math.floor(t/60),prior_day_min:priorDayMin,prior_day_any_lt70:priorDayAny70,prior_day_any_lt100:priorDayAny100,prev_preD:preD1,prev2_preD:preD2,preD_declining_2day:preDDeclining2,prev_preD_le180:preDAtOrBelow180,current_preB:preB,current_preL:preL,morning_any_lt100:morningAnyLt100,morning_any_lt140:morningAnyLt140,lunch_u:lunchDose,prev_lunch_u:prevLunch,lunch_increased_vs_prev:lunchDose>prevLunch});
}
function pct(k){return n20?100*ev.filter(e=>e[k]).length/n20:0}
const out={purpose:'Observable precursor audit before residual first-<20 events under combined policy. Diagnostic only; no thresholds selected from outcomes.',n:N,patients_below20_pct:100*n20/N,event_count:n20,precursors:{prior_day_any_lt70_pct:pct('prior_day_any_lt70'),prior_day_any_lt100_pct:pct('prior_day_any_lt100'),preD_declining_2day_pct:pct('preD_declining_2day'),prev_preD_le180_pct:pct('prev_preD_le180'),morning_any_lt100_pct:pct('morning_any_lt100'),morning_any_lt140_pct:pct('morning_any_lt140'),lunch_increased_vs_prev_pct:pct('lunch_increased_vs_prev'),mean_prior_day_min:mean(ev.map(e=>e.prior_day_min).filter(Number.isFinite)),mean_prev_preD:mean(ev.map(e=>e.prev_preD).filter(Number.isFinite)),mean_current_preB:mean(ev.map(e=>e.current_preB).filter(Number.isFinite)),mean_current_preL:mean(ev.map(e=>e.current_preL).filter(Number.isFinite)),mean_lunch_u:mean(ev.map(e=>e.lunch_u))},events:ev};
const dir='analysis/combined_policy_residual_observable_precursors';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));
const p=out.precursors;const md=['# Combined-policy residual observable precursor audit','','Diagnostic only. All candidate warning signals are observable bedside data; trajectory labels are used only for post hoc grouping.','','Patients <20: '+out.patients_below20_pct.toFixed(2)+'% ('+n20+'/'+N+')','','| precursor before first <20 | prevalence among events |','|---|---:|',`| prior-day any glucose <70 | ${p.prior_day_any_lt70_pct.toFixed(1)}% |`,`| prior-day any glucose <100 | ${p.prior_day_any_lt100_pct.toFixed(1)}% |`,`| pre-dinner falling vs prior day | ${p.preD_declining_2day_pct.toFixed(1)}% |`,`| previous pre-dinner <=180 | ${p.prev_preD_le180_pct.toFixed(1)}% |`,`| event-day preB or preL <100 | ${p.morning_any_lt100_pct.toFixed(1)}% |`,`| event-day preB or preL <140 | ${p.morning_any_lt140_pct.toFixed(1)}% |`,`| lunch dose increased vs prior day | ${p.lunch_increased_vs_prev_pct.toFixed(1)}% |`,'',`Mean prior-day minimum: ${p.mean_prior_day_min.toFixed(1)}`,`Mean previous pre-dinner: ${p.mean_prev_preD.toFixed(1)}`,`Mean event-day pre-breakfast: ${p.mean_current_preB.toFixed(1)}`,`Mean event-day pre-lunch: ${p.mean_current_preL.toFixed(1)}`,`Mean event lunch dose: ${p.mean_lunch_u.toFixed(1)} U`,'','Guardrails:','- Do not convert the ADA 0.3–0.6 U/kg/day usual starting range into a hard safety cap.','- ADA 2026 states that a documented BG <70 mg/dL should trigger treatment-plan review and notes fasting BG <100 mg/dL predicts next-day hypoglycemia.','- Use this audit only to decide whether an observable de-intensification rule is justified.'];fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
