#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P1=T2DMPatientPhenotypeV1ShanghaiExp,P3=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const RP=.20,N_MECH=800,N_SH=3000;
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}
function mechanism(mult){const gp=PK.get('glulisine'),patient=[];for(let i=1;i<=N_MECH;i++){const p=P3.sample(i,{preset:'us_obese_inpatient_sensitivity'}),admission=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:admission});o.basal_u=Math.max(0,Math.round(o.basal_u*mult));const trajectory=T.choose(i),patch=B.statePatch(M,RP),cfg={days:8,titrate:false,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,steroid:false,admission_glucose_offset_mg_dl:0,initial_stress_severity:0,stress_daily_decay:0,state_modifier_fn:({day})=>({...T.statePatch(trajectory,day,i),...patch})};const c=C.simulateCourse(M,D,p,o,cfg,i),xs=[],nox=[];for(const rec of c.records)for(let t=0;t<1440;t+=15){xs.push(rec.series[t]);if(t<360)nox.push(rec.series[t]);}patient.push({mean:mean(xs),nocturnal54:nox.some(x=>x<54)});}return{mean:mean(patient.map(x=>x.mean)),nocturnal54:100*patient.filter(x=>x.nocturnal54).length/patient.length};}
function shanghai(){const DAYS=8,WARM=2,modes={legacy:{all:[],preB:[],preL:[],preD:[],d120:[]},candidate:{all:[],preB:[],preL:[],preD:[],d120:[]}};for(let i=1;i<=N_SH;i++){const p={...P1.sample(i)};p.dynamic_fasting_setpoint_mg_dl=Math.max(70,Math.min(260,122.8+(p.dynamic_fasting_setpoint_mg_dl-147)*(31.5/28)));p.fasting_setpoint_mg_dl=p.dynamic_fasting_setpoint_mg_dl;const base=M.suggestOrder(p,M.DEFAULT_MEALS),order={breakfast_u:base.breakfast_u,lunch_u:base.lunch_u,dinner_u:base.dinner_u,basal_u:Math.max(0,Math.round(.201*p.body_weight_kg))};for(const mode of Object.keys(modes)){let state=null;for(let d=0;d<DAYS;d++){const out=mode==='legacy'?M.simulateDay(p,order,{meal_plan_carb_g:M.DEFAULT_MEALS},i,state):D.simulateDay(M,p,order,{meal_plan_carb_g:M.DEFAULT_MEALS,...B.statePatch(M,RP)},i,state);state=out.next_state;if(d<WARM)continue;const s=out.series,q=modes[mode];for(let t=0;t<1440;t++)q.all.push(s[t]);q.preB.push(s[420]);q.preL.push(s[720]);q.preD.push(s[1080]);q.d120.push(s[600]-s[480]);}}}function sum(q){const pct=(a,f)=>100*a.filter(f).length/a.length;return{mean:mean(q.all),tbr:pct(q.all,x=>x<70),tir:pct(q.all,x=>x>=70&&x<=180),preB:mean(q.preB),preL:mean(q.preL),preD:mean(q.preD),delta120:mean(q.d120)}}const a=sum(modes.legacy),b=sum(modes.candidate),d={};for(const k of Object.keys(a))d[k]=b[k]-a[k];return{legacy:a,candidate:b,delta:d};}
const low=mechanism(.8),high=mechanism(1.2),s=shanghai(),slope=low.mean-high.mean;const checks={mechanism:slope>5,nocturnal_direction:high.nocturnal54>=low.nocturnal54,sh_mean:Math.abs(s.delta.mean)<5,sh_preB:Math.abs(s.delta.preB)<5,sh_preL:Math.abs(s.delta.preL)<5,sh_preD:Math.abs(s.delta.preD)<5,sh_delta120:Math.abs(s.delta.delta120)<2,sh_tbr:Math.abs(s.delta.tbr)<1,sh_tir:Math.abs(s.delta.tir)<3};const pass=Object.values(checks).every(Boolean),out={relative_potency:RP,derived_daily_gain:B.unitConsistentDailyGain(M,RP),n:{mechanism:N_MECH,shanghai:N_SH},mechanism:{low_basal_08:low,high_basal_12:high,mean_slope_08_to_12:slope},shanghai:s,checks,pass};const dir='analysis/basal_relative_potency_020_confirmation';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));const d=s.delta,md=['# Basal relative potency 0.20 large-N confirmation','',`N mechanism=${N_MECH}, Shanghai=${N_SH}. Candidate was chosen before this run as the weakest positive coarse-screen candidate satisfying all pre-specified constraints. Emory outcomes are not used here.`,'',`Derived gain: ${out.derived_daily_gain.toFixed(2)} mg/dL-equivalent/U/day at SI=1.`,`Mechanism mean slope (basal 0.8→1.2): ${slope.toFixed(2)} mg/dL.`,`Nocturnal <54 incidence: ${low.nocturnal54.toFixed(2)}% → ${high.nocturnal54.toFixed(2)}%.`,'',`Shanghai deltas: mean ${d.mean.toFixed(2)}, TBR ${d.tbr.toFixed(2)} pp, TIR ${d.tir.toFixed(2)} pp, preB/L/D ${d.preB.toFixed(2)}/${d.preL.toFixed(2)}/${d.preD.toFixed(2)}, Δ120 ${d.delta120.toFixed(2)}.`,'','## Checks'];for(const [k,v] of Object.entries(checks))md.push(`- ${v?'PASS':'FAIL'} — ${k}`);md.push('',pass?'**CONFIRMED: relative potency 0.20 is admissible and may be frozen before external re-validation.**':'**NOT CONFIRMED: do not promote 0.20.**');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));if(!pass)process.exitCode=2;
