#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_poc_safety_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_basal_potency_prior_exp.js','t2dm_counterregulation_v2_egp_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV1ShanghaiExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1PocSafetyExp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,B=InsulinBasalPotencyPriorExp,CR=T2DMCounterregulationV2EgpExp;
const N=5000,map={basal_u:'pre_breakfast',breakfast_u:'pre_lunch',lunch_u:'pre_dinner',dinner_u:'bedtime'};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function persistent2of4(order,bg){const next=TP.componentTitrate(order,bg),vals=Object.values(bg).map(Number).filter(Number.isFinite),nHigh=vals.filter(x=>x>=180).length;for(const [comp,key] of Object.entries(map)){const cur=Number(order[comp])||0,nxt=Number(next[comp])||0,signal=Number(bg[key]);if(nxt>cur&&!(Number.isFinite(signal)&&signal>=180&&nHigh>=2))next[comp]=cur;}return next}
function safetyOverride({poc_glucose_mg_dl,planned_units}){const bg=Number(poc_glucose_mg_dl),u=Math.max(0,Math.round(Number(planned_units)||0));if(bg<70)return Math.max(0,u-2);if(bg<100)return Math.max(0,u-1);return u;}
function run(arm){const all=[],preB=[],preL=[],preD=[],d120=[];let tbr70=0,tir=0,total=0;for(let i=1;i<=N;i++){const p=P.sample(i),adm=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:adm});const current=arm==='current',cr=arm==='cr_width10';const cfg={days:8,titrate:true,allow_meal_mismatch:false,allow_npo:false,bolus_tau_min:90,bolus_duration_min:330,titrate_order_fn:current?((ord,bg)=>TP.componentTitrate(ord,bg)):persistent2of4,state_modifier_fn:()=>({...B.statePatch(M,.20),...(cr?CR.statePatch(M,{reserve:1,activation_width_mg_dl:10}):{}),...(current?{}:{prandial_safety_adjustment_fn:safetyOverride})})};const c=C.simulateCourse(M,D,p,o,cfg,i);for(let d=2;d<c.records.length;d++){const r=c.records[d];for(let t=0;t<1440;t++){const x=r.series[t];all.push(x);total++;if(x<70)tbr70++;if(x>=70&&x<=180)tir++;}preB.push(r.series[420]);preL.push(r.series[720]);preD.push(r.series[1080]);d120.push(r.series[600]-r.series[480]);}}
return{arm,mean:mean(all),preB:mean(preB),preL:mean(preL),preD:mean(preD),delta120:mean(d120),tbr70:100*tbr70/total,tir:100*tir/total};}
const rows=[run('current'),run('combined_legacy'),run('cr_width10')],ref=rows[0],cand=rows[2],delta={};for(const k of ['mean','preB','preL','preD','delta120','tbr70','tir'])delta[k]=cand[k]-ref[k];const gate=Math.abs(delta.mean)<5&&Math.abs(delta.preB)<5&&Math.abs(delta.preL)<5&&Math.abs(delta.preD)<5&&Math.abs(delta.delta120)<2&&Math.abs(delta.tbr70)<1&&Math.abs(delta.tir)<3;
const out={purpose:'High-N confirmatory Shanghai preservation for the pre-specified counterregulation V2 width10 healthy-reserve primary arm after safer policy. Gate unchanged; no thresholds or parameters are retuned.',n:N,rows,delta_candidate_vs_current:delta,gate};const dir='analysis/counterregulation_v2_shanghai_highn';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(out,null,2));let md=['# Counterregulation V2 Shanghai high-N confirmation','',`N=${N}, 8 days, analyze days 3–8. Gate unchanged.`,'','| arm | mean | preB | preL | preD | Δ120 | TBR<70 | TIR |','|---|---:|---:|---:|---:|---:|---:|---:|'];for(const r of rows)md.push(`| ${r.arm} | ${r.mean.toFixed(2)} | ${r.preB.toFixed(2)} | ${r.preL.toFixed(2)} | ${r.preD.toFixed(2)} | ${r.delta120.toFixed(2)} | ${r.tbr70.toFixed(3)}% | ${r.tir.toFixed(3)}% |`);md.push('',`Formal Shanghai gate: **${gate?'PASS':'FAIL'}**`,`Δmean ${delta.mean.toFixed(3)}, ΔpreB ${delta.preB.toFixed(3)}, ΔpreL ${delta.preL.toFixed(3)}, ΔpreD ${delta.preD.toFixed(3)}, Δ120 ${delta.delta120.toFixed(3)}, ΔTBR ${delta.tbr70.toFixed(3)}pp, ΔTIR ${delta.tir.toFixed(3)}pp`,'','Guardrail: this is replication only. Do not relax the ±3pp TIR gate or retune counterregulation width/reserve.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));if(!gate)process.exitCode=2;
