const fs=require('fs'),vm=require('vm');
global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_game_model_v2_order_decomp_exp.js']) vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=global.T2DMPatientPhenotypeV1ShanghaiExp,M=global.T2DMGameModelV2OrderDecompExp;
function hash32(x){let h=2166136261>>>0;for(const c of String(x)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=hash32(seed);return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function randn(r){let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function logMult(r,cv){if(cv<=0)return 1;const s2=Math.log(1+cv*cv),s=Math.sqrt(s2),mu=-.5*s2;return Math.exp(mu+s*randn(r))}
function mean(a){return a.reduce((x,y)=>x+y,0)/a.length}
function sd(a){const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/a.length)}
function gamma1(dt,tau){return (dt/tau)*Math.exp(1-dt/tau)}
function kernelArea(tau,dur=330){let a=0;for(let dt=0;dt<dur;dt++)a+=gamma1(dt,tau);return a}
const PROXY_CV={breakfast:75.98621722681969/115.40601503759399,lunch:100.68674533159886/121.1217162872154,dinner:80.71613119459934/109.88185654008439};
const CFG={eq_center:147,eq_sd:35,coverage:.80,meal_var_scale:.55,bolus_mismatch_sd:.10};
const target={mean:164.3,sd:57.6,tbr:1.51,tir:61.62,tar:36.88,Bm:147.7,Bsd:35.4,Lm:156.7,Lsd:67.6,Dm:171.9,Dsd:65.0,d120m:44.4,d120sd:28.1};
function simulateDay(p,order,meal,state,mealTau,bolusTau){const n=1441,g=new Float64Array(n),eq=p.dynamic_fasting_setpoint_mg_dl;g[0]=state??eq;const mr=M.mealResponseMultiplier(p);const refBas=M.maintenanceBasalReference(p);const me=[[480,meal.breakfast],[780,meal.lunch],[1140,meal.dinner]],bo=[[465,order.breakfast_u],[765,order.lunch_u],[1125,order.dinner_u]];for(let t=0;t<n-1;t++){let md=0,bd=0;for(const [tm,c] of me){const dt=t-tm;if(dt>=0&&dt<330)md+=c*gamma1(dt,mealTau)*M.SCALE.meal_gain*mr}for(const [tb,u] of bo){const dt=t-tb;if(dt>=0&&dt<330)bd+=u*gamma1(dt,bolusTau)*M.SCALE.bolus_gain*p.si_relative}const basal=(order.basal_u-refBas)/1440*M.SCALE.basal_delta_gain*p.si_relative,restore=-M.SCALE.restore_gain*(g[t]-eq);g[t+1]=g[t]+md-bd-basal+restore;}return g}
function evalCfg(mealTau,bolusTau,N=800,DAYS=8){let vals=[],B=[],L=[],Dn=[],pmeans=[],lo=0,hi=0,total=0;const mealArea=kernelArea(mealTau),bolusArea=kernelArea(bolusTau),balance=(M.SCALE.meal_gain*mealArea)/(M.SCALE.bolus_gain*bolusArea);for(let i=1;i<=N;i++){const p={...P.sample(i)};p.dynamic_fasting_setpoint_mg_dl=Math.max(75,Math.min(260,CFG.eq_center+(p.dynamic_fasting_setpoint_mg_dl-147)*(CFG.eq_sd/28)));p.fasting_setpoint_mg_dl=p.dynamic_fasting_setpoint_mg_dl;const mr=M.mealResponseMultiplier(p),uPerG=CFG.coverage*balance*mr/p.si_relative;base={breakfast_u:Math.max(0,Math.round(50*uPerG)),lunch_u:Math.max(0,Math.round(70*uPerG)),dinner_u:Math.max(0,Math.round(60*uPerG)),basal_u:M.maintenanceBasalReference(p)};let state=null,ds=[];const r=rng(`k:${mealTau}:${bolusTau}:${i}`);for(let d=0;d<DAYS;d++){const meal={breakfast:50*logMult(r,PROXY_CV.breakfast*CFG.meal_var_scale),lunch:70*logMult(r,PROXY_CV.lunch*CFG.meal_var_scale),dinner:60*logMult(r,PROXY_CV.dinner*CFG.meal_var_scale)};const order={...base};for(const k of ['breakfast','lunch','dinner'])order[k+'_u']=Math.max(0,Math.round(base[k+'_u']*(1+CFG.bolus_mismatch_sd*randn(r))));const g=simulateDay(p,order,meal,state,mealTau,bolusTau);state=g[1440];if(d>=2){for(let t=0;t<g.length;t+=5){const x=g[t];vals.push(x);if(x<70)lo++;if(x>180)hi++;total++;}B.push(g[420]);L.push(g[720]);Dn.push(g[1080]);ds.push(g[600]-g[480]);}}pmeans.push(mean(ds));}
const out={meal_tau:mealTau,bolus_tau:bolusTau,mean:mean(vals),sd:sd(vals),tbr:100*lo/total,tar:100*hi/total};out.tir=100-out.tbr-out.tar;Object.assign(out,{B_mean:mean(B),B_sd:sd(B),L_mean:mean(L),L_sd:sd(L),D_mean:mean(Dn),D_sd:sd(Dn),d120_mean:mean(pmeans),d120_between_sd:sd(pmeans)});out.score=Math.abs(out.mean-target.mean)/4+Math.abs(out.sd-target.sd)/5+Math.abs(out.tbr-target.tbr)+Math.abs(out.tar-target.tar)/4+Math.abs(out.B_mean-target.Bm)/5+Math.abs(out.B_sd-target.Bsd)/5+Math.abs(out.L_mean-target.Lm)/6+Math.abs(out.L_sd-target.Lsd)/8+Math.abs(out.D_mean-target.Dm)/6+Math.abs(out.D_sd-target.Dsd)/8+Math.abs(out.d120_mean-target.d120m)/6+Math.abs(out.d120_between_sd-target.d120sd)/6;return out}
let results=[];for(const mt of [50,55,60,65,70])for(const bt of [120,135,150,165])results.push(evalCfg(mt,bt));results.sort((a,b)=>a.score-b.score);fs.mkdirSync('analysis/basal_bolus_kernel_24h',{recursive:true});fs.writeFileSync('analysis/basal_bolus_kernel_24h/results.json',JSON.stringify({cfg:CFG,target,results},null,2));let md='# Basal-bolus 24h kernel grid\n\n';for(const x of results){md+=`- mealTau ${x.meal_tau}, bolusTau ${x.bolus_tau}: score ${x.score.toFixed(2)}; pooled ${x.mean.toFixed(1)}±${x.sd.toFixed(1)}, TBR ${x.tbr.toFixed(2)}%, TIR ${x.tir.toFixed(2)}%, TAR ${x.tar.toFixed(2)}%; pre B/L/D ${x.B_mean.toFixed(1)}±${x.B_sd.toFixed(1)} / ${x.L_mean.toFixed(1)}±${x.L_sd.toFixed(1)} / ${x.D_mean.toFixed(1)}±${x.D_sd.toFixed(1)}; Δ120 ${x.d120_mean.toFixed(1)}±between ${x.d120_between_sd.toFixed(1)}\n`;}
fs.writeFileSync('analysis/basal_bolus_kernel_24h/report.md',md);console.log(md);