#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_renal_insulin_modifier_v1_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,R=T2DMRenalInsulinModifierV1Exp;
const TARGET={mean:176.1,tir:53.5,tar:42.2,tbr:4.5,cv:32.0};
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function metrics(xs){const m=mean(xs),s=sd(xs);return{mean:m,tir:100*xs.filter(x=>x>=70&&x<=180).length/xs.length,tar:100*xs.filter(x=>x>180).length/xs.length,tbr:100*xs.filter(x=>x<70).length/xs.length,cv:100*s/m}}
function courseMetrics(c){const xs=[];for(const r of c.records)for(let t=0;t<=1440;t+=15)xs.push(r.series[t]);return metrics(xs)}
function config(useRenal){const gp=PK.get('glulisine');return{days:8,titrate:true,admission_glucose_offset_mg_dl:120,initial_stress_severity:.70,stress_daily_decay:.10,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(o,bg)=>TP.proportionalTitrate(o,bg),state_modifier_fn:useRenal?(({patient})=>({insulin_exposure_multiplier:R.exposureMultiplier(patient)})):null};}
function run(useRenal){const N=1600,all=[],by={};for(const k of Object.keys(P.DEFAULT_WEIGHTS))by[k]=[];for(let i=1;i<=N;i++){
 const p=P.sample(i),admissionBg=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),order=TP.startingOrder(p,{admission_bg_mg_dl:admissionBg}),course=C.simulateCourse(M,D,p,order,config(useRenal),i),m=courseMetrics(course);all.push({p,m,order});by[p.patient_archetype].push({p,m,order});}
 function summarise(rows){const mm=rows.map(x=>x.m),tdd=rows.map(x=>(x.order.breakfast_u+x.order.lunch_u+x.order.dinner_u+x.order.basal_u)/x.p.body_weight_kg);return{n:rows.length,mean:mean(mm.map(x=>x.mean)),tir:mean(mm.map(x=>x.tir)),tar:mean(mm.map(x=>x.tar)),tbr:mean(mm.map(x=>x.tbr)),cv:mean(mm.map(x=>x.cv)),initial_tdd_kg:mean(tdd),bmi:mean(rows.map(x=>x.p.bmi_kg_m2)),si:mean(rows.map(x=>x.p.si_relative)),egfr:mean(rows.map(x=>x.p.egfr_ml_min_1_73m2)),fpg:mean(rows.map(x=>x.p.observed_fasting_glucose_mg_dl))};}
 const result={pooled:summarise(all),archetypes:{}};for(const [k,v] of Object.entries(by))result.archetypes[k]=summarise(v);return result;}
const off=run(false),on=run(true),results={target:TARGET,version:P.version,renal_modifier:{off,on}};
const dir='analysis/emory_v3_inpatient_mix';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(results,null,2));
let md=['# Emory external validation — V3 heterogeneous inpatient phenotype','','This is an external sensitivity test, not a fit. Patient physiology is broadened first; treatment policy sees observable data only. Glulisine uses the literature-prior midpoint. The renal modifier is compared OFF vs ON; eGFR>=60 leaves insulin exposure unchanged. Emory excluded severe renal disease, so renal ON is a directional specificity test rather than an attempt to improve pooled Emory fit.','','External target: mean 176.1, TIR 53.5%, TAR 42.2%, TBR 4.5%, CV 32.0%.'];
function block(label,res){md+=['',`## ${label}`,'','| group | n | BMI | SI | eGFR | FPG | initial TDD/kg | mean | TIR | TAR | TBR | CV |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];function row(name,x){return `| ${name} | ${x.n} | ${x.bmi.toFixed(1)} | ${x.si.toFixed(2)} | ${x.egfr.toFixed(0)} | ${x.fpg.toFixed(0)} | ${x.initial_tdd_kg.toFixed(3)} | ${x.mean.toFixed(1)} | ${x.tir.toFixed(1)}% | ${x.tar.toFixed(1)}% | ${x.tbr.toFixed(2)}% | ${x.cv.toFixed(1)}% |`};md.push(row('pooled',res.pooled));for(const [k,x] of Object.entries(res.archetypes))md.push(row(k,x));}
block('Renal modifier OFF',off);block('Renal modifier ON',on);
md+=['','## Renal directional deltas',''];for(const k of Object.keys(on.archetypes)){const a=off.archetypes[k],b=on.archetypes[k];md.push(`- ${k}: mean ${(b.mean-a.mean).toFixed(1)}, TBR ${(b.tbr-a.tbr).toFixed(2)} pp, CV ${(b.cv-a.cv).toFixed(1)} pp`)}
md+=['','## Guardrails','- DEFAULT_WEIGHTS are sensitivity weights, not prevalence estimates.','- Do not tune archetype weights to match Emory glucose outcomes.','- Renal modifier is retained only if CKD moves preferentially toward greater insulin exposure/hypoglycemia while eGFR>=60 groups remain nearly unchanged.','- Generic glucose noise remains off.'];
fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
