#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV2Shanghai106Exp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp;
const TARGET={mean:176.1,tir:53.5,tar:42.2,tbr:4.5,cv:32.0};
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function metrics(xs){const m=mean(xs),s=sd(xs);return{mean:m,tir:100*xs.filter(x=>x>=70&&x<=180).length/xs.length,tar:100*xs.filter(x=>x>180).length/xs.length,tbr:100*xs.filter(x=>x<70).length/xs.length,cv:100*s/m}}
function courseMetrics(c){const xs=[];for(const r of c.records)for(let t=0;t<=1440;t+=15)xs.push(r.series[t]);return metrics(xs)}
function cfg(){const gp=PK.get('glulisine');return{days:8,titrate:true,admission_glucose_offset_mg_dl:140,initial_stress_severity:.85,stress_daily_decay:.10,allow_meal_mismatch:true,partial_meal_probability:.20,meal_shift_max_min:30,bolus_delay_max_min:40,underbolus_probability:.12,allow_npo:true,npo_day_probability:.10,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min};}
function run(kind,n=1200){const pm=[],tdds=[];for(let i=1;i<=n;i++){const p=P.sample(i);const admissionBg=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl));const order=kind==='oracle'?M.suggestOrder(p):TP.startingOrder(p,{admission_bg_mg_dl:admissionBg});tdds.push((order.breakfast_u+order.lunch_u+order.dinner_u+order.basal_u)/p.body_weight_kg);const c=C.simulateCourse(M,D,p,order,cfg(),i);pm.push(courseMetrics(c));}return{kind,n,initial_tdd_kg:mean(tdds),mean:mean(pm.map(x=>x.mean)),tir:mean(pm.map(x=>x.tir)),tar:mean(pm.map(x=>x.tar)),tbr:mean(pm.map(x=>x.tbr)),cv:mean(pm.map(x=>x.cv))};}
const results=[run('oracle'),run('physiology_blind')];
const dir='analysis/emory_policy_decoupling';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify({target:TARGET,results},null,2));
let md=['# Emory external validation — treatment-policy decoupling','','The only change compared with the oracle reference is how the initial order is generated. Physiology-blind policy uses observable weight, age, eGFR and admission glucose only; hidden SI, beta-cell reserve and hepatic IR are unavailable to the prescribing policy. Core physiology is unchanged. Glulisine uses the literature-prior midpoint (65/270), not an Emory-fitted coordinate.','',`Target: mean ${TARGET.mean}, TIR ${TARGET.tir}%, TAR ${TARGET.tar}%, TBR ${TARGET.tbr}%, CV ${TARGET.cv}%.`,'','| policy | initial TDD/kg | mean | TIR | TAR | TBR | CV |','|---|---:|---:|---:|---:|---:|---:|'];for(const x of results)md.push(`| ${x.kind} | ${x.initial_tdd_kg.toFixed(3)} | ${x.mean.toFixed(1)} | ${x.tir.toFixed(1)}% | ${x.tar.toFixed(1)}% | ${x.tbr.toFixed(2)}% | ${x.cv.toFixed(1)}% |`);md+=['','## Guardrail','- Do not tune the physiology-blind policy to the Emory outcome distribution here.','- A useful decoupling should allow hidden insulin resistance to produce harder glycemia rather than being automatically cancelled by an oracle dose.','- Generic glucose noise remains off.'];fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
