#!/usr/bin/env node
'use strict';
const fs=require('fs'),vm=require('vm');global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_patient_phenotype_v3_inpatient_mix_exp.js','t2dm_game_model_v2_order_decomp_exp.js','t2dm_inpatient_dynamic_v1_exp.js','t2dm_inpatient_course_v1_exp.js','t2dm_treatment_policy_weight_bg_exp.js','insulin_prandial_pk_prior_ranges_exp.js','t2dm_inpatient_trajectory_v1_exp.js','insulin_basal_potency_prior_exp.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const P=T2DMPatientPhenotypeV3InpatientMixExp,M=T2DMGameModelV2OrderDecompExp,D=T2DMInpatientDynamicV1Exp,C=T2DMInpatientCourseV1Exp,TP=T2DMTreatmentPolicyWeightBgExp,PK=InsulinPrandialPkPriorRangesExp,T=T2DMInpatientTrajectoryV1Exp,B=InsulinBasalPotencyPriorExp;
const RP=.20,N=1200,TARGET={mean:176.1,tir:53.5,tar:42.2,tar250:16.1,tbr70:4.5,tbr54:1.58,cv:32,any70:56,any54:36,nocturnal54:26};
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function baseConfig(useBasal,trajectory,seed){const gp=PK.get('glulisine');return{days:8,titrate:true,allow_meal_mismatch:true,partial_meal_probability:.14,meal_shift_max_min:25,bolus_delay_max_min:30,underbolus_probability:.08,allow_npo:true,npo_day_probability:.06,bolus_tau_min:gp.candidate.tau_min,bolus_duration_min:gp.candidate.duration_min,titrate_order_fn:(o,bg)=>TP.componentTitrate(o,bg),steroid:false,admission_glucose_offset_mg_dl:0,initial_stress_severity:0,stress_daily_decay:0,state_modifier_fn:({day})=>({...T.statePatch(trajectory,day,seed),...(useBasal?B.statePatch(M,RP):{})})};}
function patientMetrics(c){const xs=[],nox=[];for(const r of c.records)for(let t=0;t<1440;t+=15){const x=r.series[t];xs.push(x);if(t<360)nox.push(x);}const m=mean(xs),s=sd(xs);return{mean:m,tir:100*xs.filter(x=>x>=70&&x<=180).length/xs.length,tar:100*xs.filter(x=>x>180).length/xs.length,tar250:100*xs.filter(x=>x>250).length/xs.length,tbr70:100*xs.filter(x=>x<70).length/xs.length,tbr54:100*xs.filter(x=>x<54).length/xs.length,cv:100*s/m,any70:xs.some(x=>x<70),any54:xs.some(x=>x<54),nocturnal54:nox.some(x=>x<54)};}
function run(useBasal){const rows=[],hourly=Array.from({length:24},()=>({n:0,lt70:0,lt54:0})),daily=Array.from({length:8},()=>[]);for(let i=1;i<=N;i++){const p=P.sample(i,{preset:'us_obese_inpatient_sensitivity'}),admission=Math.max(70,Math.min(400,p.observed_fasting_glucose_mg_dl)),o=TP.startingOrder(p,{admission_bg_mg_dl:admission}),trajectory=T.choose(i),c=C.simulateCourse(M,D,p,o,baseConfig(useBasal,trajectory,i),i),m=patientMetrics(c);rows.push({p,m,trajectory,c});for(let d=0;d<8;d++){for(let t=0;t<1440;t+=15){const x=c.records[d].series[t],h=Math.floor(t/60),q=hourly[h];q.n++;if(x<70)q.lt70++;if(x<54)q.lt54++;daily[d].push(x);}}}
 const ms=rows.map(r=>r.m),pooled={n:N,mean:mean(ms.map(x=>x.mean)),tir:mean(ms.map(x=>x.tir)),tar:mean(ms.map(x=>x.tar)),tar250:mean(ms.map(x=>x.tar250)),tbr70:mean(ms.map(x=>x.tbr70)),tbr54:mean(ms.map(x=>x.tbr54)),cv:mean(ms.map(x=>x.cv)),any70:100*ms.filter(x=>x.any70).length/N,any54:100*ms.filter(x=>x.any54).length/N,nocturnal54:100*ms.filter(x=>x.nocturnal54).length/N};
 return{pooled,hourly:hourly.map((q,h)=>({hour:h,tbr70:100*q.lt70/q.n,tbr54:100*q.lt54/q.n})),daily:daily.map((xs,d)=>({day:d+1,mean:mean(xs),tbr70:100*xs.filter(x=>x<70).length/xs.length,tbr54:100*xs.filter(x=>x<54).length/xs.length,tar:100*xs.filter(x=>x>180).length/xs.length}))};}
const off=run(false),on=run(true),result={target:TARGET,n:N,basal_relative_potency:RP,derived_gain:B.unitConsistentDailyGain(M,RP),off,on};const dir='analysis/emory_frozen_basal_020';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/results.json',JSON.stringify(result,null,2));function row(name,x){return `| ${name} | ${x.mean.toFixed(1)} | ${x.tir.toFixed(1)}% | ${x.tar.toFixed(1)}% | ${x.tar250.toFixed(1)}% | ${x.tbr70.toFixed(2)}% | ${x.tbr54.toFixed(2)}% | ${x.cv.toFixed(1)}% | ${x.any70.toFixed(1)}% | ${x.any54.toFixed(1)}% | ${x.nocturnal54.toFixed(1)}% |`}
const md=['# Emory external re-validation — frozen basal potency 0.20','','The basal candidate was frozen before this run using only mechanism responsiveness and Shanghai preservation. Same phenotype preset, stress trajectories, treatment policy, glulisine prior and meal/NPO environment in both arms. Renal modifier and steroids are OFF.','','| arm | mean | TIR | TAR | >250 | TBR<70 | TBR<54 | CV | any<70 | any<54 | nocturnal<54 |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|',row('basal prior OFF',off.pooled),row('frozen basal 0.20',on.pooled),'','## Hourly TBR <54','','| hour | OFF | basal 0.20 |','|---:|---:|---:|'];for(let h=0;h<24;h++)md.push(`| ${String(h).padStart(2,'0')}:00 | ${off.hourly[h].tbr54.toFixed(3)}% | ${on.hourly[h].tbr54.toFixed(3)}% |`);md.push('','## Daily course','','| day | OFF mean | ON mean | OFF TBR<70 | ON TBR<70 | OFF TBR<54 | ON TBR<54 | OFF TAR | ON TAR |','|---:|---:|---:|---:|---:|---:|---:|---:|---:|');for(let d=0;d<8;d++){const a=off.daily[d],b=on.daily[d];md.push(`| ${d+1} | ${a.mean.toFixed(1)} | ${b.mean.toFixed(1)} | ${a.tbr70.toFixed(2)}% | ${b.tbr70.toFixed(2)}% | ${a.tbr54.toFixed(2)}% | ${b.tbr54.toFixed(2)}% | ${a.tar.toFixed(1)}% | ${b.tar.toFixed(1)}% |`);}md.push('','## Interpretation guardrail','- Do not change relative potency 0.20 based on this Emory result.','- If nocturnal hypoglycemia remains far below the observed 26% patient incidence, the next mechanism must address basal/fasting temporal structure rather than increasing this frozen scalar.');fs.writeFileSync(dir+'/report.md',md.join('\n')+'\n');console.log(md.join('\n'));
