const fs=require('fs'),vm=require('vm');
global.window=global;
for(const f of ['t2dm_patient_phenotype_v1_shanghai_exp.js','t2dm_patient_phenotype_v2_shanghai106_exp.js','t2dm_game_model_v2_order_decomp_exp.js']) vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const M=global.T2DMGameModelV2OrderDecompExp;
function hash32(x){let h=2166136261>>>0;for(const c of String(x)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=hash32(seed);return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function randn(r){let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function logMult(r,cv){if(cv<=0)return 1;const s2=Math.log(1+cv*cv),s=Math.sqrt(s2),mu=-.5*s2;return Math.exp(mu+s*randn(r))}
function stat(a){const n=a.length,m=a.reduce((x,y)=>x+y,0)/n,s=Math.sqrt(a.reduce((x,y)=>x+(y-m)*(y-m),0)/n);return{n,mean:m,sd:s}}
const PROXY_CV={breakfast:75.98621722681969/115.40601503759399,lunch:100.68674533159886/121.1217162872154,dinner:80.71613119459934/109.88185654008439};
const BASECFG={breakfast:0.45,lunch:0.20,dinner:0.20,mismatch_sd:0.10};
function run(si_cv,N=1600,days=6){let vals=[],slots={breakfast:[],lunch:[],dinner:[]},low=0,high=0,total=0;for(let i=1;i<=N;i++){const p0=T2DMPatientPhenotypeV2Shanghai106Exp.sample(i),nom={...M.DEFAULT_MEALS},base=M.suggestOrder(p0,nom);let state=null;const r=rng('dsi:'+si_cv+':'+i);for(let d=0;d<days;d++){const meal={};for(const k of ['breakfast','lunch','dinner'])meal[k]=nom[k]*logMult(r,PROXY_CV[k]*BASECFG[k]);const order={...base};for(const k of ['breakfast','lunch','dinner']){const key=k+'_u';order[key]=Math.max(0,Math.round(order[key]*(1+BASECFG.mismatch_sd*randn(r))))}const p={...p0,si_relative:Math.max(0.20,Math.min(1.80,p0.si_relative*logMult(r,si_cv)))};const out=M.simulateDay(p,order,{meal_plan_carb_g:meal},i,state);state=out.next_state;if(d>=2){for(let t=0;t<out.series.length;t+=5){const g=out.series[t];vals.push(g);if(g<70)low++;if(g>180)high++;total++}slots.breakfast.push(out.bg.pre_breakfast);slots.lunch.push(out.bg.pre_lunch);slots.dinner.push(out.bg.pre_dinner)}}}const s=stat(vals);return{si_cv,pooled:{mean:s.mean,sd:s.sd,tbr:100*low/total,tir:100*(total-low-high)/total,tar:100*high/total},slots:{breakfast:stat(slots.breakfast),lunch:stat(slots.lunch),dinner:stat(slots.dinner)}}}
const target={pooled:{mean:138.9854,sd:49.6216,tbr:2.3155,tir:79.5993,tar:18.0852},slots:{breakfast:{mean:131.9034,sd:35.5345},lunch:{mean:133.1606,sd:50.8746},dinner:{mean:136.1030,sd:48.8568}}};
const results=[0,.03,.05,.075,.10,.125,.15,.175,.20].map(run);
for(const x of results){const p=x.pooled,s=x.slots;x.score=Math.abs(p.mean-target.pooled.mean)/5+Math.abs(p.sd-target.pooled.sd)/7+Math.abs(p.tbr-target.pooled.tbr)/1.5+Math.abs(p.tir-target.pooled.tir)/5+Math.abs(s.breakfast.sd-target.slots.breakfast.sd)/6+Math.abs(s.lunch.sd-target.slots.lunch.sd)/7+Math.abs(s.dinner.sd-target.slots.dinner.sd)/7+Math.abs(s.lunch.mean-target.slots.lunch.mean)/8+Math.abs(s.dinner.mean-target.slots.dinner.mean)/8}
results.sort((a,b)=>a.score-b.score);
fs.mkdirSync('analysis/t2dm_v2_day_si',{recursive:true});fs.writeFileSync('analysis/t2dm_v2_day_si/results.json',JSON.stringify({target,base_cfg:BASECFG,proxy_cv:PROXY_CV,results},null,2));let md='# T2DM v2 day-level SI calibration\n\n';for(const x of results){md+=`- SI CV ${(100*x.si_cv).toFixed(1)}%: score ${x.score.toFixed(2)}; pooled ${x.pooled.mean.toFixed(1)}±${x.pooled.sd.toFixed(1)}, TBR ${x.pooled.tbr.toFixed(2)}%, TIR ${x.pooled.tir.toFixed(2)}%, TAR ${x.pooled.tar.toFixed(2)}%; premeal mean B/L/D ${x.slots.breakfast.mean.toFixed(1)}/${x.slots.lunch.mean.toFixed(1)}/${x.slots.dinner.mean.toFixed(1)}; SD ${x.slots.breakfast.sd.toFixed(1)}/${x.slots.lunch.sd.toFixed(1)}/${x.slots.dinner.sd.toFixed(1)}\n`;}
fs.writeFileSync('analysis/t2dm_v2_day_si/report.md',md);console.log(md);
